/* SPDX-License-Identifier: GPL-2.0 */
/*
 * This header provides constants specific to Novatek NS02301 pinctrl bindings.
 */
#ifndef __DT_BINDINGS_INTERRUPT_NS02301_INTERRUPT_H
#define __DT_BINDINGS_INTERRUPT_NS02301_INTERRUPT_H

#define INT_GIC_SPI_START_ID    32

#define INT_ID_TIMER             	(INT_GIC_SPI_START_ID +   0)
#define INT_ID_SIE 	             	(INT_GIC_SPI_START_ID +   1)
#define INT_ID_SIE2              	(INT_GIC_SPI_START_ID +   2)
#define INT_ID_SIE3              	(INT_GIC_SPI_START_ID +   3)
#define INT_ID_DRTC               	(INT_GIC_SPI_START_ID +   4)
#define INT_ID_IPE 	              	(INT_GIC_SPI_START_ID +   5)
#define INT_ID_IME 	              	(INT_GIC_SPI_START_ID +   6)
#define INT_ID_VPE 	              	(INT_GIC_SPI_START_ID +   7)
#define INT_ID_IFE 			        (INT_GIC_SPI_START_ID +   8)
#define INT_ID_ETHERNET_TX 	        (INT_GIC_SPI_START_ID +   9)
#define INT_ID_I2C 			        (INT_GIC_SPI_START_ID +  10)
#define INT_ID_CNN 			        (INT_GIC_SPI_START_ID +  11)
#define INT_ID_SDP              	(INT_GIC_SPI_START_ID +  12)
#define INT_ID_NUE2             	(INT_GIC_SPI_START_ID +  13)
#define INT_ID_NUE 	            	(INT_GIC_SPI_START_ID +  14)
#define INT_ID_DAI              	(INT_GIC_SPI_START_ID +  15)
#define INT_ID_H26X 	       		(INT_GIC_SPI_START_ID +  16)
#define INT_ID_JPEG 	       		(INT_GIC_SPI_START_ID +  17)
#define INT_ID_GRAPHIC 	       		(INT_GIC_SPI_START_ID +  18)
#define INT_ID_GRAPHIC2        		(INT_GIC_SPI_START_ID +  19)
#define INT_ID_RSA 	             	(INT_GIC_SPI_START_ID +  20)
#define INT_ID_ISE 	             	(INT_GIC_SPI_START_ID +  21)
#define INT_ID_TGE 	             	(INT_GIC_SPI_START_ID +  22)
#define INT_ID_TSE 	             	(INT_GIC_SPI_START_ID +  23)
#define INT_ID_GPIO 	            (INT_GIC_SPI_START_ID +  24)
#define INT_ID_REMOTE 	            (INT_GIC_SPI_START_ID +  25)
#define INT_ID_PWM 		            (INT_GIC_SPI_START_ID +  26)
#define INT_ID_USB 		            (INT_GIC_SPI_START_ID +  27)
#define INT_ID_HASH 	            (INT_GIC_SPI_START_ID +  28)
#define INT_ID_NAND 	            (INT_GIC_SPI_START_ID +  29)
#define INT_ID_SDIO 	            (INT_GIC_SPI_START_ID +  30)
#define INT_ID_SDIO2              	(INT_GIC_SPI_START_ID +  31)
#define INT_ID_SDIO3 	       		(INT_GIC_SPI_START_ID +  32)
#define INT_ID_DMA 		       		(INT_GIC_SPI_START_ID +  33)
#define INT_ID_ETHERNET        		(INT_GIC_SPI_START_ID +  34)
#define INT_ID_SPI 		       		(INT_GIC_SPI_START_ID +  35)
#define INT_ID_SPI2 	         	(INT_GIC_SPI_START_ID +  36)
#define INT_ID_SPI3 	         	(INT_GIC_SPI_START_ID +  37)
#define INT_ID_CRYPTO 	         	(INT_GIC_SPI_START_ID +  38)
#define INT_ID_TZPC               	(INT_GIC_SPI_START_ID +  39)
#define INT_ID_SIF 	             	(INT_GIC_SPI_START_ID +  40)
#define INT_ID_I2C2              	(INT_GIC_SPI_START_ID +  41)
#define INT_ID_I2C3              	(INT_GIC_SPI_START_ID +  42)
#define INT_ID_UART               	(INT_GIC_SPI_START_ID +  43)
#define INT_ID_UART2 	            (INT_GIC_SPI_START_ID +  44)
#define INT_ID_UART3 	            (INT_GIC_SPI_START_ID +  45)
#define INT_ID_MDBC 	            (INT_GIC_SPI_START_ID +  46)
//#define INT_ID_NULL               (INT_GIC_SPI_START_ID +  47)
#define INT_ID_IDE             		(INT_GIC_SPI_START_ID +  48)
#define INT_ID_GPIO2 		        (INT_GIC_SPI_START_ID +  49)
#define INT_ID_ECDSA 		        (INT_GIC_SPI_START_ID +  50)
#define INT_ID_ETHERNET_RX 	        (INT_GIC_SPI_START_ID +  51)
#define INT_ID_TIMER2 	            (INT_GIC_SPI_START_ID +  52)
#define INT_ID_IVE 			        (INT_GIC_SPI_START_ID +  53)
#define INT_ID_LVDS 		        (INT_GIC_SPI_START_ID +  54)
#define INT_ID_LVDS2                (INT_GIC_SPI_START_ID +  55)
#define INT_ID_CFE 		            (INT_GIC_SPI_START_ID +  56)
#define INT_ID_PWM2 	            (INT_GIC_SPI_START_ID +  57)
#define INT_ID_CG 		            (INT_GIC_SPI_START_ID +  58)
#define INT_ID_UVCP                 (INT_GIC_SPI_START_ID +  59)
#define INT_ID_PRI2C 		        (INT_GIC_SPI_START_ID +  60)
#define INT_ID_TIMER64 		        (INT_GIC_SPI_START_ID +  61)
#define INT_ID_TIMER64_2 	        (INT_GIC_SPI_START_ID +  62)
#define INT_ID_TIMER64_3 	        (INT_GIC_SPI_START_ID +  63)
#define INT_ID_TIMER64_4            (INT_GIC_SPI_START_ID +  64)
#define INT_ID_TIMER64_5            (INT_GIC_SPI_START_ID +  65)
//#define INT_ID_NULL              	(INT_GIC_SPI_START_ID +  66)
#define INT_ID_YDCC              	(INT_GIC_SPI_START_ID +  67)
//#define INT_ID_NULL              	(INT_GIC_SPI_START_ID +  68)
#define INT_ID_SIF2              	(INT_GIC_SPI_START_ID +  69)

#define INT_ID_PRUART 	            (INT_GIC_SPI_START_ID +  70)
#define INT_ID_PRUART2 	            (INT_GIC_SPI_START_ID +  71)
#define INT_ID_PRPWM 	            (INT_GIC_SPI_START_ID +  72)
#define INT_ID_PRADC 	            (INT_GIC_SPI_START_ID +  73)
#define INT_ID_PRTIMER64 		    (INT_GIC_SPI_START_ID +  74)
#define INT_ID_PRWDT 			    (INT_GIC_SPI_START_ID +  75)
#define INT_ID_PRRTC 			    (INT_GIC_SPI_START_ID +  76)
#define INT_ID_PRGPIO2             	(INT_GIC_SPI_START_ID +  77)
#define INT_ID_PRGPIO3             	(INT_GIC_SPI_START_ID +  78)
#define INT_ID_PRWIEGAND           	(INT_GIC_SPI_START_ID +  79)
#define INT_ID_PRISP               	(INT_GIC_SPI_START_ID +  80)
#define INT_ID_PRPWM2 		       	(INT_GIC_SPI_START_ID +  81)
#define INT_ID_PRMCU             	(INT_GIC_SPI_START_ID +  82)
#define INT_ID_PRCG             	(INT_GIC_SPI_START_ID +  83)
#define INT_ID_PRCC             	(INT_GIC_SPI_START_ID +  84)
#define INT_ID_PRCC2             	(INT_GIC_SPI_START_ID +  85)
#define INT_ID_PRSPI              	(INT_GIC_SPI_START_ID +  86)
#define INT_ID_PRAUDIO             	(INT_GIC_SPI_START_ID +  87)
#define INT_ID_CNT               	(INT_GIC_SPI_START_ID +  88)
#define INT_ID_MAX               	(INT_ID_CNT - INT_GIC_SPI_START_ID)
#define INT_ID_DUMMY_DGPIO       	(INT_ID_MAX + 1)

#define INT_ID_WFI               	229
#define INT_ID_GIC_TOTAL         	256

#endif