/*
    Register offset and bit definition for GPENC module

    Register offset and bit definition for GPENC module.

    @file       gpenc_reg.h
    @ingroup    miDrvDisplay_GPENC
    @note       Nothing.

    Copyright   Novatek Microelectronics Corp. 2011.  All rights reserved.
*/

#ifndef _GPENC_REG_H
#define _GPENC_REG_H

#ifndef __KERNEL__
#include "rcw_macro.h"
#include "kwrap/type.h"
#else
#include "mach/rcw_macro.h"
#include "kwrap/type.h"
#endif

/*
    @addtogroup miDrvDisplay_GPENC
*/
//@{

//0x00
REGDEF_OFFSET(GPENC_CTRL_REG, 0x00)
REGDEF_BEGIN(GPENC_CTRL_REG)
REGDEF_BIT(FIRE, 1)
REGDEF_BIT(, 7)
REGDEF_BIT(INDEX_WIDTH, 3)
REGDEF_BIT(SRC_WIDTH, 2)
REGDEF_BIT(WAIT_TIME, 4)
REGDEF_BIT(, 14)
REGDEF_BIT(SW_RST, 1)
REGDEF_END(GPENC_CTRL_REG)

//0x30 LOW
REGDEF_OFFSET(GPENC_READ_ADDR_REG, 0x30)
REGDEF_BEGIN(GPENC_READ_ADDR_REG)
REGDEF_BIT(READ_ADDR, 32)
REGDEF_END(GPENC_READ_ADDR_REG)

//0x34 HIGH
REGDEF_OFFSET(GPENC_READ_ADDR_REG_H, 0x34)
REGDEF_BEGIN(GPENC_READ_ADDR_REG_H)
REGDEF_BIT(READ_ADDR_H, 32)
REGDEF_END(GPENC_READ_ADDR_REG_H)

//0x08
REGDEF_OFFSET(GPENC_READ_SIZE_REG, 0x08)
REGDEF_BEGIN(GPENC_READ_SIZE_REG)
REGDEF_BIT(READ_SIZE, 32)
REGDEF_END(GPENC_READ_SIZE_REG)

//0x38 LOW
REGDEF_OFFSET(GPENC_WRITE_ADDR_REG, 0x38)
REGDEF_BEGIN(GPENC_WRITE_ADDR_REG)
REGDEF_BIT(WRITE_ADDR, 32)
REGDEF_END(GPENC_WRITE_ADDR_REG)

//0x3C HIGH
REGDEF_OFFSET(GPENC_WRITE_ADDR_REG_H, 0x3C)
REGDEF_BEGIN(GPENC_WRITE_ADDR_REG_H)
REGDEF_BIT(WRITE_ADDR_H, 32)
REGDEF_END(GPENC_WRITE_ADDR_REG_H)

//0x10
REGDEF_OFFSET(GPENC_WRITE_LMT_REG, 0x10)
REGDEF_BEGIN(GPENC_WRITE_LMT_REG)
REGDEF_BIT(WRITE_LMT, 32)
REGDEF_END(GPENC_WRITE_LMT_REG)

//0x14
REGDEF_OFFSET(GPENC_ENC_SIZE_REG, 0x14)
REGDEF_BEGIN(GPENC_ENC_SIZE_REG)
REGDEF_BIT(ENC_SIZE, 32)
REGDEF_END(GPENC_ENC_SIZE_REG)

//0x1C
REGDEF_OFFSET(GPENC_STS_REG, 0x1C)
REGDEF_BEGIN(GPENC_STS_REG)
REGDEF_BIT(ENC_DONE, 1)
REGDEF_BIT(WRITE_OVER_LMT, 1)
REGDEF_BIT(, 30)
REGDEF_END(GPENC_STS_REG)

//0x20
REGDEF_OFFSET(GPENC_INT_REG, 0x20)
REGDEF_BEGIN(GPENC_INT_REG)
REGDEF_BIT(ENC_DONE, 1)
REGDEF_BIT(WRITE_OVER_LMT, 1)
REGDEF_BIT(, 30)
REGDEF_END(GPENC_INT_REG)

//0x40
REGDEF_OFFSET(GPENC_IMGW_REG, 0x40)
REGDEF_BEGIN(GPENC_IMGW_REG)
REGDEF_BIT(IMG_W, 13)
REGDEF_BIT(, 19)
REGDEF_END(GPENC_IMGW_REG)

//0x44
REGDEF_OFFSET(GPENC_IMGH_REG, 0x44)
REGDEF_BEGIN(GPENC_IMGH_REG)
REGDEF_BIT(IMG_H, 13)
REGDEF_BIT(, 19)
REGDEF_END(GPENC_IMGH_REG)

//0x48
REGDEF_OFFSET(GPENC_IMGOFS_REG, 0x48)
REGDEF_BEGIN(GPENC_IMGOFS_REG)
REGDEF_BIT(IMG_OFS, 16)
REGDEF_BIT(, 16)
REGDEF_END(GPENC_IMGOFS_REG)


//@}

#endif
