obj-y += nvt-pcie-cascade-drv.o
nvt-pcie-cascade-drv-objs := \
	nvt-pcie-drv.o \
	nvt-pcie-ep.o \
	nvt-pcie-proc.o \
	nvt_pcie_ctrl.o \
	pcie-drv-wrap.o \
	nvt_msix.o \
	nvt_pcie_edma.o \
	nvt_pcie_tba.o
