#ifndef __DRE_DRV_LIMIT_H__
#define __DRE_DRV_LIMIT_H__

//=====================================================
// input limitation for Y-8bit
#define DRE_SRCBUF_Y8BIT_WMIN         8//8//DRE_SRCBUF_W_MIN
#define DRE_SRCBUF_Y8BIT_WMAX         65535//65503//DRE_SRCBUF_W_MAX
#define DRE_SRCBUF_Y8BIT_WALIGN       1//DRE_SRCBUF_Y8_W_ALIGN

#define DRE_SRCBUF_Y8BIT_HMIN         8//8//DRE_SRCBUF_H_MIN
#define DRE_SRCBUF_Y8BIT_HMAX         65535//65535//DRE_SRCBUF_H_MAX
#define DRE_SRCBUF_Y8BIT_HALIGN       1//DRE_SRCBUF_Y8_H_ALIGN

#define DRE_SRCBUF_Y8BIT_LOFF_ALIGN   4//DRE_SRCBUF_LOFS_ALIGN
#define DRE_SRCBUF_Y8BIT_ADDR_ALIGN   1//DRE_SRCBUF_Y8_BUF_ADDR_ALIGN

//=====================================================
// input limitation for Y-4bit
#define DRE_SRCBUF_Y4BIT_WMIN         8//DRE_SRCBUF_W_MIN
#define DRE_SRCBUF_Y4BIT_WMAX         65535//DRE_SRCBUF_W_MAX
#define DRE_SRCBUF_Y4BIT_WALIGN       2//DRE_SRCBUF_Y4_W_ALIGN

#define DRE_SRCBUF_Y4BIT_HMIN         8//DRE_SRCBUF_H_MIN
#define DRE_SRCBUF_Y4BIT_HMAX         65535//DRE_SRCBUF_H_MAX
#define DRE_SRCBUF_Y4BIT_HALIGN       1//DRE_SRCBUF_Y4_H_ALIGN

#define DRE_SRCBUF_Y4BIT_LOFF_ALIGN   4//DRE_SRCBUF_LOFS_ALIGN
#define DRE_SRCBUF_Y4BIT_ADDR_ALIGN   1//DRE_SRCBUF_Y4_BUF_ADDR_ALIGN


//=====================================================
// input limitation for UV-packing
#define DRE_SRCBUF_UVP_WMIN         8//DRE_SRCBUF_W_MIN
#define DRE_SRCBUF_UVP_WMAX         65535//DRE_SRCBUF_W_MAX
#define DRE_SRCBUF_UVP_WALIGN       2//DRE_SRCBUF_UV_W_ALIGN

#define DRE_SRCBUF_UVP_HMIN         8//DRE_SRCBUF_H_MIN
#define DRE_SRCBUF_UVP_HMAX         65535//DRE_SRCBUF_H_MAX
#define DRE_SRCBUF_UVP_HALIGN       1//DRE_SRCBUF_UV_H_ALIGN

#define DRE_SRCBUF_UVP_LOFF_ALIGN   4//DRE_SRCBUF_LOFS_ALIGN
#define DRE_SRCBUF_UVP_ADDR_ALIGN   2//DRE_SRCBUF_UV_BUF_ADDR_ALIGN

//=====================================================
// input limitation for 420 Semi Planar UV-packing
#define DRE_SRCBUF_420UVP_WMIN         8//DRE_SRCBUF_W_MIN
#define DRE_SRCBUF_420UVP_WMAX         65535//DRE_SRCBUF_W_MAX
#define DRE_SRCBUF_420UVP_WALIGN       2//DRE_SRCBUF_YUV420_W_ALIGN

#define DRE_SRCBUF_420UVP_HMIN         8//DRE_SRCBUF_H_MIN
#define DRE_SRCBUF_420UVP_HMAX         65535//DRE_SRCBUF_H_MAX
#define DRE_SRCBUF_420UVP_HALIGN       2//DRE_SRCBUF_YUV420_H_ALIGN

#define DRE_SRCBUF_420UVP_LOFF_ALIGN   4//DRE_SRCBUF_LOFS_ALIGN
#define DRE_SRCBUF_420UVP_ADDR_ALIGN   2//DRE_SRCBUF_YUV420_BUF_ADDR_ALIGN

//=====================================================
// input limitation for 420 ycc (YUV420)
#define DRE_SRCBUF_420YCC_WMIN         (32)
#define DRE_SRCBUF_420YCC_WMAX         (65535)
#define DRE_SRCBUF_420YCC_WALIGN       (32)

#define DRE_SRCBUF_420YCC_HMIN         (8)
#define DRE_SRCBUF_420YCC_HMAX         (65535)
#define DRE_SRCBUF_420YCC_HALIGN       (2)

#define DRE_SRCBUF_420YCC_LOFF_ALIGN   (4)
#define DRE_SRCBUF_420YCC_ADDR_ALIGN   (4)

//=====================================================
// input limitation for 422
#define DRE_SRCBUF_422_WMIN         8//DRE_SRCBUF_W_MIN
#define DRE_SRCBUF_422_WMAX         65535//DRE_SRCBUF_W_MAX
#define DRE_SRCBUF_422_WALIGN       2//DRE_SRCBUF_VYUY_W_ALIGN

#define DRE_SRCBUF_422_HMIN         8//DRE_SRCBUF_H_MIN
#define DRE_SRCBUF_422_HMAX         65535//DRE_SRCBUF_H_MAX
#define DRE_SRCBUF_422_HALIGN       1//DRE_SRCBUF_VYUY_H_ALIGN

#define DRE_SRCBUF_422_LOFF_ALIGN   4//DRE_SRCBUF_LOFS_ALIGN
#define DRE_SRCBUF_422_ADDR_ALIGN   2//DRE_SRCBUF_VYUY_BUF_ADDR_ALIGN

//=====================================================
// input limitation for RGB565
#define DRE_SRCBUF_RGB565_WMIN         8//DRE_SRCBUF_W_MIN
#define DRE_SRCBUF_RGB565_WMAX         65503//DRE_SRCBUF_W_MAX
#define DRE_SRCBUF_RGB565_WALIGN       1//DRE_SRCBUF_RGB565_W_ALIGN

#define DRE_SRCBUF_RGB565_HMIN         8//DRE_SRCBUF_H_MIN
#define DRE_SRCBUF_RGB565_HMAX         65535//DRE_SRCBUF_H_MAX
#define DRE_SRCBUF_RGB565_HALIGN       1//DRE_SRCBUF_RGB565_H_ALIGN

#define DRE_SRCBUF_RGB565_LOFF_ALIGN   4//DRE_SRCBUF_LOFS_ALIGN
#define DRE_SRCBUF_RGB565_ADDR_ALIGN   2//DRE_SRCBUF_RGB565_BUF_ADDR_ALIGN

//=====================================================
// input limitation for RGB1555
#define DRE_SRCBUF_RGB1555_WMIN         8//DRE_SRCBUF_W_MIN
#define DRE_SRCBUF_RGB1555_WMAX         65535//DRE_SRCBUF_W_MAX
#define DRE_SRCBUF_RGB1555_WALIGN       1//DRE_SRCBUF_ARGB1555_W_ALIGN

#define DRE_SRCBUF_RGB1555_HMIN         8//DRE_SRCBUF_H_MIN
#define DRE_SRCBUF_RGB1555_HMAX         65535//DRE_SRCBUF_H_MAX
#define DRE_SRCBUF_RGB1555_HALIGN       1//DRE_SRCBUF_ARGB1555_H_ALIGN

#define DRE_SRCBUF_RGB1555_LOFF_ALIGN   4//DRE_SRCBUF_LOFS_ALIGN
#define DRE_SRCBUF_RGB1555_ADDR_ALIGN   2//DRE_SRCBUF_ARGB1555_BUF_ADDR_ALIGN

//=====================================================
// input limitation for RGB4444
#define DRE_SRCBUF_RGB4444_WMIN         8//DRE_SRCBUF_W_MIN
#define DRE_SRCBUF_RGB4444_WMAX         65503//DRE_SRCBUF_W_MAX
#define DRE_SRCBUF_RGB4444_WALIGN       1//DRE_SRCBUF_ARGB4444_W_ALIGN

#define DRE_SRCBUF_RGB4444_HMIN         8//DRE_SRCBUF_H_MIN
#define DRE_SRCBUF_RGB4444_HMAX         65535//DRE_SRCBUF_H_MAX
#define DRE_SRCBUF_RGB4444_HALIGN       1//DRE_SRCBUF_ARGB4444_H_ALIGN

#define DRE_SRCBUF_RGB4444_LOFF_ALIGN   4//DRE_SRCBUF_LOFS_ALIGN
#define DRE_SRCBUF_RGB4444_ADDR_ALIGN   2//DRE_SRCBUF_ARGB4444_BUF_ADDR_ALIGN

//=====================================================
// input limitation for RGB8888
#define DRE_SRCBUF_RGB8888_WMIN         8//DRE_SRCBUF_W_MIN
#define DRE_SRCBUF_RGB8888_WMAX         65535//DRE_SRCBUF_W_MAX
#define DRE_SRCBUF_RGB8888_WALIGN       1//DRE_SRCBUF_ARGB8888_W_ALIGN

#define DRE_SRCBUF_RGB8888_HMIN         8//DRE_SRCBUF_H_MIN
#define DRE_SRCBUF_RGB8888_HMAX         65535//DRE_SRCBUF_H_MAX
#define DRE_SRCBUF_RGB8888_HALIGN       1//DRE_SRCBUF_ARGB8888_H_ALIGN

#define DRE_SRCBUF_RGB8888_LOFF_ALIGN   4//DRE_SRCBUF_LOFS_ALIGN
#define DRE_SRCBUF_RGB8888_ADDR_ALIGN   4//DRE_SRCBUF_ARGB8888_BUF_ADDR_ALIGN

//=====================================================
// output limitation for Y-8bit
#define DRE_DSTBUF_Y8BIT_WMIN         8//DRE_DSTBUF_W_MIN
#define DRE_DSTBUF_Y8BIT_WMAX         65535//DRE_DSTBUF_W_MAX
#define DRE_DSTBUF_Y8BIT_WALIGN       1//DRE_DSTBUF_Y8_W_ALIGN

#define DRE_DSTBUF_Y8BIT_HMIN         8//DRE_DSTBUF_H_MIN
#define DRE_DSTBUF_Y8BIT_HMAX         65535//DRE_DSTBUF_H_MAX
#define DRE_DSTBUF_Y8BIT_HALIGN       1//DRE_DSTBUF_Y8_H_ALIGN

#define DRE_DSTBUF_Y8BIT_LOFF_ALIGN   4//DRE_DSTBUF_LOFS_ALIGN
#define DRE_DSTBUF_Y8BIT_ADDR_ALIGN   1//DRE_DSTBUF_Y8_BUF_ADDR_ALIGN

//=====================================================
// output limitation for Y-4bit
#define DRE_DSTBUF_Y4BIT_WMIN         8//DRE_DSTBUF_W_MIN
#define DRE_DSTBUF_Y4BIT_WMAX         65535//DRE_DSTBUF_W_MAX
#define DRE_DSTBUF_Y4BIT_WALIGN       2//DRE_DSTBUF_Y4_W_ALIGN

#define DRE_DSTBUF_Y4BIT_HMIN         8//DRE_DSTBUF_H_MIN
#define DRE_DSTBUF_Y4BIT_HMAX         65535//DRE_DSTBUF_H_MAX
#define DRE_DSTBUF_Y4BIT_HALIGN       1//DRE_DSTBUF_Y4_H_ALIGN

#define DRE_DSTBUF_Y4BIT_LOFF_ALIGN   4//DRE_DSTBUF_LOFS_ALIGN
#define DRE_DSTBUF_Y4BIT_ADDR_ALIGN   1//DRE_DSTBUF_Y4_BUF_ADDR_ALIGN


//=====================================================
// output limitation for UV-packing
#define DRE_DSTBUF_UVP_WMIN         8//DRE_DSTBUF_W_MIN
#define DRE_DSTBUF_UVP_WMAX         65535//DRE_DSTBUF_W_MAX
#define DRE_DSTBUF_UVP_WALIGN       2//DRE_DSTBUF_UV_W_ALIGN

#define DRE_DSTBUF_UVP_HMIN         8//DRE_DSTBUF_H_MIN
#define DRE_DSTBUF_UVP_HMAX         65535//DRE_DSTBUF_H_MAX
#define DRE_DSTBUF_UVP_HALIGN       1//DRE_DSTBUF_UV_H_ALIGN

#define DRE_DSTBUF_UVP_LOFF_ALIGN   4//DRE_DSTBUF_LOFS_ALIGN
#define DRE_DSTBUF_UVP_ADDR_ALIGN   2//DRE_DSTBUF_UV_BUF_ADDR_ALIGN

//=====================================================
// output limitation for 420 Semi Planar UV-packing
#define DRE_DSTBUF_420UVP_WMIN         8//DRE_DSTBUF_W_MIN
#define DRE_DSTBUF_420UVP_WMAX         65535//DRE_DSTBUF_W_MAX
#define DRE_DSTBUF_420UVP_WALIGN       2//DRE_DSTBUF_YUV420_W_ALIGN

#define DRE_DSTBUF_420UVP_HMIN         8//DRE_DSTBUF_H_MIN
#define DRE_DSTBUF_420UVP_HMAX         65535//DRE_DSTBUF_H_MAX
#define DRE_DSTBUF_420UVP_HALIGN       2//DRE_DSTBUF_YUV420_H_ALIGN

#define DRE_DSTBUF_420UVP_LOFF_ALIGN   4//DRE_DSTBUF_LOFS_ALIGN
#define DRE_DSTBUF_420UVP_ADDR_ALIGN   2//DRE_DSTBUF_YUV420_BUF_ADDR_ALIGN

//=====================================================
// input limitation for 420 ycc (YUV420)
#define DRE_DSTBUF_420YCC_WMIN         (32)
#define DRE_DSTBUF_420YCC_WMAX         (65535)
#define DRE_DSTBUF_420YCC_WALIGN       (32)

#define DRE_DSTBUF_420YCC_HMIN         (8)
#define DRE_DSTBUF_420YCC_HMAX         (65535)
#define DRE_DSTBUF_420YCC_HALIGN       (2)

#define DRE_DSTBUF_420YCC_LOFF_ALIGN   (4)
#define DRE_DSTBUF_420YCC_ADDR_ALIGN   (4)

//=====================================================
// output limitation for 422
#define DRE_DSTBUF_422_WMIN         8//DRE_DSTBUF_W_MIN
#define DRE_DSTBUF_422_WMAX         65535//DRE_DSTBUF_W_MAX
#define DRE_DSTBUF_422_WALIGN       2//DRE_DSTBUF_VYUY_W_ALIGN

#define DRE_DSTBUF_422_HMIN         8//DRE_DSTBUF_H_MIN
#define DRE_DSTBUF_422_HMAX         65535//DRE_DSTBUF_H_MAX
#define DRE_DSTBUF_422_HALIGN       1//DRE_DSTBUF_VYUY_H_ALIGN

#define DRE_DSTBUF_422_LOFF_ALIGN   4//DRE_DSTBUF_LOFS_ALIGN
#define DRE_DSTBUF_422_ADDR_ALIGN   2//DRE_DSTBUF_VYUY_BUF_ADDR_ALIGN

//=====================================================
// output limitation for RGB565
#define DRE_DSTBUF_RGB565_WMIN         8//DRE_DSTBUF_W_MIN
#define DRE_DSTBUF_RGB565_WMAX         65535//DRE_DSTBUF_W_MAX
#define DRE_DSTBUF_RGB565_WALIGN       1//DRE_DSTBUF_RGB565_W_ALIGN

#define DRE_DSTBUF_RGB565_HMIN         8//DRE_DSTBUF_H_MIN
#define DRE_DSTBUF_RGB565_HMAX         65535//DRE_DSTBUF_H_MAX
#define DRE_DSTBUF_RGB565_HALIGN       1//DRE_DSTBUF_RGB565_H_ALIGN

#define DRE_DSTBUF_RGB565_LOFF_ALIGN   4//DRE_DSTBUF_LOFS_ALIGN
#define DRE_DSTBUF_RGB565_ADDR_ALIGN   2//DRE_DSTBUF_RGB565_BUF_ADDR_ALIGN

//=====================================================
// output limitation for RGB1555
#define DRE_DSTBUF_RGB1555_WMIN         8//DRE_DSTBUF_W_MIN
#define DRE_DSTBUF_RGB1555_WMAX         65535//DRE_DSTBUF_W_MAX
#define DRE_DSTBUF_RGB1555_WALIGN       1//DRE_DSTBUF_ARGB1555_W_ALIGN

#define DRE_DSTBUF_RGB1555_HMIN         8//DRE_DSTBUF_H_MIN
#define DRE_DSTBUF_RGB1555_HMAX         65535//DRE_DSTBUF_H_MAX
#define DRE_DSTBUF_RGB1555_HALIGN       1//DRE_DSTBUF_ARGB1555_H_ALIGN

#define DRE_DSTBUF_RGB1555_LOFF_ALIGN   4//DRE_DSTBUF_LOFS_ALIGN
#define DRE_DSTBUF_RGB1555_ADDR_ALIGN   2//DRE_DSTBUF_ARGB1555_BUF_ADDR_ALIGN

//=====================================================
// output limitation for RGB4444
#define DRE_DSTBUF_RGB4444_WMIN         8//DRE_DSTBUF_W_MIN
#define DRE_DSTBUF_RGB4444_WMAX         65535//DRE_DSTBUF_W_MAX
#define DRE_DSTBUF_RGB4444_WALIGN       1//DRE_DSTBUF_ARGB4444_W_ALIGN

#define DRE_DSTBUF_RGB4444_HMIN         8//DRE_DSTBUF_H_MIN
#define DRE_DSTBUF_RGB4444_HMAX         65535//DRE_DSTBUF_H_MAX
#define DRE_DSTBUF_RGB4444_HALIGN       1//DRE_DSTBUF_ARGB4444_H_ALIGN

#define DRE_DSTBUF_RGB4444_LOFF_ALIGN   4//DRE_DSTBUF_LOFS_ALIGN
#define DRE_DSTBUF_RGB4444_ADDR_ALIGN   2//DRE_DSTBUF_ARGB4444_BUF_ADDR_ALIGN

//=====================================================
// output limitation for RGB8888
#define DRE_DSTBUF_RGB8888_WMIN         8//DRE_DSTBUF_W_MIN
#define DRE_DSTBUF_RGB8888_WMAX         65535//DRE_DSTBUF_W_MAX
#define DRE_DSTBUF_RGB8888_WALIGN       1//DRE_DSTBUF_ARGB8888_W_ALIGN

#define DRE_DSTBUF_RGB8888_HMIN         8//DRE_DSTBUF_H_MIN
#define DRE_DSTBUF_RGB8888_HMAX         65535//DRE_DSTBUF_H_MAX
#define DRE_DSTBUF_RGB8888_HALIGN       1//DRE_DSTBUF_ARGB8888_H_ALIGN

#define DRE_DSTBUF_RGB8888_LOFF_ALIGN   4//DRE_DSTBUF_LOFS_ALIGN
#define DRE_DSTBUF_RGB8888_ADDR_ALIGN   4//DRE_DSTBUF_ARGB8888_BUF_ADDR_ALIGN

//=====================================================

#define DRE_DRV_MAX_SCALE_RATIO		(32)
#define DRE_DRV_ALIGN_DMA_LLC		(4)
#endif /* __DRE_DRV_LIMIT_H__ */
