#ifndef _VPE_ENG_INT_H_
#define _VPE_ENG_INT_H_

#include "kwrap/type.h"
#include "kwrap/util.h"
#include "vpe_eng.h"
#include "vpe_eng_int_reg.h"
#include "vpe_eng_ctrl_base.h"


//extern volatile NT9863X_VPE_REG_STRUCT *p_vpe_reg_st[VPE_ID_MAX_NUM] ;
//extern volatile UINT8 *p_vpe_reg_chg_flag[VPE_ID_MAX_NUM];

#define VPE_ENG_REG_NUM	    		732

#define MASK_WIN_REG_GAP 0x24
#define MASK_DID_MSK 0x03
#define MASK_PAL_SEL_MSK 0x07
#define MASK_PAL_SEL_OFS 4
#define MASK_LINE_HIT_MSK 0x03
#define MASK_LINE_HIT_OFS 8
#define MASK_ALPHA_MSK 0x1FF
#define MASK_ALPHA_OFS 16
#define MASK_SHAPE_MSK 0x3
#define MASK_SHAPE_OFS 25



#define LINE_REG_GAP 0x8


#define MASK_LINE_REG_GAP 0x24
#define MASK_LINE_COEFFA_MSK 0xFFFF
#define MASK_LINE_COEFFB_MSK 0xFFFF
#define MASK_LINE_COEFFB_OFS 16

#define MASK_LINE_COEFFC_MSK 0x3FFFFFFF
#define MASK_LINE_COMP_MSK 0x3
#define MASK_LINE_COMP_OFS 30

#define MASK_LINE_X_REG_GAP 0x8


#define TMNR_Y_NOISE_MODE_GAP 0x8
#define TMNR_Y_BASE_MSK 0xFFFFF
#define TMNR_Y_STD_MSK 0xFFFF
#define TMNR_Y_STD_OFS 16
#define TMNR_Y_COEFA_MSK 0xFFFFF
#define TMNR_Y_COEFB_MSK 0xFFFF
#define TMNR_Y_COEFB_OFS 16

#define TMNR_CHROMA_NOISE_MODE_GAP 0x4
#define TMNR_CHROMA_MEAN_MSK 0xFFFFF
#define TMNR_CHROMA_STD_MSK 0xFFFF
#define TMNR_CHROMA_STD_OFS 16

#define COLX_SIZE1_REG_GAP 0x20
#define PROC_WIDTH_MSK 0x0FFF
#define PROC_X_START_MSK 0x3FFF
#define PROC_X_START_OFS 16

#define COLX_SIZE2_REG_GAP 0x20
#define REFR_X_START_MSK 0x1FFF
#define REFW_X_START_MSK 0x1FFF
#define REFW_X_START_OFS 16

#define COLX_SIZE3_REG_GAP 0x20
#define REFW_CROP_X_START_MSK 0x1FFF
#define REFW_CROP_WIDTH_MSK 0x0FFF
#define REFW_CROP_WIDTH_OFS 16

#define COLX_SIZE4_REG_GAP 0x20
#define MD_WIN_X_MSK 0x0FFF
#define MD_WIN_X_NUM_MSK 0x0FF
#define MD_WIN_X_NUM_OFS 16
//#define MD_WIN_X_START_NUM_MSK 0x0FF
//#define MD_WIN_X_START_NUM_OFS 24


#define COLX_SIZE5_REG_GAP 0x20
#define TMNR_INFO_XNUM_MSK 0x0FFF
#define TMNR_INFO_XOFT_MSK 0x0FFF
#define TMNR_INFO_XOFT_OFS 16

#define COLX_SIZE7_REG_GAP 0x20
#define COL_X_START_MSK 0x3FFF
#define COLX_SIZE7_REG_GAP 0x20

#define COLX_SIZE8_REG_GAP 0x20
#define MD_WIN_X_START_NUM_MSK 0x1FF

#define COLX_SIZE9_REG_GAP 0x20
#define PROC_WIDTH2_MSK 0x1FFF



#define RESX_COLX_SIZE1_REG_GAP 0x20
#define RESX_COLX_SIZE1_SCA_WIDTH_MSK 0x0FFF
//#define RESX_COLX_SIZE1_SCA_HSTEP_OFT_MSK 0x7FFF
//#define RESX_COLX_SIZE1_SCA_HSTEP_OFT_OFS 16


#define RESX_COLX_SIZE2_REG_GAP 0x20
#define RESX_COLX_SIZE2_OUT_X_START_MSK 0x7FFF
#define RESX_COLX_SIZE2_OUT_WIDTH_MSK 0x0FFF
#define RESX_COLX_SIZE2_OUT_WIDTH_OFS 16

#define RESX_COLX_SIZE3_REG_GAP 0x20
#define RESX_COLX_SIZE3_RLT_X_START_MSK 0x07FF
#define RESX_COLX_SIZE3_RLT_WIDTH_MSK 0x0FFF
#define RESX_COLX_SIZE3_RLT_WIDTH_OFS 16

#define RESX_COLX_SIZE4_REG_GAP 0x20
#define RESX_COLX_SIZE4_PIP_X_START_MSK 0x07FF
#define RESX_COLX_SIZE4_PIP_WIDTH_MSK 0x0FFF
#define RESX_COLX_SIZE4_PIP_WIDTH_OFS 16

#define RESX_COLX_SIZE5_REG_GAP 0x20
#define RESX_COLX_SIZE5_SCA_CROP_X_START_MSK 0x07FF
#define RESX_COLX_SIZE5_SCA_CROP_WIDTH_MSK 0x0FFF
#define RESX_COLX_SIZE5_SCA_CROP_WIDTH_OFS 16

#define RESX_COLX_SIZE6_REG_GAP 0x20
#define RESX_COLX_SIZE6_TC_CROP_X_START_MSK 0x07FF
#define RESX_COLX_SIZE6_TC_CROP_WIDTH_MSK 0x0FFF
#define RESX_COLX_SIZE6_TC_CROP_WIDTH_OFS 16
#define RESX_COLX_SIZE6_TC_CROP_SKIP_MSK 0x1
#define RESX_COLX_SIZE6_TC_CROP_SKIP_OFS 31

#define RESX_COLX_SIZE7_REG_GAP 0x20
#define RESX_COLX_SIZE7_SCA_FACTOR_H_INIT_OFS_MSK 0x1FFFFFF


//#define RESX_COLX_SIZE1_SCA_HSTEP_OFT_MSK 0x7FFF
//#define RESX_COLX_SIZE1_SCA_HSTEP_OFT_OFS 16



#define MRNR_THR_ORDER_REG_GAP 0x4

#define MD_INIT_WEIGHT_MSK 0x7FFF
#define MD_INIT_WEIGHT_ODD_OFS 16


//#define VPE_ENG_COL_MAX   24 //8
#define VPE_ENG_TIMEOUT_MS 1000

#define VPE_MAX_W             16384//4096
#define VPE_COL_MAX_W         2048
#define VPE_ROT_COL_MAX_W     512
#define COLUMN_OVERLAP        48
#define COLUMN_SCE_OVERLAP    64
#define COLUMN_MAX_WIDTH      1936
#define COLUMN_MAX_PROC_W     (COLUMN_MAX_WIDTH + COLUMN_OVERLAP)

#define VPE321_RES_LIMIT         0
#define VPE321_CPU_UTILIZATION   0
#define VPE321_COL_RLT           1

#define LL_TAB_STS_REG_GAP       0x4
#define LL_TAB_STS_FRM_GAP       0x4
#define LL_TAB_STS_MSK           0xF
#define LL_STS_FRM_DONE_OFS      0
#define LL_STS_DMA_ERR_OFS       3



#endif //_VPE_ENG_INT_H_
