# Copyright (C) 2015-2021 Novatek corp.
#
# SPDX-License-Identifier:	GPL-2.0+
#
KBUILD_CFLAGS := -fno-builtin -Werror -Iboard/$(BOARDDIR)/../common/include -fshort-wchar -Iinclude

obj-$(CONFIG_PCIE_NVT) += nvt_pcie_utils.o
obj-$(CONFIG_PHY_NOVATEK_PCIE_V2) += nvt_pcie_ep.o
