#
# Copyright (C) 2021 NovaTek Corp.
#
#

obj-$(CONFIG_NVT_CRYPTO) += ns02401_crypto.o
obj-$(CONFIG_NVT_HASH) += ns02401_hash.o
obj-$(CONFIG_NVT_RSA) += ns02401_rsa.o
obj-$(CONFIG_NVT_ECDSA) += ns02401_ecdsa.o
