INCLUDES = -Iinclude -I../groupsock/include
#PREFIX = /usr/local
PREFIX = ../../../release/nvtlive555
LIBDIR = $(PREFIX)/lib
##### Change the following for your environment:
INCLUDE_DIR = $(LIBRARY_DIR)/include
OUTPUT_DIR = $(LIBRARY_DIR)/output
COMPILE_OPTS = $(INCLUDES) -I. -I$(INCLUDE_DIR) -I$(NVT_VOS_DIR)/include -O2 -DSOCKLEN_T=socklen_t -D_LARGEFILE_SOURCE=1 -D_FILE_OFFSET_BITS=64 -fPIC $(PLATFORM_CFLAGS) -D__LINUX520 -D__LINUX -D_NO_NVT_IPC_ -D_NO_NVT_INFO_ -D_NO_NVT_SSENDER_ -DXLOCALE_NOT_USED=1
C =			c
C_COMPILER =	$(CROSS_COMPILE)gcc
C_FLAGS =		$(NVT_ASAN) $(COMPILE_OPTS) $(CPPFLAGS) $(CFLAGS)
CPP =			cpp
CPLUSPLUS_COMPILER =	$(CROSS_COMPILE)gcc
CPLUSPLUS_FLAGS =	$(NVT_ASAN) $(COMPILE_OPTS) -fpermissive -Wall -DBSD=1 $(CPPFLAGS) $(CXXFLAGS)
OBJ =			o
LINK =			$(CROSS_COMPILE)gcc
LINK_OPTS =		$(NVT_ASAN) -L$(LIBRARY_DIR) -lstdc++ -lpthread -lm -lnvtlive555 -lnvtinfo
CONSOLE_LINK_OPTS =	$(LINK_OPTS)
LIBRARY_LINK =		$(CROSS_COMPILE)ar cr
LIBRARY_LINK_OPTS =
NM		  =     $(CROSS_COMPILE)nm
LIB_SUFFIX =			a
LIBS_FOR_CONSOLE_APPLICATION =
#_680_TODO -lnvtauth
LIBS_FOR_GUI_APPLICATION =
#EXE =
EXE = .a
NM =
SHARED_LIB = ON
LD_FLAGS	= $(NVT_ASAN) -fPIC -shared
##### End of variables to change

NAME = libUsageEnvironment
USAGE_ENVIRONMENT_LIB = $(NAME).$(LIB_SUFFIX)
ALL = $(USAGE_ENVIRONMENT_LIB)
all:	$(ALL)

OBJS = UsageEnvironment.$(OBJ) HashTable.$(OBJ) strDup.$(OBJ)

$(USAGE_ENVIRONMENT_LIB): $(OBJS)
	@echo Creating library $* ...
	@$(LIBRARY_LINK) $@ $(LIBRARY_LINK_OPTS) $(OBJS)

.$(C).$(OBJ):
	@echo Compiling $<
	@$(C_COMPILER) -c $(C_FLAGS) $<

.$(CPP).$(OBJ):
	@echo Compiling $<
	@$(CPLUSPLUS_COMPILER) -c $(CPLUSPLUS_FLAGS) $<

UsageEnvironment.$(CPP):	include/UsageEnvironment.hh
include/UsageEnvironment.hh:	include/UsageEnvironment_version.hh include/Boolean.hh include/strDup.hh
HashTable.$(CPP):		include/HashTable.hh
include/HashTable.hh:		include/Boolean.hh
strDup.$(CPP):			include/strDup.hh

clean:
	-rm -rf *.$(OBJ) $(ALL) core *.core *~ include/*~

install: install1 $(INSTALL2)
install1: $(USAGE_ENVIRONMENT_LIB)
	  install -d $(DESTDIR)$(LIBDIR)
	  install -m 644 $(USAGE_ENVIRONMENT_LIB) $(DESTDIR)$(LIBDIR)
#	  install -d $(DESTDIR)$(PREFIX)/include/UsageEnvironment $(DESTDIR)$(LIBDIR)
#	  install -m 644 include/*.hh $(DESTDIR)$(PREFIX)/include/UsageEnvironment
#	  install -m 644 $(USAGE_ENVIRONMENT_LIB) $(DESTDIR)$(LIBDIR)
install_shared_libraries: $(USAGE_ENVIRONMENT_LIB)
	  ln -s $(NAME).$(LIB_SUFFIX) $(DESTDIR)$(LIBDIR)/$(NAME).$(SHORT_LIB_SUFFIX)
	  ln -s $(NAME).$(LIB_SUFFIX) $(DESTDIR)$(LIBDIR)/$(NAME).so

##### Any additional, platform-specific rules come here:
