/*
    Register definition header file for arbiter module.

    This file is the header file that define the address offset and bit
    definition of registers of arbiter module.

    @file       ddr_arb_reg.h
    @ingroup    miDrvComm_Arb
    @note       Nothing.

    Copyright   Novatek Microelectronics Corp. 2019.  All rights reserved.
*/

#ifndef _DDR_ARB_REG_H
#define _DDR_ARB_REG_H

#if defined (__UITRON) || defined(__ECOS)  || defined (__FREERTOS)
#include <rcw_macro.h>
#include <kwrap/nvt_type.h>

#else
#include <linux/soc/nvt/rcw_macro.h>
#include "kwrap/type.h"
#endif

// DDRC
#define DMA_POISONCFG_REG_OFS	   0x36C
REGDEF_BEGIN(DMA_POISONCFG_REG)
REGDEF_BIT(wr_poison_slverr_en, 1)
REGDEF_BIT(, 3)
REGDEF_BIT(wr_poison_intr_en, 1)
REGDEF_BIT(, 3)
REGDEF_BIT(wr_poison_intr_clr, 1)
REGDEF_BIT(, 7)
REGDEF_BIT(rd_poison_slverr_en, 1)
REGDEF_BIT(, 3)
REGDEF_BIT(rd_poison_intr_en, 1)
REGDEF_BIT(, 3)
REGDEF_BIT(rd_poison_intr_clr, 1)
REGDEF_BIT(, 7)
REGDEF_END(DMA_POISONCFG_REG)

#define DMA_POISONSTAT_REG_OFS	   0x370
REGDEF_BEGIN(DMA_POISONSTAT_REG)
REGDEF_BIT(wr_poison_intr_0, 1)
REGDEF_BIT(wr_poison_intr_1, 1)
REGDEF_BIT(wr_poison_intr_2, 1)
REGDEF_BIT(wr_poison_intr_3, 1)
REGDEF_BIT(wr_poison_intr_4, 1)
REGDEF_BIT(wr_poison_intr_5, 1)
REGDEF_BIT(wr_poison_intr_6, 1)
REGDEF_BIT(wr_poison_intr_7, 1)
REGDEF_BIT(, 8)
REGDEF_BIT(rd_poison_intr_0, 1)
REGDEF_BIT(rd_poison_intr_1, 1)
REGDEF_BIT(rd_poison_intr_2, 1)
REGDEF_BIT(rd_poison_intr_3, 1)
REGDEF_BIT(rd_poison_intr_4, 1)
REGDEF_BIT(rd_poison_intr_5, 1)
REGDEF_BIT(rd_poison_intr_6, 1)
REGDEF_BIT(rd_poison_intr_7, 1)
REGDEF_BIT(, 8)
REGDEF_END(DMA_POISONSTAT_REG)

// DDRC port priority related
#define DMA_PCCFG_REG_OFS	   0x400
REGDEF_BEGIN(DMA_PCCFG_REG)
REGDEF_BIT(go2critical_en, 1)
REGDEF_BIT(, 3)
REGDEF_BIT(pagematch_limit, 1)
REGDEF_BIT(, 3)
REGDEF_BIT(bl_exp_mode, 1)
REGDEF_BIT(, 23)
REGDEF_END(DMA_PCCFG_REG)

#define DMA_PCFGR_0_REG_OFS	   0x404
REGDEF_BEGIN(DMA_PCFGR_0_REG)
REGDEF_BIT(rd_port_priority, 10)
REGDEF_BIT(, 2)
REGDEF_BIT(rd_port_aging_en, 1)
REGDEF_BIT(rd_port_urgent_en, 1)
REGDEF_BIT(rd_port_pagematch_en, 1)
REGDEF_BIT(, 1)
REGDEF_BIT(rdwr_ordered_en, 1)
REGDEF_BIT(, 15)
REGDEF_END(DMA_PCFGR_0_REG)

#define DMA_PCFGW_0_REG_OFS	   0x408
REGDEF_BEGIN(DMA_PCFGW_0_REG)
REGDEF_BIT(wr_port_priority, 10)
REGDEF_BIT(, 2)
REGDEF_BIT(wr_port_aging_en, 1)
REGDEF_BIT(wr_port_urgent_en, 1)
REGDEF_BIT(wr_port_pagematch_en, 1)
REGDEF_BIT(, 17)
REGDEF_END(DMA_PCFGW_0_REG)

#define DMA_PCTRL_0_REG_OFS	   0x490

#define DMA_PCFGRQOS0_0_REG_OFS	   0x494
REGDEF_BEGIN(DMA_PCFGRQOS0_0_REG)
REGDEF_BIT(rqos_map_level1, 4)
REGDEF_BIT(, 4)
REGDEF_BIT(rqos_map_level2, 4)
REGDEF_BIT(, 4)
REGDEF_BIT(rqos_map_region1, 2)
REGDEF_BIT(, 2)
REGDEF_BIT(rqos_map_region2, 2)
REGDEF_BIT(, 6)
REGDEF_END(DMA_PCFGRQOS0_0_REG)

#define DMA_PCFGRQOS1_0_REG_OFS	   0x498
REGDEF_BEGIN(DMA_PCFGRQOS1_0_REG)
REGDEF_BIT(rqos_map_timeoutb, 11)
REGDEF_BIT(, 5)
REGDEF_BIT(rqos_map_timeoutr, 11)
REGDEF_BIT(, 5)
REGDEF_END(DMA_PCFGRQOS1_0_REG)

#define DMA_PCFGWQOS0_0_REG_OFS	   0x49C
REGDEF_BEGIN(DMA_PCFGWQOS0_0_REG)
REGDEF_BIT(wqos_map_level1, 4)
REGDEF_BIT(, 4)
REGDEF_BIT(wqos_map_level2, 4)
REGDEF_BIT(, 4)
REGDEF_BIT(wqos_map_region0, 2)
REGDEF_BIT(, 2)
REGDEF_BIT(wqos_map_region1, 2)
REGDEF_BIT(, 2)
REGDEF_BIT(wqos_map_region2, 2)
REGDEF_BIT(, 6)
REGDEF_END(DMA_PCFGWQOS0_0_REG)

#define DMA_PCFGWQOS1_0_REG_OFS	   0x4A0
REGDEF_BEGIN(DMA_PCFGWQOS1_0_REG)
REGDEF_BIT(wqos_map_timeout1, 11)
REGDEF_BIT(, 5)
REGDEF_BIT(wqos_map_timeout2, 11)
REGDEF_BIT(, 5)
REGDEF_END(DMA_PCFGWQOS1_0_REG)




// protect reg
#define DMA_DETECT_CH0_W_REG_OFS   0x00
#define DMA_DETECT_CH1_W_REG_OFS   0x04
#define DMA_DETECT_CH2_W_REG_OFS   0x08
#define DMA_DETECT_CH3_W_REG_OFS   0x0C
#define DMA_DETECT_CH4_W_REG_OFS   0x10
#define DMA_DETECT_CH5_W_REG_OFS   0x14
#define DMA_DETECT_CH6_W_REG_OFS   0x18
#define DMA_DETECT_CH7_W_REG_OFS   0x1C

#define DMA_DETECT_CH0_R_REG_OFS   0x20
#define DMA_DETECT_CH1_R_REG_OFS   0x24
#define DMA_DETECT_CH2_R_REG_OFS   0x28
#define DMA_DETECT_CH3_R_REG_OFS   0x2C
#define DMA_DETECT_CH4_R_REG_OFS   0x30
#define DMA_DETECT_CH5_R_REG_OFS   0x34
#define DMA_DETECT_CH6_R_REG_OFS   0x38
#define DMA_DETECT_CH7_R_REG_OFS   0x3C

#define DMA_PROTECT_CH0_W_REG_OFS   0x40
#define DMA_PROTECT_CH1_W_REG_OFS   0x44
#define DMA_PROTECT_CH2_W_REG_OFS   0x48
#define DMA_PROTECT_CH3_W_REG_OFS   0x4C
#define DMA_PROTECT_CH4_W_REG_OFS   0x50
#define DMA_PROTECT_CH5_W_REG_OFS   0x54
#define DMA_PROTECT_CH6_W_REG_OFS   0x58
#define DMA_PROTECT_CH7_W_REG_OFS   0x5C

#define DMA_PROTECT_CH0_R_REG_OFS   0x60
#define DMA_PROTECT_CH1_R_REG_OFS   0x64
#define DMA_PROTECT_CH2_R_REG_OFS   0x68
#define DMA_PROTECT_CH3_R_REG_OFS   0x6C
#define DMA_PROTECT_CH4_R_REG_OFS   0x70
#define DMA_PROTECT_CH5_R_REG_OFS   0x74
#define DMA_PROTECT_CH6_R_REG_OFS   0x78
#define DMA_PROTECT_CH7_R_REG_OFS   0x7C

#define DMA_RANGE_SEL_REG_OFS		0x80
REGDEF_BEGIN(DMA_RANGE_SEL_REG)
REGDEF_BIT(range_sel_w, 8)
REGDEF_BIT(, 8)
REGDEF_BIT(range_sel_r, 8)
REGDEF_BIT(, 8)
REGDEF_END(DMA_RANGE_SEL_REG)

#define DMA_PROTECT_START_ADDR_REG_OFS		0x88
#define DMA_PROTECT_END_ADDR_REG_OFS		0x8C


// misc
#define DMA_INTE_REG_OFS			0x4020
REGDEF_BEGIN(DMA_INTE_REG)
REGDEF_BIT(awdet_inte, 8)
REGDEF_BIT(ardet_inte, 8)
REGDEF_BIT(awpoison_inte, 8)
REGDEF_BIT(arpoison_inte, 8)
REGDEF_END(DMA_INTE_REG)

#define DMA_INTR_REG_OFS			0x4024
REGDEF_BEGIN(DMA_INTR_REG)
REGDEF_BIT(awdet_intr, 8)
REGDEF_BIT(ardet_intr, 8)
REGDEF_BIT(awpoison_intr, 8)
REGDEF_BIT(arpoison_intr, 8)
REGDEF_END(DMA_INTR_REG)

#define DMA_PERF_INTE_REG_OFS		0x4028
#define DMA_PERF_INTR_REG_OFS		0x402C


#define DMA_DETECT_ID_REG0_OFS		0x4030
REGDEF_BEGIN(DMA_DETECT_ID_REG0)
REGDEF_BIT(ch0_awdet_id, 8)
REGDEF_BIT(ch1_awdet_id, 8)
REGDEF_BIT(ch2_awdet_id, 8)
REGDEF_BIT(ch3_awdet_id, 8)
REGDEF_END(DMA_DETECT_ID_REG0)

#define DMA_DETECT_ID_REG1_OFS		0x4034
REGDEF_BEGIN(DMA_DETECT_ID_REG1)
REGDEF_BIT(ch4_awdet_id, 8)
REGDEF_BIT(ch5_awdet_id, 8)
REGDEF_BIT(ch6_awdet_id, 8)
REGDEF_BIT(ch7_awdet_id, 8)
REGDEF_END(DMA_DETECT_ID_REG1)

#define DMA_DETECT_ID_REG2_OFS		0x4038
REGDEF_BEGIN(DMA_DETECT_ID_REG2)
REGDEF_BIT(ch0_ardet_id, 8)
REGDEF_BIT(ch1_ardet_id, 8)
REGDEF_BIT(ch2_ardet_id, 8)
REGDEF_BIT(ch3_ardet_id, 8)
REGDEF_END(DMA_DETECT_ID_REG2)

#define DMA_DETECT_ID_REG3_OFS		0x403C
REGDEF_BEGIN(DMA_DETECT_ID_REG3)
REGDEF_BIT(ch4_ardet_id, 8)
REGDEF_BIT(ch5_ardet_id, 8)
REGDEF_BIT(ch6_ardet_id, 8)
REGDEF_BIT(ch7_ardet_id, 8)
REGDEF_END(DMA_DETECT_ID_REG3)

#define DMA_DETECT_CH0_ADDR_OFS		0x4050
#define DMA_DETECT_CH1_ADDR_OFS		0x4054
#define DMA_DETECT_CH2_ADDR_OFS		0x4058
#define DMA_DETECT_CH3_ADDR_OFS		0x405C
#define DMA_DETECT_CH4_ADDR_OFS		0x4060
#define DMA_DETECT_CH5_ADDR_OFS		0x4064
#define DMA_DETECT_CH6_ADDR_OFS		0x4068
#define DMA_DETECT_CH7_ADDR_OFS		0x406C



// monitor
#define DMA_PERF_TRIG_REG_OFS		0x00
REGDEF_BEGIN(DMA_PERF_TRIG_REG)
REGDEF_BIT(ddr_perf_trig, 1)
REGDEF_BIT(, 15)
REGDEF_BIT(aw_n_perf_trig, 8)
REGDEF_BIT(ar_n_perf_trig, 8)
REGDEF_END(DMA_PERF_TRIG_REG)

#define DMA_PERF_SEL_REG_OFS		0x04
REGDEF_BEGIN(DMA_PERF_SEL_REG)
REGDEF_BIT(ddr_perf_sel0, 6)
REGDEF_BIT(, 2)
REGDEF_BIT(ddr_perf_sel1, 6)
REGDEF_BIT(, 2)
REGDEF_BIT(ddr_perf_sel2, 6)
REGDEF_BIT(, 2)
REGDEF_BIT(ddr_perf_sel3, 6)
REGDEF_BIT(, 2)
REGDEF_END(DMA_PERF_SEL_REG)

#define DMA_PERF_PERIOD_REG_OFS		0x08


#define DMA_PERF_OUT0_REG_OFS		0x10
#define DMA_PERF_OUT1_REG_OFS		0x14
#define DMA_PERF_OUT2_REG_OFS		0x18
#define DMA_PERF_OUT3_REG_OFS		0x1C

#define DMA_CH0_PERF_SEL_REG_OFS	0x30
#define DMA_CH1_PERF_SEL_REG_OFS	0x34
#define DMA_CH2_PERF_SEL_REG_OFS	0x38
#define DMA_CH3_PERF_SEL_REG_OFS	0x3C
#define DMA_CH4_PERF_SEL_REG_OFS	0x40
#define DMA_CH5_PERF_SEL_REG_OFS	0x44
#define DMA_CH6_PERF_SEL_REG_OFS	0x48
#define DMA_CH7_PERF_SEL_REG_OFS	0x4C

#define DMA_CH0_AWPERF_OUT_REG_OFS	0x50
#define DMA_CH1_AWPERF_OUT_REG_OFS	0x54
#define DMA_CH2_AWPERF_OUT_REG_OFS	0x58
#define DMA_CH3_AWPERF_OUT_REG_OFS	0x5C
#define DMA_CH4_AWPERF_OUT_REG_OFS	0x60
#define DMA_CH5_AWPERF_OUT_REG_OFS	0x64
#define DMA_CH6_AWPERF_OUT_REG_OFS	0x68
#define DMA_CH7_AWPERF_OUT_REG_OFS	0x6C

#define DMA_CH0_ARPERF_OUT_REG_OFS	0x70
#define DMA_CH1_ARPERF_OUT_REG_OFS	0x74
#define DMA_CH2_ARPERF_OUT_REG_OFS	0x78
#define DMA_CH3_ARPERF_OUT_REG_OFS	0x7C
#define DMA_CH4_ARPERF_OUT_REG_OFS	0x80
#define DMA_CH5_ARPERF_OUT_REG_OFS	0x84
#define DMA_CH6_ARPERF_OUT_REG_OFS	0x88
#define DMA_CH7_ARPERF_OUT_REG_OFS	0x8C

// Qos


// heavyload
#define DMA_HEAVY_LOAD_STOP_OFS     (0x58)
REGDEF_BEGIN(DMA_HEAVY_LOAD_STOP_REG)  /* declare register cache type "DMA_CHANNEL0_HEAVY_LOAD_CTRL_REG" begin */
REGDEF_BIT(HVY_TEST_STOP, 1)
REGDEF_BIT(, 31)
REGDEF_END(DMA_HEAVY_LOAD_STOP_REG)    /* declare register cache type "DMA_CHANNEL0_HEAVY_LOAD_CTRL_REG" end */

#define DMA_HEAVY_LOAD_TRIG_OFS     (0x5C)
REGDEF_BEGIN(DMA_HEAVY_LOAD_TRIG_REG)  /* declare register cache type "DMA_CHANNEL0_HEAVY_LOAD_CTRL_REG" begin */
REGDEF_BIT(CH0_TEST_START, 1)
REGDEF_BIT(CH1_TEST_START, 1)
REGDEF_BIT(CH2_TEST_START, 1)
REGDEF_BIT(, 29)
REGDEF_END(DMA_HEAVY_LOAD_TRIG_REG)    /* declare register cache type "DMA_CHANNEL0_HEAVY_LOAD_CTRL_REG" end */

#define DMA_CHANNEL0_HEAVY_LOAD_CTRL_OFS    (0x60)
REGDEF_BEGIN(DMA_CHANNEL0_HEAVY_LOAD_CTRL_REG)  /* declare register cache type "DMA_CHANNEL0_HEAVY_LOAD_CTRL_REG" begin */
REGDEF_BIT(CH0_OUTSTANDING, 1)
REGDEF_BIT(, 1)
REGDEF_BIT(CH0_SKIP_COMPARE, 1)
REGDEF_BIT(, 1)
REGDEF_BIT(CH0_TEST_METHOD, 2)
REGDEF_BIT(CH0_OUTSTANDING_MODE, 2)
REGDEF_BIT(CH0_BURST_LEN, 7)
REGDEF_BIT(RANDOM, 1)
REGDEF_BIT(CH0_TEST_TIMES, 16)
REGDEF_END(DMA_CHANNEL0_HEAVY_LOAD_CTRL_REG)    /* declare register cache type "DMA_CHANNEL0_HEAVY_LOAD_CTRL_REG" end */

#define DMA_CHANNEL0_HEAVY_LOAD_START_ADDR_OFS      (0x64)
#define DMA_CHANNEL0_HEAVY_LOAD_DMA_SIZE_OFS        (0x68)

#define DMA_CHANNEL0_HEAVY_LOAD_WAIT_CYCLE_OFS      (0x6C)
REGDEF_BEGIN(DMA_CHANNEL0_HEAVY_LOAD_WAIT_CYCLE)    /* declare register cache type "DMA_CHANNEL0_HEAVY_LOAD_WAIT_CYCLE" begin */
REGDEF_BIT(INTERVAL_REQ, 10)
REGDEF_BIT(, 6)
REGDEF_BIT(CHECKSUM, 16)
REGDEF_END(DMA_CHANNEL0_HEAVY_LOAD_WAIT_CYCLE)      /* declare register cache type "DMA_CHANNEL0_HEAVY_LOAD_WAIT_CYCLE" end */

#define DMA_HEAVY_LOAD_TEST_XOR_PATTERN_OFS			(0x90)

#define DMA_HEAVY_LOAD_STS_OFS    (0xA0)
REGDEF_BEGIN(DMA_HEAVY_LOAD_STS_REG)  /* declare register cache type "DMA_HEAVY_LOAD_STS_REG" begin */
REGDEF_BIT(HEAVY_LOAD_COMPLETE_STS, 1)
REGDEF_BIT(HEAVY_LOAD_ERROR_STS, 1)
REGDEF_BIT(, 30)
REGDEF_END(DMA_HEAVY_LOAD_STS_REG)    /* declare register cache type "DMA_HEAVY_LOAD_STS_REG" end */

#define DMA_HEAVY_LOAD_ERROR_DATA_OFS               (0xA4)
#define DMA_HEAVY_LOAD_CORRECT_DATA_OFS             (0xA8)
#define DMA_HEAVY_LOAD_CURRENT_ADDR_OFS             (0xAC)

#define DMA_HEAVY_LOAD_TEST_PATTERN0_OFS            (0xD0)
#define DMA_HEAVY_LOAD_TEST_PATTERN1_OFS            (0xD4)
#define DMA_HEAVY_LOAD_TEST_PATTERN2_OFS            (0xD8)
#define DMA_HEAVY_LOAD_TEST_PATTERN3_OFS            (0xDC)

// Monitor
#define MAU_MONITOR_PERIOD_OFS 0x330
REGDEF_BEGIN(MAU_MONITOR_PERIOD_REG)
REGDEF_BIT(COUNTER_START, 1)
REGDEF_BIT(COUNTER_CLEAR, 1)
REGDEF_BIT(, 2)
REGDEF_BIT(MONITOR_PERIOD, 28)
REGDEF_END(MAU_MONITOR_PERIOD_REG)

#define MAU_MONITOR_SETTING_OFS 0x334

#define MAU_MONITOR0_CH_EN_OFS0 0x338
#define MAU_MONITOR0_CH_EN_OFS1 0x33C
#define MAU_MONITOR1_CH_EN_OFS0 0x340
#define MAU_MONITOR1_CH_EN_OFS1 0x344
#define MAU_MONITOR2_CH_EN_OFS0 0x348
#define MAU_MONITOR2_CH_EN_OFS1 0x34C
#define MAU_MONITOR3_CH_EN_OFS0 0x350
#define MAU_MONITOR3_CH_EN_OFS1 0x354

#define MAU_MONITOR0_COUNTER_OUT_OFS 0x360
#define MAU_MONITOR1_COUNTER_OUT_OFS 0x364
#define MAU_MONITOR2_COUNTER_OUT_OFS 0x368
#define MAU_MONITOR3_COUNTER_OUT_OFS 0x36C

#define MAU_MONITOR_AXI_CNT_OFS 0x370
#define MAU_MONITOR_AXI_4WORD_CNT_OFS 0x374
#define MAU_MONITOR_AXI_8WORD_CNT_OFS 0x378
#define MAU_MONITOR_AXI_16WORD_CNT_OFS 0x37C

#define MAU_BUSY_COUNT_OFS 0x600
#define MAU_BUSY_COUNT_DDR4_1X_OFS 0x604
#define MAU_DATA_COUNT_OFS 0x608

// Protect
#define MAU_IN_RANGE_PROTECT0_ENABLE_OFS0 0x440
#define MAU_IN_RANGE_PROTECT1_ENABLE_OFS0 0x448
#define MAU_IN_RANGE_PROTECT2_ENABLE_OFS0 0x450
#define MAU_IN_RANGE_PROTECT3_ENABLE_OFS0 0x458
#define MAU_IN_RANGE_PROTECT4_ENABLE_OFS0 0x460
#define MAU_OUT_RANGE_PROTECT_ENABLE_OFS0 0x468

#define MAU_IN_RANGE_PROTECT0_ENABLE_OFS1 0x444
#define MAU_IN_RANGE_PROTECT1_ENABLE_OFS1 0x44C
#define MAU_IN_RANGE_PROTECT2_ENABLE_OFS1 0x454
#define MAU_IN_RANGE_PROTECT3_ENABLE_OFS1 0x45C
#define MAU_IN_RANGE_PROTECT4_ENABLE_OFS1 0x464
#define MAU_OUT_RANGE_PROTECT_ENABLE_OFS1 0x46C

#define MAU_PROTECT_MODE_OFS 0x48C
REGDEF_BEGIN(MAU_PROTECT_MODE_REG)
REGDEF_BIT(WP0_MODE, 2)
REGDEF_BIT(, 2)
REGDEF_BIT(WP1_MODE, 2)
REGDEF_BIT(, 2)
REGDEF_BIT(WP2_MODE, 2)
REGDEF_BIT(, 2)
REGDEF_BIT(WP3_MODE, 2)
REGDEF_BIT(, 2)
REGDEF_BIT(WP4_MODE, 2)
REGDEF_BIT(, 2)
REGDEF_BIT(OUT_WP_MODE, 2)
REGDEF_BIT(, 10)
REGDEF_END(MAU_PROTECT_MODE_REG)

#define MAU_PROTECT0_START_ADDR 0x490
#define MAU_PROTECT0_END_ADDR 0x494
#define MAU_PROTECT1_START_ADDR 0x498
#define MAU_PROTECT1_END_ADDR 0x49C
#define MAU_PROTECT2_START_ADDR 0x4A0
#define MAU_PROTECT2_END_ADDR 0x4A4
#define MAU_PROTECT3_START_ADDR 0x4A8
#define MAU_PROTECT3_END_ADDR 0x4AC
#define MAU_PROTECT4_START_ADDR 0x4B0
#define MAU_PROTECT4_END_ADDR 0x4B4
#define MAU_OUT_PROTECT_START_ADDR 0x4B8
#define MAU_OUT_PROTECT_END_ADDR 0x4BC

#define MAU_IN_RANGE_CH0_CH3_INFO_OFS 0x4D0
REGDEF_BEGIN(MAU_IN_RANGE_CH0_CH3_INFO_REG)
REGDEF_BIT(CH0_IN_RANGE_STS, 5)
REGDEF_BIT(, 3)
REGDEF_BIT(CH1_IN_RANGE_STS, 5)
REGDEF_BIT(, 3)
REGDEF_BIT(CH2_IN_RANGE_STS, 5)
REGDEF_BIT(, 3)
REGDEF_BIT(CH3_IN_RANGE_STS, 5)
REGDEF_BIT(, 3)
REGDEF_END(MAU_IN_RANGE_CH0_CH3_INFO_REG)

#define MAU_IN_RANGE_CH4_CH7_INFO_OFS 0x4D4
REGDEF_BEGIN(MAU_IN_RANGE_CH4_CH7_INFO_REG)
REGDEF_BIT(CH4_IN_RANGE_STS, 5)
REGDEF_BIT(, 3)
REGDEF_BIT(CH5_IN_RANGE_STS, 5)
REGDEF_BIT(, 3)
REGDEF_BIT(CH6_IN_RANGE_STS, 5)
REGDEF_BIT(, 3)
REGDEF_BIT(CH7_IN_RANGE_STS, 5)
REGDEF_BIT(, 3)
REGDEF_END(MAU_IN_RANGE_CH4_CH7_INFO_REG)

#define MAU_PROTECT_ERR_ADDR_OFS0 0x4E0
#define MAU_PROTECT_ERR_ID_OFS0   0x4E4
#define MAU_PROTECT_ERR_ADDR_OFS1 0x4E8
#define MAU_PROTECT_ERR_ID_OFS1   0x4EC
#define MAU_PROTECT_ERR_ADDR_OFS2 0x4F0
#define MAU_PROTECT_ERR_ID_OFS2   0x4F4
#define MAU_PROTECT_ERR_ADDR_OFS3 0x4F8
#define MAU_PROTECT_ERR_ID_OFS3   0x4FC
#define MAU_PROTECT_ERR_ADDR_OFS4 0x500
#define MAU_PROTECT_ERR_ID_OFS4   0x504
#define MAU_PROTECT_ERR_ADDR_OFS5 0x508
#define MAU_PROTECT_ERR_ID_OFS5   0x50C
#define MAU_PROTECT_ERR_ADDR_OFS6 0x510
#define MAU_PROTECT_ERR_ID_OFS6   0x514
#define MAU_PROTECT_ERR_ADDR_OFS7 0x518
#define MAU_PROTECT_ERR_ID_OFS7   0x51C

// MAU

#define MAU_SETTING_OFS 0x8
REGDEF_BEGIN(MAU_SETTING_REG)
REGDEF_BIT(, 5)
REGDEF_BIT(, 1)
REGDEF_BIT(, 2)
REGDEF_BIT(, 2)
REGDEF_BIT(, 2)
REGDEF_BIT(M_REF_PERIOD_CFG, 13)
REGDEF_BIT(PP_REF_TH_CFG, 1)
REGDEF_BIT(MRS_SETTING, 1)
REGDEF_BIT(DDR4_CFG, 1)
REGDEF_BIT(DRAM_16B_CFG, 1)
REGDEF_BIT(NO_PP_REF_CFG, 1)
REGDEF_BIT(DDDR4_2X_MODE_EN, 1)
REGDEF_BIT(DDDR4_2X_T_CCD_L, 1)
REGDEF_END(MAU_SETTING_REG)

#define MAU_INT_ENABLE_OFS 0x190
REGDEF_BEGIN(MAU_INT_ENABLE_REG)
REGDEF_BIT(ERR_MEM_INT_EN0, 1)
REGDEF_BIT(ERR_MEM_INT_EN1, 1)
REGDEF_BIT(ERR_MEM_INT_EN2, 1)
REGDEF_BIT(ERR_MEM_INT_EN3, 1)
REGDEF_BIT(ERR_MEM_INT_EN4, 1)
REGDEF_BIT(ERR_MEM_INT_EN5, 1)
REGDEF_BIT(ERR_MEM_INT_EN6, 1)
REGDEF_BIT(ERR_MEM_INT_EN7, 1)
REGDEF_BIT(ERR_WT_INT_EN0, 1)
REGDEF_BIT(ERR_WT_INT_EN1, 1)
REGDEF_BIT(ERR_WT_INT_EN2, 1)
REGDEF_BIT(ERR_WT_INT_EN3, 1)
REGDEF_BIT(ERR_WT_INT_EN4, 1)
REGDEF_BIT(ERR_WT_INT_EN5, 1)
REGDEF_BIT(ERR_WT_INT_EN6, 1)
REGDEF_BIT(ERR_WT_INT_EN7, 1)
REGDEF_BIT(READ_TIMEOUT_INT_EN, 1)
REGDEF_BIT(MON_UPDATE_INT_EN, 1)
REGDEF_BIT(, 14)
REGDEF_END(MAU_INT_ENABLE_REG)

#define MAU_INT_STATUS_OFS 0x194
REGDEF_BEGIN(MAU_INT_STATUS_REG)
REGDEF_BIT(ERR_MEM_INT0, 1)
REGDEF_BIT(ERR_MEM_INT1, 1)
REGDEF_BIT(ERR_MEM_INT2, 1)
REGDEF_BIT(ERR_MEM_INT3, 1)
REGDEF_BIT(ERR_MEM_INT4, 1)
REGDEF_BIT(ERR_MEM_INT5, 1)
REGDEF_BIT(ERR_MEM_INT6, 1)
REGDEF_BIT(ERR_MEM_INT7, 1)
REGDEF_BIT(ERR_WT_INT0, 1)
REGDEF_BIT(ERR_WT_INT1, 1)
REGDEF_BIT(ERR_WT_INT2, 1)
REGDEF_BIT(ERR_WT_INT3, 1)
REGDEF_BIT(ERR_WT_INT4, 1)
REGDEF_BIT(ERR_WT_INT5, 1)
REGDEF_BIT(ERR_WT_INT6, 1)
REGDEF_BIT(ERR_WT_INT7, 1)
REGDEF_BIT(READ_TIMEOUT_INT, 1)
REGDEF_BIT(MON_UPDATE_INT, 1)
REGDEF_BIT(, 14)
REGDEF_END(MAU_INT_STATUS_REG)

// Grant count
#define MAU_W_GRANT_CNT 0x61C
#define MAU_R_GRANT_CNT 0x620
REGDEF_BEGIN(MAU_W_GRANT_CNT_REG)
REGDEF_BIT(CH0_W_GRANT_CNT, 4)
REGDEF_BIT(CH1_W_GRANT_CNT, 4)
REGDEF_BIT(CH2_W_GRANT_CNT, 4)
REGDEF_BIT(CH3_W_GRANT_CNT, 4)
REGDEF_BIT(CH4_W_GRANT_CNT, 4)
REGDEF_BIT(CH5_W_GRANT_CNT, 4)
REGDEF_BIT(CH6_W_GRANT_CNT, 4)
REGDEF_BIT(CH7_W_GRANT_CNT, 4)
REGDEF_END(MAU_W_GRANT_CNT_REG)

// Channel disable
#define MAU_CHANNEL_DISABLE 0x62C
REGDEF_BEGIN(MAU_CHANNEL_DISABLE_REG)
REGDEF_BIT(W_CH0_DISABLE, 1)
REGDEF_BIT(W_CH1_DISABLE, 1)
REGDEF_BIT(W_CH2_DISABLE, 1)
REGDEF_BIT(W_CH3_DISABLE, 1)
REGDEF_BIT(W_CH4_DISABLE, 1)
REGDEF_BIT(W_CH5_DISABLE, 1)
REGDEF_BIT(W_CH6_DISABLE, 1)
REGDEF_BIT(W_CH7_DISABLE, 1)
REGDEF_BIT(R_CH0_DISABLE, 1)
REGDEF_BIT(R_CH1_DISABLE, 1)
REGDEF_BIT(R_CH2_DISABLE, 1)
REGDEF_BIT(R_CH3_DISABLE, 1)
REGDEF_BIT(R_CH4_DISABLE, 1)
REGDEF_BIT(R_CH5_DISABLE, 1)
REGDEF_BIT(R_CH6_DISABLE, 1)
REGDEF_BIT(R_CH7_DISABLE, 1)
REGDEF_BIT(W_CH_IDLE, 8)
REGDEF_BIT(R_CH_IDLE, 8)
REGDEF_END(MAU_CHANNEL_DISABLE_REG)

// Priority
#define MAU_W_CH_PRIORITY 0x540
#define MAU_R_CH_PRIORITY 0x550
// Priority threshold
#define MAU_UH_PRIORITY_TH 0x680
#define MAU_LM_PRIORITY_TH 0x684

// dynamic priority
#define MAU_DY_PRIORITY_EN 0x560
#define MAU_DY_PRIORITY    0x564
#endif // _DMAREG_H
