#ifndef __DRIVERS_NVT_TZASC_NS02401_REG_H
#define __DRIVERS_NVT_TZASC_NS02401_REG_H

#include <stdint.h>
#include <trace_levels.h>
#include <types_ext.h>
#include <util.h>
#include <plat/io_address.h>
#include <rcw_macro.h>
#include <kwrap/nvt_type.h>

#ifndef ENUM_DUMMY4WORD
#define ENUM_DUMMY4WORD(name)   E_##name = 0x10000000
#endif

#if defined(_BSP_NA51102_) || defined(_BSP_NS02201_)
// protect reg
#define DMA_DETECT_CH0_W_REG_OFS   0x00
#define DMA_DETECT_CH1_W_REG_OFS   0x04
#define DMA_DETECT_CH2_W_REG_OFS   0x08
#define DMA_DETECT_CH3_W_REG_OFS   0x0C
#define DMA_DETECT_CH4_W_REG_OFS   0x10
#define DMA_DETECT_CH5_W_REG_OFS   0x14
#define DMA_DETECT_CH6_W_REG_OFS   0x18
#define DMA_DETECT_CH7_W_REG_OFS   0x1C

#define DMA_DETECT_CH0_R_REG_OFS   0x20
#define DMA_DETECT_CH1_R_REG_OFS   0x24
#define DMA_DETECT_CH2_R_REG_OFS   0x28
#define DMA_DETECT_CH3_R_REG_OFS   0x2C
#define DMA_DETECT_CH4_R_REG_OFS   0x30
#define DMA_DETECT_CH5_R_REG_OFS   0x34
#define DMA_DETECT_CH6_R_REG_OFS   0x38
#define DMA_DETECT_CH7_R_REG_OFS   0x3C

#define DMA_PROTECT_CH0_W_REG_OFS   0x40
#define DMA_PROTECT_CH1_W_REG_OFS   0x44
#define DMA_PROTECT_CH2_W_REG_OFS   0x48
#define DMA_PROTECT_CH3_W_REG_OFS   0x4C
#define DMA_PROTECT_CH4_W_REG_OFS   0x50
#define DMA_PROTECT_CH5_W_REG_OFS   0x54
#define DMA_PROTECT_CH6_W_REG_OFS   0x58
#define DMA_PROTECT_CH7_W_REG_OFS   0x5C

#define DMA_PROTECT_CH0_R_REG_OFS   0x60
#define DMA_PROTECT_CH1_R_REG_OFS   0x64
#define DMA_PROTECT_CH2_R_REG_OFS   0x68
#define DMA_PROTECT_CH3_R_REG_OFS   0x6C
#define DMA_PROTECT_CH4_R_REG_OFS   0x70
#define DMA_PROTECT_CH5_R_REG_OFS   0x74
#define DMA_PROTECT_CH6_R_REG_OFS   0x78
#define DMA_PROTECT_CH7_R_REG_OFS   0x7C
#define DMA_RANGE_SEL_REG_OFS       0x80
REGDEF_BEGIN(DMA_RANGE_SEL_REG)
REGDEF_BIT(range_sel_w, 8)
REGDEF_BIT(, 8)
REGDEF_BIT(range_sel_r, 8)
REGDEF_BIT(, 8)
REGDEF_END(DMA_RANGE_SEL_REG)

#define DMA_PROTECT_START_ADDR_REG_OFS      0x88
#define DMA_PROTECT_END_ADDR_REG_OFS        0x8C

#elif defined(_BSP_NS02401_)
#define TZASC_ID_REG_OFS   			0x00
#define TZASC_CONFIG_REG0_OFS   	0x04
REGDEF_BEGIN(TZASC_CONFIG_REG0)
REGDEF_BIT(range_sel_w, 4)
REGDEF_BIT(range_sel_r, 4)
REGDEF_BIT(addr0_h, 8)
REGDEF_BIT(addr1_h, 8)
REGDEF_BIT(, 8)
REGDEF_END(TZASC_CONFIG_REG0)
#define TZASC_START_ADDR_REG_OFS 	0x08
#define TZASC_END_ADDR_REG_OFS   	0x0c

#define TZASC_DEBUG_REG0_OFS    	0x80
REGDEF_BEGIN(TZASC_DEBUG_REG0)
REGDEF_BIT(inten, 1)
REGDEF_BIT(error_off, 1)
REGDEF_BIT(, 2)
REGDEF_BIT(rdsel, 4)
REGDEF_BIT(, 24)
REGDEF_END(TZASC_DEBUG_REG0)

#define TZASC_STATUS_REG0_OFS    	0x84
REGDEF_BEGIN(TZASC_STATUS_REG0)
REGDEF_BIT(awsts, 13)
REGDEF_BIT(, 3)
REGDEF_BIT(arsts, 13)
REGDEF_BIT(, 3)
REGDEF_END(TZASC_STATUS_REG0)

#define TZASC_STATUS_REG1_OFS    	0x88
REGDEF_BEGIN(TZASC_STATUS_REG1)
REGDEF_BIT(awusr, 3)
REGDEF_BIT(, 29)
REGDEF_END(TZASC_STATUS_REG1)

#define TZASC_STATUS_REG2_OFS    	0x8c
REGDEF_BEGIN(TZASC_STATUS_REG2)
REGDEF_BIT(arusr, 3)
REGDEF_BIT(, 29)
REGDEF_END(TZASC_STATUS_REG2)

#define TZASC_STATUS_REG3_OFS    	0x90
#define TZASC_STATUS_REG4_OFS    	0x94
#define TZASC_STATUS_REG5_OFS    	0x98
#define TZASC_STATUS_REG6_OFS    	0x9c

#elif defined(_BSP_NS02301_) || defined(_BSP_NA51089_) || defined(_BSP_NA51055_)
#define DMA_PROTECT_CTRL_REG_OFS   0x00
REGDEF_BEGIN(DMA_PROTECT_CTRL_REG)    /* declare register cache type "DMA_PROTECT_CTRL_REG" begin */
REGDEF_BIT(DMA_WPWD0_EN, 1)
REGDEF_BIT(DMA_WPWD1_EN, 1)
REGDEF_BIT(DMA_WPWD2_EN, 1)
REGDEF_BIT(DMA_WPWD3_EN, 1)
REGDEF_BIT(DMA_WPWD4_EN, 1)
REGDEF_BIT(DMA_WPWD5_EN, 1)
REGDEF_BIT(, 2)
REGDEF_BIT(DMA_WPWD0_MODE, 1)
REGDEF_BIT(DMA_WPWD1_MODE, 1)
REGDEF_BIT(DMA_WPWD2_MODE, 1)
REGDEF_BIT(DMA_WPWD3_MODE, 1)
REGDEF_BIT(DMA_WPWD4_MODE, 1)
REGDEF_BIT(DMA_WPWD5_MODE, 1)
REGDEF_BIT(, 2)
REGDEF_BIT(DMA_WPWD0_SEL, 2)
REGDEF_BIT(DMA_WPWD1_SEL, 2)
REGDEF_BIT(DMA_WPWD2_SEL, 2)
REGDEF_BIT(DMA_WPWD3_SEL, 2)
REGDEF_BIT(DMA_WPWD4_SEL, 2)
REGDEF_BIT(DMA_WPWD5_SEL, 2)
REGDEF_BIT(, 4)
REGDEF_END(DMA_PROTECT_CTRL_REG)      /* declare register cache type "DMA_PROTECT_CTRL_REG" end */

#define DMA_PROTECT_REGION_EN_REG0_OFS   0x40
REGDEF_BEGIN(DMA_PROTECT_REGION_EN_REG0)    /* declare register cache type "DMA_PROTECT_CTRL_REG" begin */
REGDEF_BIT(DRAM_PROTECT0_REGIONS_EN, 4)
REGDEF_BIT(, 4)
REGDEF_BIT(DRAM_PROTECT1_REGIONS_EN, 4)
REGDEF_BIT(, 4)
REGDEF_BIT(DRAM_PROTECT2_REGIONS_EN, 4)
REGDEF_BIT(, 4)
REGDEF_BIT(DRAM_PROTECT3_REGIONS_EN, 4)
REGDEF_BIT(, 4)
REGDEF_END(DMA_PROTECT_REGION_EN_REG0)      /* declare register cache type "DMA_PROTECT_CTRL_REG" end */

#define DMA_PROTECT_REGION_EN_REG1_OFS   0x44
REGDEF_BEGIN(DMA_PROTECT_REGION_EN_REG1)    /* declare register cache type "DMA_PROTECT_CTRL_REG" begin */
REGDEF_BIT(DRAM_PROTECT4_REGIONS_EN, 4)
REGDEF_BIT(, 4)
REGDEF_BIT(DRAM_PROTECT5_REGIONS_EN, 4)
REGDEF_BIT(, 20)
REGDEF_END(DMA_PROTECT_REGION_EN_REG1)      /* declare register cache type "DMA_PROTECT_CTRL_REG" end */
///// PROTECT /////
#define DMA_PROTECT_INTCTRL_REG_OFS   0x64
REGDEF_BEGIN(DMA_PROTECT_INTCTRL_REG)    /* declare register cache type "DMA_PROTECT_INTCTRL_REG_OFS" begin */
REGDEF_BIT(DMA_WPWD0_INTEN0, 1)
REGDEF_BIT(DMA_WPWD0_INTEN1, 1)
REGDEF_BIT(DMA_WPWD0_INTEN2, 1)
REGDEF_BIT(DMA_WPWD0_INTEN3, 1)
REGDEF_BIT(DMA_WPWD1_INTEN0, 1)
REGDEF_BIT(DMA_WPWD1_INTEN1, 1)
REGDEF_BIT(DMA_WPWD1_INTEN2, 1)
REGDEF_BIT(DMA_WPWD1_INTEN3, 1)
REGDEF_BIT(DMA_WPWD2_INTEN0, 1)
REGDEF_BIT(DMA_WPWD2_INTEN1, 1)
REGDEF_BIT(DMA_WPWD2_INTEN2, 1)
REGDEF_BIT(DMA_WPWD2_INTEN3, 1)
REGDEF_BIT(DMA_WPWD3_INTEN0, 1)
REGDEF_BIT(DMA_WPWD3_INTEN1, 1)
REGDEF_BIT(DMA_WPWD3_INTEN2, 1)
REGDEF_BIT(DMA_WPWD3_INTEN3, 1)
REGDEF_BIT(DMA_WPWD4_INTEN0, 1)
REGDEF_BIT(DMA_WPWD4_INTEN1, 1)
REGDEF_BIT(DMA_WPWD4_INTEN2, 1)
REGDEF_BIT(DMA_WPWD4_INTEN3, 1)
REGDEF_BIT(DMA_WPWD5_INTEN0, 1)
REGDEF_BIT(DMA_WPWD5_INTEN1, 1)
REGDEF_BIT(DMA_WPWD5_INTEN2, 1)
REGDEF_BIT(DMA_WPWD5_INTEN3, 1)
REGDEF_BIT(AUTO_REFRESH_TIMEOUT_INTEN, 1)
REGDEF_BIT(DMA_OUTRANGE_INTEN, 1)
REGDEF_BIT(DMA_UPDATE_USAGE_INTEN, 1)
REGDEF_BIT(, 5)
REGDEF_END(DMA_PROTECT_INTCTRL_REG)      /* declare register cache type "DMA_PROTECT_INTCTRL_REG_OFS" end */

#define DMA_PROTECT_INTSTS_REG_OFS   0x68
REGDEF_BEGIN(DMA_PROTECT_INTSTS_REG)    /* declare register cache type "DMA_PROTECT_INTSTS_REG_OFS" begin */
REGDEF_BIT(DMA_WPWD0_STS0, 1)
REGDEF_BIT(DMA_WPWD0_STS1, 1)
REGDEF_BIT(DMA_WPWD0_STS2, 1)
REGDEF_BIT(DMA_WPWD0_STS3, 1)
REGDEF_BIT(DMA_WPWD1_STS0, 1)
REGDEF_BIT(DMA_WPWD1_STS1, 1)
REGDEF_BIT(DMA_WPWD1_STS2, 1)
REGDEF_BIT(DMA_WPWD1_STS3, 1)
REGDEF_BIT(DMA_WPWD2_STS0, 1)
REGDEF_BIT(DMA_WPWD2_STS1, 1)
REGDEF_BIT(DMA_WPWD2_STS2, 1)
REGDEF_BIT(DMA_WPWD2_STS3, 1)
REGDEF_BIT(DMA_WPWD3_STS0, 1)
REGDEF_BIT(DMA_WPWD3_STS1, 1)
REGDEF_BIT(DMA_WPWD3_STS2, 1)
REGDEF_BIT(DMA_WPWD3_STS3, 1)
REGDEF_BIT(DMA_WPWD4_STS0, 1)
REGDEF_BIT(DMA_WPWD4_STS1, 1)
REGDEF_BIT(DMA_WPWD4_STS2, 1)
REGDEF_BIT(DMA_WPWD4_STS3, 1)
REGDEF_BIT(DMA_WPWD5_STS0, 1)
REGDEF_BIT(DMA_WPWD5_STS1, 1)
REGDEF_BIT(DMA_WPWD5_STS2, 1)
REGDEF_BIT(DMA_WPWD5_STS3, 1)
REGDEF_BIT(AUTO_REFRESH_TIMEOUT_STS, 1)
REGDEF_BIT(DMA_OUTRANGE_STS, 1)
REGDEF_BIT(DMA_UPDATE_USAGE_STS, 1)
REGDEF_BIT(, 5)
REGDEF_END(DMA_PROTECT_INTSTS_REG)      /* declare register cache type "DMA_PROTECT_INTSTS_REG_OFS" end */
#define DMA_PROTECT_STARTADDR0_REG0_OFS  0x100
REGDEF_BEGIN(DMA_PROTECT_STARTADDR0_REG0)    /* declare register cache type "DMA_PROTECT_STAADR0_REG" begin */
REGDEF_BIT(STA_ADDR, 32)
REGDEF_END(DMA_PROTECT_STARTADDR0_REG0)      /* declare register cache type "DMA_PROTECT_STAADR0_REG" end */

#define DMA_PROTECT_STOPADDR0_REG0_OFS  0x104
REGDEF_BEGIN(DMA_PROTECT_STOPADDR0_REG0)    /* declare register cache type "DMA_PROTECT_STAADR0_REG" begin */
REGDEF_BIT(STP_ADDR, 32)
REGDEF_END(DMA_PROTECT_STOPADDR0_REG0)      /* declare register cache type "DMA_PROTECT_STAADR0_REG" end */

#define DMA_PROTECT_RANGE0_MSK0_REG_OFS 0x200
REGDEF_BEGIN(DMA_PROTECT_RANGE0_MSK0_REG)   /* declare register cache type "DMA_PROTECT_RANGE0_MSK0_REG" begin */
REGDEF_BIT(, 32)
REGDEF_END(DMA_PROTECT_RANGE0_MSK0_REG)     /* declare register cache type "DMA_PROTECT_RANGE0_MSK0_REG" end */

#define DMA_PROTECT_RANGE0_MSK1_REG_OFS 0x204
REGDEF_BEGIN(DMA_PROTECT_RANGE0_MSK1_REG)   /* declare register cache type "DMA_PROTECT_RANGE0_MSK1_REG" begin */
REGDEF_BIT(, 32)
REGDEF_END(DMA_PROTECT_RANGE0_MSK1_REG)     /* declare register cache type "DMA_PROTECT_RANGE0_MSK1_REG" end */

#define DMA_PROTECT_RANGE0_MSK2_REG_OFS 0x208
REGDEF_BEGIN(DMA_PROTECT_RANGE0_MSK2_REG)   /* declare register cache type "DMA_PROTECT_RANGE0_MSK2_REG" begin */
REGDEF_BIT(, 32)
REGDEF_END(DMA_PROTECT_RANGE0_MSK2_REG)     /* declare register cache type "DMA_PROTECT_RANGE0_MSK2_REG" end */

#define DMA_PROTECT_RANGE0_MSK3_REG_OFS 0x20C
REGDEF_BEGIN(DMA_PROTECT_RANGE0_MSK3_REG)   /* declare register cache type "DMA_PROTECT_RANGE0_MSK3_REG" begin */
REGDEF_BIT(, 32)
REGDEF_END(DMA_PROTECT_RANGE0_MSK3_REG)     /* declare register cache type "DMA_PROTECT_RANGE0_MSK3_REG" end */

#define DMA_PROTECT_RANGE0_MSK4_REG_OFS 0x210
REGDEF_BEGIN(DMA_PROTECT_RANGE0_MSK4_REG)   /* declare register cache type "DMA_PROTECT_RANGE0_MSK4_REG" begin */
REGDEF_BIT(, 32)
REGDEF_END(DMA_PROTECT_RANGE0_MSK4_REG)     /* declare register cache type "DMA_PROTECT_RANGE0_MSK4_REG" end */

#define DMA_PROTECT_RANGE0_MSK5_REG_OFS 0x214
REGDEF_BEGIN(DMA_PROTECT_RANGE0_MSK5_REG)   /* declare register cache type "DMA_PROTECT_RANGE0_MSK5_REG" begin */
REGDEF_BIT(, 32)
REGDEF_END(DMA_PROTECT_RANGE0_MSK5_REG)     /* declare register cache type "DMA_PROTECT_RANGE0_MSK5_REG" end */
#else
#define MAU_INT_ENABLE_OFS 0x190
REGDEF_BEGIN(MAU_INT_ENABLE_REG)
REGDEF_BIT(ERR_MEM_INT_EN0, 1)
REGDEF_BIT(ERR_MEM_INT_EN1, 1)
REGDEF_BIT(ERR_MEM_INT_EN2, 1)
REGDEF_BIT(ERR_MEM_INT_EN3, 1)
REGDEF_BIT(ERR_MEM_INT_EN4, 1)
REGDEF_BIT(ERR_MEM_INT_EN5, 1)
REGDEF_BIT(ERR_MEM_INT_EN6, 1)
REGDEF_BIT(ERR_MEM_INT_EN7, 1)
REGDEF_BIT(ERR_WT_INT_EN0, 1)
REGDEF_BIT(ERR_WT_INT_EN1, 1)
REGDEF_BIT(ERR_WT_INT_EN2, 1)
REGDEF_BIT(ERR_WT_INT_EN3, 1)
REGDEF_BIT(ERR_WT_INT_EN4, 1)
REGDEF_BIT(ERR_WT_INT_EN5, 1)
REGDEF_BIT(ERR_WT_INT_EN6, 1)
REGDEF_BIT(ERR_WT_INT_EN7, 1)
REGDEF_BIT(READ_TIMEOUT_INT_EN, 1)
REGDEF_BIT(MON_UPDATE_INT_EN, 1)
REGDEF_BIT(, 14)
REGDEF_END(MAU_INT_ENABLE_REG)

#define MAU_INT_STATUS_OFS 0x194
REGDEF_BEGIN(MAU_INT_STATUS_REG)
REGDEF_BIT(ERR_MEM_INT0, 1)
REGDEF_BIT(ERR_MEM_INT1, 1)
REGDEF_BIT(ERR_MEM_INT2, 1)
REGDEF_BIT(ERR_MEM_INT3, 1)
REGDEF_BIT(ERR_MEM_INT4, 1)
REGDEF_BIT(ERR_MEM_INT5, 1)
REGDEF_BIT(ERR_MEM_INT6, 1)
REGDEF_BIT(ERR_MEM_INT7, 1)
REGDEF_BIT(ERR_WT_INT0, 1)
REGDEF_BIT(ERR_WT_INT1, 1)
REGDEF_BIT(ERR_WT_INT2, 1)
REGDEF_BIT(ERR_WT_INT3, 1)
REGDEF_BIT(ERR_WT_INT4, 1)
REGDEF_BIT(ERR_WT_INT5, 1)
REGDEF_BIT(ERR_WT_INT6, 1)
REGDEF_BIT(ERR_WT_INT7, 1)
REGDEF_BIT(READ_TIMEOUT_INT, 1)
REGDEF_BIT(MON_UPDATE_INT, 1)
REGDEF_BIT(, 14)
REGDEF_END(MAU_INT_STATUS_REG)

#define MAU_PROTECT_MODE_OFS 0x48C
REGDEF_BEGIN(MAU_PROTECT_MODE_REG)
REGDEF_BIT(WP0_MODE, 2)
REGDEF_BIT(, 2)
REGDEF_BIT(WP1_MODE, 2)
REGDEF_BIT(, 2)
REGDEF_BIT(WP2_MODE, 2)
REGDEF_BIT(, 2)
REGDEF_BIT(WP3_MODE, 2)
REGDEF_BIT(, 2)
REGDEF_BIT(WP4_MODE, 2)
REGDEF_BIT(, 2)
REGDEF_BIT(OUT_WP_MODE, 2)
REGDEF_BIT(, 10)
REGDEF_END(MAU_PROTECT_MODE_REG)

// Protect
#define MAU_IN_RANGE_PROTECT0_ENABLE_OFS0 0x440
#define MAU_IN_RANGE_PROTECT1_ENABLE_OFS0 0x448
#define MAU_IN_RANGE_PROTECT2_ENABLE_OFS0 0x450
#define MAU_IN_RANGE_PROTECT3_ENABLE_OFS0 0x458
#define MAU_IN_RANGE_PROTECT4_ENABLE_OFS0 0x460
#define MAU_OUT_RANGE_PROTECT_ENABLE_OFS0 0x468

#define MAU_IN_RANGE_PROTECT0_ENABLE_OFS1 0x444
#define MAU_IN_RANGE_PROTECT1_ENABLE_OFS1 0x44C
#define MAU_IN_RANGE_PROTECT2_ENABLE_OFS1 0x454
#define MAU_IN_RANGE_PROTECT3_ENABLE_OFS1 0x45C
#define MAU_IN_RANGE_PROTECT4_ENABLE_OFS1 0x464
#define MAU_OUT_RANGE_PROTECT_ENABLE_OFS1 0x46C

#define MAU_PROTECT0_START_ADDR     0x490
#define MAU_PROTECT0_END_ADDR       0x494
#define MAU_PROTECT1_START_ADDR     0x498
#define MAU_PROTECT1_END_ADDR       0x49C
#define MAU_PROTECT2_START_ADDR     0x4A0
#define MAU_PROTECT2_END_ADDR       0x4A4
#define MAU_PROTECT3_START_ADDR     0x4A8
#define MAU_PROTECT3_END_ADDR       0x4AC
#define MAU_PROTECT4_START_ADDR     0x4B0
#define MAU_PROTECT4_END_ADDR       0x4B4
#define MAU_OUT_PROTECT_START_ADDR  0x4B8
#define MAU_OUT_PROTECT_END_ADDR    0x4BC
#endif
#endif
