#ifndef _TOUCH_DTSI_H_
#define _TOUCH_DTSI_H_

#define TOUCH_DTSI_NAME_LENGTH    256
#define TOUCH_NODE_NAME_LENGTH    24


typedef enum _TOUCH_DTSI_ITEM {

	TOUCH_DTSI_I2C_ID,
	TOUCH_DTSI_I2C_ADDR,

	TOUCH_DTSI_GPIO_PWR_PIN,
	TOUCH_DTSI_GPIO_RST_PIN,
	TOUCH_DTSI_GPIO_INT_PIN,

	TOUCH_DTSI_RESET_TIME,
	TOUCH_DTSI_ITEM_MAX_NUM,
	ENUM_DUMMY4WORD(TOUCH_DTSI_ITEM)
} TOUCH_DTSI_ITEM;


typedef struct _TOUCH_DTSI_INFO {
	CHAR node_path[TOUCH_DTSI_NAME_LENGTH];
	CHAR file_path[TOUCH_DTSI_NAME_LENGTH];
	UINT8 *buf_addr;
} TOUCH_DTSI_INFO;

typedef struct _TOUCH_DTSI_FILE {
	CHAR node_name[TOUCH_NODE_NAME_LENGTH];
	CHAR data_name[TOUCH_NODE_NAME_LENGTH];
	UINT8 *pdata;
	INT32 size;
} TOUCH_DTSI_FILE;

typedef struct _TOUCH_DTSI {
	CHAR item_name[TOUCH_NODE_NAME_LENGTH];
	CHAR data_name[TOUCH_NODE_NAME_LENGTH];
	UINT32 tmp_buf;
} TOUCH_DTSI;


#endif

