/*
    Crypto driver register definition

    Crypto idriver register definition.

    @file       crypto_reg.h
    @ingroup    mIDrvMisc_Crypto
    @note       Nothing

    Copyright   Novatek Microelectronics Corp. 2020.  All rights reserved.
*/

#ifndef _CRYPTO_REG_H
#define _CRYPTO_REG_H

#include <rcw_macro.h>

REGDEF_OFFSET(CRYPTO_CONFIG_REG,   0x00)
REGDEF_BEGIN(CRYPTO_CONFIG_REG)
    REGDEF_BIT(SWRST        ,1) //0
    REGDEF_BIT(CRYPTO_EN    ,1) //1
    REGDEF_BIT(             ,2) //3..2
    REGDEF_BIT(MODE         ,2) //5..4
    REGDEF_BIT(             ,2) //7..6
    REGDEF_BIT(TYPE         ,1) //8
    REGDEF_BIT(             ,23)//31..9
REGDEF_END(CRYPTO_CONFIG_REG)

REGDEF_OFFSET(CRYPTO_CONTROL_REG,     0x04)
REGDEF_BEGIN(CRYPTO_CONTROL_REG)
    REGDEF_BIT(PIO_EN       ,1) //0
    REGDEF_BIT(PIO_CLR      ,1) //1
    REGDEF_BIT(             ,2) //3..2
    REGDEF_BIT(DMA_CH0_EN   ,1) //4
    REGDEF_BIT(DMA_CH1_EN   ,1) //5
    REGDEF_BIT(DMA_CH2_EN   ,1) //6
    REGDEF_BIT(DMA_CH3_EN   ,1) //7
    REGDEF_BIT(DMA_CH0_CLR  ,1) //8
    REGDEF_BIT(DMA_CH1_CLR  ,1) //9
    REGDEF_BIT(DMA_CH2_CLR  ,1) //10
    REGDEF_BIT(DMA_CH3_CLR  ,1) //11
    REGDEF_BIT(             ,20)//31..12
REGDEF_END(CRYPTO_CONTROL_REG)

REGDEF_OFFSET(CRYPTO_INT_EN_REG,      0x08)
REGDEF_BEGIN(CRYPTO_INT_EN_REG)
    REGDEF_BIT(PIO_DONE_EN  ,1) //0
    REGDEF_BIT(             ,3) //3..1
    REGDEF_BIT(CH0_DONE_EN  ,1) //4
    REGDEF_BIT(CH1_DONE_EN  ,1) //5
    REGDEF_BIT(CH2_DONE_EN  ,1) //6
    REGDEF_BIT(CH3_DONE_EN  ,1) //7
    REGDEF_BIT(CH0_BLKED_EN ,1) //8
    REGDEF_BIT(CH1_BLKED_EN ,1) //9
    REGDEF_BIT(CH2_BLKED_EN ,1) //10
    REGDEF_BIT(CH3_BLKED_EN ,1) //11
    REGDEF_BIT(             ,20)//31..12
REGDEF_END(CRYPTO_INT_EN_REG)

REGDEF_OFFSET(CRYPTO_INT_STS_REG,     0x0C)
REGDEF_BEGIN(CRYPTO_INT_STS_REG)
    REGDEF_BIT(PIO_DONE_STS ,1) //0
    REGDEF_BIT(             ,3) //3..1
    REGDEF_BIT(CH0_DONE_STS ,1) //4
    REGDEF_BIT(CH1_DONE_STS ,1) //5
    REGDEF_BIT(CH2_DONE_STS ,1) //6
    REGDEF_BIT(CH3_DONE_STS ,1) //7
    REGDEF_BIT(CH0_BLKED_STS,1) //8
    REGDEF_BIT(CH1_BLKED_STS,1) //9
    REGDEF_BIT(CH2_BLKED_STS,1) //10
    REGDEF_BIT(CH3_BLKED_STS,1) //11
    REGDEF_BIT(             ,4) //15..12
    REGDEF_BIT(DMA_CURR_CH0 ,1) //16
    REGDEF_BIT(DMA_CURR_CH1 ,1) //17
    REGDEF_BIT(DMA_CURR_CH2 ,1) //18
    REGDEF_BIT(DMA_CURR_CH3 ,1) //19
    REGDEF_BIT(DMA_CURR_PIO ,1) //20
    REGDEF_BIT(             ,3) //23..21
    REGDEF_BIT(DMA_CURR_BLK ,8) //31..24
REGDEF_END(CRYPTO_INT_STS_REG)

REGDEF_OFFSET(CRYPTO_KEY0_REG,        0x10)
REGDEF_OFFSET(CRYPTO_KEY1_REG,        0x14)
REGDEF_OFFSET(CRYPTO_KEY2_REG,        0x18)
REGDEF_OFFSET(CRYPTO_KEY3_REG,        0x1C)
REGDEF_OFFSET(CRYPTO_KEY4_REG,        0x20)
REGDEF_OFFSET(CRYPTO_KEY5_REG,        0x24)
REGDEF_OFFSET(CRYPTO_KEY6_REG,        0x28)
REGDEF_OFFSET(CRYPTO_KEY7_REG,        0x2C)

REGDEF_OFFSET(CRYPTO_INPUT_0_REG,     0x30)
REGDEF_OFFSET(CRYPTO_INPUT_1_REG,     0x34)
REGDEF_OFFSET(CRYPTO_INPUT_2_REG,     0x38)
REGDEF_OFFSET(CRYPTO_INPUT_3_REG,     0x3C)

REGDEF_OFFSET(CRYPTO_OUTPUT_0_REG,    0x40)
REGDEF_OFFSET(CRYPTO_OUTPUT_1_REG,    0x44)
REGDEF_OFFSET(CRYPTO_OUTPUT_2_REG,    0x48)
REGDEF_OFFSET(CRYPTO_OUTPUT_3_REG,    0x4C)

REGDEF_OFFSET(CRYPTO_DMA_CH0_ADDR_REG,0x50)
REGDEF_BEGIN(CRYPTO_DMA_CH0_ADDR_REG)
    REGDEF_BIT(CH0_ADDR              ,32)
REGDEF_END(CRYPTO_DMA_CH0_ADDR_REG)

REGDEF_OFFSET(CRYPTO_DMA_CH1_ADDR_REG,0x54)
REGDEF_BEGIN(CRYPTO_DMA_CH1_ADDR_REG)
    REGDEF_BIT(CH1_ADDR              ,32)
REGDEF_END(CRYPTO_DMA_CH1_ADDR_REG)

REGDEF_OFFSET(CRYPTO_DMA_CH2_ADDR_REG,0x58)
REGDEF_BEGIN(CRYPTO_DMA_CH2_ADDR_REG)
    REGDEF_BIT(CH2_ADDR              ,32)
REGDEF_END(CRYPTO_DMA_CH2_ADDR_REG)

REGDEF_OFFSET(CRYPTO_DMA_CH3_ADDR_REG,0x5C)
REGDEF_BEGIN(CRYPTO_DMA_CH3_ADDR_REG)
    REGDEF_BIT(CH3_ADDR              ,32)
REGDEF_END(CRYPTO_DMA_CH3_ADDR_REG)

REGDEF_OFFSET(CRYPTO_KEY_READ_REG,    0x60)
REGDEF_BEGIN(CRYPTO_KEY_READ_REG)
    REGDEF_BIT(KEY0                  ,1)
    REGDEF_BIT(KEY1                  ,1)
    REGDEF_BIT(KEY2                  ,1)
    REGDEF_BIT(KEY3                  ,1)
    REGDEF_BIT(KEY4                  ,1)
    REGDEF_BIT(KEY5                  ,1)
    REGDEF_BIT(KEY6                  ,1)
    REGDEF_BIT(KEY7                  ,1)
    REGDEF_BIT(                      ,24)
REGDEF_END(CRYPTO_KEY_READ_REG)

REGDEF_OFFSET(CRYPTO_DMA_BUS_CTRL_REG,    0x68)
REGDEF_BEGIN(CRYPTO_BUS_CTRL_REG)        /* BUS IO Control Register */
REGDEF_BIT(MONI_WOSTD_NUM, 8)
REGDEF_BIT(MONI_ROSTD_NUM, 8)
REGDEF_BIT(MONI_CH_DIS, 1)
REGDEF_BIT(MONI_CH_IDLE, 1)
REGDEF_BIT(DMA_WRAP_EN, 1)
REGDEF_BIT(DMA_LOCK_DIS, 1)
REGDEF_BIT(, 12)
REGDEF_END(CRYPTO_DMA_BUS_CTRL_REG)          /* BUS IO Control Register */

REGDEF_OFFSET(CRYPTO_DMA_CH0_ADDR_H_REG,0x70)
REGDEF_BEGIN(CRYPTO_DMA_CH0_ADDR_H_REG)
    REGDEF_BIT(CH0_ADDR_H              ,8)
    REGDEF_BIT(                        ,24)
REGDEF_END(CRYPTO_DMA_CH0_ADDR_H_REG)

REGDEF_OFFSET(CRYPTO_DMA_CH1_ADDR_H_REG,0x74)
REGDEF_BEGIN(CRYPTO_DMA_CH1_ADDR_H_REG)
    REGDEF_BIT(CH1_ADDR_H              ,8)
    REGDEF_BIT(                        ,24)
REGDEF_END(CRYPTO_DMA_CH1_ADDR_H_REG)

REGDEF_OFFSET(CRYPTO_DMA_CH2_ADDR_H_REG,0x78)
REGDEF_BEGIN(CRYPTO_DMA_CH2_ADDR_H_REG)
    REGDEF_BIT(CH2_ADDR_H              ,8)
    REGDEF_BIT(                        ,24)
REGDEF_END(CRYPTO_DMA_CH2_ADDR_H_REG)

REGDEF_OFFSET(CRYPTO_DMA_CH3_ADDR_H_REG,0x7C)
REGDEF_BEGIN(CRYPTO_DMA_CH3_ADDR_H_REG)
    REGDEF_BIT(CH3_ADDR_H              ,8)
    REGDEF_BIT(                        ,24)
REGDEF_END(CRYPTO_DMA_CH3_ADDR_H_REG)

#endif  /* _CRYPTO_REG_H */
