/*
    Copyright   Novatek Microelectronics Corp. 2007.  All rights reserved.

    @file       USIDCVerInfo.c
    @ingroup    mIAPP

    @brief      USIDC version and build date information
                USIDC version and build date information

    @note       This file is generated by CreateAppVer.bat

    @version    V1.92.000
    @author     Lily Kao
    @date       2010/12/17
*/

/** \addtogroup mIAPP */
//@{
#include <kwrap/verinfo.h>

VOS_MODULE_VERSION(UVAC, 1, 00, 015, 00)

//@}


