#ifndef __NVT_CRYPTO_PROTECTED_H__
#define __NVT_CRYPTO_PROTECTED_H__

#include "nvt_pll_cfg.h"

#if defined(__FREERTOS) || defined(__OPTEEOS)

#if !defined(_BSP_NA51090_) && !defined(_BSP_NA51089_) && !defined(_BSP_NA51055_)
#define HOST_AXI_CH
#endif

#if defined(_BSP_NA51055_) || defined(_BSP_NA51090_) \
    || defined(_BSP_NA51102_) || defined(_BSP_NA51103_) \
    || defined(_BSP_NS02201_) || defined(_BSP_NS02302_) \
    || defined(_BSP_NS02401_)
#define RSA4096_SUPPORT
#endif

#define PLL_NOT_SUPPORT 1000

#if defined(_BSP_NA51055_)
typedef enum {
    CRYPTO_CLKSEL0 = PLL_CLKSEL_CRYPTO_240,
    CRYPTO_CLKSEL1 = PLL_CLKSEL_CRYPTO_320,
    CRYPTO_CLKSEL2 = PLL_CLKSEL_CRYPTO_PLL9,
} CRYPTO_CLKSEL;

typedef enum {
    HASH_CLKSEL0 = PLL_CLKSEL_HASH_240,
    HASH_CLKSEL1 = PLL_CLKSEL_HASH_320,
    HASH_CLKSEL2 = PLL_CLKSEL_HASH_PLL9,
} HASH_CLKSEL;

typedef enum {
    RSA_CLKSEL0 = PLL_CLKSEL_RSA_240,
    RSA_CLKSEL1 = PLL_CLKSEL_RSA_320,
    RSA_CLKSEL2 = PLL_CLKSEL_RSA_PLL9,
} RSA_CLKSEL;

#define PLL_FREE
#define CLKSELMAX   3

#elif defined(_BSP_NA51089_)
typedef enum {
    CRYPTO_CLKSEL0 = PLL_CLKSEL_CRYPTO_240,
    CRYPTO_CLKSEL1 = PLL_CLKSEL_CRYPTO_320,
    CRYPTO_CLKSEL2 = PLL_CLKSEL_CRYPTO_PLL9,
} CRYPTO_CLKSEL;

typedef enum {
    HASH_CLKSEL0 = PLL_CLKSEL_HASH_240,
    HASH_CLKSEL1 = PLL_CLKSEL_HASH_320,
    HASH_CLKSEL2 = PLL_CLKSEL_HASH_PLL9,
} HASH_CLKSEL;

typedef enum {
    RSA_CLKSEL0 = PLL_CLKSEL_RSA_240,
    RSA_CLKSEL1 = PLL_CLKSEL_RSA_320,
    RSA_CLKSEL2 = PLL_CLKSEL_RSA_PLL9,
} RSA_CLKSEL;

#define PLL_FREE
#define CLKSELMAX   3

#elif defined(_BSP_NA51090_)
typedef enum {
    CRYPTO_CLKSEL0 = PLL_CLKSEL_CRYPTO_PLL2,
    CRYPTO_CLKSEL1 = PLL_CLKSEL_CRYPTO_PLL13,
    CRYPTO_CLKSEL2 = PLL_NOT_SUPPORT,
} CRYPTO_CLKSEL;

typedef enum {
    HASH_CLKSEL0 = PLL_CLKSEL_HASH_PLL2,
    HASH_CLKSEL1 = PLL_CLKSEL_HASH_PLL13,
    HASH_CLKSEL2 = PLL_NOT_SUPPORT,
} HASH_CLKSEL;

typedef enum {
    RSA_CLKSEL0 = PLL_CLKSEL_RSA_PLL2,
    RSA_CLKSEL1 = PLL_CLKSEL_RSA_PLL13,
    RSA_CLKSEL2 = PLL_NOT_SUPPORT,
} RSA_CLKSEL;

typedef enum {
    PLLEN0 = PLL_ID_2,
    PLLEN1 = PLL_ID_13,
} PLL_EN;

#define CLKSELMAX   2

#elif defined(_BSP_NA51102_)
typedef enum {
    CRYPTO_CLKSEL0 = PLL_CLKSEL_CRYPTO_PLL2,
    CRYPTO_CLKSEL1 = PLL_CLKSEL_CRYPTO_PLL13,
    CRYPTO_CLKSEL2 = PLL_NOT_SUPPORT,
} CRYPTO_CLKSEL;

typedef enum {
    HASH_CLKSEL0 = PLL_CLKSEL_HASH_PLL2,
    HASH_CLKSEL1 = PLL_CLKSEL_HASH_PLL13,
    HASH_CLKSEL2 = PLL_NOT_SUPPORT,
} HASH_CLKSEL;

typedef enum {
    RSA_CLKSEL0 = PLL_CLKSEL_RSA_PLL2,
    RSA_CLKSEL1 = PLL_CLKSEL_RSA_PLL13,
    RSA_CLKSEL2 = PLL_NOT_SUPPORT,
} RSA_CLKSEL;

typedef enum {
    PLLEN0 = PLL_ID_2,
    PLLEN1 = PLL_ID_13,
} PLL_EN;

#define CLKSELMAX   2

#elif defined(_BSP_NA51103_)
typedef enum {
    CRYPTO_CLKSEL0 = PLL_CLKSEL_CRYPTO_PLL2,
    CRYPTO_CLKSEL1 = PLL_CLKSEL_CRYPTO_PLL13,
    CRYPTO_CLKSEL2 = PLL_NOT_SUPPORT,
} CRYPTO_CLKSEL;

typedef enum {
    HASH_CLKSEL0 = PLL_CLKSEL_HASH_PLL2,
    HASH_CLKSEL1 = PLL_CLKSEL_HASH_PLL13,
    HASH_CLKSEL2 = PLL_NOT_SUPPORT,
} HASH_CLKSEL;

typedef enum {
    RSA_CLKSEL0 = PLL_CLKSEL_RSA_PLL2,
    RSA_CLKSEL1 = PLL_CLKSEL_RSA_PLL13,
    RSA_CLKSEL2 = PLL_NOT_SUPPORT, 
} RSA_CLKSEL;

typedef enum {
    PLLEN0 = PLL_ID_2,
    PLLEN1 = PLL_ID_13,
} PLL_EN;

#define CLKSELMAX   2

#elif defined(_BSP_NS02201_)
typedef enum {
    CRYPTO_CLKSEL0 = PLL_CLKSEL_CRYPTO_PLL13,
    CRYPTO_CLKSEL1 = PLL_CLKSEL_CRYPTO_FIX320,
    CRYPTO_CLKSEL2 = PLL_NOT_SUPPORT,
} CRYPTO_CLKSEL;

typedef enum {
    HASH_CLKSEL0 = PLL_CLKSEL_HASH_PLL13,
    HASH_CLKSEL1 = PLL_CLKSEL_HASH_FIX320,
    HASH_CLKSEL2 = PLL_NOT_SUPPORT,
} HASH_CLKSEL;

typedef enum {
    RSA_CLKSEL0 = PLL_CLKSEL_RSA_PLL13,
    RSA_CLKSEL1 = PLL_CLKSEL_RSA_FIX320,
} RSA_CLKSEL;

typedef enum {
    PLLEN0 = PLL_ID_13,
} PLL_EN;

#define CLKSELMAX   2

#elif defined(_BSP_NS02301_)
typedef enum {
    CRYPTO_CLKSEL0 = PLL_CLKSEL_CRYPTO_240,
    CRYPTO_CLKSEL1 = PLL_CLKSEL_CRYPTO_320,
    CRYPTO_CLKSEL2 = PLL_CLKSEL_CRYPTO_PLL6,
} CRYPTO_CLKSEL;

typedef enum {
    HASH_CLKSEL0 = PLL_CLKSEL_HASH_240,
    HASH_CLKSEL1 = PLL_CLKSEL_HASH_320,
    HASH_CLKSEL2 = PLL_CLKSEL_HASH_PLL6,
} HASH_CLKSEL;

typedef enum {
    RSA_CLKSEL0 = PLL_CLKSEL_RSA_240,
    RSA_CLKSEL1 = PLL_CLKSEL_RSA_320,
    RSA_CLKSEL2 = PLL_CLKSEL_RSA_PLL6,
} RSA_CLKSEL;

typedef enum {
    ECDSA_CLKSEL0 = PLL_CLKSEL_ECDSA_240,
    ECDSA_CLKSEL1 = PLL_CLKSEL_ECDSA_320,
    ECDSA_CLKSEL2 = PLL_CLKSEL_ECDSA_PLL6,
} ECDSA_CLKSEL;

#define PLL_FREE
#define CLKSELMAX   3

#elif defined(_BSP_NS02302_)
typedef enum {
    CRYPTO_CLKSEL0 = PLL_CLKSEL_CRYPTO_240,
    CRYPTO_CLKSEL1 = PLL_CLKSEL_CRYPTO_320,
    CRYPTO_CLKSEL2 = PLL_CLKSEL_CRYPTO_PLL9,
} CRYPTO_CLKSEL;

typedef enum {
    HASH_CLKSEL0 = PLL_CLKSEL_HASH_240,
    HASH_CLKSEL1 = PLL_CLKSEL_HASH_320,
    HASH_CLKSEL2 = PLL_CLKSEL_HASH_PLL9,
} HASH_CLKSEL;

typedef enum {
    RSA_CLKSEL0 = PLL_CLKSEL_RSA_240,
    RSA_CLKSEL1 = PLL_CLKSEL_RSA_320,
    RSA_CLKSEL2 = PLL_CLKSEL_RSA_PLL9,
} RSA_CLKSEL;

typedef enum {
    ECDSA_CLKSEL0 = PLL_CLKSEL_ECDSA_240,
    ECDSA_CLKSEL1 = PLL_CLKSEL_ECDSA_320,
    ECDSA_CLKSEL2 = PLL_CLKSEL_ECDSA_PLL9,
} ECDSA_CLKSEL;

#define PLL_FREE
#define CLKSELMAX   3

#elif defined(_BSP_NS02401_)
typedef enum {
    CRYPTO_CLKSEL0 = PLL_CLKSEL_CRYPTO_PLL13,
    CRYPTO_CLKSEL1 = PLL_CLKSEL_CRYPTO_320,
} CRYPTO_CLKSEL;

typedef enum {
    HASH_CLKSEL0 = PLL_CLKSEL_HASH_PLL13,
    HASH_CLKSEL1 = PLL_CLKSEL_HASH_320,
} HASH_CLKSEL;

typedef enum {
    RSA_CLKSEL0 = PLL_CLKSEL_RSA_PLL13,
    RSA_CLKSEL1 = PLL_CLKSEL_RSA_320,
} RSA_CLKSEL;

typedef enum {
    ECDSA_CLKSEL0 = PLL_CLKSEL_ECDSA_PLL13,
    ECDSA_CLKSEL1 = PLL_CLKSEL_ECDSA_320,
} ECDSA_CLKSEL;

#define PLL_FREE
#define CLKSELMAX   2
#endif

#endif
#endif