# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (c) 2021 Novateck, Inc
#
ifneq ($(CONFIG_TARGET_NA51090_A64),y)
obj-$(CONFIG_DISP_IF8B_LCD1_PW35P00_HX8238D) += disp_if8b_lcd1_pw35p00_hx8238d/
obj-$(CONFIG_DISP_IF8B_LCD1_AUCN01) += disp_if8b_lcd1_aucn01/
obj-$(CONFIG_DISP_IF8B_LCD1_PSD300) += disp_if8b_lcd1_psd300_ili8961/
obj-$(CONFIG_DISP_IF8B_LCD1_TP2803) += disp_if8b_lcd1_tp2803/
obj-$(CONFIG_DISP_IFDSI_LCD1_UT35067A0) += disp_ifdsi_lcd1_ut35067a0_ili9488/
obj-$(CONFIG_DISP_IF8B_LCD2_PW35P00_HX8238D) += disp_if8b_lcd2_pw35p00_hx8238d/
ifeq ($(CONFIG_TARGET_NS02302_A64),y)
obj-$(CONFIG_VIDEO_LOGO) += dispdev_panlcomn.o dispdev_platform.o
else
obj-$(CONFIG_DISP_IFPA_LCD3_RGB8888) += disp_ifpa_lcd3_rgb888/
obj-$(CONFIG_VIDEO_LOGO) += pinctrl-nvt-plat.o dispdev_panlcomn.o dispdev_platform.o
endif
endif
