#include "ipcam/nginx_manager.h"
#include <ipcam/config.h>
#include <spdlog/spdlog.h>
#include <fstream>
#include <sstream>
#include <thread>
#include <chrono>

namespace ipcam {
namespace networking {

// Singleton implementation
NginxManager& NginxManager::Instance() {
    static NginxManager instance;
    return instance;
}

NginxManager::NginxManager() = default;
NginxManager::~NginxManager() = default;

Result<void> NginxManager::GenerateConfig(const std::string& output_path) {
    // Get configuration values
    bool http_enabled = config::Get<bool>("network.http.enabled", true);
    int http_port = config::Get<int>("network.http.port", 80);
    bool https_enabled = config::Get<bool>("network.https.enabled", true);
    int https_port = config::Get<int>("network.https.port", 443);
    std::string web_root = config::Get<std::string>("network.http.web_root", "/var/www/");
    std::string ssl_cert = config::Get<std::string>("network.https.ssl_certificate", "/etc/nginx/ssl/Server.crt");
    std::string ssl_key = config::Get<std::string>("network.https.ssl_certificate_key", "/etc/nginx/ssl/Server.key");
    
    // Open output file
    std::ofstream conf(output_path, std::ios::trunc);
    if (!conf) {
        return Result<void>::Err("Failed to open " + output_path + " for writing");
    }
    
    // Write nginx configuration
    conf << "# Auto-generated nginx configuration\n";
    conf << "# Generated by ipcamd networking module\n\n";
    
    conf << "user nobody;\n";
    conf << "worker_processes 1;\n";
    conf << "worker_rlimit_nofile 512;\n";
    conf << "error_log /var/log/nginx/error.log error;\n";
    conf << "pid /var/run/nginx.pid;\n\n";
    
    conf << "events {\n";
    conf << "    worker_connections 128;\n";
    conf << "    use epoll;\n";
    conf << "}\n\n";
    
    conf << "http {\n";
    conf << "    include mime.types;\n";
    conf << "    default_type application/octet-stream;\n";
    conf << "    underscores_in_headers on;\n\n";
    
    conf << "    # Logging\n";
    conf << "    log_format ipcam '$remote_addr - $remote_user [$time_local] '\n";
    conf << "                     '\"$request\" $status $body_bytes_sent '\n";
    conf << "                     '\"$http_referer\" \"$http_user_agent\" $request_time';\n";
    conf << "    access_log /var/log/nginx/access.log ipcam;\n";
    conf << "    error_log /var/log/nginx/error.log error;\n\n";
    
    conf << "    # Performance - optimized for low memory\n";
    conf << "    sendfile on;\n";
    conf << "    tcp_nopush on;\n";
    conf << "    tcp_nodelay on;\n";
    conf << "    keepalive_timeout 30;\n";
    conf << "    keepalive_requests 50;\n";
    conf << "    reset_timedout_connection on;\n";
    conf << "    client_body_timeout 10;\n";
    conf << "    send_timeout 10;\n\n";
    
    conf << "    # Buffer sizes - reduced for 512MB RAM\n";
    conf << "    client_body_buffer_size 16k;\n";
    conf << "    client_max_body_size 200m;  # For firmware uploads\n";
    conf << "    client_header_buffer_size 1k;\n";
    conf << "    large_client_header_buffers 2 4k;\n";
    conf << "    client_body_temp_path /mnt/app/ipcamera/nginx_temp 1 2;\n\n";
    
    conf << "    # Gzip - disabled to save CPU/RAM\n";
    conf << "    gzip off;\n\n";
    
    conf << "    # Essential security headers\n";
    conf << "    add_header X-Frame-Options \"SAMEORIGIN\" always;\n";
    conf << "    add_header X-Content-Type-Options \"nosniff\" always;\n";
    conf << "    add_header X-XSS-Protection \"1; mode=block\" always;\n";
    conf << "    add_header Referrer-Policy \"strict-origin-when-cross-origin\" always;\n\n";
    
    conf << "    # Hide nginx version\n";
    conf << "    server_tokens off;\n\n";
    
    conf << "    # Rate limiting zones - optimized for embedded\n";
    conf << "    limit_req_zone $binary_remote_addr zone=api_limit:512k rate=50r/s;\n";
    conf << "    limit_conn_zone $binary_remote_addr zone=conn_limit:256k;\n\n";
    
    conf << "    # Upstream for CivetWeb Unix socket\n";
    conf << "    upstream civetweb_backend {\n";
    conf << "        server unix:/var/run/ipcam_api.sock;\n";
    conf << "    }\n\n";
    
    // HTTP server block - redirect to HTTPS
    if (http_enabled) {
        conf << "    # HTTP Server - redirect to HTTPS\n";
        conf << "    server {\n";
        conf << "        listen " << http_port << ";\n";
        conf << "        server_name _;\n\n";
        
        conf << "        # Allow snapshot over HTTP (camera functionality)\n";
        conf << "        location /snapshot {\n";
        conf << "            root /tmp;\n";
        conf << "            add_header Content-Disposition \"inline\";\n";
        conf << "            try_files /test_jpeg0.jpeg =404;\n";
        conf << "        }\n\n";
        
        // ONVIF proxy - allows ONVIF clients to discover camera on standard port 80
        int onvif_port = config::Get<int>("network.onvif.port", 5000);
        conf << "        # ONVIF services - proxy to internal ONVIF server\n";
        conf << "        # ONVIF clients typically use HTTP port 80 for device discovery\n";
        conf << "        location /onvif/ {\n";
        conf << "            proxy_pass http://127.0.0.1:" << onvif_port << "/onvif/;\n";
        conf << "            proxy_http_version 1.1;\n";
        conf << "            proxy_set_header Host $host;\n";
        conf << "            proxy_set_header X-Real-IP $remote_addr;\n";
        conf << "            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n";
        conf << "            proxy_set_header Content-Type $content_type;\n";
        conf << "            proxy_set_header SOAPAction $http_soapaction;\n";
        conf << "            proxy_connect_timeout 30s;\n";
        conf << "            proxy_send_timeout 60s;\n";
        conf << "            proxy_read_timeout 60s;\n";
        conf << "            proxy_buffering off;\n";
        conf << "        }\n\n";
        
        conf << "        # Redirect everything else to HTTPS\n";
        conf << "        location / {\n";
        conf << "            return 301 https://$host$request_uri;\n";
        conf << "        }\n";
        conf << "    }\n\n";
    }
    
    // HTTPS server block
    if (https_enabled) {
        conf << "    # HTTPS Server\n";
        conf << "    server {\n";
        conf << "        listen " << https_port << " ssl;\n";
        conf << "        http2 on;\n";
        conf << "        server_name _;\n\n";
        
        conf << "        # SSL configuration - optimized for embedded with HTTP/2\n";
        conf << "        ssl_certificate " << ssl_cert << ";\n";
        conf << "        ssl_certificate_key " << ssl_key << ";\n";
        conf << "        ssl_protocols TLSv1.2 TLSv1.3;\n";
        conf << "        ssl_prefer_server_ciphers off;\n";
        conf << "        ssl_ciphers 'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384';\n";
        conf << "        ssl_session_cache shared:SSL:512k;\n";
        conf << "        ssl_session_timeout 5m;\n";
        conf << "        ssl_session_tickets off;\n\n";
        
        conf << "        # HTTP/2 settings for embedded\n";
        conf << "        http2_max_concurrent_streams 32;\n";
        conf << "        client_header_timeout 30s;\n\n";
        
        conf << "        # Root and index\n";
        conf << "        root " << web_root << ";\n";
        conf << "        index index.html index.htm index.csr.html;\n\n";
        
        conf << "        # API endpoints - reverse proxy to CivetWeb Unix socket\n";
        conf << "        location /api/ {\n";
        conf << "            # Rate limiting for API protection (permissive)\n";
        conf << "            limit_req zone=api_limit burst=50 nodelay;\n";
        conf << "            limit_conn conn_limit 25;\n\n";
        
        conf << "            proxy_pass http://civetweb_backend;\n";
        conf << "            proxy_http_version 1.1;\n";
        conf << "            proxy_buffering off;\n";
        conf << "            proxy_request_buffering off;\n";
        conf << "            proxy_pass_request_headers on;\n";
        conf << "            proxy_set_header Connection \"\";\n";
        conf << "            proxy_set_header Host $host;\n";
        conf << "            proxy_set_header X-Real-IP $remote_addr;\n";
        conf << "            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n";
        conf << "            proxy_set_header X-Forwarded-Proto $scheme;\n\n";
        
        conf << "            # Default timeouts for regular API calls\n";
        conf << "            proxy_connect_timeout 30s;\n";
        conf << "            proxy_send_timeout 120s;\n";
        conf << "            proxy_read_timeout 120s;\n";
        conf << "        }\n\n";
        
        conf << "        # Firmware upload - dynamic timeout based on upload speed\n";
        conf << "        location /api/firmware/upload {\n";
        conf << "            limit_conn conn_limit 1;\n\n";
        
        conf << "            proxy_pass http://civetweb_backend;\n";
        conf << "            proxy_http_version 1.1;\n";
        conf << "            proxy_buffering off;\n";
        conf << "            proxy_request_buffering off;\n";
        conf << "            proxy_set_header Host $host;\n";
        conf << "            proxy_set_header X-Real-IP $remote_addr;\n";
        conf << "            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n";
        conf << "            proxy_set_header X-Forwarded-Proto $scheme;\n";
        conf << "            proxy_set_header Authorization $http_authorization;\n\n";
        
        conf << "            # Extended for large uploads: 200MB @ 100KB/s = ~35min worst case\n";
        conf << "            proxy_connect_timeout 60s;\n";
        conf << "            proxy_send_timeout 0;  # Disable - let upload complete\n";
        conf << "            proxy_read_timeout 0;  # Disable - dynamic based on data flow\n";
        conf << "        }\n\n";
        
        conf << "        # go2rtc WebRTC/WebSocket proxy - same port as web UI for SSL certificate sharing\n";
        conf << "        location /go2rtc/ {\n";
        conf << "            proxy_pass http://127.0.0.1:1984/;\n";
        conf << "            proxy_http_version 1.1;\n";
        conf << "            proxy_set_header Upgrade $http_upgrade;\n";
        conf << "            proxy_set_header Connection \"upgrade\";\n";
        conf << "            proxy_set_header Host $host;\n";
        conf << "            proxy_set_header X-Real-IP $remote_addr;\n";
        conf << "            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n";
        conf << "            proxy_set_header X-Forwarded-Proto $scheme;\n";
        conf << "            proxy_read_timeout 86400s;\n";
        conf << "            proxy_send_timeout 86400s;\n";
        conf << "            proxy_buffering off;\n";
        conf << "        }\n\n";
        
        conf << "        # Static files\n";
        conf << "        location / {\n";
        conf << "            try_files $uri $uri/ /index.csr.html;\n\n";
        
        conf << "            # Cache static assets - shorter for embedded\n";
        conf << "            location ~* \\.(jpg|jpeg|png|gif|ico|css|js|svg|woff|woff2|ttf|eot)$ {\n";
        conf << "                expires 7d;\n";
        conf << "                add_header Cache-Control \"public\";\n";
        conf << "            }\n";
        conf << "        }\n\n";
        
        conf << "        # BMP images from SD card\n";
        conf << "        location ~* \\.bmp$ {\n";
        conf << "            root /mnt/sd;\n";
        conf << "            add_header Content-Disposition \"inline\";\n";
        conf << "            add_header Cache-Control \"no-cache\";\n";
        conf << "            expires 0;\n";
        conf << "        }\n\n";
        
        conf << "        # Snapshot endpoint\n";
        conf << "        location /snapshot {\n";
        conf << "            root /tmp;\n";
        conf << "            add_header Content-Disposition \"inline\";\n";
        conf << "            add_header Cache-Control \"no-cache\";\n";
        conf << "            try_files /test_jpeg0.jpeg =404;\n";
        conf << "        }\n\n";
        
        conf << "        # Security - block hidden files\n";
        conf << "        location ~ /\\. {\n";
        conf << "            deny all;\n";
        conf << "            access_log off;\n";
        conf << "            log_not_found off;\n";
        conf << "        }\n\n";
        
        conf << "        # Custom 404 fallback to root\n";
        conf << "        error_page 404 /;\n";
        conf << "    }\n";
    }
    
    conf << "}\n";
    conf.close();
    
    spdlog::info("nginx.conf generated successfully at {}", output_path);
    spdlog::info("HTTP: enabled={}, port={}", http_enabled, http_port);
    spdlog::info("HTTPS: enabled={}, port={}", https_enabled, https_port);
    
    return Result<void>::Ok();
}

Result<void> NginxManager::Reload() {
    spdlog::info("Reloading nginx configuration...");
    
    // Check if nginx is running
    bool is_running = IsRunning();
    
    if (!is_running) {
        spdlog::info("nginx is not running, skipping reload");
        return Result<void>::Ok();
    }
    
    // Nginx is running - try graceful reload
    spdlog::info("nginx is running, attempting graceful reload...");
    int reload_rc = system("/etc/init.d/S50nginx reload 2>&1");
    if (reload_rc == 0) {
        spdlog::info("nginx reloaded successfully");
        return Result<void>::Ok();
    }
    
    spdlog::warn("Graceful reload failed (exit code: {}), attempting restart...", reload_rc);
    
    // Graceful reload failed, restart
    return Restart();
}

Result<void> NginxManager::Start() {
    if (IsRunning()) {
        spdlog::info("nginx is already running");
        return Result<void>::Ok();
    }
    
    spdlog::info("Starting nginx...");
    
    // Ensure required directories exist
    system("mkdir -p /mnt/app/ipcamera/nginx_temp");
    system("mkdir -p /var/log/nginx");
    system("mkdir -p /var/run");
    
    // Kill any lingering processes
    system("pkill -0 nginx 2>/dev/null && pkill -9 nginx 2>/dev/null; true");
    std::this_thread::sleep_for(std::chrono::milliseconds(500));
    
    int rc = system("/etc/init.d/S50nginx start 2>&1");
    if (rc != 0) {
        return Result<void>::Err("Failed to start nginx (exit code: " + std::to_string(rc) + ")");
    }
    
    // Verify nginx started
    if (!WaitForStart(15)) {
        return Result<void>::Err("nginx command succeeded but process is not running or ports not bound");
    }
    
    spdlog::info("nginx started successfully");
    return Result<void>::Ok();
}

Result<void> NginxManager::Stop() {
    if (!IsRunning()) {
        spdlog::info("nginx is not running");
        return Result<void>::Ok();
    }
    
    spdlog::info("Stopping nginx...");
    system("/etc/init.d/S50nginx stop 2>&1");
    
    // Wait for nginx to stop
    int retries = 10;
    while (retries-- > 0) {
        std::this_thread::sleep_for(std::chrono::milliseconds(200));
        if (!IsRunning()) {
            spdlog::info("nginx stopped successfully");
            return Result<void>::Ok();
        }
    }
    
    spdlog::warn("nginx did not stop gracefully, force killing...");
    system("pkill -9 nginx 2>&1");
    std::this_thread::sleep_for(std::chrono::milliseconds(500));
    
    return Result<void>::Ok();
}

Result<void> NginxManager::Restart() {
    spdlog::info("Restarting nginx...");
    
    auto stop_result = Stop();
    if (!stop_result.success) {
        return stop_result;
    }
    
    return Start();
}

bool NginxManager::IsRunning() const {
    return system("pgrep -x nginx > /dev/null 2>&1") == 0;
}

bool NginxManager::WaitForStart(int max_retries) const {
    while (max_retries-- > 0) {
        std::this_thread::sleep_for(std::chrono::milliseconds(300));
        
        // Check for nginx process
        if (system("pgrep -x 'nginx' > /dev/null 2>&1") == 0) {
            // Verify ports are bound (80 and/or 443)
            if (system("netstat -ln | grep -E ':(80|443) ' > /dev/null 2>&1") == 0) {
                return true;
            }
        }
    }
    return false;
}

} // namespace networking
} // namespace ipcam
