MODULE_NAME = custom_vqa_sample

# DIRs
HDAL_SAMPLE_DIR = $(NVT_HDAL_DIR)/samples
VOS_DRIVER_DIR = $(NVT_VOS_DIR)/drivers
CV_LIB_DIR = $(NVT_HDAL_DIR)/vendor/cv
VENDOR_LIB_DIR = $(NVT_HDAL_DIR)/vendor

# INCs
VOS_INC_PATH = $(VOS_DRIVER_DIR)/include
VOS_LIB_PATH = $(NVT_VOS_DIR)/output
HDAL_INC_PATH = $(NVT_HDAL_DIR)/include
HDAL_LIB_PATH = $(NVT_HDAL_DIR)/output
CV_LIB_INC_PATH = $(CV_LIB_DIR)/include
CV_LIB_OUT_PATH = $(NVT_HDAL_DIR)/vendor/output

# INC FLAGs
EXTRA_INCLUDE += -I$(HDAL_INC_PATH) -I$(VOS_INC_PATH) -I$(CV_LIB_INC_PATH)

.PHONY: all clean

###############################################################################
# Linux Makefile                                                              #
###############################################################################
ifeq ($(NVT_PRJCFG_CFG),Linux)

WARNING = -Wall -Wundef -Wsign-compare -Wno-missing-braces -Werror
COMPILE_OPTS = -I. -O2 -fPIC -ffunction-sections -fdata-sections -D__LINUX

C_CFLAGS = $(PLATFORM_CFLAGS) $(COMPILE_OPTS) $(WARNING) $(EXTRA_INCLUDE)

LD_FLAGS += -L$(HDAL_LIB_PATH) -lhdal -lpthread -lm
LD_FLAGS += -L$(CV_LIB_OUT_PATH) -lvendor_cv -lprebuilt_cv
LD_FLAGS += -L$(VOS_LIB_PATH) -lvos

LIB_NAME = $(MODULE_NAME)
SRC = custom_vqa_sample.c
OBJ = $(SRC:.c=.o)

ifeq ("$(wildcard *.c */*.c)","")
all:
	@echo "nothing to be done for '$(OUTPUT_NAME)'"
clean:
	@echo "nothing to be done for '$(OUTPUT_NAME)'"
else
all: $(LIB_NAME)

$(LIB_NAME): $(OBJ)
	@echo Creating $@...
	@$(CC) -o $@ $(OBJ) $(LD_FLAGS)
	@$(NM) -n $@ > $@.sym
	@$(STRIP) $@
	@$(OBJCOPY) -R .comment -R .note.ABI-tag -R .gnu.version $@

%.o: %.c
	@echo Compiling $<
	@$(CC) $(C_CFLAGS) -c $< -o $@

clean:
	@rm -f $(LIB_NAME) $(OBJ) $(LIB_NAME).sym *.o *.a *.so*
endif

install:
	@cp -avf $(LIB_NAME) $(ROOTFS_DIR)/rootfs/usr/bin

###############################################################################
# rtos Makefile                                                               #
###############################################################################
else ifeq ($(NVT_PRJCFG_CFG),rtos)

# RTOS build not implemented for this sample

endif
