# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (c) 2013 Samsung Electronics Co., Ltd.
# 	http://www.samsung.com

obj-$(CONFIG_EXYNOS_ACE_SHA)	+= ace_sha.o
obj-y += rsa_mod_exp/
obj-y += fsl/

obj-$(CONFIG_TARGET_NA51102_A64) += /nvt/na51102/
obj-$(CONFIG_TARGET_NS02201_A64) += /nvt/ns02201/
obj-$(CONFIG_TARGET_NS02302_A64) += /nvt/ns02302/
obj-$(CONFIG_TARGET_NS02301) += /nvt/ns02301/
obj-$(CONFIG_TARGET_NA51103) += /nvt/na51103/
obj-$(CONFIG_TARGET_NA51089) += /nvt/na51089/
obj-$(CONFIG_TARGET_NS02401_A64) += /nvt/ns02401/