#ifndef __USB3DEV_IOCTL_CMD_H_
#define __USB3DEV_IOCTL_CMD_H_

#include <linux/ioctl.h>
//#include "kwrap/type.h"
//#include "usb3dev.h"


/*
	USB Definitions
*/

#define _ENUM_DUMMY4WORD(name)   E_##name = 0x10000000


/*
	USB IOC data struct
*/
#define USB_DESC_MAX_SIZE	4096


typedef struct {
	UINT16			ui_length;
	UINT8			desc_data[USB_DESC_MAX_SIZE];
} USB3DEV_DESC;

typedef struct {
	BOOL   stall;
	UINT16 ui_length;
	UINT8  *p_data;		//va
} USB3DEV_CX_RET_DATA;

typedef struct {
	U3DEV_CONFIG_ID	cfgid;
	UINT32			cfg_value;
} USB3DEV_SETCFG;

typedef struct {
	USB_EP		epn;
	U3DEV_EPDIR ep_dir;
	UINT32		*busy;
} USB3DEV_CHKBUSY;

//USB_EVENT
typedef enum {
	USB3DEV_EVT_TYPE_CX_VENDOR,
	USB3DEV_EVT_TYPE_CX_VENDOR_DONE,
	USB3DEV_EVT_TYPE_CX_CLASS,
	USB3DEV_EVT_TYPE_CX_CLASS_DONE,
	USB3DEV_EVT_TYPE_USBEVENT_CB,
	USB3DEV_EVT_TYPE_CHARGING_CB,
	USB3DEV_EVT_TYPE_SET_INTF_CB,
	USB3DEV_EVT_TYPE_SET_CONFIG_CB,
	USB3DEV_EVT_TYPE_TXFIFO_REMAP_CB,
	USB3DEV_EVT_TYPE_STDUNKNOWN_CB,
	USB3DEV_EVT_TYPE_SUSPEND_CB,

	//USB2DEV_EVT_TYPE_SUSPEND_CB,
	ENUM_DUMMY4WORD(USB3DEV_EVT_TYPE)
}USB3DEV_EVT_TYPE;

typedef struct {
	USB3DEV_EVT_TYPE	evt_type;
	UINT32				event;
	UINT8 				device_request[8];
	UINT8              *p_data;
	UINT32				request_type;
	UINT32				ui_length;
} USB3DEV_EVENT;

typedef struct {
	USB_EP 			epn;
	UINT8			*buffer;
	UINT32			*dma_length;
	UINT32			timeout_ms;
} USB3DEV_DATA_RW;


typedef struct {
	USB_EP 			epn;
	U3DEV_ISODATA   IsoData;
	//UINT32		*uiNotFinishedSize;
	//UINT16		*uiRemainedSize; // array with uiPacketNumber
} USB3DEV_ISODATA_RW;

typedef struct {
	USB_EP 			epn;
	U3DEV_EP_CONFIG_ID	epcfgid;
	UINT32			cfg_value;
} USB3DEV_SETEPCFG;

typedef struct {
	U3DEV_INTRR 	intrr;
	BOOL			enable;
} USB3DEV_SET_INT;

typedef struct {
	USB_EP 			epn;
	UINT32 			EpType;
	UINT32 			MaxPktSz;
	UINT32 			MaxBurst;
	UINT32 			bInterval;
	BOOL 			isIN;
	UINT32 			BwNum;
} USB3DEV_RESETEP;

typedef struct {
        USB_EP                  epn;
        BOOL                    enable;
} USB3DEV_ISO_BUFF_HW;

typedef struct {
        USB_EP                  epn;
        BOOL                    enable;
} USB3DEV_ISO_BUFF_SW;

/*
typedef struct reg_info {
	uintptr_t ui_addr;
	unsigned int ui_value;
} REG_INFO;

typedef struct {
	USB_ENP_CONFIG epcfg[15];
} USB2DEV_EPCFG;

typedef struct {
	USB_EP 			epn;
	USB_EPCFG_ID	cfgid;
	UINT32			cfg_value;
} USB2DEV_SETEPCFG;
*/



//============================================================================
// IOCTL command
//============================================================================
#define USB3DEV_IOC_DESC_TYPE   'D'

/* USB3DEV_DESC */
#define USB3DEV_IOC_SET_SS_DEVICE_DESC		_IOW(USB3DEV_IOC_DESC_TYPE,  1,  void*)
#define USB3DEV_IOC_SET_HS_DEVICE_DESC		_IOW(USB3DEV_IOC_DESC_TYPE,  2,  void*)
#define USB3DEV_IOC_SET_FS_DEVICE_DESC		_IOW(USB3DEV_IOC_DESC_TYPE,  3,  void*)
#define USB3DEV_IOC_SET_CFG_SS_DESC			_IOW(USB3DEV_IOC_DESC_TYPE,  4,  void*)
#define USB3DEV_IOC_SET_CFG_HS_DESC			_IOW(USB3DEV_IOC_DESC_TYPE,  5,  void*)
#define USB3DEV_IOC_SET_CFG_FS_DESC			_IOW(USB3DEV_IOC_DESC_TYPE,  6,  void*)
#define USB3DEV_IOC_SET_STRING0_DESC_SS	 	_IOW(USB3DEV_IOC_DESC_TYPE,  7,  void*)
#define USB3DEV_IOC_SET_STRING1_DESC_SS	 	_IOW(USB3DEV_IOC_DESC_TYPE,  8,  void*)
#define USB3DEV_IOC_SET_STRING2_DESC_SS	 	_IOW(USB3DEV_IOC_DESC_TYPE,  9,  void*)
#define USB3DEV_IOC_SET_STRING3_DESC_SS	 	_IOW(USB3DEV_IOC_DESC_TYPE, 10,  void*)
#define USB3DEV_IOC_SET_STRING4_DESC_SS	 	_IOW(USB3DEV_IOC_DESC_TYPE, 11,  void*)
#define USB3DEV_IOC_SET_STRING5_DESC_SS	 	_IOW(USB3DEV_IOC_DESC_TYPE, 12,  void*)
#define USB3DEV_IOC_SET_STRING6_DESC_SS	 	_IOW(USB3DEV_IOC_DESC_TYPE, 13,  void*)
#define USB3DEV_IOC_SET_STRING7_DESC_SS	 	_IOW(USB3DEV_IOC_DESC_TYPE, 14,  void*)
#define USB3DEV_IOC_SET_STRING0_DESC_HS	 	_IOW(USB3DEV_IOC_DESC_TYPE, 15,  void*)
#define USB3DEV_IOC_SET_STRING1_DESC_HS	 	_IOW(USB3DEV_IOC_DESC_TYPE, 16,  void*)
#define USB3DEV_IOC_SET_STRING2_DESC_HS	 	_IOW(USB3DEV_IOC_DESC_TYPE, 17,  void*)
#define USB3DEV_IOC_SET_STRING3_DESC_HS	 	_IOW(USB3DEV_IOC_DESC_TYPE, 18,  void*)
#define USB3DEV_IOC_SET_STRING4_DESC_HS	 	_IOW(USB3DEV_IOC_DESC_TYPE, 19,  void*)
#define USB3DEV_IOC_SET_STRING5_DESC_HS	 	_IOW(USB3DEV_IOC_DESC_TYPE, 20,  void*)
#define USB3DEV_IOC_SET_STRING6_DESC_HS	 	_IOW(USB3DEV_IOC_DESC_TYPE, 21,  void*)
#define USB3DEV_IOC_SET_STRING7_DESC_HS	 	_IOW(USB3DEV_IOC_DESC_TYPE, 22,  void*)
#define USB3DEV_IOC_SET_STRING0_DESC_FS	 	_IOW(USB3DEV_IOC_DESC_TYPE, 23,  void*)
#define USB3DEV_IOC_SET_STRING1_DESC_FS	 	_IOW(USB3DEV_IOC_DESC_TYPE, 24,  void*)
#define USB3DEV_IOC_SET_STRING2_DESC_FS	 	_IOW(USB3DEV_IOC_DESC_TYPE, 25,  void*)
#define USB3DEV_IOC_SET_STRING3_DESC_FS	 	_IOW(USB3DEV_IOC_DESC_TYPE, 26,  void*)
#define USB3DEV_IOC_SET_STRING4_DESC_FS	 	_IOW(USB3DEV_IOC_DESC_TYPE, 27,  void*)
#define USB3DEV_IOC_SET_STRING5_DESC_FS	 	_IOW(USB3DEV_IOC_DESC_TYPE, 28,  void*)
#define USB3DEV_IOC_SET_STRING6_DESC_FS	 	_IOW(USB3DEV_IOC_DESC_TYPE, 29,  void*)
#define USB3DEV_IOC_SET_STRING7_DESC_FS	 	_IOW(USB3DEV_IOC_DESC_TYPE, 30,  void*)
#define USB3DEV_IOC_SET_BOS_DESC_SS			_IOW(USB3DEV_IOC_DESC_TYPE, 31,  void*)
#define USB3DEV_IOC_SET_BOS_DESC_HS			_IOW(USB3DEV_IOC_DESC_TYPE, 32,  void*)
#define USB3DEV_IOC_SET_DEVQUALI_DESC_HS	_IOW(USB3DEV_IOC_DESC_TYPE, 33,  void*)
#define USB3DEV_IOC_SET_DEVQUALI_DESC_FS	_IOW(USB3DEV_IOC_DESC_TYPE, 34,  void*)
#define USB3DEV_IOC_SET_OTHERSPD_DESC_HS	_IOW(USB3DEV_IOC_DESC_TYPE, 35,  void*)
#define USB3DEV_IOC_SET_OTHERSPD_DESC_FS	_IOW(USB3DEV_IOC_DESC_TYPE, 36,  void*)
#define USB3DEV_IOC_SET_STRING8_DESC_SS	 	_IOW(USB3DEV_IOC_DESC_TYPE, 37,  void*)
#define USB3DEV_IOC_SET_STRING9_DESC_SS	 	_IOW(USB3DEV_IOC_DESC_TYPE, 38,  void*)
#define USB3DEV_IOC_SET_STRING10_DESC_SS	 	_IOW(USB3DEV_IOC_DESC_TYPE, 39,  void*)
#define USB3DEV_IOC_SET_STRING11_DESC_SS	 	_IOW(USB3DEV_IOC_DESC_TYPE, 40,  void*)
#define USB3DEV_IOC_SET_STRING8_DESC_HS	 	_IOW(USB3DEV_IOC_DESC_TYPE, 41,  void*)
#define USB3DEV_IOC_SET_STRING9_DESC_HS	 	_IOW(USB3DEV_IOC_DESC_TYPE, 42,  void*)
#define USB3DEV_IOC_SET_STRING10_DESC_HS	 	_IOW(USB3DEV_IOC_DESC_TYPE, 43,  void*)
#define USB3DEV_IOC_SET_STRING11_DESC_HS	 	_IOW(USB3DEV_IOC_DESC_TYPE, 44,  void*)
#define USB3DEV_IOC_SET_STRING8_DESC_FS	 	_IOW(USB3DEV_IOC_DESC_TYPE, 45,  void*)
#define USB3DEV_IOC_SET_STRING9_DESC_FS	 	_IOW(USB3DEV_IOC_DESC_TYPE, 46,  void*)
#define USB3DEV_IOC_SET_STRING10_DESC_FS	 	_IOW(USB3DEV_IOC_DESC_TYPE, 47,  void*)
#define USB3DEV_IOC_SET_STRING11_DESC_FS	 	_IOW(USB3DEV_IOC_DESC_TYPE, 48,  void*)


//////////////////////////////////////////////////////////////////////////////
#define USB3DEV_IOC_COMMON_TYPE 'S'

/* REG_INFO */
#define USB3DEV_IOC_READ_REG                _IOR(USB3DEV_IOC_COMMON_TYPE,  1,  void*)
#define USB3DEV_IOC_WRITE_REG               _IOW(USB3DEV_IOC_COMMON_TYPE,  2,  void*)

/* No Data */
#define USB3DEV_IOC_OPEN                    _IO(USB3DEV_IOC_COMMON_TYPE,   3)
#define USB3DEV_IOC_CLOSE                   _IO(USB3DEV_IOC_COMMON_TYPE,   4)

/* USB3DEV_CX_RET_DATA */
#define USB3DEV_IOC_CX_RET_DATA   			_IOW(USB3DEV_IOC_COMMON_TYPE,  5,  void*)

/* USB3DEV_SETCFG */
#define USB3DEV_IOC_SET_CFG   				_IOW(USB3DEV_IOC_COMMON_TYPE,  6,  void*)

/* USB3DEV_CHKBUSY */
#define USB3DEV_IOC_CHK_EPBUSY				_IOR(USB3DEV_IOC_COMMON_TYPE,  7,  void*)

/* UINT32 */
#define USB3DEV_IOC_GET_DEVINFO				_IOWR(USB3DEV_IOC_COMMON_TYPE, 8,  void*)
#define USB3DEV_IOC_GET_SOF					_IOR(USB3DEV_IOC_COMMON_TYPE,  9,  void*)


/* USB3DEV_EVENT */
#define USB3DEV_IOC_GET_EVENT				_IOWR(USB3DEV_IOC_COMMON_TYPE, 10,  void*)

/* No Data */
#define USB3DEV_IOC_SET_EVENT_DONE			_IO(USB3DEV_IOC_COMMON_TYPE,  11)

/* USB3DEV_DATA_RW */
#define USB3DEV_IOC_WRITE_EP   				_IOWR(USB3DEV_IOC_COMMON_TYPE, 12,  void*)
#define USB3DEV_IOC_READ_EP   				_IOWR(USB3DEV_IOC_COMMON_TYPE, 13,  void*)

#define USB3DEV_IOC_SET_WRITE_EP   			_IOWR(USB3DEV_IOC_COMMON_TYPE, 25,  void*)
#define USB3DEV_IOC_WAIT_WRITE_EP_DONE		_IOWR(USB3DEV_IOC_COMMON_TYPE, 26,  void*)

/* USB3DEV_ISODATA_RW */
#define USB3DEV_IOC_WRITE_ISOEP   			_IOWR(USB3DEV_IOC_COMMON_TYPE, 14,  void*)

#define USB3DEV_IOC_ABORT_EP   			    _IOWR(USB3DEV_IOC_COMMON_TYPE, 15,  void*)

/* USB3DEV_SETCFG */
#define USB3DEV_IOC_SET_EP_CFG   			_IOW(USB3DEV_IOC_COMMON_TYPE,  16,  void*)

#define USB3DEV_IOC_SET_INT   		    	_IOW(USB3DEV_IOC_COMMON_TYPE,  17,  void*)
#define USB3DEV_IOC_GET_BYTECNT				_IOR(USB3DEV_IOC_COMMON_TYPE, 18,  void*)
#define USB3DEV_IOC_STALL_EP				_IOW(USB3DEV_IOC_COMMON_TYPE, 19,  void*)
#define USB3DEV_IOC_SET_TX0				    _IOW(USB3DEV_IOC_COMMON_TYPE, 20,  void*)

#define USB3DEV_IOC_WRITE_EP_TMOT   		_IOWR(USB3DEV_IOC_COMMON_TYPE, 21,  void*)
#define USB3DEV_IOC_RESET_EP_CFG   		_IOWR(USB3DEV_IOC_COMMON_TYPE, 22,  void*)

#define USB3DEV_IOC_CHK_CHARGER			_IOR(USB3DEV_IOC_COMMON_TYPE, 23,  void*)
#define USB3DEV_IOC_STATE_CHG				_IOR(USB3DEV_IOC_COMMON_TYPE, 24,  void*)

/* ISO buff mechanism */
#define USB3DEV_IOC_ISO_BUFF_HW			_IOW(USB3DEV_IOC_COMMON_TYPE,  27,  void*)
#define USB3DEV_IOC_ISO_BUFF_SW			_IOW(USB3DEV_IOC_COMMON_TYPE,  28,  void*)

#if 0
/* USB2DEV_EPCFG */
#define USB3DEV_IOC_SET_EPCFG_HS	 		_IOW(USB3DEV_IOC_COMMON_TYPE, 19,  void*)
#define USB3DEV_IOC_SET_EPCFG_FS	 		_IOW(USB3DEV_IOC_COMMON_TYPE, 20,  void*)

/* UINT32 */
#define USB3DEV_IOC_SET_CFG_NUMBER	 		_IOW(USB3DEV_IOC_COMMON_TYPE, 21,  void*)
#define USB3DEV_IOC_SET_STRING_NUMBER	 	_IOW(USB3DEV_IOC_COMMON_TYPE, 22,  void*)
#define USB3DEV_IOC_SET_UNMASK_EPINT		_IOW(USB3DEV_IOC_COMMON_TYPE, 23,  void*)
#define USB3DEV_IOC_SET_MASK_EPINT			_IOW(USB3DEV_IOC_COMMON_TYPE, 24,  void*)
#define USB3DEV_IOC_ABORT_EP				_IOW(USB3DEV_IOC_COMMON_TYPE, 35,  void*)
#define USB3DEV_IOC_GET_BYTECNT				_IOR(USB3DEV_IOC_COMMON_TYPE, 36,  void*)
#define USB3DEV_IOC_STALL_EP				_IOW(USB3DEV_IOC_COMMON_TYPE, 37,  void*)
#define USB3DEV_IOC_TX0_BYTE				_IOW(USB3DEV_IOC_COMMON_TYPE, 38,  void*)
#define USB3DEV_IOC_CLEAR_EPFIFO			_IOW(USB3DEV_IOC_COMMON_TYPE, 40,  void*)
#define USB3DEV_IOC_STATE_CHG				_IOR(USB3DEV_IOC_COMMON_TYPE, 42,  void*)
#define USB3DEV_IOC_CHK_CHARGER				_IOR(USB3DEV_IOC_COMMON_TYPE, 43,  void*)
#define USB3DEV_IOC_IS_HIGHSPEED			_IOR(USB3DEV_IOC_COMMON_TYPE, 44,  void*)
//#define USB3DEV_IOC_SET_CX_DONE   			_IO(USB3DEV_IOC_COMMON_TYPE,  29)
/* USB2DEV_SETEPCFG */
#define USB3DEV_IOC_SET_EPCFG   			_IOW(USB3DEV_IOC_COMMON_TYPE, 30,  void*)
/* USB2DEV_DATA_RW */
#define USB3DEV_IOC_SET_EP_R   				_IOWR(USB3DEV_IOC_COMMON_TYPE, 31,  void*)
#define USB3DEV_IOC_SET_EP_W   				_IOWR(USB3DEV_IOC_COMMON_TYPE, 32,  void*)
#endif

#endif
