# Makefile for Audio Processing Tests
# Uses libaec.a, libagc.a, libaudfilt.a from code/lib/output/

MODULE_NAME = audio_processing_test

# DIRs
VOS_DRIVER_DIR = $(NVT_VOS_DIR)/drivers
HDAL_SAMPLE_DIR = $(NVT_HDAL_DIR)/samples
OUTPUT_DIR = $(HDAL_SAMPLE_DIR)/output
VENDOR_INC_PATH = $(NVT_HDAL_DIR)/vendor/media/include
VENDOR_LIB_PATH = $(NVT_HDAL_DIR)/vendor/output

# Userspace audio library paths
LIB_SRC_PATH = $(NVT_HDAL_DIR)/../lib/output
LIB_INC_PATH = $(NVT_HDAL_DIR)/../lib/include

# INCs
VOS_INC_PATH = $(VOS_DRIVER_DIR)/include
HDAL_INC_PATH = $(NVT_HDAL_DIR)/include
HDAL_LIB_PATH = $(NVT_HDAL_DIR)/output

# INC FLAGs
EXTRA_INCLUDE += \
	-I$(HDAL_INC_PATH) \
	-I$(VOS_INC_PATH) \
	-I$(VENDOR_INC_PATH) \
	-I$(LIB_INC_PATH)

###############################################################################
# Linux Makefile
###############################################################################
ifeq ($(NVT_PRJCFG_CFG),Linux)
EXTRA_CFLAGS += $(NVT_ASAN) -D__LINUX -Wno-error=unused-but-set-variable
EXTRA_LDFLAGS = $(NVT_ASAN) -L$(HDAL_LIB_PATH) -L$(VENDOR_LIB_PATH) -L$(LIB_SRC_PATH) -lhdal -lvendor_media -lagc -laec -laudfilt -lpthread -lm
SRC += audio_processing_test.c
endif

include $(NVT_HDAL_DIR)/executable.mk
