# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_PHY_NOVATEK_PCIE_V1)	+= phy-nvt-pcie-v1.o
obj-$(CONFIG_PHY_NOVATEK_PCIE_V2)	+= phy-nvt-pcie-v2.o
obj-$(CONFIG_PHY_NS02201_SATA)		+= phy-ns02201-sata.o
obj-$(CONFIG_PHY_TC98110_SATA)		+= phy-tc98110-sata.o