
#ifndef ENUM_DUMMY4WORD
#define ENUM_DUMMY4WORD(name)   E_##name = 0x10000000
#endif

// ref from code/hdal/drivers/k_driver/include/rtos_na51102/pll.h
typedef enum {
	AXI0_CLK,  			///< AXI0 clock
	AXI1_MCLK,          ///< AXI1 clock
	AXI2_MCLK,          ///< AXI2 clock
	AXI3_MCLK,          ///< AXI3 clock
	AXI4_MCLK,          ///< AXI4 clock
	AXI5_MCLK,          ///< AXI5 clock
	AXI6_MCLK,          ///< AXI6 clock
	AXI7_MCLK,          ///< AXI7 clock
	DSP_CLK 	  = 10,	///< DSP  clock
	EFUSE_CLK,		    ///< EFUSE clock
	MAU_CLK,		    ///< MAU clock
	IME_CLK,            ///< IME clock
	SIE_CLK,            ///< SIE clock
	SIE2_CLK,           ///< SIE2 Clock
	SIE3_CLK,           ///< SIE3 clock
	SIE4_CLK,           ///< SIE4 clock
	SIE5_CLK,           ///< SIE5 clock
	SIE6_CLK,           ///< SIE6 clock
	GPENC_CLK,			///< GPENC clock
	GPENC2_CLK, 		///< GPENC clock
	JPEG_CLK, 	        ///< JPEG clock
	JPG_CLK = JPEG_CLK,
	UVCP_CLK,			///< UVCP clock
	UVCP_CLKEN = UVCP_CLK,
	VIE_CLK,			///< VIE clock
	VIE2_CLK,			///< VIE2 clock
	DIS_CLK,            ///< DIS clock
	ETH_CLK,            ///< ETH clock
	ISE_CLK,            ///< ISE clock
	HASH_CLK,           ///< HASH clock
	RSA_CLK,            ///< RSA clock
	CRYPTO_CLK,			///< Crypto clock

	VENC_CLK	 = 32,	///< VENC clock
	VTRC_CLK,			///< VTRC clock
	IPE_CLK,            ///< IPE clock
	DCE_CLK,            ///< DCE clock
	IFE_CLK,            ///< IFE clock
	IDE_CLK,		    ///< IDE clock
	IDE1_CLK = IDE_CLK,
	IDE2_CLK,		    ///< IDE2 clock
	ETHPHY_CLK,		    ///< ETH EXT PHY clock
	MDBC_CLK,           ///< MDBC clock
	HWCOPY_CLK,     	///< Hwcopy clock
	NAND_CLK,		    ///< NAND clock
	SDIO_CLK, 			///< SDIO clock
	SDIO2_CLK,			///< SDIO2 clock
	SDIO3_CLK,          ///< SDIO3 clock
	HDMITX_CLK, 		///< HDMITX clock (audio part)
	NUE_CLK, 			///< NUE clock
	NUE2_CLK, 			///< NUE2 clock
	TRKE_CLK, 			///< TRKE clock
	IVE_CLK, 			///< IVE clock
	SATA_CLK,           ///< SATA clock
	SIE_MCLK,           ///< SIE MCLK
	SIE_MCLK2,          ///< SIE MCLK2
	SIE_MCLK3,          ///< SIE MCLK3
	SIE_MCLK4,          ///< SIE MCLK4
	SIE_MCLK5,          ///< SIE MCLK5
	USB2_CLK, 			///< USB2 clock
	USB3_CLK,			///< USB3 clock
	TSE_CLK, 			///< TSE  clock
	CNN_CLK,            ///< CNN clock
	CNN2_CLK,           ///< CNN2 clock
	VPE_CLK,			///< VPE clock
	VPEL_CLK,			///< VPE-lite clock

	I2C_CLK       = 64, ///< I2C clock
	I2C2_CLK,			///< I2C2 clock 
	I2C3_CLK,			///< I2C3 clock
	I2C4_CLK,			///< I2C4 clock 
	I2C5_CLK,			///< I2C5 clock 
	I2C6_CLK,			///< I2C6 clock 
	I2C7_CLK,			///< I2C7 clock 
	I2C8_CLK,			///< I2C8 clock 
	I2C9_CLK,			///< I2C9 clock 
	I2C10_CLK,			///< I2C10 clock 
	I2C11_CLK,			///< I2C11 clock 
	MI_CLK,				///< MI clock
	TMR_CLK,            ///< timer clock
	TMR2_CLK,           ///< timer2 clock
	TMR3_CLK,           ///< timer3 clock
	UVCP2_CLK,			///< UVCP2 clock
	SIF_CLK,            ///< SIF clock
	GRAPH_CLK,          ///< Graphic clock
	GRAPH2_CLK,         ///< Graphic2 clock
	GRAPH3_CLK,         ///< Graphic3 clock
	UART_CLK,           ///< UART clock
	UART2_CLK,          ///< UART2 clock
	UART3_CLK,          ///< UART3 clock
	UART4_CLK,          ///< UART4 clock
	UART5_CLK,          ///< UART5 clock
	REMOTE_CLK,         ///< Remote clock
	DRTC_CLK,		    ///< DRTC clock
	ADC_CLK,            ///< ADC clock
	ADC_TSEN_CLK,		///< ADC T-sensor clock
	TRNG_CLK,           ///< TRNG clock
	TRNG_RO_CLK, 		///< TRNGRO clock
	RO32K_CLK,			///< RO 32k clock

	PWM_CCNT_CLK  = 96, ///< PWM CCNT clock
	PWM_CCNT0_CLK = 96, ///< PWM CCNT0 clock
	PWM_CCNT1_CLK,      ///< PWM CCNT1 clock
	PWM_CCNT2_CLK,      ///< PWM CCNT2 clock
	PMC_CLK,			///< PMC clock
	WDT_CLK,			///< WDT clock
	ETH2_CLK,		///< USB2_0 PHY clock
	ETHPHY2_CLK,           ///< ISE2 clock
	ETH2_PTP_REF_CLK,	///< USB3 SATA combo PHY clock
	ETH_PTP_REF_CLK,	///< ETH Ref clock
	JPEG2_CLK, 	        ///< JPEG2 clock
	AE_CLK,				///< AE clock
	JPEG_LITE_CLK,		///< JPEG Lite clock
	HVYLD_CLK,			///< heavyload clock
	HVYLD2_CLK,			///< heavyload2 clock
	HVYLD3_CLK,			///< heavyload3 clock
	DRE_CLK,			///< DRE clock
	DAI_CLK,            ///< DAI clock
	DAI2_CLK,           ///< DAI2 clock
	EAC_A_ADC_CLK,		///< EAC analog AD clock
	EAC_A_DAC_CLK,		///< EAC analog DA clock
	EAC_D_CLKEN, 		///< EAC digital clock
	UART6_CLK,          ///< UART6 clock
	UART7_CLK,          ///< UART7 clock
	UART8_CLK,          ///< UART8 clock
	UART9_CLK,          ///< UART9 clock
	CSI_CLK,			///< CSI clock
	CSI2_CLK,           ///< CSI2 clock
	CSI3_CLK,           ///< CSI3 clock
	CSI4_CLK,           ///< CSI4 clock
	CSI5_CLK,           ///< CSI5 clock
	SDE_CLK,			///< SDE clock
	TGE_CLK,            ///< TGE clock

	CSI_CK0D4_CLK = 128,///< MIPI CSI PHY HS-CLK0/4
	CSI2_CK0D4_CLK,		///< MIPI CSI2 PHY HS-CLK0/4
	CSI2_CK1D4_CLK,		///< MIPI CSI2 PHY HS-CLK1/4
	CSI2_CK2D4_CLK,		///< MIPI CSI2 PHY HS-CLK2/4
	CSI2_CK3D4_CLK,		///< MIPI CSI2 PHY HS-CLK3/4
	CSI3_CK1D4_CLK,		///< MIPI CSI3 PHY HS-CLK1/4
	CSI4_CK2D4_CLK,		///< MIPI CSI4 PHY HS-CLK2/4
	CSI4_CK0D4_CLK = CSI4_CK2D4_CLK,
	CSI4_CK3D4_CLK,		///< MIPI CSI4 PHY HS-CLK3/4
	CSI4_CK1D4_CLK = CSI4_CK3D4_CLK,
	CSI5_CK3D4_CLK,		///< MIPI CSI5 PHY HS-CLK3/4
	CSI5_CK1D4_CLK = CSI5_CK3D4_CLK,
	SIE_PXCLK	  = 140,///< SIE PX clock
	SIE2_PXCLK,         ///< SIE2 PX clock
	SIE3_PXCLK	  = 144,///< SIE3 PX clock	
	SIE4_PXCLK, 		///< SIE4 PX clock
	SIE5_PXCLK, 		///< SIE5 PX clock
	SIE6_PXCLK, 		///< SIE6 PX clock
	VIE_A_PXCLK,		///< VIE_A PX clock
	VIE_B_PXCLK,		///< VIE_B PX clock
	VIE2_A_PXCLK,		///< VIE2_A PX clock
	VIE2_B_PXCLK,		///< VIE2_B PX clock
	H264D_CLK	  = 153,///< H264D clock
	H265D_CLK,          ///< H265D clock	
	DSI_CLK    	  = 156,///< DSI clock
	CSI_TX_CLK,			///< CSI TX clock
	SP_CLK,             ///< special clock
	SP2_CLK,            ///< special2 clock

	PWM0_CLK      = 160,///< PWM0 clock
	PWM1_CLK,           ///< PWM1 clock
	PWM2_CLK,           ///< PWM2 clock
	PWM3_CLK,           ///< PWM3 clock
	PWM4_CLK,           ///< PWM4 clock
	PWM5_CLK,           ///< PWM5 clock
	PWM6_CLK,           ///< PWM6 clock
	PWM7_CLK,           ///< PWM7 clock
	PWM8_CLK,           ///< PWM8 clock
	PWM9_CLK,           ///< PWM9 clock
	PWM10_CLK,          ///< PWM10 clock
	PWM11_CLK,          ///< PWM11 clock
	SDP_CLK       = 176,///< SDP clock
	SPI_CLK,            ///< SPI clock
	SPI2_CLK,           ///< SPI2 clock
	SPI3_CLK,           ///< SPI3 clock
	SPI4_CLK,           ///< SPI4 clock
	SPI5_CLK,           ///< SPI5 clock

	CSI_SIE_CLK	  = 192,///< CSI to SIE clock
	CSI_SIE2_CLK,		///< CSI to SIE2 clock
	CSI_SIE3_CLK,		///< CSI to SIE3 clock
	CSI_SIE4_CLK,		///< CSI to SIE4 clock
	
	CSI2_SIE3_CLK,	    ///< CSI2 to SIE3 clock
	CSI2_SIE4_CLK,		///< CSI2 to SIE4 clock
	CSI2_SIE5_CLK,	    ///< CSI2 to SIE5 clock
	CSI2_SIE6_CLK,		///< CSI2 to SIE6 clock
	CSI2_VIE_CLK,		///< CSI2 to VIE clock
	
	CSI3_SIE3_CLK = 204,///< CSI3 to SIE4 clock
	CSI3_SIE4_CLK,		///< CSI3 to SIE4 clock
	CSI3_SIE5_CLK,		///< CSI3 to SIE5 clock
	CSI3_SIE6_CLK,		///< CSI3 to SIE6 clock
	
	CSI4_SIE3_CLK = 208,///< CSI4 to SIE3 clock
	CSI4_SIE4_CLK,		///< CSI4 to SIE4 clock
	CSI4_SIE5_CLK,		///< CSI4 to SIE5 clock
	CSI4_SIE6_CLK,		///< CSI4 to SIE6 clock
	CSI4_VIE2_CLK,		///< CSI4 to VIE2 clock

	CSI5_SIE5_CLK = 216,///< CSI5 to SIE5 clock
	CSI5_SIE6_CLK,		///< CSI5 to SIE6 clock

	ENUM_DUMMY4WORD(CG_EN)
} CG_EN;

typedef enum {
	PLL_ID_0        = 0,        ///< PLL0 (for AXI0)
	PLL_ID_1        = 1,        ///< PLL1 (for internal 480 MHz)
	PLL_ID_2        = 2,        ///< PLL2 (for AXI1)
	PLL_ID_3        = 3,        ///< PLL3 (for DRAM)
	PLL_ID_4        = 4,        ///< PLL4 (for AHB)
	PLL_ID_5        = 5,        ///< PLL5 (for SIE_MCLK2)
	PLL_ID_6        = 6,        ///< PLL6 (for SDC)
	PLL_ID_7        = 7,        ///< PLL7 (for ETH)
	PLL_ID_8        = 8,        ///< PLL8 (for CNN)
	PLL_ID_9        = 9,        ///< PLL9 (for DISP0)
	PLL_ID_10       = 10,       ///< PLL10 (for DISP1)
	PLL_ID_11       = 11,       ///< PLL11 (for SIE_MCLK)
	PLL_ID_12       = 12,       ///< PLL12 (for AUDIO)
	PLL_ID_13       = 13,       ///< PLL13 (for AXI2)
	PLL_ID_14       = 14,       ///< PLL14 (for VENC)
	PLL_ID_15       = 15,       ///< PLL15 (for IPP CODEC BAKUP0)
	PLL_ID_16       = 16,       ///< PLL16 (for CPU)
	PLL_ID_17       = 17,       ///< PLL17 (for DSI)
	PLL_ID_18       = 18,       ///< PLL18 (for IPP CODEC BAKUP1)
	PLL_ID_19       = 19,       ///< PLL19 (for SIE SENSOR)
	PLL_ID_20       = 20,       ///< PLL20 (for USB3 PHY)
	PLL_ID_21       = 21,       ///< PLL21 (for DSP)
	PLL_ID_22       = 22,       ///< PLL22 (for SATA PHY)
	PLL_ID_23       = 23,       ///< PLL23 (for VIE)
	PLL_ID_24       = 24,       ///< PLL24 (for AE)

	PLL_ID_FIXED320 = 25,		///< Fixed 320MHz PLL

	PLL_ID_MAX,
	ENUM_DUMMY4WORD(PLL_ID)
} PLL_ID;

//
// Clock Rate bit definition
//
#define PLL_CLKSEL_CPU_MASK             (0x03 << PLL_CLKSEL_CPU)
#define PLL_CLKSEL_APB_MASK             (0x03 << PLL_CLKSEL_APB)
#define PLL_CLKSEL_DMA_ARBT_MASK		(0x01 << PLL_CLKSEL_DMA_ARBT)
#define PLL_CLKSEL_DDRPHY_MASK          (0x01 << PLL_CLKSEL_DDRPHY)
#define PLL_CLKSEL_IFE_SRAM_MASK        (0x01 << PLL_CLKSEL_IFE_SRAM)


/*r1*/
#define PLL_CLKSEL_IVE_MASK             (0x03 << (PLL_CLKSEL_IVE - PLL_CLKSEL_R1_OFFSET))
#define PLL_CLKSEL_TRKE_MASK            (0x03 << (PLL_CLKSEL_TRKE - PLL_CLKSEL_R1_OFFSET))
#define PLL_CLKSEL_MDBC_MASK            (0x03 << (PLL_CLKSEL_MDBC - PLL_CLKSEL_R1_OFFSET))
#define PLL_CLKSEL_CNN_MASK             (0x03 << (PLL_CLKSEL_CNN - PLL_CLKSEL_R1_OFFSET))
#define PLL_CLKSEL_CNN2_MASK            (0x03 << (PLL_CLKSEL_CNN2 - PLL_CLKSEL_R1_OFFSET))
#define PLL_CLKSEL_ISE_MASK             (0x03 << (PLL_CLKSEL_ISE - PLL_CLKSEL_R1_OFFSET))
#define PLL_CLKSEL_DIS_MASK             (0x03 << (PLL_CLKSEL_DIS - PLL_CLKSEL_R1_OFFSET))
#define PLL_CLKSEL_NUE_MASK             (0x03 << (PLL_CLKSEL_NUE - PLL_CLKSEL_R1_OFFSET))
#define PLL_CLKSEL_NUE2_MASK            (0x03 << (PLL_CLKSEL_NUE2 - PLL_CLKSEL_R1_OFFSET))
#define PLL_CLKSEL_IME_MASK             (0x03 << (PLL_CLKSEL_IME - PLL_CLKSEL_R1_OFFSET))
#define PLL_CLKSEL_IPE_MASK             (0x03 << (PLL_CLKSEL_IPE - PLL_CLKSEL_R1_OFFSET))
#define PLL_CLKSEL_DCE_MASK             (0x03 << (PLL_CLKSEL_DCE - PLL_CLKSEL_R1_OFFSET))
#define PLL_CLKSEL_IFE_MASK             (0x03 << (PLL_CLKSEL_IFE - PLL_CLKSEL_R1_OFFSET))
#define PLL_CLKSEL_VPE_MASK             (0x03 << (PLL_CLKSEL_VPE - PLL_CLKSEL_R1_OFFSET))
#define PLL_CLKSEL_VPE_LITE_MASK		(0x03 << (PLL_CLKSEL_VPE_LITE - PLL_CLKSEL_R1_OFFSET))
#define PLL_CLKSEL_ISE2_MASK            (0x03 << (PLL_CLKSEL_ISE2 - PLL_CLKSEL_R1_OFFSET))
#define PLL_CLKSEL_SDE_MASK             (0x03 << (PLL_CLKSEL_SDE - PLL_CLKSEL_R1_OFFSET))

/*r2*/
#define PLL_CLKSEL_SIE_MCLKINV_MASK     (0x01 << (PLL_CLKSEL_SIE_MCLKINV - PLL_CLKSEL_R2_OFFSET))
#define PLL_CLKSEL_SIE_MCLK2INV_MASK    (0x01 << (PLL_CLKSEL_SIE_MCLK2INV - PLL_CLKSEL_R2_OFFSET))
#define PLL_CLKSEL_SIE_MCLK3INV_MASK    (0x01 << (PLL_CLKSEL_SIE_MCLK3INV - PLL_CLKSEL_R2_OFFSET))
#define PLL_CLKSEL_SIE_MCLK4INV_MASK    (0x01 << (PLL_CLKSEL_SIE_MCLK4INV - PLL_CLKSEL_R2_OFFSET))
#define PLL_CLKSEL_SIE_MCLK5INV_MASK    (0x01 << (PLL_CLKSEL_SIE_MCLK5INV - PLL_CLKSEL_R2_OFFSET))
#define PLL_CLKSEL_TGE_MASK             (0x01 << (PLL_CLKSEL_TGE - PLL_CLKSEL_R2_OFFSET))

/*r3*/
#define PLL_CLKSEL_JPEG_MASK            (0x03 << (PLL_CLKSEL_JPEG - PLL_CLKSEL_R3_OFFSET))
#define PLL_CLKSEL_UVCP_MASK			(0x03 << (PLL_CLKSEL_UVCP - PLL_CLKSEL_R3_OFFSET))
#define PLL_CLKSEL_VENC_MASK            (0x03 << (PLL_CLKSEL_VENC - PLL_CLKSEL_R3_OFFSET))
#define PLL_CLKSEL_DRE_MASK             (0x03 << (PLL_CLKSEL_DRE - PLL_CLKSEL_R3_OFFSET))
#define PLL_CLKSEL_JPEG2_MASK           (0x03 << (PLL_CLKSEL_JPEG2 - PLL_CLKSEL_R3_OFFSET))
#define PLL_CLKSEL_H264D_A_MASK         (0x03 << (PLL_CLKSEL_H264D_A - PLL_CLKSEL_R3_OFFSET))
#define PLL_CLKSEL_H265D_A_MASK         (0x03 << (PLL_CLKSEL_H265D_A - PLL_CLKSEL_R3_OFFSET))
#define PLL_CLKSEL_H264D_M_MASK         (0x03 << (PLL_CLKSEL_H264D_M - PLL_CLKSEL_R3_OFFSET))
#define PLL_CLKSEL_H265D_M_MASK         (0x03 << (PLL_CLKSEL_H265D_M - PLL_CLKSEL_R3_OFFSET))
#define PLL_CLKSEL_JPEG_LITE_MASK  	    (0x03 << (PLL_CLKSEL_JPEG_LITE - PLL_CLKSEL_R3_OFFSET))
#define PLL_CLKSEL_VTRC_AE_MASK    	    (0x03 << (PLL_CLKSEL_VTRC_AE - PLL_CLKSEL_R3_OFFSET))


/*r4*/
#define PLL_CLKSEL_SDIO_MASK            (0x03 << (PLL_CLKSEL_SDIO - PLL_CLKSEL_R4_OFFSET))
#define PLL_CLKSEL_SDIO2_MASK           (0x03 << (PLL_CLKSEL_SDIO2 - PLL_CLKSEL_R4_OFFSET))
#define PLL_CLKSEL_SDIO3_MASK           (0x03 << (PLL_CLKSEL_SDIO3 - PLL_CLKSEL_R4_OFFSET))
#define PLL_CLKSEL_ETHPHY_CLKSRC_MASK   (0x03 << (PLL_CLKSEL_ETHPHY_CLKSRC - PLL_CLKSEL_R4_OFFSET))
#define PLL_CLKSEL_SP_MASK              (0x03 << (PLL_CLKSEL_SP - PLL_CLKSEL_R4_OFFSET))
#define PLL_CLKSEL_SP2_MASK             (0x03 << (PLL_CLKSEL_SP2 - PLL_CLKSEL_R4_OFFSET))
#define PLL_CLKSEL_GPENC_MASK           (0x03 << (PLL_CLKSEL_GPENC - PLL_CLKSEL_R4_OFFSET))
#define PLL_CLKSEL_GPENC2_MASK          (0x03 << (PLL_CLKSEL_GPENC2 - PLL_CLKSEL_R4_OFFSET))
#define PLL_CLKSEL_UVCP2_MASK			(0x03 << (PLL_CLKSEL_UVCP2 - PLL_CLKSEL_R4_OFFSET))
#define PLL_CLKSEL_HWCOPY_MASK			(0x03 << (PLL_CLKSEL_HWCOPY - PLL_CLKSEL_R4_OFFSET))
#define PLL_CLKSEL_PMC_MASK				(0x03 << (PLL_CLKSEL_PMC - PLL_CLKSEL_R4_OFFSET))
#define PLL_CLKSEL_DSI_LPSRC_MASK       (0x03 << (PLL_CLKSEL_DSI_LPSRC - PLL_CLKSEL_R4_OFFSET))
#define PLL_CLKSEL_CSI_TX_LPSRC_MASK    (0x03 << (PLL_CLKSEL_CSI_TX_LPSRC - PLL_CLKSEL_R4_OFFSET))
#define PLL_CLKSEL_MI_MASK				(0x03 << (PLL_CLKSEL_MI - PLL_CLKSEL_R4_OFFSET))
#define PLL_CLKSEL_ETH2PHY_CLKSRC_MASK  (0x03 << (PLL_CLKSEL_ETH2PHY_CLKSRC - PLL_CLKSEL_R4_OFFSET))

/*r5*/
#define PLL_CLKSEL_HASH_MASK            (0x01 << (PLL_CLKSEL_HASH - PLL_CLKSEL_R5_OFFSET))
#define PLL_CLKSEL_RSA_MASK             (0x01 << (PLL_CLKSEL_RSA - PLL_CLKSEL_R5_OFFSET))
#define PLL_CLKSEL_CRYPTO_MASK          (0x01 << (PLL_CLKSEL_CRYPTO - PLL_CLKSEL_R5_OFFSET))
#define PLL_CLKSEL_ADC_PD_MASK          (0x01 << (PLL_CLKSEL_ADC_PD - PLL_CLKSEL_R5_OFFSET))
#define PLL_CLKSEL_TRNG_MASK            (0x01 << (PLL_CLKSEL_TRNG - PLL_CLKSEL_R5_OFFSET))
#define PLL_CLKSEL_TRNGRO_CLKSRC_MASK   (0x01 << (PLL_CLKSEL_TRNGRO_CLKSRC- PLL_CLKSEL_R5_OFFSET))
#define PLL_CLKSEL_DRTC_MASK            (0x03 << (PLL_CLKSEL_DRTC - PLL_CLKSEL_R5_OFFSET))
#define PLL_CLKSEL_REMOTE_MASK          (0x03 << (PLL_CLKSEL_REMOTE - PLL_CLKSEL_R5_OFFSET))
#define PLL_CLKSEL_GRAPHIC_MASK         (0x03 << (PLL_CLKSEL_GRAPHIC - PLL_CLKSEL_R5_OFFSET))
#define PLL_CLKSEL_GRAPHIC2_MASK        (0x03 << (PLL_CLKSEL_GRAPHIC2 - PLL_CLKSEL_R5_OFFSET))
#define PLL_CLKSEL_IDE_CLKSRC_MASK      (0x0F << (PLL_CLKSEL_IDE_CLKSRC - PLL_CLKSEL_R5_OFFSET))
#define PLL_CLKSEL_IDE2_CLKSRC_MASK     (0x0F << (PLL_CLKSEL_IDE2_CLKSRC - PLL_CLKSEL_R5_OFFSET))
#define PLL_CLKSEL_GRAPHIC3_MASK        (0x03 << (PLL_CLKSEL_GRAPHIC3 - PLL_CLKSEL_R5_OFFSET))

/*r6*/
#define PLL_CLKSEL_CSI2_PXCLK_MASK      (0x01 << (PLL_CLKSEL_CSI2_PXCLK - PLL_CLKSEL_R6_OFFSET))
#define PLL_CLKSEL_CSI4_PXCLK_MASK      (0x01 << (PLL_CLKSEL_CSI4_PXCLK - PLL_CLKSEL_R6_OFFSET))
#define PLL_CLKSEL_CSI_MASK             (0x03 << (PLL_CLKSEL_CSI - PLL_CLKSEL_R6_OFFSET))
#define PLL_CLKSEL_CSI2_MASK            (0x03 << (PLL_CLKSEL_CSI2 - PLL_CLKSEL_R6_OFFSET))
#define PLL_CLKSEL_CSI3_MASK            (0x03 << (PLL_CLKSEL_CSI3 - PLL_CLKSEL_R6_OFFSET))
#define PLL_CLKSEL_CSI4_MASK            (0x03 << (PLL_CLKSEL_CSI4 - PLL_CLKSEL_R6_OFFSET))
#define PLL_CLKSEL_CSI5_MASK            (0x03 << (PLL_CLKSEL_CSI5 - PLL_CLKSEL_R6_OFFSET))



/*r7*/
#define PLL_CLKSEL_DAI_MASK             (0x01 << (PLL_CLKSEL_DAI - PLL_CLKSEL_R7_OFFSET))
#define PLL_CLKSEL_I2S_MCLKSEL_MASK     (0x01 << (PLL_CLKSEL_I2S_MCLK - PLL_CLKSEL_R7_OFFSET))
#define PLL_CLKSEL_I2S2_MCLKSEL_MASK    (0x01 << (PLL_CLKSEL_I2S2_MCLK - PLL_CLKSEL_R7_OFFSET))
#define PLL_CLKSEL_TSE_MASK             (0x03 << (PLL_CLKSEL_TSE - PLL_CLKSEL_R7_OFFSET))


/*r8*/
#define PLL_CLKSEL_PWM0_3_CLKDIV_MASK   (0x3FFF << (PLL_CLKSEL_PWM0_3_CLKDIV - PLL_CLKSEL_R8_OFFSET))
#define PLL_CLKSEL_PWM4_7_CLKDIV_MASK   (0x3FFF << (PLL_CLKSEL_PWM4_7_CLKDIV - PLL_CLKSEL_R8_OFFSET))

/*r9*/
#define PLL_CLKSEL_PWM8_CLKDIV_MASK     (0x3FFF << (PLL_CLKSEL_PWM8_CLKDIV - PLL_CLKSEL_R9_OFFSET))
#define PLL_CLKSEL_PWM9_CLKDIV_MASK     (0x3FFF << (PLL_CLKSEL_PWM9_CLKDIV - PLL_CLKSEL_R9_OFFSET))

/*r10*/
#define PLL_CLKSEL_PWM10_CLKDIV_MASK     (0x3FFF << (PLL_CLKSEL_PWM10_CLKDIV - PLL_CLKSEL_R10_OFFSET))
#define PLL_CLKSEL_PWM11_CLKDIV_MASK     (0x3FFF << (PLL_CLKSEL_PWM11_CLKDIV - PLL_CLKSEL_R10_OFFSET))

/*r11*/
#define PLL_CLKSEL_ADO_MCLKDIV_MASK     (0xFF << (PLL_CLKSEL_DAI_MCLKDIV - PLL_CLKSEL_R11_OFFSET))
#define PLL_CLKSEL_ADO2_MCLKDIV_MASK    (0xFF << (PLL_CLKSEL_DAI2_MCLKDIV - PLL_CLKSEL_R11_OFFSET))
#define PLL_CLKSEL_SP_CLKDIV_MASK       (0xFF << (PLL_CLKSEL_SP_CLKDIV - PLL_CLKSEL_R11_OFFSET))
#define PLL_CLKSEL_SP2_CLKDIV_MASK      (0xFF << (PLL_CLKSEL_SP2_CLKDIV - PLL_CLKSEL_R11_OFFSET))

/*r12*/
#define PLL_CLKSEL_SDIO_CLKDIV_MASK     (0x7FF<< (PLL_CLKSEL_SDIO_CLKDIV - PLL_CLKSEL_R12_OFFSET))
#define PLL_CLKSEL_SDIO2_CLKDIV_MASK    (0x7FF<< (PLL_CLKSEL_SDIO2_CLKDIV - PLL_CLKSEL_R12_OFFSET))

/*r13*/
#define PLL_CLKSEL_UART_CLKDIV_MASK    (0xFF << (PLL_CLKSEL_UART_CLKDIV - PLL_CLKSEL_R13_OFFSET))
#define PLL_CLKSEL_UART2_CLKDIV_MASK    (0xFF << (PLL_CLKSEL_UART2_CLKDIV - PLL_CLKSEL_R13_OFFSET))
#define PLL_CLKSEL_UART3_CLKDIV_MASK    (0xFF << (PLL_CLKSEL_UART3_CLKDIV - PLL_CLKSEL_R13_OFFSET))
#define PLL_CLKSEL_UART4_CLKDIV_MASK    (0xFF << (PLL_CLKSEL_UART4_CLKDIV - PLL_CLKSEL_R13_OFFSET))

/*r14*/
#define PLL_CLKSEL_UART5_CLKDIV_MASK    (0xFF << (PLL_CLKSEL_UART5_CLKDIV - PLL_CLKSEL_R14_OFFSET))
#define PLL_CLKSEL_NAND_CLKDIV_MASK     (0x3F << (PLL_CLKSEL_NAND_CLKDIV - PLL_CLKSEL_R14_OFFSET))
#define PLL_CLKSEL_ETH_PTP_CLKDIV_MASK  (0x3 << (PLL_CLKSEL_ETH_PTP_CLKDIV - PLL_CLKSEL_R14_OFFSET))
#define PLL_CLKSEL_ETH2_PTP_CLKDIV_MASK (0x3 << (PLL_CLKSEL_ETH2_PTP_CLKDIV - PLL_CLKSEL_R14_OFFSET))

/*r15*/
#define PLL_CLKSEL_IDE_CLKDIV_MASK        (0xFF << (PLL_CLKSEL_IDE_CLKDIV - PLL_CLKSEL_R15_OFFSET))
#define PLL_CLKSEL_IDE_OUTIF_CLKDIV_MASK  (0xFF << (PLL_CLKSEL_IDE_OUTIF_CLKDIV - PLL_CLKSEL_R15_OFFSET))
#define PLL_CLKSEL_IDE2_CLKDIV_MASK       (0xFF << (PLL_CLKSEL_IDE2_CLKDIV - PLL_CLKSEL_R15_OFFSET))
#define PLL_CLKSEL_IDE2_OUTIF_CLKDIV_MASK (0xFF << (PLL_CLKSEL_IDE2_OUTIF_CLKDIV - PLL_CLKSEL_R15_OFFSET))

/*r16*/
#define PLL_CLKSEL_TRNG_RO_CLKDIV_MASK   (0xFF << (PLL_CLKSEL_TRNG_RO_CLKDIV - PLL_CLKSEL_R16_OFFSET))
#define PLL_CLKSEL_RO_PHY_MASK			 (0x3 << (PLL_CLKSEL_RO_PHY - PLL_CLKSEL_R16_OFFSET))
#define PLL_CLKSEL_RO_PHY_FREQ_MASK		 (0x1 << (PLL_CLKSEL_RO_PHY_FREQ- PLL_CLKSEL_R16_OFFSET))
#define PLL_CLKSEL_RO32K_CLKDIV_MASK	 (0x3FF << (PLL_CLKSEL_RO32K_CLKDIV- PLL_CLKSEL_R16_OFFSET))
#define PLL_CLKSEL_RO32K_DIV_TESTEN_MASK (0x1 << (PLL_CLKSEL_RO32K_DIV_TESTEN- PLL_CLKSEL_R16_OFFSET))
#define PLL_CLKSEL_TRNG_CLKDIV_MASK      (0xFF << (PLL_CLKSEL_TRNG_CLKDIV - PLL_CLKSEL_R16_OFFSET))

/*r17*/
#define PLL_CLKSEL_DSP_IOP_CLKDIV_MASK   (0x3 << (PLL_CLKSEL_DSP_IOP_CLKDIV - PLL_CLKSEL_R17_OFFSET))
#define PLL_CLKSEL_DSP_EDP_CLKDIV_MASK   (0x1 << (PLL_CLKSEL_DSP_EDP_CLKDIV - PLL_CLKSEL_R17_OFFSET))
#define PLL_CLKSEL_DSP_EPP_CLKDIV_MASK   (0x1 << (PLL_CLKSEL_DSP_EPP_CLKDIV - PLL_CLKSEL_R17_OFFSET))
#define PLL_CLKSEL_DSP_EDAP_CLKDIV_MASK  (0x3 << (PLL_CLKSEL_DSP_EDAP_CLKDIV - PLL_CLKSEL_R17_OFFSET))
#define PLL_CLKSEL_DSP_OCEM_CLKDIV_MASK  (0x3 << (PLL_CLKSEL_DSP_OCEM_CLKDIV - PLL_CLKSEL_R17_OFFSET))


/*r18*/
#define PLL_CLKSEL_ADO_CLKDIV_MASK      (0xFF << (PLL_CLKSEL_DAI_CLKDIV - PLL_CLKSEL_R18_OFFSET))
#define PLL_CLKSEL_ADO_OSR_CLKDIV_MASK  (0xFF << (PLL_CLKSEL_DAI_OSR_CLKDIV - PLL_CLKSEL_R18_OFFSET))
#define PLL_CLKSEL_ADO2_CLKDIV_MASK     (0xFF << (PLL_CLKSEL_DAI2_CLKDIV - PLL_CLKSEL_R18_OFFSET))


/*r19*/
#define PLL_CLKSEL_SDIO3_CLKDIV_MASK    (0x7FF<< (PLL_CLKSEL_SDIO3_CLKDIV - PLL_CLKSEL_R19_OFFSET))
#define PLL_CLKSEL_MI_CLKDIV_MASK    	(0xFF<< (PLL_CLKSEL_MI_CLKDIV - PLL_CLKSEL_R19_OFFSET))

/*r20*/
#define PLL_CLKSEL_UART6_CLKDIV_MASK    (0xFF << (PLL_CLKSEL_UART6_CLKDIV - PLL_CLKSEL_R20_OFFSET))
#define PLL_CLKSEL_UART7_CLKDIV_MASK    (0xFF << (PLL_CLKSEL_UART7_CLKDIV - PLL_CLKSEL_R20_OFFSET))
#define PLL_CLKSEL_UART8_CLKDIV_MASK    (0xFF << (PLL_CLKSEL_UART8_CLKDIV - PLL_CLKSEL_R20_OFFSET))
#define PLL_CLKSEL_UART9_CLKDIV_MASK    (0xFF << (PLL_CLKSEL_UART9_CLKDIV - PLL_CLKSEL_R20_OFFSET))

/*r21*/
#define PLL_CLKSEL_SPI_CLKDIV_MASK      (0x7FF << (PLL_CLKSEL_SPI_CLKDIV - PLL_CLKSEL_R21_OFFSET))
#define PLL_CLKSEL_SPI2_CLKDIV_MASK     (0x7FF << (PLL_CLKSEL_SPI2_CLKDIV - PLL_CLKSEL_R21_OFFSET))

/*r22*/
#define PLL_CLKSEL_SPI3_CLKDIV_MASK     (0x7FF << (PLL_CLKSEL_SPI3_CLKDIV - PLL_CLKSEL_R22_OFFSET))
#define PLL_CLKSEL_SPI4_CLKDIV_MASK     (0x7FF << (PLL_CLKSEL_SPI4_CLKDIV - PLL_CLKSEL_R22_OFFSET))

/*r23*/
#define PLL_CLKSEL_SPI5_CLKDIV_MASK     (0x7FF << (PLL_CLKSEL_SPI5_CLKDIV - PLL_CLKSEL_R23_OFFSET))

/*r24*/
#define PLL_CLKSEL_SIE_CLKSRC_MASK      (0x0F << (PLL_CLKSEL_SIE_CLKSRC - PLL_CLKSEL_R24_OFFSET))
#define PLL_CLKSEL_SIE2_CLKSRC_MASK     (0x0F << (PLL_CLKSEL_SIE2_CLKSRC - PLL_CLKSEL_R24_OFFSET))
#define PLL_CLKSEL_SIE3_CLKSRC_MASK     (0x0F << (PLL_CLKSEL_SIE3_CLKSRC - PLL_CLKSEL_R24_OFFSET))
#define PLL_CLKSEL_SIE4_CLKSRC_MASK     (0x0F << (PLL_CLKSEL_SIE4_CLKSRC - PLL_CLKSEL_R24_OFFSET))
#define PLL_CLKSEL_SIE5_CLKSRC_MASK     (0x0F << (PLL_CLKSEL_SIE5_CLKSRC - PLL_CLKSEL_R24_OFFSET))
#define PLL_CLKSEL_SIE6_CLKSRC_MASK     (0x0F << (PLL_CLKSEL_SIE6_CLKSRC - PLL_CLKSEL_R24_OFFSET))
#define PLL_CLKSEL_SIE_MCLKSRC_MASK     (0x0F << (PLL_CLKSEL_SIE_MCLKSRC - PLL_CLKSEL_R24_OFFSET))
/*r25*/
#define PLL_CLKSEL_SIE_MCLK2SRC_MASK    (0xF << (PLL_CLKSEL_SIE_MCLK2SRC - PLL_CLKSEL_R25_OFFSET))
#define PLL_CLKSEL_SIE_MCLK3SRC_MASK    (0x0F << (PLL_CLKSEL_SIE_MCLK3SRC - PLL_CLKSEL_R25_OFFSET))
#define PLL_CLKSEL_SIE_MCLK4SRC_MASK    (0x0F << (PLL_CLKSEL_SIE_MCLK4SRC - PLL_CLKSEL_R25_OFFSET))
#define PLL_CLKSEL_SIE_MCLK5SRC_MASK    (0x0F << (PLL_CLKSEL_SIE_MCLK5SRC - PLL_CLKSEL_R25_OFFSET))
#define PLL_CLKSEL_VIE_CLKSRC_MASK      (0x0F << (PLL_CLKSEL_VIE_CLKSRC - PLL_CLKSEL_R25_OFFSET))
#define PLL_CLKSEL_VIE2_CLKSRC_MASK     (0x0F << (PLL_CLKSEL_VIE2_CLKSRC - PLL_CLKSEL_R25_OFFSET))

/*r26*/
#define PLL_CLKSEL_SIE3_PXCLKSRC_MASK   (0x01 << (PLL_CLKSEL_SIE3_PXCLKSRC - PLL_CLKSEL_R26_OFFSET))
#define PLL_CLKSEL_SIE4_PXCLKSRC_MASK   (0x01 << (PLL_CLKSEL_SIE4_PXCLKSRC - PLL_CLKSEL_R26_OFFSET))
#define PLL_CLKSEL_SIE5_PXCLKSRC_MASK   (0x01 << (PLL_CLKSEL_SIE5_PXCLKSRC - PLL_CLKSEL_R26_OFFSET))
#define PLL_CLKSEL_SIE6_PXCLKSRC_MASK   (0x01 << (PLL_CLKSEL_SIE6_PXCLKSRC - PLL_CLKSEL_R26_OFFSET))

/*r27*/
#define PLL_CLKSEL_SIE_CLKDIV_MASK      (0xFF << (PLL_CLKSEL_SIE_CLKDIV - PLL_CLKSEL_R27_OFFSET))
#define PLL_CLKSEL_SIE2_CLKDIV_MASK     (0xFF << (PLL_CLKSEL_SIE2_CLKDIV - PLL_CLKSEL_R27_OFFSET))
#define PLL_CLKSEL_SIE3_CLKDIV_MASK     (0xFF << (PLL_CLKSEL_SIE3_CLKDIV - PLL_CLKSEL_R27_OFFSET))
#define PLL_CLKSEL_SIE4_CLKDIV_MASK     (0xFF << (PLL_CLKSEL_SIE4_CLKDIV - PLL_CLKSEL_R27_OFFSET))

/*r28*/
#define PLL_CLKSEL_SIE5_CLKDIV_MASK     (0xFF << (PLL_CLKSEL_SIE5_CLKDIV - PLL_CLKSEL_R28_OFFSET))
#define PLL_CLKSEL_SIE6_CLKDIV_MASK     (0xFF << (PLL_CLKSEL_SIE6_CLKDIV - PLL_CLKSEL_R28_OFFSET))
#define PLL_CLKSEL_SIE_MCLKDIV_MASK     (0xFF << (PLL_CLKSEL_SIE_MCLKDIV - PLL_CLKSEL_R28_OFFSET))
#define PLL_CLKSEL_SIE_MCLK2DIV_MASK    (0xFF << (PLL_CLKSEL_SIE_MCLK2DIV - PLL_CLKSEL_R28_OFFSET))

/*r29*/
#define PLL_CLKSEL_SIE_MCLK3DIV_MASK    (0xFF << (PLL_CLKSEL_SIE_MCLK3DIV - PLL_CLKSEL_R29_OFFSET))
#define PLL_CLKSEL_SIE_MCLK4DIV_MASK    (0xFF << (PLL_CLKSEL_SIE_MCLK4DIV - PLL_CLKSEL_R29_OFFSET))
#define PLL_CLKSEL_SIE_MCLK5DIV_MASK    (0xFF << (PLL_CLKSEL_SIE_MCLK5DIV - PLL_CLKSEL_R29_OFFSET))
#define PLL_CLKSEL_VIE_CLKDIV_MASK      (0xFF << (PLL_CLKSEL_VIE_CLKDIV - PLL_CLKSEL_R29_OFFSET))

/*r30*/
#define PLL_CLKSEL_VIE2_CLKDIV_MASK     (0xFF << (PLL_CLKSEL_VIE2_CLKDIV - PLL_CLKSEL_R30_OFFSET))