
#ifndef ENUM_DUMMY4WORD
#define ENUM_DUMMY4WORD(name)   E_##name = 0x10000000
#endif

// ref from code/hdal/drivers/k_driver/include/rtos_na51055/pll.h
typedef enum {
	DMA2_CLK,           ///< DMA(SDRAM2) clock
	DMA_CLK,            ///< DMA(SDRAM) clock
	SIE_MCLK,           ///< SIE MCLK
	SIE_MCLK2,          ///< SIE MCLK2
	SIE_CLK,            ///< SIE clock
	SIE2_CLK,           ///< SIE2 Clock
	TGE_CLK,            ///< TGE clock
	IPE_CLK,            ///< IPE clock
	DIS_CLK,            ///< DIS clock
	IME_CLK,            ///< IME clock
	SIE_MCLK3,          ///< SIE MCLK3
	ISE_CLK,            ///< ISE clock
	SP_CLK,             ///< special clock
	IFE_CLK,            ///< IFE clock
	DCE_CLK,            ///< DCE clock
	IFE2_CLK,           ///< IFE2 clock
	IDE1_CLK,           ///< IDE clock
	SIE3_CLK,           ///< SIE3 clock
	SIE4_CLK,           ///< SIE4 clock
	SIE5_CLK,           ///< SIE5 clock
	SDE_CLK,            ///< SDE clock
	VPE_CLK,            ///< VPE clock
	CRYPTO_CLK	= 23,   ///< Crypto clock
	H264_CLK	= 24,   ///< H.264 clock
	H265_CLK	= 24,   ///< H.265 clock
	H26X_CLK    = 24,   ///< H.26X clock
	AFFINE_CLK  = 25,   ///< AFFINE clock
	JPG_CLK		= 26,   ///< JPEG clock
	GRAPH_CLK,          ///< Graphic clock
	GRAPH2_CLK,         ///< Graphic2 clock
	DAI_CLK,            ///< DAI clock
	EAC_A_ADC_CLK,      ///< EAC analog AD clock
	EAC_A_DAC_CLK,      ///< EAC analog DA clock

	NAND_CLK	= 32,   ///< NAND clock
	SDIO_CLK	= 34,   ///< SDIO clock
	SDIO2_CLK,          ///< SDIO2 clock
	I2C_CLK = 36,       ///< I2C clock
	I2C2_CLK = 37,      ///< I2C2 clock
	SPI_CLK,            ///< SPI clock
	SPI2_CLK,           ///< SPI2 clock
	SPI3_CLK,           ///< SPI3 clock
	SIF_CLK,            ///< SIF clock
	UART_CLK,           ///< UART clock
	UART2_CLK,          ///< UART2 clock
	REMOTE_CLK,         ///< Remote clock
	ADC_CLK,            ///< ADC clock
	SDIO3_CLK,          ///< SDIO3 clock
	WDT_CLK		= 49,   ///< WDT clock
	TMR_CLK,            ///< Timer clock
	EAC_D_CLKEN = 52,   ///< EAC digital clock
	UART3_CLK	= 54,   ///< UART3 clock
	UART4_CLK	= 55,   ///< UART4 clock
	UART5_CLK	= 56,   ///< UART5 clock
	UART6_CLK	= 57,   ///< UART6 clock
	I2C4_CLK = 58,      ///< I2C4 clock
	I2C5_CLK = 59,      ///< I2C5 clock
	EFUSE_CLK	= 60,   ///< EFUSE clock
	ETH_CLK,            ///< ETH clock
	SP2_CLK,            ///< SP2 clock
	I2C3_CLK = 63,      ///< I2C3 clock

	MIPI_LVDS_CLK = 65, ///< MIPI/LVDS clock
	MIPI_LVDS2_CLK,     ///< MIPI/LVDS2 clock
	MIPI_DSI_CLK,       ///< MIPI DSI clock
	SIE_PXCLK,          ///< SIE PX clock
	SIE2_PXCLK,         ///< SIE2 PX clock
	SIE3_PXCLK,         ///< SIE3 PX clock
	SIE4_PXCLK,         ///< SIE4 PX clock
	PWM_CCNT_CLK = 72,  ///< PWM CCNT clock
	PWM_CCNT0_CLK = 72, ///< PWM CCNT0 clock
	PWM_CCNT1_CLK,      ///< PWM CCNT1 clock
	PWM_CCNT2_CLK,      ///< PWM CCNT2 clock
	SPI4_CLK,			///< SPI4 clock
	SPI5_CLK,			///< SPI5 clock
	TSE_CLK      = 77,  ///< TSE  clock
	DRTC_CLK     = 86,  ///< DRTC clock
	ETHPHY_CLK   = 88,  ///< ETH PHY clock
	TRNG_CLK,           ///< TRNG clock
	RSA_CLK,            ///< RSA clock
	HASH_CLK,           ///< HASH clock
	TRNG_RO_CLK,        ///< TRNG clock
	MIPI_LVDS_PHYD4_CLK2 = 93,///< MIPI/LVDS PHY HS-clock/4
	MIPI_LVDS_PHYD4_CLK = 94,///< MIPI/LVDS PHY HS-clock/4
	MIPI_LVDS2_PHYD4_CLK = 95,///< MIPI/LVDS2 PHY HS-clock/4

	PWM0_CLK = 96,      ///< PWM0 clock
	PWM1_CLK,           ///< PWM1 clock
	PWM2_CLK,           ///< PWM2 clock
	PWM3_CLK,           ///< PWM3 clock
	PWM4_CLK,           ///< PWM4 clock
	PWM5_CLK,           ///< PWM5 clock
	PWM6_CLK,           ///< PWM6 clock
	PWM7_CLK,           ///< PWM7 clock
	PWM8_CLK,           ///< PWM8 clock
	PWM9_CLK,           ///< PWM9 clock
	PWM10_CLK,          ///< PWM10 clock
	PWM11_CLK,          ///< PWM11 clock

	SDP_CLK = 112,		///< SDP clock
	NUE_CLK = 116,		///< NUE clock
	NUE2_CLK,			///< NUE2 clock
	MDBC_CLK,			///< MDBC clock
	CNN_CLK,			///< CNN clock
	CNN2_CLK,			///< CNN2 clock
	IVE_CLK,			///< IVE clock

	ENUM_DUMMY4WORD(CG_EN)
} CG_EN;

typedef enum {
	PLL_ID_1        = 1,        ///< PLL1 (internal 480 MHz)
	PLL_ID_3        = 3,        ///< PLL3 (for DMA)
	PLL_ID_4        = 4,        ///< PLL4 (for SSPLL)
	PLL_ID_5        = 5,        ///< PLL5 (for sensor1)
	PLL_ID_6        = 6,        ///< PLL6 (for IDE/eth)
	PLL_ID_7        = 7,        ///< PLL7 (for audio)
	PLL_ID_8        = 8,        ///< PLL8 (for CPU)
	PLL_ID_9        = 9,        ///< PLL9 (for IDE/eth backup)
	PLL_ID_10       = 10,       ///< PLL10 (for CNN)
	PLL_ID_11       = 11,       ///< PLL11 (for DSI)
	PLL_ID_12       = 12,       ///< PLL12 (for sensor2)
	PLL_ID_13       = 13,       ///< PLL13 (for IPP)
	PLL_ID_14       = 14,       ///< PLL14 (for DMA2)
	PLL_ID_15       = 15,       ///< PLL15 (for H264/H265)
	PLL_ID_16       = 16,       ///< PLL16 (for ETH)<528 only>
	PLL_ID_17       = 17,       ///< PLL17 (for IPP2)<528 only>
	PLL_ID_18       = 18,       ///< PLL18 (for SENSOR3)<528 only>

	PLL_ID_FIXED320 = 24,       ///< Fixed 320MHz PLL
	PLL_ID_MAX,
	ENUM_DUMMY4WORD(PLL_ID)
} PLL_ID;

//
// Clock Rate bit definition
//
#define PLL_CLKSEL_CPU_MASK             (0x03 << PLL_CLKSEL_CPU)
#define PLL_CLKSEL_APB_MASK             (0x03 << PLL_CLKSEL_APB)
#define PLL_CLKSEL_DMA_ARBT_MASK		(0x01 << PLL_CLKSEL_DMA_ARBT)
#define PLL_CLKSEL_DDRPHY_MASK          (0x01 << PLL_CLKSEL_DDRPHY)

#define PLL_CLKSEL_CNN_MASK             (0x03 << (PLL_CLKSEL_CNN - PLL_CLKSEL_R1_OFFSET))
#define PLL_CLKSEL_IVE_MASK             (0x03 << (PLL_CLKSEL_IVE - PLL_CLKSEL_R1_OFFSET))
#define PLL_CLKSEL_IPE_MASK             (0x03 << (PLL_CLKSEL_IPE - PLL_CLKSEL_R1_OFFSET))
#define PLL_CLKSEL_DIS_MASK             (0x03 << (PLL_CLKSEL_DIS - PLL_CLKSEL_R1_OFFSET))
#define PLL_CLKSEL_IME_MASK             (0x03 << (PLL_CLKSEL_IME - PLL_CLKSEL_R1_OFFSET))
#define PLL_CLKSEL_CNN2_MASK            (0x03 << (PLL_CLKSEL_CNN2- PLL_CLKSEL_R1_OFFSET))
#define PLL_CLKSEL_SDE_MASK             (0x03 << (PLL_CLKSEL_SDE - PLL_CLKSEL_R1_OFFSET))
#define PLL_CLKSEL_MDBC_MASK            (0x03 << (PLL_CLKSEL_MDBC- PLL_CLKSEL_R1_OFFSET))
#define PLL_CLKSEL_VPE_MASK             (0x03 << (PLL_CLKSEL_VPE - PLL_CLKSEL_R1_OFFSET))
#define PLL_CLKSEL_ISE_MASK             (0x03 << (PLL_CLKSEL_ISE - PLL_CLKSEL_R1_OFFSET))
#define PLL_CLKSEL_DCE_MASK             (0x03 << (PLL_CLKSEL_DCE - PLL_CLKSEL_R1_OFFSET))

#define PLL_CLKSEL_IFE_MASK             (0x03 << (PLL_CLKSEL_IFE - PLL_CLKSEL_R2_OFFSET))
#define PLL_CLKSEL_IFE2_MASK            (0x03 << (PLL_CLKSEL_IFE2 - PLL_CLKSEL_R2_OFFSET))
#define PLL_CLKSEL_SIE_MCLKSRC_MASK     (0x03 << (PLL_CLKSEL_SIE_MCLKSRC - PLL_CLKSEL_R2_OFFSET))
#define PLL_CLKSEL_SIE_MCLK2SRC_MASK    (0x03 << (PLL_CLKSEL_SIE_MCLK2SRC - PLL_CLKSEL_R2_OFFSET))
#define PLL_CLKSEL_SIE_MCLK3SRC_MASK    (0x03 << (PLL_CLKSEL_SIE_MCLK3SRC - PLL_CLKSEL_R2_OFFSET))
#define PLL_CLKSEL_SIE_IO_PXCLKSRC_MASK (0x01 << (PLL_CLKSEL_SIE_IO_PXCLKSRC - PLL_CLKSEL_R2_OFFSET))
#define PLL_CLKSEL_SIE2_IO_PXCLKSRC_MASK (0x01 << (PLL_CLKSEL_SIE2_IO_PXCLKSRC - PLL_CLKSEL_R2_OFFSET))
#define PLL_CLKSEL_SIE_PXCLKSRC_MASK    (0x01 << (PLL_CLKSEL_SIE_PXCLKSRC - PLL_CLKSEL_R2_OFFSET))
#define PLL_CLKSEL_SIE2_PXCLKSRC_MASK   (0x01 << (PLL_CLKSEL_SIE2_PXCLKSRC - PLL_CLKSEL_R2_OFFSET))
#define PLL_CLKSEL_SIE3_PXCLKSRC_MASK   (0x01 << (PLL_CLKSEL_SIE3_PXCLKSRC - PLL_CLKSEL_R2_OFFSET))
#define PLL_CLKSEL_SIE_MCLKINV_MASK     (0x01 << (PLL_CLKSEL_SIE_MCLKINV - PLL_CLKSEL_R2_OFFSET))
#define PLL_CLKSEL_SIE4_IO_PXCLKSRC_MASK (0x01 << (PLL_CLKSEL_SIE4_IO_PXCLKSRC - PLL_CLKSEL_R2_OFFSET))
#define PLL_CLKSEL_SIE4_PXCLKSRC_MASK   (0x01 << (PLL_CLKSEL_SIE4_PXCLKSRC - PLL_CLKSEL_R2_OFFSET))
#define PLL_CLKSEL_TGE_MASK             (0x01 << (PLL_CLKSEL_TGE - PLL_CLKSEL_R2_OFFSET))
#define PLL_CLKSEL_TGE2_MASK            (0x01 << (PLL_CLKSEL_TGE2 - PLL_CLKSEL_R2_OFFSET))
#define PLL_CLKSEL_SIE_MCLK2INV_MASK    (0x01 << (PLL_CLKSEL_SIE_MCLK2INV - PLL_CLKSEL_R2_OFFSET))
#define PLL_CLKSEL_SIE_MCLK3INV_MASK    (0x01 << (PLL_CLKSEL_SIE_MCLK3INV - PLL_CLKSEL_R2_OFFSET))
#define PLL_CLKSEL_NUE_MASK             (0x03 << (PLL_CLKSEL_NUE - PLL_CLKSEL_R2_OFFSET))
#define PLL_CLKSEL_NUE2_MASK            (0x03 << (PLL_CLKSEL_NUE2 - PLL_CLKSEL_R2_OFFSET))

#define PLL_CLKSEL_JPEG_MASK            (0x03 << (PLL_CLKSEL_JPEG - PLL_CLKSEL_R3_OFFSET))
#define PLL_CLKSEL_H265_MASK            (0x03 << (PLL_CLKSEL_H265 - PLL_CLKSEL_R3_OFFSET))
#define PLL_CLKSEL_GRAPHIC_MASK         (0x03 << (PLL_CLKSEL_GRAPHIC - PLL_CLKSEL_R3_OFFSET))
#define PLL_CLKSEL_AFFINE_MASK          (0x03 << (PLL_CLKSEL_AFFINE - PLL_CLKSEL_R3_OFFSET))
#define PLL_CLKSEL_GRAPHIC2_MASK        (0x03 << (PLL_CLKSEL_GRAPHIC2 - PLL_CLKSEL_R3_OFFSET))
#define PLL_CLKSEL_SIE3_CLKSRC_MASK     (0x07 << (PLL_CLKSEL_SIE3_CLKSRC - PLL_CLKSEL_R3_OFFSET))
#define PLL_CLKSEL_CRYPTO_MASK          (0x03 << (PLL_CLKSEL_CRYPTO - PLL_CLKSEL_R3_OFFSET))
#define PLL_CLKSEL_RSA_MASK             (0x03 << (PLL_CLKSEL_RSA - PLL_CLKSEL_R3_OFFSET))
#define PLL_CLKSEL_SIE_CLKSRC_MASK      (0x07 << (PLL_CLKSEL_SIE_CLKSRC - PLL_CLKSEL_R3_OFFSET))
#define PLL_CLKSEL_SIE2_CLKSRC_MASK     (0x07 << (PLL_CLKSEL_SIE2_CLKSRC - PLL_CLKSEL_R3_OFFSET))

#define PLL_CLKSEL_SDIO_MASK            (0x03 << (PLL_CLKSEL_SDIO - PLL_CLKSEL_R4_OFFSET))
#define PLL_CLKSEL_SDIO2_MASK           (0x03 << (PLL_CLKSEL_SDIO2 - PLL_CLKSEL_R4_OFFSET))
#define PLL_CLKSEL_MIPI_LVDS_MASK       (0x01 << (PLL_CLKSEL_MIPI_LVDS - PLL_CLKSEL_R4_OFFSET))
#define PLL_CLKSEL_LVDS_CLKPHASE_MASK   (0x01 << (PLL_CLKSEL_LVDS_CLKPHASE - PLL_CLKSEL_R4_OFFSET))
#define PLL_CLKSEL_LVDS2_CLKPHASE_MASK  (0x01 << (PLL_CLKSEL_LVDS2_CLKPHASE - PLL_CLKSEL_R4_OFFSET))
#define PLL_CLKSEL_MIPI_LVDS2_MASK      (0x01 << (PLL_CLKSEL_MIPI_LVDS2 - PLL_CLKSEL_R4_OFFSET))
#define PLL_CLKSEL_IDE_CLKSRC_MASK      (0x07 << (PLL_CLKSEL_IDE_CLKSRC - PLL_CLKSEL_R4_OFFSET))
#define PLL_CLKSEL_DSI_LPSRC_MASK       (0x01 << (PLL_CLKSEL_DSI_LPSRC - PLL_CLKSEL_R4_OFFSET))
#define PLL_CLKSEL_ADO_MCLKSEL_MASK     (0x01 << (PLL_CLKSEL_ADO_MCLKSEL - PLL_CLKSEL_R4_OFFSET))
#define PLL_CLKSEL_ETH_MASK             (0x01 << (PLL_CLKSEL_ETH - PLL_CLKSEL_R4_OFFSET))

#define PLL_CLKSEL_SDIO3_MASK           (0x03 << (PLL_CLKSEL_SDIO3 - PLL_CLKSEL_R5_OFFSET))
#define PLL_CLKSEL_TSE_MASK             (0x03 << (PLL_CLKSEL_TSE - PLL_CLKSEL_R5_OFFSET))
#define PLL_CLKSEL_SP_MASK              (0x03 << (PLL_CLKSEL_SP - PLL_CLKSEL_R5_OFFSET))
#define PLL_CLKSEL_SP2_MASK             (0x03 << (PLL_CLKSEL_SP2 - PLL_CLKSEL_R5_OFFSET))
#define PLL_CLKSEL_ETH_REFCLK_INV_MASK  (0x01 << (PLL_CLKSEL_ETH_REFCLK_INV - PLL_CLKSEL_R5_OFFSET))
#define PLL_CLKSEL_HASH_MASK            (0x03 << (PLL_CLKSEL_HASH - PLL_CLKSEL_R5_OFFSET))
#define PLL_CLKSEL_TRNG_MASK            (0x01 << (PLL_CLKSEL_TRNG - PLL_CLKSEL_R5_OFFSET))
#define PLL_CLKSEL_TRNGRO_CLKSRC_MASK   (0x01 << (PLL_CLKSEL_TRNGRO_CLKSRC- PLL_CLKSEL_R5_OFFSET))
#define PLL_CLKSEL_DRTC_MASK            (0x01 << (PLL_CLKSEL_DRTC - PLL_CLKSEL_R5_OFFSET))
#define PLL_CLKSEL_REMOTE_MASK          (0x01 << (PLL_CLKSEL_REMOTE - PLL_CLKSEL_R5_OFFSET))
#define PLL_CLKSEL_ADC_PD_MASK          (0x01 << (PLL_CLKSEL_ADC_PD - PLL_CLKSEL_R5_OFFSET))
#define PLL_CLKSEL_ETHPHY_CLKSRC_MASK   (0x03 << (PLL_CLKSEL_ETHPHY_CLKSRC - PLL_CLKSEL_R5_OFFSET))

#define PLL_CLKSEL_CSILPCLK_D0_MASK		(0x03 << (PLL_CLKSEL_CSILPCLK_D0 - PLL_CLKSEL_R6_OFFSET))
#define PLL_CLKSEL_CSILPCLK_D1_MASK		(0x03 << (PLL_CLKSEL_CSILPCLK_D1 - PLL_CLKSEL_R6_OFFSET))
#define PLL_CLKSEL_CSILPCLK_D2_MASK		(0x03 << (PLL_CLKSEL_CSILPCLK_D2 - PLL_CLKSEL_R6_OFFSET))
#define PLL_CLKSEL_CSILPCLK_D3_MASK		(0x03 << (PLL_CLKSEL_CSILPCLK_D3 - PLL_CLKSEL_R6_OFFSET))

#define PLL_CLKSEL_SIE4_CLKSRC_MASK     (0x07 << (PLL_CLKSEL_SIE4_CLKSRC - PLL_CLKSEL_R7_OFFSET))
#define PLL_CLKSEL_SIE5_CLKSRC_MASK     (0x07 << (PLL_CLKSEL_SIE5_CLKSRC - PLL_CLKSEL_R7_OFFSET))
#define PLL_CLKSEL_SIE4_CLKDIV_MASK     (0xFF << (PLL_CLKSEL_SIE4_CLKDIV - PLL_CLKSEL_R7_OFFSET))
#define PLL_CLKSEL_SIE5_CLKDIV_MASK     (0xFF << (PLL_CLKSEL_SIE5_CLKDIV - PLL_CLKSEL_R7_OFFSET))

#define PLL_CLKSEL_SIE_MCLKDIV_MASK     (0xFF << (PLL_CLKSEL_SIE_MCLKDIV - PLL_CLKSEL_R8_OFFSET))
#define PLL_CLKSEL_SIE_MCLK2DIV_MASK    (0xFF << (PLL_CLKSEL_SIE_MCLK2DIV - PLL_CLKSEL_R8_OFFSET))
#define PLL_CLKSEL_SIE_CLKDIV_MASK      (0xFF << (PLL_CLKSEL_SIE_CLKDIV - PLL_CLKSEL_R8_OFFSET))
#define PLL_CLKSEL_SIE2_CLKDIV_MASK     (0xFF << (PLL_CLKSEL_SIE2_CLKDIV - PLL_CLKSEL_R8_OFFSET))

#define PLL_CLKSEL_IDE_CLKDIV_MASK      (0xFF << (PLL_CLKSEL_IDE_CLKDIV - PLL_CLKSEL_R9_OFFSET))
#define PLL_CLKSEL_IDE_OUTIF_CLKDIV_MASK (0xFF << (PLL_CLKSEL_IDE_OUTIF_CLKDIV - PLL_CLKSEL_R9_OFFSET))
#define PLL_CLKSEL_SIE_MCLK3DIV_MASK    (0xFF << (PLL_CLKSEL_SIE_MCLK3DIV - PLL_CLKSEL_R9_OFFSET))
#define PLL_CLKSEL_TRNG_CLKDIV_MASK     (0xFF << (PLL_CLKSEL_TRNG_CLKDIV - PLL_CLKSEL_R9_OFFSET))

#define PLL_CLKSEL_SP_CLKDIV_MASK       (0xFF << (PLL_CLKSEL_SP_CLKDIV - PLL_CLKSEL_R10_OFFSET))
#define PLL_CLKSEL_SIE3_CLKDIV_MASK     (0xFF << (PLL_CLKSEL_SIE3_CLKDIV - PLL_CLKSEL_R10_OFFSET))
#define PLL_CLKSEL_ADO_CLKDIV_MASK      (0xFF << (PLL_CLKSEL_ADO_CLKDIV - PLL_CLKSEL_R10_OFFSET))
#define PLL_CLKSEL_ADO_OSR_CLKDIV_MASK  (0xFF << (PLL_CLKSEL_ADO_OSR_CLKDIV - PLL_CLKSEL_R10_OFFSET))

#define PLL_CLKSEL_SDIO_CLKDIV_MASK     (0x7FF<< (PLL_CLKSEL_SDIO_CLKDIV - PLL_CLKSEL_R11_OFFSET))
#define PLL_CLKSEL_SDIO2_CLKDIV_MASK    (0x7FF<< (PLL_CLKSEL_SDIO2_CLKDIV - PLL_CLKSEL_R11_OFFSET))

#define PLL_CLKSEL_SDIO3_CLKDIV_MASK    (0x7FF<< (PLL_CLKSEL_SDIO3_CLKDIV - PLL_CLKSEL_R12_OFFSET))
#define PLL_CLKSEL_NAND_CLKDIV_MASK     (0x3F << (PLL_CLKSEL_NAND_CLKDIV - PLL_CLKSEL_R12_OFFSET))
#define PLL_CLKSEL_SP2_CLKDIV_MASK      (0xFF << (PLL_CLKSEL_SP2_CLKDIV - PLL_CLKSEL_R12_OFFSET))

#define PLL_CLKSEL_SPI_CLKDIV_MASK      (0x7FF << (PLL_CLKSEL_SPI_CLKDIV - PLL_CLKSEL_R13_OFFSET))
#define PLL_CLKSEL_SPI2_CLKDIV_MASK     (0x7FF << (PLL_CLKSEL_SPI2_CLKDIV - PLL_CLKSEL_R13_OFFSET))

#define PLL_CLKSEL_SPI3_CLKDIV_MASK     (0x7FF << (PLL_CLKSEL_SPI3_CLKDIV - PLL_CLKSEL_R14_OFFSET))
#define PLL_CLKSEL_SPI4_CLKDIV_MASK     (0x7FF << (PLL_CLKSEL_SPI4_CLKDIV - PLL_CLKSEL_R14_OFFSET))

#define PLL_CLKSEL_UART2_CLKDIV_MASK    (0xFF << (PLL_CLKSEL_UART2_CLKDIV - PLL_CLKSEL_R15_OFFSET))
#define PLL_CLKSEL_UART3_CLKDIV_MASK    (0xFF << (PLL_CLKSEL_UART3_CLKDIV - PLL_CLKSEL_R15_OFFSET))
#define PLL_CLKSEL_UART4_CLKDIV_MASK    (0xFF << (PLL_CLKSEL_UART4_CLKDIV - PLL_CLKSEL_R15_OFFSET))
#define PLL_CLKSEL_UART5_CLKDIV_MASK    (0xFF << (PLL_CLKSEL_UART5_CLKDIV - PLL_CLKSEL_R15_OFFSET))

#define PLL_CLKSEL_TRNG_RO_CLKDIV_MASK  (0xFF << (PLL_CLKSEL_TRNG_RO_CLKDIV - PLL_CLKSEL_R20_OFFSET))
#define PLL_CLKSEL_TRNG_RO_DELAY_MASK   (0xF  << (PLL_CLKSEL_TRNG_RO_DELAY - PLL_CLKSEL_R20_OFFSET))
#define PLL_CLKSEL_UART6_CLKDIV_MASK    (0xFF << (PLL_CLKSEL_UART6_CLKDIV - PLL_CLKSEL_R20_OFFSET))
#define PLL_CLKSEL_ADO_MCLKDIV_MASK     (0xFF << (PLL_CLKSEL_ADO_MCLKDIV - PLL_CLKSEL_R20_OFFSET))

#define PLL_CLKSEL_SPI5_CLKDIV_MASK     (0x7FF << (PLL_CLKSEL_SPI5_CLKDIV - PLL_CLKSEL_R21_OFFSET))