
#ifndef ENUM_DUMMY4WORD
#define ENUM_DUMMY4WORD(name)   E_##name = 0x10000000
#endif

// ref from code/hdal/drivers/k_driver/source/rtos_ns02301/pll/pll_int.h
typedef enum {
	DMA_CLK       = 1,  ///< DMA(SDRAM) clock
	SIE_MCLK,           ///< SIE MCLK
	SIE_MCLK2,          ///< SIE MCLK2
	SIE_CLK,            ///< SIE clock
	SIE2_CLK,           ///< SIE2 Clock
	TGE_CLK,            ///< TGE clock
	IPE_CLK,            ///< IPE clock
	IME_CLK       = 9,  ///< IME clock
	SIE_MCLK3,          ///< SIE MCLK3
	ISE_CLK,            ///< ISE clock
	SP_CLK,             ///< special clock
	IFE_CLK,            ///< IFE clock
	IDE1_CLK      = 16, ///< IDE clock
	SIE3_CLK,           ///< SIE3 clock
	CFGE_CLK      = 20, ///< CFG clock
	CRYPTO_CLK    = 23, ///< Crypto clock
	VENC_CLK      = 24, ///< VENC clock
	YDCC_CLK      = 25, ///< YDCC clock
	JPG_CLK       = 26, ///< JPEG clock
	JPEG_CLK=JPG_CLK,
	GRAPH_CLK,          ///< Graphic clock
	GRAPH2_CLK,         ///< Graphic2 clock
	DAI_CLK,            ///< DAI clock
	EAC_A_ADC_CLK,      ///< EAC analog AD clock
	EAC_A_DAC_CLK,      ///< EAC analog DA clock

	NAND_CLK      = 32, ///< NAND clock
	SDIO_CLK      = 34, ///< SDIO clock
	SDIO2_CLK,          ///< SDIO2 clock
	I2C_CLK       = 36, ///< I2C clock
	I2C2_CLK      = 37, ///< I2C2 clock
	SPI_CLK,            ///< SPI clock
	SPI2_CLK,           ///< SPI2 clock
	SPI3_CLK,           ///< SPI3 clock
	SIF_CLK,            ///< SIF clock
	UART_CLK,           ///< UART clock
	UART2_CLK,          ///< UART2 clock
	REMOTE_CLK,         ///< Remote clock
	ADC_CLK,            ///< ADC clock
	SDIO3_CLK,          ///< SDIO3 clock
	TMR_CLK       = 32+18, ///< Timer clock
	EAC_D_CLKEN   = 52, ///< EAC digital clock
	UVCP_CLKEN    = 53, ///< UVCP clock
	UART3_CLK     = 54, ///< UART3 clock
	EFUSE_CLK     = 60, ///< EFUSE clock
	ETH_CLK,            ///< ETH clock
	SP2_CLK,            ///< SP2 clock


	MIPI_CSI_CLK = 65, 	///< MIPI/CSI clock
	MIPI_CSI2_CLK,     	///< MIPI/CSI clock

	SIE_PXCLK    = 64+4,///< SIE PX clock
	SIE2_PXCLK,         ///< SIE2 PX clock
	SIE3_PXCLK,         ///< SIE3 PX clock
	ECDSA_CLK,          ///< ECDSA clock
	PWM_CCNT_CLK  = 72, ///< PWM CCNT clock
	PWM_CCNT0_CLK = 72, ///< PWM CCNT0 clock
	PWM_CCNT1_CLK,      ///< PWM CCNT1 clock
	PWM_CCNT2_CLK,      ///< PWM CCNT2 clock
	TSE_CLK       = 77, ///< TSE  clock
	HRTMR_CLK,      	///< HRTMR clock
	HRTMR2_CLK,      	///< HRTMR2 clock
	HRTMR3_CLK,      	///< HRTMR3 clock
	HRTMR4_CLK,      	///< HRTMR4 clock
	HRTM5R_CLK,      	///< HRTMR5 clock
	DRTC_CLK      = 86, ///< DRTC clock
	ETHPHY_CLK    = 88, ///< ETH PHY clock
	TRNG_CLK,           ///< TRNG clock
	RSA_CLK,            ///< RSA clock
	HASH_CLK,           ///< HASH clock
	TRNG_RO_CLK,        ///< TRNG clock
	MIPI_CSI_PHYD4_CLK = 93,///< MIPI/CSI PHY HS-clock/4
	MIPI_CSI_PHYD4_CLK2  = 94,///< MIPI/CSI PHY HS-clock/4
	MIPI_CSI2_PHYD4_CLK = 95,///< MIPI/CSI2 PHY HS-clock/4

	PWM0_CLK      = 96, ///< PWM0 clock
	PWM1_CLK,           ///< PWM1 clock
	PWM2_CLK,           ///< PWM2 clock
	PWM3_CLK,           ///< PWM3 clock
	PWM4_CLK,           ///< PWM4 clock
	PWM5_CLK,           ///< PWM5 clock
	PWM6_CLK,           ///< PWM6 clock
	PWM7_CLK,           ///< PWM7 clock
	PWM8_CLK,           ///< PWM8 clock
	PWM9_CLK,           ///< PWM9 clock
	PWM10_CLK,          ///< PWM10 clock
	PWM11_CLK,          ///< PWM11 clock

	SDP_CLK       = 112, ///< SDP clock
	VPE_CLK       = 96+17, ///< VPE clock
	NUE2_CLK      = 117, ///< NUE2 clock
	MDBC_CLK,            ///< MDBC clock
	CNN_CLK,             ///< CNN clock
	IVE_CLK       = 121, ///< IVE clock
	IP_ACLK_CLK   = 127, ///< IP_ACLK clock

//==========================================================================
//[0xE0]
//==========================================================================

	//0xE0 start from 896
	//(0x70 + X/32 * 4) = 0xE0
	//0xE0 - 0x70 = X/8
	//X=0x380(896)

	TMR_PROG_CLKEN = 896,
	HRTMR_PROG_CLKEN,
	HRTMR2_PROG_CLKEN,
	HRTMR3_PROG_CLKEN,
	HRTMR4_PROG_CLKEN,
	HRTMR5_PROG_CLKEN,
	EAC_PROG_CLKEN,
	SENPHY_PROG_CLKEN,
	DRTC_PROG_CLKEN,
	DAI_PROG_CLKEN = 896+10,
	I2C_PROG_CLKEN,
	I2C2_PROG_CLKEN,
	PWM_PROG_CLKEN = 896+14,
	UVCP_PROG_CLKEN,
	ETH_PROG_CLKEN = 896+17,
	DMA_PROG_CLKEN = 896+18,
	EFUSE_PROG_CLKEN = 896+20,
	JPG_PROG_CLKEN,
	VENC_PROG_CLKEN,
	IDE_PROG_CLKEN,
	TSENSOR_PROG_CLKEN,
	USB_PROG_CLKEN,
	REMOTE_PROG_CLKEN,
	SDP_PROG_CLKEN,
	SIF_PROG_CLKEN,
	SPI_PROG_CLKEN,
	SPI2_PROG_CLKEN,
	SPI3_PROG_CLKEN,

	UART_PROG_CLKEN = 896+32,
	UART2_PROG_CLKEN,
	UART3_PROG_CLKEN,
	MIPI_CSI_PROG_CLKEN,
	MIPI_CSI2_PROG_CLKEN,
	NAND_PROG_CLKEN,
	SDIO_PROG_CLKEN,
	SDIO2_PROG_CLKEN,
	SDIO3_PROG_CLKEN,
	HASH_PROG_CLKEN,
	RSA_PROG_CLKEN,
	CRYPTO_PROG_CLKEN,
	TSE_PROG_CLKEN,
	ECDSA_PROG_CLKEN,
	TRNG_PROG_CLKEN,
	SIE_PROG_CLKEN,
	SIE2_PROG_CLKEN,
	SIE3_PROG_CLKEN,
	TGE_PROG_CLKEN,
	IPE_PROG_CLKEN,
	IME_PROG_CLKEN,
	NUE_PROG_CLKEN,
	NUE2_PROG_CLKEN,
	MDBC_PROG_CLKEN,
	IVE_PROG_CLKEN,
	CNN_PROG_CLKEN,
	IFE_PROG_CLKEN,
	GRA_PROG_CLKEN,
	GRA2_PROG_CLKEN,
	ISE_PROG_CLKEN,
	VPE_PROG_CLKEN,
	YDCC_PROG_CLKEN,

//==========================================================================
//[PR CG]
//==========================================================================

	//PR CG
	PR_FLL_EN	= 8387712, 			///< PR FLL clock (0x10_0000-70)/4*32
	PR_FLL_DIS_EN,					///< PR FLL dis clock (0x10_0000-70)/4*32

	//PR CG Module
	PR_MCU_CLK			= 8387968, 		///< PR MCU clock (0x10_0020-70)/4*32
	PR_CC_CLK			= 8387968 + 5,	///< PR CC clock
	PR_ACLK_CLK,						///< PR ALCK clock
	PR_ISP_CLK			= 8387968 + 8,	///< PR ISP clock
	PR_ISP_MCLK_CLK,					///< PR ISP MCLK clock
	PR_ISP_PXCLK,						///< PR ISP PX clock
	PR_I2C_CLK,							///< PR I2C clock
	PR_WIEGAND_CLK,						///< PR WIEGAND clock
	PR_UART_CLK,						///< PR UART clock
	PR_UART2_CLK,						///< PR UART clock
	PR_ADC_CLK,							///< PR ADC clock
	PR_WDT_CLK			= 8387968 + 17,	///< PR WDT clock
	PR_HRTMR_CLK,						///< PR HRTIMER clock
	PR_PWM0_CLK,						///< PR PWM0 clock
	PR_PWM1_CLK,						///< PR PWM0 clock
	PR_TCM0_CLK			= 8387968 + 22,	///< PR TCM0 clock
	PR_TCM1_CLK,						///< PR TCM1 clock
	PR_TCM2_CLK,						///< PR TCM2 clock
	PR_TCM3_CLK,						///< PR TCM3 clock
	PR_SPI_CLK			= 8387968 + 28,	///< PR SPI clock
	PR_DAI_CLK,							///< PR DAI clock
	PR_EAC_CLK,							///< PR EAC clock


	//PR CG PROG Module
	PR_INTC_PROG_CLKEN			= 8388000 + 1, 		///< PR INTC PROG clock (0x10_0024-70)/4*32
	PR_CC_PROG_CLKEN			= 8388000 + 5,
	PR_ISP_PROG_CLKEN			= 8388000 + 8,
	PR_I2C_PROG_CLKEN			= 8388000 + 11,
	PR_WIEGAND_PROG_CLKEN		= 8388000 + 12,
	PR_UART_PROG_CLKEN			= 8388000 + 13,
	PR_UART2_PROG_CLKEN			= 8388000 + 14,
	PR_ADC_PROG_CLKEN			= 8388000 + 15,
	PR_RTC_PROG_CLKEN			= 8388000 + 16,
	PR_WDT_PROG_CLKEN			= 8388000 + 17,
	PR_HRTMR_PROG_CLKEN			= 8388000 + 18,
	PR_PWM_PROG_CLKEN			= 8388000 + 19,
	PR_SPI_PROG_CLKEN			= 8388000 + 28,
	PR_DAI_PROG_CLKEN			= 8388000 + 29,
	PR_EAC_PROG_CLKEN			= 8388000 + 30,




	ENUM_DUMMY4WORD(CG_EN)
} CG_EN;

typedef enum {
	PLL_ID_1        = 1,        ///< PLL1 (internal 480 MHz)
	PLL_ID_3        = 3,        ///< PLL3 (for DMA)
	PLL_ID_4        = 4,        ///< PLL4 (N/A:dummy)
	PLL_ID_5        = 5,        ///< PLL5 (for sensor1)
	PLL_ID_6        = 6,        ///< PLL6 (for IDE/eth)
	PLL_ID_7        = 7,        ///< PLL7 (for audio)
	PLL_ID_8        = 8,        ///< PLL8 (for CPU)
	PLL_ID_9        = 9,        ///< PLL9 (for IDE/eth backup)
	PLL_ID_10       = 10,       ///< PLL10 (N/A:dummy)
	PLL_ID_11       = 11,       ///< PLL11 (for DSI)
	PLL_ID_12       = 12,       ///< PLL12 (for sensor2)

	PLL_ID_13       = 13,       ///< PLL13 (N/A:dummy)
	PLL_ID_14       = 14,       ///< PLL14 (N/A:dummy)
	PLL_ID_15       = 15,       ///< PLL15 (N/A:dummy)
	PLL_ID_16       = 16,       ///< PLL16 (N/A:dummy)
	PLL_ID_17       = 17,       ///< PLL17 (N/A:dummy)
	PLL_ID_18       = 18,       ///< PLL18 (N/A:dummy)

	PLL_ID_FIXED320 = 24,       ///< Fixed 320MHz PLL
	PLL_ID_MAX,
	ENUM_DUMMY4WORD(PLL_ID)
} PLL_ID;

//
// Clock Rate bit definition
//
#define PLL_CLKSEL_CPU_MASK             (0x03 << PLL_CLKSEL_CPU)
#define PLL_CLKSEL_APB_MASK             (0x03 << PLL_CLKSEL_APB)
#define PLL_CLKSEL_DMA_ARBT_MASK		(0x01 << PLL_CLKSEL_DMA_ARBT)
#define PLL_CLKSEL_PR_SYS_MASK			(0x03 << PLL_CLKSEL_PR_SYS)
#define PLL_CLKSEL_DDRPHY_MASK          (0x01 << PLL_CLKSEL_DDRPHY)

#define PLL_CLKSEL_CNN_MASK             (0x03 << (PLL_CLKSEL_CNN - PLL_CLKSEL_R1_OFFSET))
#define PLL_CLKSEL_IVE_MASK             (0x03 << (PLL_CLKSEL_IVE - PLL_CLKSEL_R1_OFFSET))
#define PLL_CLKSEL_IPE_MASK             (0x03 << (PLL_CLKSEL_IPE - PLL_CLKSEL_R1_OFFSET))
#define PLL_CLKSEL_TGE_MSH_MASK         (0x03 << (PLL_CLKSEL_TGE_MSH - PLL_CLKSEL_R1_OFFSET))
#define PLL_CLKSEL_IME_MASK             (0x03 << (PLL_CLKSEL_IME - PLL_CLKSEL_R1_OFFSET))
#define PLL_CLKSEL_TGE_FLASH_MASK       (0x03 << (PLL_CLKSEL_TGE_FLASH - PLL_CLKSEL_R1_OFFSET))
#define PLL_CLKSEL_MDBC_MASK            (0x03 << (PLL_CLKSEL_MDBC- PLL_CLKSEL_R1_OFFSET))
#define PLL_CLKSEL_ISE_MASK             (0x03 << (PLL_CLKSEL_ISE - PLL_CLKSEL_R1_OFFSET))

#define PLL_CLKSEL_IFE_MASK             (0x03 << (PLL_CLKSEL_IFE - PLL_CLKSEL_R2_OFFSET))
#define PLL_CLKSEL_IPE_SRAM_MASK        (0x03 << (PLL_CLKSEL_IPE_SRAM - PLL_CLKSEL_R2_OFFSET))
#define PLL_CLKSEL_IME_SRAM_MASK        (0x03 << (PLL_CLKSEL_IME_SRAM - PLL_CLKSEL_R2_OFFSET))
#define PLL_CLKSEL_SIE_MCLKSRC_MASK     (0x03 << (PLL_CLKSEL_SIE_MCLKSRC - PLL_CLKSEL_R2_OFFSET))
#define PLL_CLKSEL_SIE_MCLK2SRC_MASK    (0x03 << (PLL_CLKSEL_SIE_MCLK2SRC - PLL_CLKSEL_R2_OFFSET))
#define PLL_CLKSEL_SIE_MCLK3SRC_MASK    (0x03 << (PLL_CLKSEL_SIE_MCLK3SRC - PLL_CLKSEL_R2_OFFSET))
#define PLL_CLKSEL_SIE_MCLKINV_MASK     (0x01 << (PLL_CLKSEL_SIE_MCLKINV - PLL_CLKSEL_R2_OFFSET))
#define PLL_CLKSEL_SIE_MCLK2INV_MASK    (0x01 << (PLL_CLKSEL_SIE_MCLK2INV - PLL_CLKSEL_R2_OFFSET))
#define PLL_CLKSEL_SIE_MCLK3INV_MASK    (0x01 << (PLL_CLKSEL_SIE_MCLK3INV - PLL_CLKSEL_R2_OFFSET))
#define PLL_CLKSEL_IFE_SRAM_MASK        (0x01 << (PLL_CLKSEL_IFE_SRAM - PLL_CLKSEL_R2_OFFSET))
#define PLL_CLKSEL_SIE2_INT_MASK        (0x01 << (PLL_CLKSEL_SIE2_INT - PLL_CLKSEL_R2_OFFSET))
#define PLL_CLKSEL_CNN_SRAM_MASK        (0x03 << (PLL_CLKSEL_CNN_SRAM - PLL_CLKSEL_R2_OFFSET))
#define PLL_CLKSEL_NUE_MASK             (0x03 << (PLL_CLKSEL_NUE - PLL_CLKSEL_R2_OFFSET))
#define PLL_CLKSEL_NUE2_MASK            (0x03 << (PLL_CLKSEL_NUE2 - PLL_CLKSEL_R2_OFFSET))

#define PLL_CLKSEL_JPEG_MASK            (0x03 << (PLL_CLKSEL_JPEG - PLL_CLKSEL_R3_OFFSET))
#define PLL_CLKSEL_YDCC_MASK            (0x03 << (PLL_CLKSEL_YDCC - PLL_CLKSEL_R3_OFFSET))
#define PLL_CLKSEL_VENC_MASK            (0x03 << (PLL_CLKSEL_VENC - PLL_CLKSEL_R3_OFFSET))
#define PLL_CLKSEL_ECDSA_MASK           (0x03 << (PLL_CLKSEL_ECDSA - PLL_CLKSEL_R3_OFFSET))
#define PLL_CLKSEL_GRAPHIC_MASK         (0x03 << (PLL_CLKSEL_GRAPHIC - PLL_CLKSEL_R3_OFFSET))
#define PLL_CLKSEL_GRAPHIC2_MASK        (0x03 << (PLL_CLKSEL_GRAPHIC2 - PLL_CLKSEL_R3_OFFSET))
#define PLL_CLKSEL_UVCP_MASK		    (0x03 << (PLL_CLKSEL_UVCP - PLL_CLKSEL_R3_OFFSET))
#define PLL_CLKSEL_SIE3_CLKSRC_MASK     (0x07 << (PLL_CLKSEL_SIE3_CLKSRC - PLL_CLKSEL_R3_OFFSET))
#define PLL_CLKSEL_CRYPTO_MASK          (0x03 << (PLL_CLKSEL_CRYPTO - PLL_CLKSEL_R3_OFFSET))
#define PLL_CLKSEL_RSA_MASK             (0x03 << (PLL_CLKSEL_RSA - PLL_CLKSEL_R3_OFFSET))
#define PLL_CLKSEL_SIE_CLKSRC_MASK      (0x07 << (PLL_CLKSEL_SIE_CLKSRC - PLL_CLKSEL_R3_OFFSET))
#define PLL_CLKSEL_SIE2_CLKSRC_MASK     (0x07 << (PLL_CLKSEL_SIE2_CLKSRC - PLL_CLKSEL_R3_OFFSET))

#define PLL_CLKSEL_SDIO_MASK            (0x03 << (PLL_CLKSEL_SDIO - PLL_CLKSEL_R4_OFFSET))
#define PLL_CLKSEL_SDIO2_MASK           (0x03 << (PLL_CLKSEL_SDIO2 - PLL_CLKSEL_R4_OFFSET))
#define PLL_CLKSEL_CSI_MASK        		(0x03 << (PLL_CLKSEL_CSI - PLL_CLKSEL_R4_OFFSET))
#define PLL_CLKSEL_CSI2_MASK       		(0x03 << (PLL_CLKSEL_CSI2 - PLL_CLKSEL_R4_OFFSET))
#define PLL_CLKSEL_IDE_CLKSRC_MASK      (0x07 << (PLL_CLKSEL_IDE_CLKSRC - PLL_CLKSEL_R4_OFFSET))
#define PLL_CLKSEL_SENPHY_CSI_CK1_PHASE_MASK   (0x01 << (PLL_CLKSEL_SENPHY_CSI_CK1_PHASE - PLL_CLKSEL_R4_OFFSET))
#define PLL_CLKSEL_SENPHY_CSI_CK0_PHASE_MASK  (0x01 << (PLL_CLKSEL_SENPHY_CSI_CK0_PHASE - PLL_CLKSEL_R4_OFFSET))
#define PLL_CLKSEL_DAI_MASK             (0x01 << (PLL_CLKSEL_DAI - PLL_CLKSEL_R4_OFFSET))
#define PLL_CLKSEL_I2S_MCLKSEL_MASK     (0x01 << (PLL_CLKSEL_I2S_MCLKSEL - PLL_CLKSEL_R4_OFFSET))
#define PLL_CLKSEL_SENPHY_CSI2_CK1_PHASE_MASK  (0x01 << (PLL_CLKSEL_SENPHY_CSI2_CK1_PHASE - PLL_CLKSEL_R4_OFFSET))
#define PLL_CLKSEL_ETH_MASK             (0x01 << (PLL_CLKSEL_ETH - PLL_CLKSEL_R4_OFFSET))
#define PLL_CLKSEL_NAND_MASK            (0x03 << (PLL_CLKSEL_NAND - PLL_CLKSEL_R4_OFFSET))
#define PLL_CLKSEL_NAND_BCH_MASK        (0x01 << (PLL_CLKSEL_NAND_BCH - PLL_CLKSEL_R4_OFFSET))

#define PLL_CLKSEL_SDIO3_MASK           (0x03 << (PLL_CLKSEL_SDIO3 - PLL_CLKSEL_R5_OFFSET))
#define PLL_CLKSEL_TSE_MASK             (0x03 << (PLL_CLKSEL_TSE - PLL_CLKSEL_R5_OFFSET))
#define PLL_CLKSEL_VPE_MASK             (0x03 << (PLL_CLKSEL_VPE - PLL_CLKSEL_R5_OFFSET))
#define PLL_CLKSEL_SP_MASK              (0x03 << (PLL_CLKSEL_SP - PLL_CLKSEL_R5_OFFSET))
#define PLL_CLKSEL_SP2_MASK             (0x03 << (PLL_CLKSEL_SP2 - PLL_CLKSEL_R5_OFFSET))
#define PLL_CLKSEL_HASH_MASK            (0x03 << (PLL_CLKSEL_HASH - PLL_CLKSEL_R5_OFFSET))
#define PLL_CLKSEL_TRNG_MASK            (0x01 << (PLL_CLKSEL_TRNG - PLL_CLKSEL_R5_OFFSET))
#define PLL_CLKSEL_TRNGRO_CLKSRC_MASK   (0x01 << (PLL_CLKSEL_TRNGRO_CLKSRC- PLL_CLKSEL_R5_OFFSET))
#define PLL_CLKSEL_DRTC_MASK            (0x01 << (PLL_CLKSEL_DRTC - PLL_CLKSEL_R5_OFFSET))
#define PLL_CLKSEL_REMOTE_MASK          (0x03 << (PLL_CLKSEL_REMOTE - PLL_CLKSEL_R5_OFFSET))
#define PLL_CLKSEL_ADC_PD_MASK          (0x01 << (PLL_CLKSEL_ADC_PD - PLL_CLKSEL_R5_OFFSET))
#define PLL_CLKSEL_ETHPHY_CLKSRC_MASK   (0x03 << (PLL_CLKSEL_ETHPHY_CLKSRC - PLL_CLKSEL_R5_OFFSET))
#define PLL_CLKSEL_IPACLK_CLKSRC_MASK   (0x01 << (PLL_CLKSEL_IPACLK_CLKSRC - PLL_CLKSEL_R5_OFFSET))


#define PLL_CLKSEL_CSILPCLK_D0_MASK		(0x03 << (PLL_CLKSEL_CSILPCLK_D0 - PLL_CLKSEL_R6_OFFSET))
#define PLL_CLKSEL_CSILPCLK_D1_MASK		(0x03 << (PLL_CLKSEL_CSILPCLK_D1 - PLL_CLKSEL_R6_OFFSET))
#define PLL_CLKSEL_CSILPCLK_D2_MASK		(0x03 << (PLL_CLKSEL_CSILPCLK_D2 - PLL_CLKSEL_R6_OFFSET))
#define PLL_CLKSEL_CSILPCLK_D3_MASK		(0x03 << (PLL_CLKSEL_CSILPCLK_D3 - PLL_CLKSEL_R6_OFFSET))

#define PLL_CLKSEL_SIE4_CLKSRC_MASK     (0x07 << (PLL_CLKSEL_SIE4_CLKSRC - PLL_CLKSEL_R7_OFFSET))
#define PLL_CLKSEL_SIE5_CLKSRC_MASK     (0x07 << (PLL_CLKSEL_SIE5_CLKSRC - PLL_CLKSEL_R7_OFFSET))
#define PLL_CLKSEL_SIE4_CLKDIV_MASK     (0xFF << (PLL_CLKSEL_SIE4_CLKDIV - PLL_CLKSEL_R7_OFFSET))
#define PLL_CLKSEL_SIE5_CLKDIV_MASK     (0xFF << (PLL_CLKSEL_SIE5_CLKDIV - PLL_CLKSEL_R7_OFFSET))

#define PLL_CLKSEL_SIE_MCLKDIV_MASK     (0xFF << (PLL_CLKSEL_SIE_MCLKDIV - PLL_CLKSEL_R8_OFFSET))
#define PLL_CLKSEL_SIE_MCLK2DIV_MASK    (0xFF << (PLL_CLKSEL_SIE_MCLK2DIV - PLL_CLKSEL_R8_OFFSET))
#define PLL_CLKSEL_SIE_CLKDIV_MASK      (0xFF << (PLL_CLKSEL_SIE_CLKDIV - PLL_CLKSEL_R8_OFFSET))
#define PLL_CLKSEL_SIE2_CLKDIV_MASK     (0xFF << (PLL_CLKSEL_SIE2_CLKDIV - PLL_CLKSEL_R8_OFFSET))

#define PLL_CLKSEL_IDE_CLKDIV_MASK      (0xFF << (PLL_CLKSEL_IDE_CLKDIV - PLL_CLKSEL_R9_OFFSET))
#define PLL_CLKSEL_IDE_OUTIF_CLKDIV_MASK (0xFF << (PLL_CLKSEL_IDE_OUTIF_CLKDIV - PLL_CLKSEL_R9_OFFSET))
#define PLL_CLKSEL_SIE_MCLK3DIV_MASK    (0xFF << (PLL_CLKSEL_SIE_MCLK3DIV - PLL_CLKSEL_R9_OFFSET))
#define PLL_CLKSEL_TRNG_CLKDIV_MASK     (0xFF << (PLL_CLKSEL_TRNG_CLKDIV - PLL_CLKSEL_R9_OFFSET))

#define PLL_CLKSEL_SP_CLKDIV_MASK       (0xFF << (PLL_CLKSEL_SP_CLKDIV - PLL_CLKSEL_R10_OFFSET))
#define PLL_CLKSEL_SIE3_CLKDIV_MASK     (0xFF << (PLL_CLKSEL_SIE3_CLKDIV - PLL_CLKSEL_R10_OFFSET))
#define PLL_CLKSEL_DAI_CLKDIV_MASK      (0xFF << (PLL_CLKSEL_DAI_CLKDIV - PLL_CLKSEL_R10_OFFSET))
#define PLL_CLKSEL_DAI_OSR_CLKDIV_MASK  (0xFF << (PLL_CLKSEL_DAI_OSR_CLKDIV - PLL_CLKSEL_R10_OFFSET))

#define PLL_CLKSEL_SDIO_CLKDIV_MASK     (0x7FF<< (PLL_CLKSEL_SDIO_CLKDIV - PLL_CLKSEL_R11_OFFSET))
#define PLL_CLKSEL_SDIO2_CLKDIV_MASK    (0x7FF<< (PLL_CLKSEL_SDIO2_CLKDIV - PLL_CLKSEL_R11_OFFSET))

#define PLL_CLKSEL_SDIO3_CLKDIV_MASK    (0x7FF<< (PLL_CLKSEL_SDIO3_CLKDIV - PLL_CLKSEL_R12_OFFSET))
#define PLL_CLKSEL_NAND_CLKDIV_MASK     (0x3F << (PLL_CLKSEL_NAND_CLKDIV - PLL_CLKSEL_R12_OFFSET))
#define PLL_CLKSEL_SP2_CLKDIV_MASK      (0xFF << (PLL_CLKSEL_SP2_CLKDIV - PLL_CLKSEL_R12_OFFSET))

#define PLL_CLKSEL_SPI_CLKDIV_MASK      (0x7FF << (PLL_CLKSEL_SPI_CLKDIV - PLL_CLKSEL_R13_OFFSET))
#define PLL_CLKSEL_SPI2_CLKDIV_MASK     (0x7FF << (PLL_CLKSEL_SPI2_CLKDIV - PLL_CLKSEL_R13_OFFSET))

#define PLL_CLKSEL_SPI3_CLKDIV_MASK     (0x7FF << (PLL_CLKSEL_SPI3_CLKDIV - PLL_CLKSEL_R14_OFFSET))

#define PLL_CLKSEL_UART2_CLKDIV_MASK    (0xFF << (PLL_CLKSEL_UART2_CLKDIV - PLL_CLKSEL_R15_OFFSET))
#define PLL_CLKSEL_UART3_CLKDIV_MASK    (0xFF << (PLL_CLKSEL_UART3_CLKDIV - PLL_CLKSEL_R15_OFFSET))

/*r16*/
#define PLL_CLKSEL_PWM0_3_CLKDIV_MASK   (0x3FFF << (PLL_CLKSEL_PWM0_3_CLKDIV - PLL_CLKSEL_R16_OFFSET))
#define PLL_CLKSEL_PWM4_7_CLKDIV_MASK   (0x3FFF << (PLL_CLKSEL_PWM4_7_CLKDIV - PLL_CLKSEL_R16_OFFSET))

/*r17*/
#define PLL_CLKSEL_PWM8_CLKDIV_MASK     (0x3FFF << (PLL_CLKSEL_PWM8_CLKDIV - PLL_CLKSEL_R17_OFFSET))
#define PLL_CLKSEL_PWM9_CLKDIV_MASK     (0x3FFF << (PLL_CLKSEL_PWM9_CLKDIV - PLL_CLKSEL_R17_OFFSET))

/*r18*/
#define PLL_CLKSEL_PWM10_CLKDIV_MASK     (0x3FFF << (PLL_CLKSEL_PWM10_CLKDIV - PLL_CLKSEL_R18_OFFSET))
#define PLL_CLKSEL_PWM11_CLKDIV_MASK     (0x3FFF << (PLL_CLKSEL_PWM11_CLKDIV - PLL_CLKSEL_R18_OFFSET))

#define PLL_CLKSEL_TRNG_RO_CLKDIV_MASK  (0xFF << (PLL_CLKSEL_TRNG_RO_CLKDIV - PLL_CLKSEL_R20_OFFSET))
#define PLL_CLKSEL_TRNG_RO_DELAY_MASK   (0xF  << (PLL_CLKSEL_TRNG_RO_DELAY - PLL_CLKSEL_R20_OFFSET))

#define PLL_CLKSEL_DAI_MCLKDIV_MASK     (0xFF << (PLL_CLKSEL_DAI_MCLKDIV - PLL_CLKSEL_R20_OFFSET))



//PR CG
/*r22*/
#define PLL_CLKSEL_PR_MAIN_MASK			(0x3 << (PLL_CLKSEL_PR_MAIN - PLL_CLKSEL_R22_OFFSET))
#define PLL_CLKSEL_PR_RST_MASK			(0x1 << (PLL_CLKSEL_PR_RST - PLL_CLKSEL_R22_OFFSET))
#define PLL_CLKSEL_PR_PR48M_MASK		(0x1 << (PLL_CLKSEL_PR_PR48M - PLL_CLKSEL_R22_OFFSET))
#define PLL_CLKSEL_PR_RTC32K_MASK		(0x1 << (PLL_CLKSEL_PR_RTC32K - PLL_CLKSEL_R22_OFFSET))
#define PLL_CLKSEL_PR_APB_MASK			(0x3 << (PLL_CLKSEL_PR_APB - PLL_CLKSEL_R22_OFFSET))
#define PLL_CLKSEL_PR_UART_MASK			(0x1 << (PLL_CLKSEL_PR_UART - PLL_CLKSEL_R22_OFFSET))
#define PLL_CLKSEL_PR_HRTIMER_MASK		(0x1 << (PLL_CLKSEL_PR_HRTIMER - PLL_CLKSEL_R22_OFFSET))
#define PLL_CLKSEL_PR_WDT_MASK			(0x1 << (PLL_CLKSEL_PR_WDT - PLL_CLKSEL_R22_OFFSET))
#define PLL_CLKSEL_PR_PWM_MASK			(0x1 << (PLL_CLKSEL_PR_PWM - PLL_CLKSEL_R22_OFFSET))
#define PLL_CLKSEL_PR_WIEGAND_MASK		(0x1 << (PLL_CLKSEL_PR_WIEGAND - PLL_CLKSEL_R22_OFFSET))

/*r23*/
#define PLL_CLKSEL_PR_ISP_MCLK_MASK			(0x1 << (PLL_CLKSEL_PR_ISP_MCLK - PLL_CLKSEL_R23_OFFSET))
#define PLL_CLKSEL_PR_ISP_MASK				(0x3 << (PLL_CLKSEL_PR_ISP - PLL_CLKSEL_R23_OFFSET))
#define PLL_CLKSEL_PR_ISP_MCLKDIV_MASK		(0x7F << (PLL_CLKSEL_PR_ISP_MCLKDIV - PLL_CLKSEL_R23_OFFSET))

/*r24*/
#define PLL_CLKSEL_PR_WIEGAND_CLKDIV_MASK		(0x3FF << (PLL_CLKSEL_PR_WIEGAND_CLKDIV - PLL_CLKSEL_R24_OFFSET))
#define PLL_CLKSEL_PR_DAI_CLKDIV_MASK			(0x1F << (PLL_CLKSEL_PR_DAI_CLKDIV - PLL_CLKSEL_R24_OFFSET))

/*r25*/
#define PLL_CLKSEL_PR_PWM0_CLKDIV_MASK		(0x1FFF << (PLL_CLKSEL_PR_PWM0_CLKDIV - PLL_CLKSEL_R25_OFFSET))
#define PLL_CLKSEL_PR_PWM1_CLKDIV_MASK		(0x1FFF << (PLL_CLKSEL_PR_PWM1_CLKDIV - PLL_CLKSEL_R25_OFFSET))

/*r26*/
#define PLL_CLKSEL_PR_SPI_CLKDIV_MASK		(0x1FFF << (PLL_CLKSEL_PR_SPI_CLKDIV - PLL_CLKSEL_R26_OFFSET))


#define PLL_CLKSEL_DIS_MASK             (0x03 << (PLL_CLKSEL_DIS - PLL_CLKSEL_R1_OFFSET))
#define PLL_CLKSEL_CNN2_MASK            (0x03 << (PLL_CLKSEL_CNN2- PLL_CLKSEL_R1_OFFSET))
#define PLL_CLKSEL_SDE_MASK             (0x03 << (PLL_CLKSEL_SDE - PLL_CLKSEL_R1_OFFSET))
#define PLL_CLKSEL_DCE_MASK             (0x03 << (PLL_CLKSEL_DCE - PLL_CLKSEL_R1_OFFSET))
#define PLL_CLKSEL_IFE2_MASK            (0x03 << (PLL_CLKSEL_IFE2 - PLL_CLKSEL_R2_OFFSET))
#define PLL_CLKSEL_SIE_IO_PXCLKSRC_MASK (0x01 << (PLL_CLKSEL_SIE_IO_PXCLKSRC - PLL_CLKSEL_R2_OFFSET))
#define PLL_CLKSEL_SIE2_IO_PXCLKSRC_MASK (0x01 << (PLL_CLKSEL_SIE2_IO_PXCLKSRC - PLL_CLKSEL_R2_OFFSET))
#define PLL_CLKSEL_SIE_PXCLKSRC_MASK    (0x01 << (PLL_CLKSEL_SIE_PXCLKSRC - PLL_CLKSEL_R2_OFFSET))
#define PLL_CLKSEL_SIE2_PXCLKSRC_MASK   (0x01 << (PLL_CLKSEL_SIE2_PXCLKSRC - PLL_CLKSEL_R2_OFFSET))
#define PLL_CLKSEL_SIE3_PXCLKSRC_MASK   (0x01 << (PLL_CLKSEL_SIE3_PXCLKSRC - PLL_CLKSEL_R2_OFFSET))
#define PLL_CLKSEL_SIE4_IO_PXCLKSRC_MASK (0x01 << (PLL_CLKSEL_SIE4_IO_PXCLKSRC - PLL_CLKSEL_R2_OFFSET))
#define PLL_CLKSEL_SIE4_PXCLKSRC_MASK   (0x01 << (PLL_CLKSEL_SIE4_PXCLKSRC - PLL_CLKSEL_R2_OFFSET))
#define PLL_CLKSEL_TGE_MASK             (0x01 << (PLL_CLKSEL_TGE - PLL_CLKSEL_R2_OFFSET))
#define PLL_CLKSEL_TGE2_MASK            (0x01 << (PLL_CLKSEL_TGE2 - PLL_CLKSEL_R2_OFFSET))
#define PLL_CLKSEL_AFFINE_MASK          (0x03 << (PLL_CLKSEL_AFFINE - PLL_CLKSEL_R3_OFFSET))
#define PLL_CLKSEL_MIPI_LVDS_MASK       (0x01 << (PLL_CLKSEL_MIPI_LVDS - PLL_CLKSEL_R4_OFFSET))
#define PLL_CLKSEL_LVDS_CLKPHASE_MASK   (0x01 << (PLL_CLKSEL_LVDS_CLKPHASE - PLL_CLKSEL_R4_OFFSET))
#define PLL_CLKSEL_LVDS2_CLKPHASE_MASK  (0x01 << (PLL_CLKSEL_LVDS2_CLKPHASE - PLL_CLKSEL_R4_OFFSET))
#define PLL_CLKSEL_MIPI_LVDS2_MASK      (0x01 << (PLL_CLKSEL_MIPI_LVDS2 - PLL_CLKSEL_R4_OFFSET))
#define PLL_CLKSEL_ADO_MCLKSEL_MASK     (0x01 << (PLL_CLKSEL_ADO_MCLKSEL - PLL_CLKSEL_R4_OFFSET))
#define PLL_CLKSEL_SPI4_CLKDIV_MASK     (0x7FF << (PLL_CLKSEL_SPI4_CLKDIV - PLL_CLKSEL_R14_OFFSET))
#define PLL_CLKSEL_UART4_CLKDIV_MASK    (0xFF << (PLL_CLKSEL_UART4_CLKDIV - PLL_CLKSEL_R15_OFFSET))
#define PLL_CLKSEL_UART5_CLKDIV_MASK    (0xFF << (PLL_CLKSEL_UART5_CLKDIV - PLL_CLKSEL_R15_OFFSET))
#define PLL_CLKSEL_UART6_CLKDIV_MASK    (0xFF << (PLL_CLKSEL_UART6_CLKDIV - PLL_CLKSEL_R20_OFFSET))
#define PLL_CLKSEL_SPI5_CLKDIV_MASK     (0x7FF << (PLL_CLKSEL_SPI5_CLKDIV - PLL_CLKSEL_R21_OFFSET))