
#ifndef ENUM_DUMMY4WORD
#define ENUM_DUMMY4WORD(name)   E_##name = 0x10000000
#endif

// ref from code/hdal/drivers/k_driver/source/rtos_ns02201/pll/pll_int.h
typedef enum {
	//==========================================================================
	//[0x70]
	//==========================================================================
	AXIC_CLK,           ///< AXI clock
	CPU_CLK,            ///< GPU clock
	SLVSEC_CLK,         ///< SLVSEC clock
	HDMI2_ADO_CLK,      ///< HDMI2 audio clock
	MCU_CLK,            ///< MCU clock
	USB2_CLK,           ///< USB2 clock
	USB3_CLK,           ///< USB3 clock
	USB3_2_CLK,         ///< USB3_2 clock
	AGE_CLK,            ///< AGE clock
	DSP2_CLK,           ///< DSP2 clock
	DSP_CLK,            ///< DSP  clock
	MAU2_CLK,           ///< MAU2 clock
	MAU_CLK,            ///< MAU clock
	IME_CLK,            ///< IME clock
	SIE_CLK,            ///< SIE clock
	SIE2_CLK,           ///< SIE2 Clock
	SIE3_CLK,           ///< SIE3 clock
	SIE4_CLK,           ///< SIE4 clock
	SIE5_CLK,           ///< SIE5 clock
	SIE6_CLK,           ///< SIE6 clock
	GPENC_CLK,          ///< GPENC clock
	GPENC2_CLK,         ///< GPENC clock
	JPEG_CLK,           ///< JPEG clock
	JPG_CLK = JPEG_CLK,
	UVCP_CLK,           ///< UVCP clock
	UVCP_CLKEN = UVCP_CLK,
	VIE_CLK,            ///< VIE clock
	VIE2_CLK,           ///< VIE2 clock
	IFE2_CLK,           ///< IFE2 clock
	ETH_CLK,            ///< ETH clock
	ISE_CLK,            ///< ISE clock
	HASH_CLK,           ///< HASH clock
	RSA_CLK,            ///< RSA clock
	CRYPTO_CLK,         ///< Crypto clock

	//==========================================================================
	//[0x74]
	//==========================================================================
	VENC_CLK     = 32,  ///< VENC clock
	VTRC_CLK,           ///< VTRC clock
	IPE_CLK,            ///< IPE clock
	IPE2_CLK,           ///< IPE2 clock
	IFE_CLK,            ///< IFE clock
	LCD_CLK,            ///< LCD clock
	LCD2_CLK,           ///< LCD2 clock
	ETHPHY_CLK,         ///< ETH EXT PHY clock
	MDBC_CLK,           ///< MDBC clock
	HWCOPY_CLK,         ///< Hwcopy clock
	NAND_CLK,           ///< NAND clock
	SDIO_CLK,           ///< SDIO clock
	SDIO2_CLK,          ///< SDIO2 clock
	SDIO3_CLK,          ///< SDIO3 clock
	HDMI_ADO_CLK,       ///< HDMI audio clock
	IME2_CLK,           ///< IME2 clock
	NUE2_CLK,           ///< NUE2 clock
	TRKE_CLK,           ///< TRKE clock
	IVE_CLK,            ///< IVE clock
	LCD_LITE_CLK,       ///< LCD lite clock
	SIE_MCLK,           ///< SIE MCLK
	SIE_MCLK2,          ///< SIE MCLK2
	SIE_MCLK3,          ///< SIE MCLK3
	SIE_MCLK4,          ///< SIE MCLK4
	SIE_MCLK5,          ///< SIE MCLK5
	SENSOR_MCLK = SIE_MCLK,
	SENSOR_MCLK2 = SIE_MCLK2,
	SENSOR_MCLK3 = SIE_MCLK3,
	SENSOR_MCLK4 = SIE_MCLK4,
	SENSOR_MCLK5 = SIE_MCLK5,
	SATA_CLK,           ///< SATA clock
	SATA2_CLK,          ///< SATA2 clock
	TSE_CLK,            ///< TSE  clock
	CONV_CLK,           ///< CONV clock
	CONV2_CLK,          ///< CONV2 clock
	VPE_CLK,            ///< VPE clock
	VPE2_CLK,           ///< VPE2 clock

	//==========================================================================
	//[0x78]
	//==========================================================================
	I2C_CLK       = 64, ///< I2C clock
	I2C2_CLK,           ///< I2C2 clock
	I2C3_CLK,           ///< I2C3 clock
	I2C4_CLK,           ///< I2C4 clock
	I2C5_CLK,           ///< I2C5 clock
	I2C6_CLK,           ///< I2C6 clock
	I2C7_CLK,           ///< I2C7 clock
	I2C8_CLK,           ///< I2C8 clock
	I2C9_CLK,           ///< I2C9 clock
	I2C10_CLK,          ///< I2C10 clock
	I2C11_CLK,          ///< I2C11 clock
	MI_CLK,             ///< MI clock
	TMR_CLK,            ///< timer clock
	HRTMR_CLK,          ///< HRtimer clock
	TMR3_CLK,           ///< HRtimer2 clock
	HRTMR2_CLK = TMR3_CLK,
	UVCP2_CLK,          ///< UVCP2 clock
	SIF_CLK,            ///< SIF clock
	GRAPH_CLK,          ///< Graphic clock
	GRAPH2_CLK,         ///< Graphic2 clock
	GRAPH3_CLK,         ///< Graphic3 clock
	UART_CLK,           ///< UART clock
	UART2_CLK,          ///< UART2 clock
	UART3_CLK,          ///< UART3 clock
	UART4_CLK,          ///< UART4 clock
	UART5_CLK,          ///< UART5 clock
	REMOTE_CLK,         ///< Remote clock
	DRTC_CLK,           ///< DRTC clock
	ADC_CLK,            ///< ADC clock
	ADC_TSEN_CLK,       ///< ADC T-sensor clock
	TRNG_CLK,           ///< TRNG clock
	DAI3_CLK,           ///< DAI3 clock
	DAI4_CLK,           ///< DAI4 clock

	//==========================================================================
	//[0x7C]
	//==========================================================================
	PWM_CCNT_CLK  = 96, ///< PWM CCNT clock
	PWM_CCNT0_CLK = 96, ///< PWM CCNT0 clock
	PWM_CCNT1_CLK,      ///< PWM CCNT1 clock
	PWM_CCNT2_CLK,      ///< PWM CCNT2 clock
	RTC_PSS_CLK,        ///< RTC PSS clock
	TRNG_RO_CLK,        ///< TRNG RO clock
	ETH2_CLK,           ///< ETH2 clock
	ETHPHY2_CLK,        ///< ETH2 phy external clock
	ETH2_PTP_REF_CLK,   ///< ETH2 PTP clock
	ETH_PTP_REF_CLK,    ///< ETH PTP clock
	JPEG2_CLK,          ///< JPEG2 clock
	AE_CLK,             ///< AE clock
	JPEG_LITE_CLK,      ///< JPEG Lite clock
	HVYLD_CLK,          ///< heavyload clock
	HVYLD2_CLK,         ///< heavyload2 clock
	HVYLD3_CLK,         ///< heavyload3 clock
	DRE_CLK,            ///< DRE clock
	DAI_CLK,            ///< DAI clock
	DAI2_CLK,           ///< DAI2 clock
	EAC_A_ADC_CLK,      ///< EAC analog AD clock
	EAC_A_DAC_CLK,      ///< EAC analog DA clock
	EAC_D_CLKEN,        ///< EAC digital clock
	UART6_CLK,          ///< UART6 clock
	UART7_CLK,          ///< UART7 clock
	UART8_CLK,          ///< UART8 clock
	UART9_CLK,          ///< UART9 clock
	CSI_CLK,            ///< CSI clock
	CSI2_CLK,           ///< CSI2 clock
	CSI3_CLK,           ///< CSI3 clock
	CSI4_CLK,           ///< CSI4 clock
	CSI5_CLK,           ///< CSI5 clock
	SDE_CLK,            ///< SDE clock
	TGE_CLK,            ///< TGE clock

	CSI_CK0D4_CLK = 128,///< MIPI CSI PHY HS-CLK0/4
	CSI_CK1D4_CLK,      ///< MIPI CSI PHY HS-CLK1/4
	CSI_CK2D4_CLK,      ///< MIPI CSI PHY HS-CLK2/4
	CSI_CK3D4_CLK,      ///< MIPI CSI PHY HS-CLK3/4
	CSI2_CK1D4_CLK,     ///< MIPI CSI2 PHY HS-CLK1/4
	CSI3_CK2D4_CLK,     ///< MIPI CSI3 PHY HS-CLK2/4
	CSI3_CK3D4_CLK,     ///< MIPI CSI3 PHY HS-CLK3/4
	CSI4_CK3D4_CLK,     ///< MIPI CSI4 PHY HS-CLK3/4
	CSI5_CK0D4_CLK,     ///< MIPI CSI5 PHY HS-CLK0/4
	CSI5_CK1D4_CLK,     ///< MIPI CSI5 PHY HS-CLK1/4
	CSI5_CK2D4_CLK,     ///< MIPI CSI5 PHY HS-CLK2/4
	CSI5_CK3D4_CLK,     ///< MIPI CSI5 PHY HS-CLK3/4
	CSI6_CK1D4_CLK,     ///< MIPI CSI6 PHY HS-CLK1/4
	CSI7_CK2D4_CLK,     ///< MIPI CSI7 PHY HS-CLK2/4
	CSI7_CK3D4_CLK,     ///< MIPI CSI7 PHY HS-CLK3/4
	CSI8_CK3D4_CLK,     ///< MIPI CSI8 PHY HS-CLK3/4
	TGE_FLASHA_CLK,     ///< TGEA Flash clock
	TGE_FLASH_CLK = TGE_FLASHA_CLK,     ///< TGE Flash clock
	TGE_MSHA_CLK,       ///< TGE MSHA clock
	TGE_MSHB_CLK,       ///< TGE MSHB clock
	PPU_CLK,            ///< PPU clock
	VIE_A_PXCLK,        ///< VIE_A PX clock
	VIE_B_PXCLK,        ///< VIE_B PX clock
	VIE2_A_PXCLK,       ///< VIE2_A PX clock
	VIE2_B_PXCLK,       ///< VIE2_B PX clock
	CSI_TX2_CLK,        ///< CSI TX clock
	AD_DEC_CLK,         ///< ad dec clock
	DEC_CLK,            ///< DEC TX clock
	DSI2_CLK,           ///< DSI2 clock
	DSI_CLK,            ///< DSI clock
	CSI_TX_CLK,         ///< CSI TX clock
	SP_CLK,             ///< special clock
	SP2_CLK,            ///< special2 clock

	PWM0_CLK      = 160,///< PWM0 clock
	PWM1_CLK,           ///< PWM1 clock
	PWM2_CLK,           ///< PWM2 clock
	PWM3_CLK,           ///< PWM3 clock
	PWM4_CLK,           ///< PWM4 clock
	PWM5_CLK,           ///< PWM5 clock
	PWM6_CLK,           ///< PWM6 clock
	PWM7_CLK,           ///< PWM7 clock
	PWM8_CLK,           ///< PWM8 clock
	PWM9_CLK,           ///< PWM9 clock
	PWM10_CLK,          ///< PWM10 clock
	PWM11_CLK,          ///< PWM11 clock
	HRTMR3_CLK,         ///< HRTMR3 clock
	HRTMR4_CLK,         ///< HRTMR4 clock
	HRTMR5_CLK,         ///< HRTMR5 clock
	VPE3_CLK,           ///< VPE3 clock
	SDP_CLK,            ///< SDP clock
	SPI_CLK,            ///< SPI clock
	SPI2_CLK,           ///< SPI2 clock
	SPI3_CLK,           ///< SPI3 clock
	SPI4_CLK,           ///< SPI4 clock
	SPI5_CLK,           ///< SPI5 clock
	CSI6_CLK,           ///< CSI6 clock
	CSI7_CLK,           ///< CSI7 clock
	CSI8_CLK,           ///< CIS8 clock
	PCIE_CLK,           ///< PCIE clock
	PCIEx1_CLK,         ///< PCIEx1 clock
	ISE2_CLK,           ///< ISE2 clock
	CONV3_CLK,          ///< CONV3 clock
	CONV4_CLK,          ///< CONV4 clock
	ROU_CLK,            ///< ROU clock
	LSU_CLK,            ///< LSU clock

	CSI_SIE_CLK    = 192, ///< CSI to SIE clock
	CSI_SIE2_CLK,       ///< CSI to SIE2 clock
	CSI_SIE3_CLK,       ///< CSI to SIE3 clock
	CSI_SIE10_CLK,      ///< CSI to SIE10 clock
	CSI2_SIE3_CLK,      ///< CSI2 to SIE3 clock
	CSI2_SIE4_CLK,      ///< CSI2 to SIE4 clock
	CSI2_SIE6_CLK,      ///< CSI2 to SIE6 clock
	CSI3_SIE4_CLK = 200,///< CSI3 to SIE4 clock
	CSI3_SIE5_CLK,      ///< CSI3 to SIE5 clock
	CSI3_SIE6_CLK,      ///< CSI3 to SIE6 clock
	CSI3_SIE11_CLK,     ///< CSI3 to SIE11 clock
	CSI4_SIE6_CLK = 204,///< CSI4 to SIE6 clock
	CSI4_SIE7_CLK,      ///< CSI4 to SIE7 clock
	CSI4_SIE8_CLK,      ///< CSI4 to SIE8 clock
	CSI5_SIE7_CLK = 208,///< CSI5 to SIE7 clock
	CSI5_SIE8_CLK,      ///< CSI5 to SIE8 clock
	CSI5_SIE9_CLK,      ///< CSI5 to SIE9 clock
	CSI5_SIE12_CLK,     ///< CSI5 to SIE12 clock
	CSI5_VIE_CLK  = 212,///< CSI5 to VIE clock
	CSI6_SIE9_CLK,      ///< CSI6 to SIE9 clock
	CSI6_SIE11_CLK,     ///< CSI6 to SIE11 clock
	CSI6_SIE12_CLK,     ///< CSI6 to SIE12 clock
	CSI7_SIE10_CLK = 217,///< CSI7 to SIE10 clock
	CSI7_SIE11_CLK,      ///< CSI7 to SIE11 clock
	CSI7_SIE12_CLK,      ///< CSI7 to SIE12 clock
	CSI7_VIE2_CLK  = 221,///< CSI7 to VIE2 clock
	CSI8_SIE11_CLK,      ///< CSI8 to SIE11 clock
	CSI8_SIE12_CLK,      ///< CSI8 to SIE12 clock



	I2C12_CLK     = 224,///< I2C12 clock
	I2C13_CLK,          ///< I2C13 clock
	I2C14_CLK,          ///< I2C14 clock
	I2C15_CLK,          ///< I2C15 clock
	I2C16_CLK,          ///< I2C16 clock
	I2C17_CLK,          ///< I2C17 clock
	I2C18_CLK,          ///< I2C18 clock
	I2C19_CLK,          ///< I2C19 clock
	I2C20_CLK,          ///< I2C20 clock
	SENSOR_MCLK6,       ///< SENSOR MCLK6
	SENSOR_MCLK7,       ///< SENSOR MCLK7
	SENSOR_MCLK8,       ///< SENSOR MCLK8
	SIE7_CLK,           ///< SIE7 clock
	SIE8_CLK,           ///< SIE8 Clock
	SIE9_CLK,           ///< SIE9 clock
	SIE10_CLK,          ///< SIE10 clock
	SIE11_CLK,          ///< SIE11 clock
	SIE12_CLK,          ///< SIE12 clock
	SLVSEC2_CLK,        ///< SLVSEC2 clock
	MSIx_CLK,           ///< MSIx clock
	MSIx2_CLK,          ///< MSIx2 clock
	DAI5_CLK,           ///< DAI5 clock
	PWM12_CLK,          ///< PWM12 clock
	LP_CLK,             ///< LP clock
	CAL_CLK,            ///< CAL clock
	UTIL_CLK,           ///< UTIL clock
	LME_CLK,            ///< LME clock
	HRTMR6_CLK,         ///< HRTMR6 clock
	LHVYLD_CLK,         ///< LHVYLD clock
	HDMI_VDO_CLK,       ///< HDMI VDO clock
	HDMI2_VDO_CLK,      ///< HDMI2 VDO clock
	XOR_CLK,            ///< XOR clock

	//0x110 start from 1280
	//(0x70 + X/32 * 4) = 0x110
	//0x110 - 0x70 = X/8
	//X=0x500(1280)
	RO_32K_DIV_TESTEN = 1280 + 16,

	//0x140 start from 1664
	//(0x70 + X/32 * 4) = 0x140
	//0x140 - 0x70 = X/8
	//X=0x680(1664)
	RO_32K_CLKEN    = 1664 + 2,
	LVD_RO_CLK12M_CLKEN,

	//0x150 start from 1792
	//(0x70 + X/32 * 4) = 0x150
	//0x150 - 0x70 = X/8
	//X=0x700(1792)

	//0x150
	MAU_PROG_CLKEN = 1792,
	HVYLD_PROG_CLKEN,
	HVYLD2_PROG_CLKEN,
	HVYLD3_PROG_CLKEN,

	CONV_PROG_CLKEN,
	CONV2_PROG_CLKEN,
	TRNG_PROG_CLKEN,
	DSP_PROG_CLKEN,

	GPENC_PROG_CLKEN,
	GPENC2_PROG_CLKEN,
	JPEG_PROG_CLKEN,
	CC_PROG_CLKEN,

	JPEG2_PROG_CLKEN,
	MI_PROG_CLKEN,
	RTC_PROG_CLKEN,
	ETH_PROG_CLKEN,

	MAU2_PROG_CLKEN,
	HASH_PROG_CLKEN,
	RSA_PROG_CLKEN,
	CRYPTO_PROG_CLKEN,

	VENC_PROG_CLKEN,
	VTRC_PROG_CLKEN,
	LCD_PROG_CLKEN,
	LCD2_PROG_CLKEN,

	GRAPHIC_PROG_CLKEN,
	GRAPHIC2_PROG_CLKEN,
	GRAPHIC3_PROG_CLKEN,
	HWCP_PROG_CLKEN,

	NAND_PROG_CLKEN,
	SDIO_PROG_CLKEN,
	SDIO2_PROG_CLKEN,
	SDIO3_PROG_CLKEN,
	//0x154
	HDMI_PROG_CLKEN = 1792 + 32,
	HDMI2_PROG_CLKEN,
	NUE2_PROG_CLKEN,
	IVE_PROG_CLKEN,

	MCU_PROG_CLKEN,
	I2C_PROG_CLKEN,
	I2C2_PROG_CLKEN,
	I2C3_PROG_CLKEN,

	I2C4_PROG_CLKEN,
	I2C5_PROG_CLKEN,
	I2C6_PROG_CLKEN,
	I2C7_PROG_CLKEN,

	I2C8_PROG_CLKEN,
	I2C9_PROG_CLKEN,
	I2C10_PROG_CLKEN,
	I2C11_PROG_CLKEN,

	MSIx_PROG_CLKEN,
	IFE_PROG_CLKEN,
	UVCP_PROG_CLKEN,
	UVCP2_PROG_CLKEN,

	VPE_PROG_CLKEN,
	VPE2_PROG_CLKEN,
	VPE3_PROG_CLKEN,
	UART_PROG_CLKEN,

	UART2_PROG_CLKEN,
	UART3_PROG_CLKEN,
	UART4_PROG_CLKEN,
	UART5_PROG_CLKEN,

	REMOTE_PROG_CLKEN,
	TIMER_PROG_CLKEN,
	HRTIMER_PROG_CLKEN,
	HRTIMER2_PROG_CLKEN,

	//0x158
	ADC_PROG_CLKEN  = 1792 + 64,
	TEMP_SENSOR_PROG_CLKEN,
	PWM_PROG_CLKEN,
	MIPI_CSI_TX2_PROG_CLKEN,

	UART6_PROG_CLKEN,
	UART7_PROG_CLKEN,
	UART8_PROG_CLKEN,
	UART9_PROG_CLKEN,

	DSP2_PROG_CLKEN,
	DRTC_PROG_CLKEN,
	PWBC_PROG_CLKEN,
	DAI_PROG_CLKEN,

	DAI2_PROG_CLKEN,
	EAC_PROG_CLKEN,
	TSE_PROG_CLKEN,
	SIF_PROG_CLKEN,

	MIPI_CSI_PROG_CLKEN,
	MIPI_CSI2_PROG_CLKEN,
	MIPI_CSI3_PROG_CLKEN,
	MIPI_CSI4_PROG_CLKEN,

	MIPI_CSI5_PROG_CLKEN,
	SDP_PROG_CLKEN,
	MIPI_DSI_PROG_CLKEN,
	MIPI_CSI_TX_PROG_CLKEN,

	SPI_PROG_CLKEN,
	SPI2_PROG_CLKEN,
	SPI3_PROG_CLKEN,
	SPI4_PROG_CLKEN,

	SPI5_PROG_CLKEN,
	AD_DEC_PROG_CLKEN,
	ETH2_PROG_CLKEN,
	//0x15C
	IFE2_PROG_CLKEN = 1888,
	ISE_PROG_CLKEN  = 1889,
	ISE2_PROG_CLKEN = 1890,
	MDBC_PROG_CLKEN = 1891,

	SDE_PROG_CLKEN,
	DRE_PROG_CLKEN,
	TRKE_PROG_CLKEN,
	ROU_PROG_CLKEN,     //1895

	IPE_PROG_CLKEN,
	IME_PROG_CLKEN,
	IPE2_PROG_CLKEN,
	IME2_PROG_CLKEN,    //1899

	HRTIMER3_PROG_CLKEN = 1901,
	HRTIMER4_PROG_CLKEN,
	HRTIMER5_PROG_CLKEN,

	SIE_PROG_CLKEN,
	SIE2_PROG_CLKEN,
	SIE3_PROG_CLKEN,
	SIE4_PROG_CLKEN,    //1907

	SIE5_PROG_CLKEN,
	SIE6_PROG_CLKEN,
	VIE_PROG_CLKEN,
	VIE2_PROG_CLKEN,    //1911

	TGE_PROG_CLKEN,
	WDT_PROG_CLKEN,
	MIPI_CSI6_PROG_CLKEN,
	MIPI_CSI7_PROG_CLKEN,   //1915

	MIPI_CSI8_PROG_CLKEN,
	LCD_LITE_PROG_CLKEN,
	MIPI_DSI2_PROG_CLKEN,
	SLVSEC_PROG_CLKEN,

	//0x160 -> 1792 + 128 (1920)
	DAI3_PROG_CLKEN = 1920,
	DAI4_PROG_CLKEN,
	//Reserved
	USB2_PROG_CLKEN = 1920 + 3, //1920+3

	USB3_PROG_CLKEN,
	USB3_2_PROG_CLKEN,
	SATA_PROG_CLKEN,
	SATA2_PROG_CLKEN,           //1920+7

	PCIE_PROG_CLKEN,
	PCIEx1_PROG_CLKEN,
	I2C12_PROG_CLKEN,
	I2C13_PROG_CLKEN,           //1920+11

	I2C14_PROG_CLKEN,
	I2C15_PROG_CLKEN,
	I2C16_PROG_CLKEN,
	I2C17_PROG_CLKEN,           //1920+15

	I2C18_PROG_CLKEN,
	I2C19_PROG_CLKEN,
	I2C20_PROG_CLKEN,
	AGE_PROG_CLKEN,             //1920+19

	SIE7_PROG_CLKEN,
	SIE8_PROG_CLKEN,
	SIE9_PROG_CLKEN,
	SIE10_PROG_CLKEN,           //1920+23

	SIE11_PROG_CLKEN,
	SIE12_PROG_CLKEN,
	//1920+26 reserved
	//1920+27 reserved
	//1920+28 reserved
	//1920+29 reserved
	//1920+30 reserved
	SLVSEC2_PROG_CLKEN  = 1920 + 31,
	//0x164 -> 1952

	CONV3_PROG_CLKEN = 1952,
	CONV4_PROG_CLKEN,
	LSU_PROG_CLKEN,
	JM_PROG_CLKEN,

	CAL_PROG_CLKEN,
	UTIL_PROG_CLKEN,
	LME_PROG_CLKEN,
	MSIx2_PROG_CLKEN,

	HRTIMER6_PROG_CLKEN,
	DAI5_PROG_CLKEN,
	DOORBELL_PROG_CLKEN,
	XOR_PROG_CLKEN,

	DSIPHY_PROG_CLKEN,
	LHVYLD_PROG_CLKEN,
	INTC_PROG_CLKEN,
	INTC2_PROG_CLKEN,

	INTC3_PROG_CLKEN,
	PPU_PROG_CLKEN,
	JMISP_PROG_CLKEN,
	TIMER2_PROG_CLKEN,


	SIE_PXCLK    = 7296,///< SIE PX clock
	SIE2_PXCLK,         ///< SIE2 PX clock
	SIE3_PXCLK,         ///< SIE3 PX clock
	SIE4_PXCLK,         ///< SIE4 PX clock
	SIE5_PXCLK,         ///< SIE5 PX clock
	SIE6_PXCLK,         ///< SIE6 PX clock
	SIE7_PXCLK,         ///< SIE7 PX clock
	SIE8_PXCLK,         ///< SIE8 PX clock
	SIE9_PXCLK,         ///< SIE9 PX clock
	SIE10_PXCLK,        ///< SIE10 PX clock
	SIE11_PXCLK,        ///< SIE11 PX clock
	SIE12_PXCLK,        ///< SIE12 PX clock
	EC_SIE_CLK   = 7312,///< SIE to SLVSEC clock
	EC_SIE2_CLK,        ///< SIE2 to SLVSEC clock
	EC_SIE3_CLK,        ///< SIE3 to SLVSEC clock
	EC2_SIE4_CLK,       ///< SIE4 to SLVSEC2 clock
	EC2_SIE5_CLK,       ///< SIE5 to SLVSEC2 clock
	EC2_SIE6_CLK,       ///< SIE6 to SLVSEC2 clock
	EC2_SIE7_CLK,       ///< SIE7 to SLVSEC2 clock
	WDT_CLK      = 7320,///< WDT clock
	SYSM_CLK,           ///< STSM clock
	TGE_FLASHB_CLK,     ///< TGE FLASHB clock
	TMR2_CLK,           ///< Timer2 clock
	TCM_CLK      = 7324,///< TCM clock
	TCM2_CLK,           ///< TCM2 clock
	TCM3_CLK,           ///< TCM3 clock
	TCM4_CLK,           ///< TCM4 clock

	SENPHY_LPCLK_D0  = 7328,///< SENPHY LPCLK D0
	SENPHY_LPCLK_D1,         ///< SENPHY LPCLK D1
	SENPHY_LPCLK_D2,         ///< SENPHY LPCLK D2
	SENPHY_LPCLK_D3,         ///< SENPHY LPCLK D3
	SENPHY_LPCLK_D4,         ///< SENPHY LPCLK D4
	SENPHY_LPCLK_D5,         ///< SENPHY LPCLK D5
	SENPHY_LPCLK_D6,         ///< SENPHY LPCLK D6
	SENPHY_LPCLK_D7,         ///< SENPHY LPCLK D7
	SENPHY2_LPCLK_D0,         ///< SENPHY2 LPCLK D0
	SENPHY2_LPCLK_D1,         ///< SENPHY2 LPCLK D1
	SENPHY2_LPCLK_D2,         ///< SENPHY2 LPCLK D2
	SENPHY2_LPCLK_D3,         ///< SENPHY2 LPCLK D3
	SENPHY2_LPCLK_D4,         ///< SENPHY2 LPCLK D4
	SENPHY2_LPCLK_D5,         ///< SENPHY2 LPCLK D5
	SENPHY2_LPCLK_D6,         ///< SENPHY2 LPCLK D6
	SENPHY2_LPCLK_D7,         ///< SENPHY2 LPCLK D7

	MAX_CLK,

	ENUM_DUMMY4WORD(CG_EN)
} CG_EN;

typedef enum {
	PLL_ID_0        = 0,        ///< PLL0 (for AXI0)
	PLL_ID_1        = 1,        ///< PLL1 (for internal 480 MHz)
	PLL_ID_2        = 2,        ///< PLL2 (for AXI1)
	PLL_ID_3        = 3,        ///< PLL3 (for DRAM)
	PLL_ID_4        = 4,        ///< PLL4 (for AHB)
	PLL_ID_5        = 5,        ///< PLL5 (for GPU)
	PLL_ID_6        = 6,        ///< PLL6 (for SDC)
	PLL_ID_7        = 7,        ///< PLL7 (for ETH)
	PLL_ID_8        = 8,        ///< PLL8 (for LCD)
	PLL_ID_9        = 9,        ///< PLL9 (for LCD2)
	PLL_ID_10       = 10,       ///< PLL10 (for LCD3)
	PLL_ID_11       = 11,       ///< PLL11 (for DSI)
	PLL_ID_12       = 12,       ///< PLL12 (for AUDIO)
	PLL_ID_13       = 13,       ///< PLL13 (for AXI2)
	PLL_ID_14       = 14,       ///< PLL14 (for USB3 phy)
	PLL_ID_15       = 15,       ///< PLL15 (for SIE SENSOR)
	PLL_ID_16       = 16,       ///< PLL16 (for CPU)
	PLL_ID_17       = 17,       ///< PLL17 (for SATA phy)
	PLL_ID_18       = 18,       ///< PLL18 (for SIE SENSOR2)
	PLL_ID_19       = 19,       ///< PLL19 (for VIE)
	PLL_ID_20       = 20,       ///< PLL20 (for SENSOR MCLK)
	PLL_ID_21       = 21,       ///< PLL21 (for DSP)
	PLL_ID_22       = 22,       ///< PLL22 (for DSP2)
	PLL_ID_23       = 23,       ///< PLL23 (for SENSOR MCLK2)
	PLL_ID_24       = 24,       ///< PLL24 (for PCIE phy)
	PLL_ID_25       = 25,       ///< PLL25 (for SATA phy SSC)
	PLL_ID_26       = 26,       ///< PLL26 (for IPP)
	PLL_ID_27       = 27,       ///< PLL27 (for DSI2)
	PLL_ID_28       = 28,       ///< PLL28 (for CNN)
	PLL_ID_29       = 29,       ///< PLL29 (for CNN2)
	PLL_ID_30       = 30,       ///< PLL30 (for VENC)
	PLL_ID_31       = 31,       ///< PLL31 (for VDEC)
	PLL_ID_32       = 32,       ///< PLL32 (for DRAM2)

	PLL_ID_FIXED320 = 33,       ///< Fixed 320MHz PLL

	PLL_ID_MAX,
	ENUM_DUMMY4WORD(PLL_ID)
} PLL_ID;

//
// Clock Rate bit definition
//
#define PLL_CLKSEL_CPU_MASK             (0x03 << PLL_CLKSEL_CPU)
#define PLL_CLKSEL_MCU_MASK             (0x03 << PLL_CLKSEL_MCU)
#define PLL_CLKSEL_APB_MASK             (0x03 << PLL_CLKSEL_APB)
#define PLL_CLKSEL_IFE_SRAM_MASK        (0x01 << PLL_CLKSEL_IFE_SRAM)
#define PLL_CLKSEL_DSP_MASK             (0x01 << PLL_CLKSEL_DSP)
#define PLL_CLKSEL_DSP2_MASK            (0x01 << PLL_CLKSEL_DSP2)
#define PLL_CLKSEL_PD_MASK              (0x01 << PLL_CLKSEL_PD)


/*r1*/
#define PLL_CLKSEL_IVE_MASK             (0x03 << (PLL_CLKSEL_IVE - PLL_CLKSEL_R1_OFFSET))
#define PLL_CLKSEL_TRKE_MASK            (0x03 << (PLL_CLKSEL_TRKE - PLL_CLKSEL_R1_OFFSET))
#define PLL_CLKSEL_MDBC_MASK            (0x03 << (PLL_CLKSEL_MDBC - PLL_CLKSEL_R1_OFFSET))
#define PLL_CLKSEL_ISE2_MASK            (0x03 << (PLL_CLKSEL_ISE2 - PLL_CLKSEL_R1_OFFSET))
#define PLL_CLKSEL_ISE_MASK             (0x03 << (PLL_CLKSEL_ISE - PLL_CLKSEL_R1_OFFSET))
#define PLL_CLKSEL_IME2_MASK            (0x03 << (PLL_CLKSEL_IME2 - PLL_CLKSEL_R1_OFFSET))
#define PLL_CLKSEL_IPE2_MASK            (0x03 << (PLL_CLKSEL_IPE2 - PLL_CLKSEL_R1_OFFSET))
#define PLL_CLKSEL_NUE2_MASK            (0x03 << (PLL_CLKSEL_NUE2 - PLL_CLKSEL_R1_OFFSET))
#define PLL_CLKSEL_IME_MASK             (0x03 << (PLL_CLKSEL_IME - PLL_CLKSEL_R1_OFFSET))
#define PLL_CLKSEL_IPE_MASK             (0x03 << (PLL_CLKSEL_IPE - PLL_CLKSEL_R1_OFFSET))
#define PLL_CLKSEL_IFE2_MASK            (0x03 << (PLL_CLKSEL_IFE2 - PLL_CLKSEL_R1_OFFSET))
#define PLL_CLKSEL_IFE_MASK             (0x03 << (PLL_CLKSEL_IFE - PLL_CLKSEL_R1_OFFSET))
#define PLL_CLKSEL_VPE_MASK             (0x03 << (PLL_CLKSEL_VPE - PLL_CLKSEL_R1_OFFSET))
#define PLL_CLKSEL_VPE2_MASK		    (0x03 << (PLL_CLKSEL_VPE2 - PLL_CLKSEL_R1_OFFSET))
#define PLL_CLKSEL_SDE_MASK             (0x07 << (PLL_CLKSEL_SDE - PLL_CLKSEL_R1_OFFSET))

/*r2*/
#define PLL_CLKSEL_SENSOR_MCLKINV_MASK  (0x01 << (PLL_CLKSEL_SIE_MCLKINV - PLL_CLKSEL_R2_OFFSET))
#define PLL_CLKSEL_SENSOR_MCLK2INV_MASK (0x01 << (PLL_CLKSEL_SIE_MCLK2INV - PLL_CLKSEL_R2_OFFSET))
#define PLL_CLKSEL_SENSOR_MCLK3INV_MASK (0x01 << (PLL_CLKSEL_SIE_MCLK3INV - PLL_CLKSEL_R2_OFFSET))
#define PLL_CLKSEL_SENSOR_MCLK4INV_MASK (0x01 << (PLL_CLKSEL_SIE_MCLK4INV - PLL_CLKSEL_R2_OFFSET))
#define PLL_CLKSEL_SENSOR_MCLK5INV_MASK (0x01 << (PLL_CLKSEL_SIE_MCLK5INV - PLL_CLKSEL_R2_OFFSET))
#define PLL_CLKSEL_SENSOR_MCLK6INV_MASK (0x01 << (PLL_CLKSEL_SENSOR_MCLK6INV - PLL_CLKSEL_R2_OFFSET))
#define PLL_CLKSEL_SENSOR_MCLK7INV_MASK (0x01 << (PLL_CLKSEL_SENSOR_MCLK7INV - PLL_CLKSEL_R2_OFFSET))
#define PLL_CLKSEL_SENSOR_MCLK8INV_MASK (0x01 << (PLL_CLKSEL_SENSOR_MCLK8INV - PLL_CLKSEL_R2_OFFSET))
#define PLL_CLKSEL_TGEA_MASK            (0x07 << (PLL_CLKSEL_TGEA - PLL_CLKSEL_R2_OFFSET))
#define PLL_CLKSEL_CONV_MASK            (0x03 << (PLL_CLKSEL_CONV - PLL_CLKSEL_R2_OFFSET))
#define PLL_CLKSEL_CONV2_MASK           (0x03 << (PLL_CLKSEL_CONV2 - PLL_CLKSEL_R2_OFFSET))
#define PLL_CLKSEL_CONV3_MASK           (0x03 << (PLL_CLKSEL_CONV3 - PLL_CLKSEL_R2_OFFSET))
#define PLL_CLKSEL_CONV4_MASK           (0x03 << (PLL_CLKSEL_CONV4 - PLL_CLKSEL_R2_OFFSET))
#define PLL_CLKSEL_ROU_MASK             (0x03 << (PLL_CLKSEL_ROU - PLL_CLKSEL_R2_OFFSET))
#define PLL_CLKSEL_LSU_MASK             (0x03 << (PLL_CLKSEL_LSU - PLL_CLKSEL_R2_OFFSET))
#define PLL_CLKSEL_CAL_MASK             (0x03 << (PLL_CLKSEL_CAL - PLL_CLKSEL_R2_OFFSET))
#define PLL_CLKSEL_UTIL_MASK            (0x03 << (PLL_CLKSEL_UTIL - PLL_CLKSEL_R2_OFFSET))
#define PLL_CLKSEL_LME_MASK             (0x03 << (PLL_CLKSEL_LME - PLL_CLKSEL_R2_OFFSET))
#define PLL_CLKSEL_VPE3_MASK            (0x03 << (PLL_CLKSEL_VPE3 - PLL_CLKSEL_R2_OFFSET))

/*r3*/
#define PLL_CLKSEL_JPEG_MASK            (0x03 << (PLL_CLKSEL_JPEG - PLL_CLKSEL_R3_OFFSET))
#define PLL_CLKSEL_UVCP_MASK			(0x03 << (PLL_CLKSEL_UVCP - PLL_CLKSEL_R3_OFFSET))
#define PLL_CLKSEL_VENC_MASK            (0x03 << (PLL_CLKSEL_VENC - PLL_CLKSEL_R3_OFFSET))
#define PLL_CLKSEL_DRE_MASK             (0x03 << (PLL_CLKSEL_DRE - PLL_CLKSEL_R3_OFFSET))
#define PLL_CLKSEL_JPEG2_MASK           (0x03 << (PLL_CLKSEL_JPEG2 - PLL_CLKSEL_R3_OFFSET))
#define PLL_CLKSEL_VDEC_AD_MASK         (0x01 << (PLL_CLKSEL_VDEC_AD - PLL_CLKSEL_R3_OFFSET))
#define PLL_CLKSEL_VDEC_BIN_MASK        (0x01 << (PLL_CLKSEL_VDEC_BIN - PLL_CLKSEL_R3_OFFSET))
#define PLL_CLKSEL_VDEC_ACLK300_MASK    (0x03 << (PLL_CLKSEL_VDEC_ACLK300 - PLL_CLKSEL_R3_OFFSET))
#define PLL_CLKSEL_VDEC_ACLK250_MASK    (0x01 << (PLL_CLKSEL_VDEC_ACLK250 - PLL_CLKSEL_R3_OFFSET))
#define PLL_CLKSEL_XOR_MASK     	    (0x03 << (PLL_CLKSEL_XOR - PLL_CLKSEL_R3_OFFSET))
#define PLL_CLKSEL_JPEG_LITE_MASK  	    (0x03 << (PLL_CLKSEL_JPEG_LITE - PLL_CLKSEL_R3_OFFSET))
#define PLL_CLKSEL_SLVSEC_MASK  	    (0x07 << (PLL_CLKSEL_SLVSEC - PLL_CLKSEL_R3_OFFSET))
#define PLL_CLKSEL_LCD_MCLK_MASK   	    (0x03 << (PLL_CLKSEL_LCD_MCLK - PLL_CLKSEL_R3_OFFSET))
#define PLL_CLKSEL_LCD2_MCLK_MASK       (0x03 << (PLL_CLKSEL_LCD2_MCLK - PLL_CLKSEL_R3_OFFSET))
#define PLL_CLKSEL_LCD_LITE_MCLK_MASK   (0x03 << (PLL_CLKSEL_LCD_LITE_MCLK - PLL_CLKSEL_R3_OFFSET))

/*r4*/
#define PLL_CLKSEL_SDIO_MASK            (0x03 << (PLL_CLKSEL_SDIO - PLL_CLKSEL_R4_OFFSET))
#define PLL_CLKSEL_SDIO2_MASK           (0x03 << (PLL_CLKSEL_SDIO2 - PLL_CLKSEL_R4_OFFSET))
#define PLL_CLKSEL_SDIO3_MASK           (0x03 << (PLL_CLKSEL_SDIO3 - PLL_CLKSEL_R4_OFFSET))
#define PLL_CLKSEL_ETHPHY_CLKSRC_MASK   (0x03 << (PLL_CLKSEL_ETHPHY_CLKSRC - PLL_CLKSEL_R4_OFFSET))
#define PLL_CLKSEL_SP_MASK              (0x03 << (PLL_CLKSEL_SP - PLL_CLKSEL_R4_OFFSET))
#define PLL_CLKSEL_SP2_MASK             (0x03 << (PLL_CLKSEL_SP2 - PLL_CLKSEL_R4_OFFSET))
#define PLL_CLKSEL_GPENC_MASK           (0x03 << (PLL_CLKSEL_GPENC - PLL_CLKSEL_R4_OFFSET))
#define PLL_CLKSEL_GPENC2_MASK          (0x03 << (PLL_CLKSEL_GPENC2 - PLL_CLKSEL_R4_OFFSET))
#define PLL_CLKSEL_UVCP2_MASK			(0x03 << (PLL_CLKSEL_UVCP2 - PLL_CLKSEL_R4_OFFSET))
#define PLL_CLKSEL_HWCOPY_MASK			(0x03 << (PLL_CLKSEL_HWCOPY - PLL_CLKSEL_R4_OFFSET))
#define PLL_CLKSEL_DSI2_LPSRC_MASK      (0x03 << (PLL_CLKSEL_DSI2_LPSRC - PLL_CLKSEL_R4_OFFSET))
#define PLL_CLKSEL_DSI_LPSRC_MASK       (0x03 << (PLL_CLKSEL_DSI_LPSRC - PLL_CLKSEL_R4_OFFSET))
#define PLL_CLKSEL_CSI_TX_LPSRC_MASK    (0x03 << (PLL_CLKSEL_CSI_TX_LPSRC - PLL_CLKSEL_R4_OFFSET))
#define PLL_CLKSEL_MI_MASK				(0x03 << (PLL_CLKSEL_MI - PLL_CLKSEL_R4_OFFSET))
#define PLL_CLKSEL_ETH2PHY_CLKSRC_MASK  (0x03 << (PLL_CLKSEL_ETH2PHY_CLKSRC - PLL_CLKSEL_R4_OFFSET))
#define PLL_CLKSEL_ETH_PTP_REF_MASK     (0x01 << (PLL_CLKSEL_ETH_PTP_REF - PLL_CLKSEL_R4_OFFSET))
#define PLL_CLKSEL_ETH2_PTP_REF_MASK    (0x01 << (PLL_CLKSEL_ETH2_PTP_REF - PLL_CLKSEL_R4_OFFSET))

/*r5*/
#define PLL_CLKSEL_LCD_LITE_MASK        (0x07 << (PLL_CLKSEL_LCD_LITE - PLL_CLKSEL_R5_OFFSET))
#define PLL_CLKSEL_U3SATA_PHY_MASK      (0x01 << (PLL_CLKSEL_U3SATA_PHY - PLL_CLKSEL_R5_OFFSET))
#define PLL_CLKSEL_NAND_MASK            (0x03 << (PLL_CLKSEL_NAND - PLL_CLKSEL_R5_OFFSET))
#define PLL_CLKSEL_HASH_MASK            (0x01 << (PLL_CLKSEL_HASH - PLL_CLKSEL_R5_OFFSET))
#define PLL_CLKSEL_RSA_MASK             (0x01 << (PLL_CLKSEL_RSA - PLL_CLKSEL_R5_OFFSET))
#define PLL_CLKSEL_CRYPTO_MASK          (0x01 << (PLL_CLKSEL_CRYPTO - PLL_CLKSEL_R5_OFFSET))
#define PLL_CLKSEL_ADC_PD_MASK          (0x01 << (PLL_CLKSEL_ADC_PD - PLL_CLKSEL_R5_OFFSET))
#define PLL_CLKSEL_TRNG_MASK            (0x01 << (PLL_CLKSEL_TRNG - PLL_CLKSEL_R5_OFFSET))
#define PLL_CLKSEL_TRNGRO_CLKSRC_MASK   (0x01 << (PLL_CLKSEL_TRNGRO_CLKSRC- PLL_CLKSEL_R5_OFFSET))
#define PLL_CLKSEL_DRTC_MASK            (0x03 << (PLL_CLKSEL_DRTC - PLL_CLKSEL_R5_OFFSET))
#define PLL_CLKSEL_REMOTE_MASK          (0x03 << (PLL_CLKSEL_REMOTE - PLL_CLKSEL_R5_OFFSET))
#define PLL_CLKSEL_GRAPHIC_MASK         (0x03 << (PLL_CLKSEL_GRAPHIC - PLL_CLKSEL_R5_OFFSET))
#define PLL_CLKSEL_GRAPHIC2_MASK        (0x03 << (PLL_CLKSEL_GRAPHIC2 - PLL_CLKSEL_R5_OFFSET))
#define PLL_CLKSEL_LCD_CLKSRC_MASK      (0x07 << (PLL_CLKSEL_LCD_CLKSRC - PLL_CLKSEL_R5_OFFSET))
#define PLL_CLKSEL_LCD2_CLKSRC_MASK     (0x07 << (PLL_CLKSEL_LCD2_CLKSRC - PLL_CLKSEL_R5_OFFSET))
#define PLL_CLKSEL_GRAPHIC3_MASK        (0x03 << (PLL_CLKSEL_GRAPHIC3 - PLL_CLKSEL_R5_OFFSET))

/*r6*/
#define PLL_CLKSEL_SLVSEC_LANE0_CLKINV_MASK      (0x01 << (PLL_CLKSEL_SLVSEC_LANE0_CLKINV - PLL_CLKSEL_R6_OFFSET))
#define PLL_CLKSEL_SLVSEC_LANE1_CLKINV_MASK      (0x01 << (PLL_CLKSEL_SLVSEC_LANE1_CLKINV - PLL_CLKSEL_R6_OFFSET))
#define PLL_CLKSEL_SLVSEC_LANE2_CLKINV_MASK      (0x01 << (PLL_CLKSEL_SLVSEC_LANE2_CLKINV - PLL_CLKSEL_R6_OFFSET))
#define PLL_CLKSEL_SLVSEC_LANE3_CLKINV_MASK      (0x01 << (PLL_CLKSEL_SLVSEC_LANE3_CLKINV - PLL_CLKSEL_R6_OFFSET))
#define PLL_CLKSEL_SLVSEC_LANE4_CLKINV_MASK      (0x01 << (PLL_CLKSEL_SLVSEC_LANE4_CLKINV - PLL_CLKSEL_R6_OFFSET))
#define PLL_CLKSEL_SLVSEC_LANE5_CLKINV_MASK      (0x01 << (PLL_CLKSEL_SLVSEC_LANE5_CLKINV - PLL_CLKSEL_R6_OFFSET))
#define PLL_CLKSEL_SLVSEC_LANE6_CLKINV_MASK      (0x01 << (PLL_CLKSEL_SLVSEC_LANE6_CLKINV - PLL_CLKSEL_R6_OFFSET))
#define PLL_CLKSEL_SLVSEC_LANE7_CLKINV_MASK      (0x01 << (PLL_CLKSEL_SLVSEC_LANE7_CLKINV - PLL_CLKSEL_R6_OFFSET))
#define PLL_CLKSEL_CSI5_PXCLK_MASK               (0x01 << (PLL_CLKSEL_CSI5_PXCLK - PLL_CLKSEL_R6_OFFSET))
#define PLL_CLKSEL_CSI7_PXCLK_MASK               (0x01 << (PLL_CLKSEL_CSI7_PXCLK - PLL_CLKSEL_R6_OFFSET))
#define PLL_CLKSEL_CSI_TX2_LPSRC_MASK            (0x03 << (PLL_CLKSEL_CSI_TX2_LPSRC - PLL_CLKSEL_R6_OFFSET))
#define PLL_CLKSEL_AGE_MASK                      (0x03 << (PLL_CLKSEL_AGE - PLL_CLKSEL_R6_OFFSET))
#define PLL_CLKSEL_PPU_MASK                      (0x03 << (PLL_CLKSEL_PPU - PLL_CLKSEL_R6_OFFSET))
#define PLL_CLKSEL_CSI_MASK                      (0x03 << (PLL_CLKSEL_CSI - PLL_CLKSEL_R6_OFFSET))
#define PLL_CLKSEL_CSI2_MASK                     (0x03 << (PLL_CLKSEL_CSI2 - PLL_CLKSEL_R6_OFFSET))
#define PLL_CLKSEL_CSI3_MASK                     (0x03 << (PLL_CLKSEL_CSI3 - PLL_CLKSEL_R6_OFFSET))
#define PLL_CLKSEL_CSI4_MASK                     (0x03 << (PLL_CLKSEL_CSI4 - PLL_CLKSEL_R6_OFFSET))
#define PLL_CLKSEL_CSI5_MASK                     (0x03 << (PLL_CLKSEL_CSI5 - PLL_CLKSEL_R6_OFFSET))
#define PLL_CLKSEL_CSI6_MASK                     (0x03 << (PLL_CLKSEL_CSI6 - PLL_CLKSEL_R6_OFFSET))
#define PLL_CLKSEL_CSI7_MASK                     (0x03 << (PLL_CLKSEL_CSI7 - PLL_CLKSEL_R6_OFFSET))
#define PLL_CLKSEL_CSI8_MASK                     (0x03 << (PLL_CLKSEL_CSI8 - PLL_CLKSEL_R6_OFFSET))

/*r7*/
#define PLL_CLKSEL_CSIPHY_CSI_CK0_PHASE_MASK     (0x01 << (PLL_CLKSEL_CSIPHY_CSI_CK0_PHASE - PLL_CLKSEL_R7_OFFSET))
#define PLL_CLKSEL_CSIPHY_CSI_CK1_PHASE_MASK     (0x01 << (PLL_CLKSEL_CSIPHY_CSI_CK1_PHASE - PLL_CLKSEL_R7_OFFSET))
#define PLL_CLKSEL_CSIPHY_CSI_CK2_PHASE_MASK     (0x01 << (PLL_CLKSEL_CSIPHY_CSI_CK2_PHASE - PLL_CLKSEL_R7_OFFSET))
#define PLL_CLKSEL_CSIPHY_CSI_CK3_PHASE_MASK     (0x01 << (PLL_CLKSEL_CSIPHY_CSI_CK3_PHASE - PLL_CLKSEL_R7_OFFSET))
#define PLL_CLKSEL_CSIPHY_CSI2_CK1_PHASE_MASK    (0x01 << (PLL_CLKSEL_CSIPHY_CSI2_CK1_PHASE - PLL_CLKSEL_R7_OFFSET))
#define PLL_CLKSEL_CSIPHY_CSI3_CK2_PHASE_MASK    (0x01 << (PLL_CLKSEL_CSIPHY_CSI3_CK2_PHASE - PLL_CLKSEL_R7_OFFSET))
#define PLL_CLKSEL_CSIPHY_CSI3_CK3_PHASE_MASK    (0x01 << (PLL_CLKSEL_CSIPHY_CSI3_CK3_PHASE - PLL_CLKSEL_R7_OFFSET))
#define PLL_CLKSEL_CSIPHY_CSI4_CK3_PHASE_MASK    (0x01 << (PLL_CLKSEL_CSIPHY_CSI4_CK3_PHASE - PLL_CLKSEL_R7_OFFSET))
#define PLL_CLKSEL_CSIPHY2_CSI5_CK0_PHASE_MASK   (0x01 << (PLL_CLKSEL_CSIPHY2_CSI5_CK0_PHASE - PLL_CLKSEL_R7_OFFSET))
#define PLL_CLKSEL_CSIPHY2_CSI5_CK1_PHASE_MASK   (0x01 << (PLL_CLKSEL_CSIPHY2_CSI5_CK1_PHASE - PLL_CLKSEL_R7_OFFSET))
#define PLL_CLKSEL_CSIPHY2_CSI5_CK2_PHASE_MASK   (0x01 << (PLL_CLKSEL_CSIPHY2_CSI5_CK2_PHASE - PLL_CLKSEL_R7_OFFSET))
#define PLL_CLKSEL_CSIPHY2_CSI5_CK3_PHASE_MASK   (0x01 << (PLL_CLKSEL_CSIPHY2_CSI5_CK3_PHASE - PLL_CLKSEL_R7_OFFSET))
#define PLL_CLKSEL_CSIPHY2_CSI6_CK1_PHASE_MASK   (0x01 << (PLL_CLKSEL_CSIPHY2_CSI6_CK1_PHASE - PLL_CLKSEL_R7_OFFSET))
#define PLL_CLKSEL_CSIPHY2_CSI7_CK2_PHASE_MASK   (0x01 << (PLL_CLKSEL_CSIPHY2_CSI7_CK2_PHASE - PLL_CLKSEL_R7_OFFSET))
#define PLL_CLKSEL_CSIPHY2_CSI7_CK3_PHASE_MASK   (0x01 << (PLL_CLKSEL_CSIPHY2_CSI7_CK3_PHASE - PLL_CLKSEL_R7_OFFSET))
#define PLL_CLKSEL_CSIPHY2_CSI8_CK3_PHASE_MASK   (0x01 << (PLL_CLKSEL_CSIPHY2_CSI8_CK3_PHASE - PLL_CLKSEL_R7_OFFSET))
#define PLL_CLKSEL_DAI3_MASK                     (0x01 << (PLL_CLKSEL_DAI3 - PLL_CLKSEL_R7_OFFSET))
#define PLL_CLKSEL_I2S_MCLKSEL_MASK              (0x01 << (PLL_CLKSEL_I2S_MCLK - PLL_CLKSEL_R7_OFFSET))
#define PLL_CLKSEL_I2S2_MCLKSEL_MASK             (0x01 << (PLL_CLKSEL_I2S2_MCLK - PLL_CLKSEL_R7_OFFSET))
#define PLL_CLKSEL_I2S3_MCLKSEL_MASK             (0x01 << (PLL_CLKSEL_I2S3_MCLK - PLL_CLKSEL_R7_OFFSET))
#define PLL_CLKSEL_TSE_MASK                      (0x03 << (PLL_CLKSEL_TSE - PLL_CLKSEL_R7_OFFSET))
#define PLL_CLKSEL_I2S4_MCLKSEL_MASK             (0x01 << (PLL_CLKSEL_I2S4_MCLK - PLL_CLKSEL_R7_OFFSET))
#define PLL_CLKSEL_SLVSEC2_MASK                  (0x03 << (PLL_CLKSEL_SLVSEC2 - PLL_CLKSEL_R7_OFFSET))
#define PLL_CLKSEL_TGE_MSHA_MASK                 (0x07 << (PLL_CLKSEL_TGE_MSHA - PLL_CLKSEL_R7_OFFSET))
#define PLL_CLKSEL_TGE_MSHB_MASK                 (0x07 << (PLL_CLKSEL_TGE_MSHB - PLL_CLKSEL_R7_OFFSET))

/*r8*/
#define PLL_CLKSEL_PWM0_3_CLKDIV_MASK   (0x3FFF << (PLL_CLKSEL_PWM0_3_CLKDIV - PLL_CLKSEL_R8_OFFSET))
#define PLL_CLKSEL_PWM4_7_CLKDIV_MASK   (0x3FFF << (PLL_CLKSEL_PWM4_7_CLKDIV - PLL_CLKSEL_R8_OFFSET))

/*r9*/
#define PLL_CLKSEL_PWM8_CLKDIV_MASK     (0x3FFF << (PLL_CLKSEL_PWM8_CLKDIV - PLL_CLKSEL_R9_OFFSET))
#define PLL_CLKSEL_PWM9_CLKDIV_MASK     (0x3FFF << (PLL_CLKSEL_PWM9_CLKDIV - PLL_CLKSEL_R9_OFFSET))

/*r10*/
#define PLL_CLKSEL_PWM10_CLKDIV_MASK     (0x3FFF << (PLL_CLKSEL_PWM10_CLKDIV - PLL_CLKSEL_R10_OFFSET))
#define PLL_CLKSEL_PWM11_CLKDIV_MASK     (0x3FFF << (PLL_CLKSEL_PWM11_CLKDIV - PLL_CLKSEL_R10_OFFSET))

/*r11*/
#define PLL_CLKSEL_DAI_MCLKDIV_MASK     (0xFF << (PLL_CLKSEL_DAI_MCLKDIV - PLL_CLKSEL_R11_OFFSET))
#define PLL_CLKSEL_DAI2_MCLKDIV_MASK    (0xFF << (PLL_CLKSEL_DAI2_MCLKDIV - PLL_CLKSEL_R11_OFFSET))
#define PLL_CLKSEL_SP_CLKDIV_MASK       (0xFF << (PLL_CLKSEL_SP_CLKDIV - PLL_CLKSEL_R11_OFFSET))
#define PLL_CLKSEL_SP2_CLKDIV_MASK      (0xFF << (PLL_CLKSEL_SP2_CLKDIV - PLL_CLKSEL_R11_OFFSET))

/*r12*/
#define PLL_CLKSEL_SDIO_CLKDIV_MASK     (0x7FF<< (PLL_CLKSEL_SDIO_CLKDIV - PLL_CLKSEL_R12_OFFSET))
#define PLL_CLKSEL_SDIO2_CLKDIV_MASK    (0x7FF<< (PLL_CLKSEL_SDIO2_CLKDIV - PLL_CLKSEL_R12_OFFSET))

/*r13*/
#define PLL_CLKSEL_UART_CLKDIV_MASK     (0xFF << (PLL_CLKSEL_UART_CLKDIV - PLL_CLKSEL_R13_OFFSET))
#define PLL_CLKSEL_UART2_CLKDIV_MASK    (0xFF << (PLL_CLKSEL_UART2_CLKDIV - PLL_CLKSEL_R13_OFFSET))
#define PLL_CLKSEL_UART3_CLKDIV_MASK    (0xFF << (PLL_CLKSEL_UART3_CLKDIV - PLL_CLKSEL_R13_OFFSET))
#define PLL_CLKSEL_UART4_CLKDIV_MASK    (0xFF << (PLL_CLKSEL_UART4_CLKDIV - PLL_CLKSEL_R13_OFFSET))

/*r14*/
#define PLL_CLKSEL_UART5_CLKDIV_MASK    (0xFF << (PLL_CLKSEL_UART5_CLKDIV - PLL_CLKSEL_R14_OFFSET))
#define PLL_CLKSEL_DAI3_MCLKDIV_MASK    (0xFF << (PLL_CLKSEL_DAI3_MCLKDIV - PLL_CLKSEL_R14_OFFSET))
#define PLL_CLKSEL_NAND_CLKDIV_MASK     (0x3F << (PLL_CLKSEL_NAND_CLKDIV - PLL_CLKSEL_R14_OFFSET))
#define PLL_CLKSEL_ETH_PTP_CLKDIV_MASK  (0x3 << (PLL_CLKSEL_ETH_PTP_CLKDIV - PLL_CLKSEL_R14_OFFSET))
#define PLL_CLKSEL_ETH2_PTP_CLKDIV_MASK (0x3 << (PLL_CLKSEL_ETH2_PTP_CLKDIV - PLL_CLKSEL_R14_OFFSET))
#define PLL_CLKSEL_XOR_CLKDIV_MASK 		(0x3 << (PLL_CLKSEL_XOR_CLKDIV - PLL_CLKSEL_R14_OFFSET))

/*r15*/
#define PLL_CLKSEL_LCD_CLKDIV_MASK        (0xFF << (PLL_CLKSEL_LCD_CLKDIV - PLL_CLKSEL_R15_OFFSET))
#define PLL_CLKSEL_LCD_OUTIF_CLKDIV_MASK  (0xFF << (PLL_CLKSEL_LCD_OUTIF_CLKDIV - PLL_CLKSEL_R15_OFFSET))
#define PLL_CLKSEL_LCD2_CLKDIV_MASK       (0xFF << (PLL_CLKSEL_LCD2_CLKDIV - PLL_CLKSEL_R15_OFFSET))
#define PLL_CLKSEL_LCD2_OUTIF_CLKDIV_MASK (0xFF << (PLL_CLKSEL_LCD2_OUTIF_CLKDIV - PLL_CLKSEL_R15_OFFSET))

/*r16*/
#define PLL_CLKSEL_TRNG_RO_CLKDIV_MASK   (0xFF << (PLL_CLKSEL_TRNG_RO_CLKDIV - PLL_CLKSEL_R16_OFFSET))
#define PLL_CLKSEL_LCD_MCLKDIV_MASK      (0xFF << (PLL_CLKSEL_LCD_MCLKDIV - PLL_CLKSEL_R16_OFFSET))
#define PLL_CLKSEL_LCD2_MCLKDIV_MASK     (0xFF << (PLL_CLKSEL_LCD2_MCLKDIV - PLL_CLKSEL_R16_OFFSET))
#define PLL_CLKSEL_TRNG_CLKDIV_MASK      (0xFF << (PLL_CLKSEL_TRNG_CLKDIV - PLL_CLKSEL_R16_OFFSET))

/*r17*/
#define PLL_CLKSEL_DSP_IOP_CLKDIV_MASK   (0x3 << (PLL_CLKSEL_DSP_IOP_CLKDIV - PLL_CLKSEL_R17_OFFSET))
#define PLL_CLKSEL_DSP_EDP_CLKDIV_MASK   (0x1 << (PLL_CLKSEL_DSP_EDP_CLKDIV - PLL_CLKSEL_R17_OFFSET))
#define PLL_CLKSEL_DSP_EPP_CLKDIV_MASK   (0x1 << (PLL_CLKSEL_DSP_EPP_CLKDIV - PLL_CLKSEL_R17_OFFSET))
#define PLL_CLKSEL_DSP_EDAP_CLKDIV_MASK  (0x3 << (PLL_CLKSEL_DSP_EDAP_CLKDIV - PLL_CLKSEL_R17_OFFSET))
#define PLL_CLKSEL_DSP2_IOP_CLKDIV_MASK  (0x3 << (PLL_CLKSEL_DSP2_IOP_CLKDIV - PLL_CLKSEL_R17_OFFSET))
#define PLL_CLKSEL_DSP2_EDP_CLKDIV_MASK  (0x1 << (PLL_CLKSEL_DSP2_EDP_CLKDIV - PLL_CLKSEL_R17_OFFSET))
#define PLL_CLKSEL_DSP2_EPP_CLKDIV_MASK  (0x1 << (PLL_CLKSEL_DSP2_EPP_CLKDIV - PLL_CLKSEL_R17_OFFSET))
#define PLL_CLKSEL_DSP2_EDAP_CLKDIV_MASK (0x3 << (PLL_CLKSEL_DSP2_EDAP_CLKDIV - PLL_CLKSEL_R17_OFFSET))
#define PLL_CLKSEL_DAI4_MCLKDIV_MASK     (0xFF << (PLL_CLKSEL_DAI4_MCLKDIV - PLL_CLKSEL_R17_OFFSET))
#define PLL_CLKSEL_DAI4_CLKDIV_MASK      (0xFF << (PLL_CLKSEL_DAI4_CLKDIV - PLL_CLKSEL_R17_OFFSET))

/*r18*/
#define PLL_CLKSEL_DAI_CLKDIV_MASK       (0xFF << (PLL_CLKSEL_DAI_CLKDIV - PLL_CLKSEL_R18_OFFSET))
#define PLL_CLKSEL_DAI3_OSR_CLKDIV_MASK  (0xFF << (PLL_CLKSEL_DAI3_OSR_CLKDIV - PLL_CLKSEL_R18_OFFSET))
#define PLL_CLKSEL_DAI2_CLKDIV_MASK      (0xFF << (PLL_CLKSEL_DAI2_CLKDIV - PLL_CLKSEL_R18_OFFSET))
#define PLL_CLKSEL_DAI3_CLKDIV_MASK      (0xFF << (PLL_CLKSEL_DAI3_CLKDIV - PLL_CLKSEL_R18_OFFSET))

/*r19*/
#define PLL_CLKSEL_SDIO3_CLKDIV_MASK    (0x7FF<< (PLL_CLKSEL_SDIO3_CLKDIV - PLL_CLKSEL_R19_OFFSET))
#define PLL_CLKSEL_MI_CLKDIV_MASK    	(0xFF<< (PLL_CLKSEL_MI_CLKDIV - PLL_CLKSEL_R19_OFFSET))

/*r20*/
#define PLL_CLKSEL_UART6_CLKDIV_MASK    (0xFF << (PLL_CLKSEL_UART6_CLKDIV - PLL_CLKSEL_R20_OFFSET))
#define PLL_CLKSEL_UART7_CLKDIV_MASK    (0xFF << (PLL_CLKSEL_UART7_CLKDIV - PLL_CLKSEL_R20_OFFSET))
#define PLL_CLKSEL_UART8_CLKDIV_MASK    (0xFF << (PLL_CLKSEL_UART8_CLKDIV - PLL_CLKSEL_R20_OFFSET))
#define PLL_CLKSEL_UART9_CLKDIV_MASK    (0xFF << (PLL_CLKSEL_UART9_CLKDIV - PLL_CLKSEL_R20_OFFSET))

/*r21*/
#define PLL_CLKSEL_SPI_CLKDIV_MASK      (0x7FF << (PLL_CLKSEL_SPI_CLKDIV - PLL_CLKSEL_R21_OFFSET))
#define PLL_CLKSEL_SPI2_CLKDIV_MASK     (0x7FF << (PLL_CLKSEL_SPI2_CLKDIV - PLL_CLKSEL_R21_OFFSET))

/*r22*/
#define PLL_CLKSEL_SPI3_CLKDIV_MASK     (0x7FF << (PLL_CLKSEL_SPI3_CLKDIV - PLL_CLKSEL_R22_OFFSET))
#define PLL_CLKSEL_SPI4_CLKDIV_MASK     (0x7FF << (PLL_CLKSEL_SPI4_CLKDIV - PLL_CLKSEL_R22_OFFSET))

/*r23*/
#define PLL_CLKSEL_SPI5_CLKDIV_MASK     (0x7FF << (PLL_CLKSEL_SPI5_CLKDIV - PLL_CLKSEL_R23_OFFSET))
#define PLL_CLKSEL_DAI5_CLKDIV_MASK     (0xFF << (PLL_CLKSEL_DAI5_CLKDIV - PLL_CLKSEL_R23_OFFSET))

/*r24*/
#define PLL_CLKSEL_SIE_CLKSRC_MASK      (0x07 << (PLL_CLKSEL_SIE_CLKSRC - PLL_CLKSEL_R24_OFFSET))
#define PLL_CLKSEL_SIE2_CLKSRC_MASK     (0x07 << (PLL_CLKSEL_SIE2_CLKSRC - PLL_CLKSEL_R24_OFFSET))
#define PLL_CLKSEL_SIE3_CLKSRC_MASK     (0x07 << (PLL_CLKSEL_SIE3_CLKSRC - PLL_CLKSEL_R24_OFFSET))
#define PLL_CLKSEL_SIE4_CLKSRC_MASK     (0x07 << (PLL_CLKSEL_SIE4_CLKSRC - PLL_CLKSEL_R24_OFFSET))
#define PLL_CLKSEL_SIE5_CLKSRC_MASK     (0x07 << (PLL_CLKSEL_SIE5_CLKSRC - PLL_CLKSEL_R24_OFFSET))
#define PLL_CLKSEL_SIE6_CLKSRC_MASK     (0x07 << (PLL_CLKSEL_SIE6_CLKSRC - PLL_CLKSEL_R24_OFFSET))
#define PLL_CLKSEL_SIE7_CLKSRC_MASK     (0x07 << (PLL_CLKSEL_SIE7_CLKSRC - PLL_CLKSEL_R24_OFFSET))
#define PLL_CLKSEL_SIE8_CLKSRC_MASK     (0x07 << (PLL_CLKSEL_SIE8_CLKSRC - PLL_CLKSEL_R24_OFFSET))

/*r25*/
#define PLL_CLKSEL_SENSOR_MCLKSRC_MASK     (0x03 << (PLL_CLKSEL_SENSOR_MCLKSRC - PLL_CLKSEL_R25_OFFSET))
#define PLL_CLKSEL_SENSOR_MCLK2SRC_MASK    (0x03 << (PLL_CLKSEL_SENSOR_MCLK2SRC - PLL_CLKSEL_R25_OFFSET))
#define PLL_CLKSEL_SENSOR_MCLK3SRC_MASK    (0x03 << (PLL_CLKSEL_SENSOR_MCLK3SRC - PLL_CLKSEL_R25_OFFSET))
#define PLL_CLKSEL_SENSOR_MCLK4SRC_MASK    (0x03 << (PLL_CLKSEL_SENSOR_MCLK4SRC - PLL_CLKSEL_R25_OFFSET))
#define PLL_CLKSEL_SENSOR_MCLK5SRC_MASK    (0x03 << (PLL_CLKSEL_SENSOR_MCLK5SRC - PLL_CLKSEL_R25_OFFSET))
#define PLL_CLKSEL_SENSOR_MCLK6SRC_MASK    (0x03 << (PLL_CLKSEL_SENSOR_MCLK6SRC - PLL_CLKSEL_R25_OFFSET))
#define PLL_CLKSEL_SENSOR_MCLK7SRC_MASK    (0x03 << (PLL_CLKSEL_SENSOR_MCLK7SRC - PLL_CLKSEL_R25_OFFSET))
#define PLL_CLKSEL_SENSOR_MCLK8SRC_MASK    (0x03 << (PLL_CLKSEL_SENSOR_MCLK8SRC - PLL_CLKSEL_R25_OFFSET))
#define PLL_CLKSEL_VIE_CLKSRC_MASK         (0x07 << (PLL_CLKSEL_VIE_CLKSRC - PLL_CLKSEL_R25_OFFSET))
#define PLL_CLKSEL_VIE2_CLKSRC_MASK        (0x07 << (PLL_CLKSEL_VIE2_CLKSRC - PLL_CLKSEL_R25_OFFSET))

/*r26*/
#define PLL_CLKSEL_SIE6_PXCLKSRC_MASK   (0x01 << (PLL_CLKSEL_SIE6_PXCLKSRC - PLL_CLKSEL_R26_OFFSET))
#define PLL_CLKSEL_SIE12_PXCLKSRC_MASK  (0x01 << (PLL_CLKSEL_SIE12_PXCLKSRC - PLL_CLKSEL_R26_OFFSET))

/*r27*/
#define PLL_CLKSEL_SIE9_CLKSRC_MASK      (0x07 << (PLL_CLKSEL_SIE9_CLKSRC - PLL_CLKSEL_R27_OFFSET))
#define PLL_CLKSEL_SIE10_CLKSRC_MASK     (0x07 << (PLL_CLKSEL_SIE10_CLKSRC - PLL_CLKSEL_R27_OFFSET))
#define PLL_CLKSEL_SIE11_CLKSRC_MASK     (0x07 << (PLL_CLKSEL_SIE11_CLKSRC - PLL_CLKSEL_R27_OFFSET))
#define PLL_CLKSEL_SIE12_CLKSRC_MASK     (0x07 << (PLL_CLKSEL_SIE12_CLKSRC - PLL_CLKSEL_R27_OFFSET))
#define PLL_CLKSEL_SIE_BCC_CLKSRC_MASK   (0x01 << (PLL_CLKSEL_SIE_BCC_CLKSRC - PLL_CLKSEL_R27_OFFSET))
#define PLL_CLKSEL_SIE2_BCC_CLKSRC_MASK   (0x01 << (PLL_CLKSEL_SIE2_BCC_CLKSRC - PLL_CLKSEL_R27_OFFSET))
#define PLL_CLKSEL_SIE3_BCC_CLKSRC_MASK   (0x01 << (PLL_CLKSEL_SIE3_BCC_CLKSRC - PLL_CLKSEL_R27_OFFSET))
#define PLL_CLKSEL_SIE4_BCC_CLKSRC_MASK   (0x01 << (PLL_CLKSEL_SIE4_BCC_CLKSRC - PLL_CLKSEL_R27_OFFSET))
#define PLL_CLKSEL_SIE5_BCC_CLKSRC_MASK   (0x01 << (PLL_CLKSEL_SIE5_BCC_CLKSRC - PLL_CLKSEL_R27_OFFSET))
#define PLL_CLKSEL_SIE6_BCC_CLKSRC_MASK   (0x01 << (PLL_CLKSEL_SIE6_BCC_CLKSRC - PLL_CLKSEL_R27_OFFSET))
#define PLL_CLKSEL_SIE7_BCC_CLKSRC_MASK   (0x01 << (PLL_CLKSEL_SIE7_BCC_CLKSRC - PLL_CLKSEL_R27_OFFSET))
#define PLL_CLKSEL_SIE8_BCC_CLKSRC_MASK   (0x01 << (PLL_CLKSEL_SIE8_BCC_CLKSRC - PLL_CLKSEL_R27_OFFSET))
#define PLL_CLKSEL_SIE9_BCC_CLKSRC_MASK   (0x01 << (PLL_CLKSEL_SIE9_BCC_CLKSRC - PLL_CLKSEL_R27_OFFSET))
#define PLL_CLKSEL_TGEB_MASK            (0x07 << (PLL_CLKSEL_TGEB - PLL_CLKSEL_R27_OFFSET))

/*r38*/
#define PLL_CLKSEL_SIE2_INT_CLKSRC_MASK      (0x01 << (PLL_CLKSEL_SIE2_INT_CLKSRC - PLL_CLKSEL_R38_OFFSET))
#define PLL_CLKSEL_SIE3_INT_CLKSRC_MASK      (0x01 << (PLL_CLKSEL_SIE3_INT_CLKSRC - PLL_CLKSEL_R38_OFFSET))
#define PLL_CLKSEL_SIE5_INT_CLKSRC_MASK      (0x01 << (PLL_CLKSEL_SIE5_INT_CLKSRC - PLL_CLKSEL_R38_OFFSET))
#define PLL_CLKSEL_SIE6_INT_CLKSRC_MASK      (0x01 << (PLL_CLKSEL_SIE6_INT_CLKSRC - PLL_CLKSEL_R38_OFFSET))
#define PLL_CLKSEL_SIE8_INT_CLKSRC_MASK      (0x01 << (PLL_CLKSEL_SIE8_INT_CLKSRC - PLL_CLKSEL_R38_OFFSET))
#define PLL_CLKSEL_SIE9_INT_CLKSRC_MASK      (0x01 << (PLL_CLKSEL_SIE9_INT_CLKSRC - PLL_CLKSEL_R38_OFFSET))
#define PLL_CLKSEL_SIE11_INT_CLKSRC_MASK      (0x01 << (PLL_CLKSEL_SIE11_INT_CLKSRC - PLL_CLKSEL_R38_OFFSET))
#define PLL_CLKSEL_SIE12_INT_CLKSRC_MASK      (0x01 << (PLL_CLKSEL_SIE12_INT_CLKSRC - PLL_CLKSEL_R38_OFFSET))

/*r28*/
#define PLL_CLKSEL_SIE_CLKDIV_MASK      (0xFF << (PLL_CLKSEL_SIE_CLKDIV - PLL_CLKSEL_R28_OFFSET))
#define PLL_CLKSEL_SIE2_CLKDIV_MASK     (0xFF << (PLL_CLKSEL_SIE2_CLKDIV - PLL_CLKSEL_R28_OFFSET))
#define PLL_CLKSEL_SIE3_CLKDIV_MASK     (0xFF << (PLL_CLKSEL_SIE3_CLKDIV - PLL_CLKSEL_R28_OFFSET))
#define PLL_CLKSEL_SIE4_CLKDIV_MASK     (0xFF << (PLL_CLKSEL_SIE4_CLKDIV - PLL_CLKSEL_R28_OFFSET))

/*r29*/
#define PLL_CLKSEL_SIE5_CLKDIV_MASK     (0xFF << (PLL_CLKSEL_SIE5_CLKDIV - PLL_CLKSEL_R29_OFFSET))
#define PLL_CLKSEL_SIE6_CLKDIV_MASK     (0xFF << (PLL_CLKSEL_SIE6_CLKDIV - PLL_CLKSEL_R29_OFFSET))
#define PLL_CLKSEL_SENSOR_MCLKDIV_MASK  (0xFF << (PLL_CLKSEL_SENSOR_MCLKDIV - PLL_CLKSEL_R29_OFFSET))
#define PLL_CLKSEL_SENSOR_MCLK2DIV_MASK (0xFF << (PLL_CLKSEL_SENSOR_MCLK2DIV - PLL_CLKSEL_R29_OFFSET))

/*r30*/
#define PLL_CLKSEL_SENSOR_MCLK3DIV_MASK (0xFF << (PLL_CLKSEL_SENSOR_MCLK3DIV - PLL_CLKSEL_R30_OFFSET))
#define PLL_CLKSEL_SENSOR_MCLK4DIV_MASK (0xFF << (PLL_CLKSEL_SENSOR_MCLK4DIV - PLL_CLKSEL_R30_OFFSET))
#define PLL_CLKSEL_SENSOR_MCLK5DIV_MASK (0xFF << (PLL_CLKSEL_SENSOR_MCLK5DIV - PLL_CLKSEL_R30_OFFSET))
#define PLL_CLKSEL_VIE_CLKDIV_MASK      (0xFF << (PLL_CLKSEL_VIE_CLKDIV - PLL_CLKSEL_R30_OFFSET))

/*r31*/
#define PLL_CLKSEL_VIE2_CLKDIV_MASK     (0xFF << (PLL_CLKSEL_VIE2_CLKDIV - PLL_CLKSEL_R31_OFFSET))

/*r32*/
#define PLL_CLKSEL_SIE7_CLKDIV_MASK     (0xFF << (PLL_CLKSEL_SIE7_CLKDIV - PLL_CLKSEL_R32_OFFSET))
#define PLL_CLKSEL_SIE8_CLKDIV_MASK     (0xFF << (PLL_CLKSEL_SIE8_CLKDIV - PLL_CLKSEL_R32_OFFSET))
#define PLL_CLKSEL_SIE9_CLKDIV_MASK     (0xFF << (PLL_CLKSEL_SIE9_CLKDIV - PLL_CLKSEL_R32_OFFSET))
#define PLL_CLKSEL_SIE10_CLKDIV_MASK    (0xFF << (PLL_CLKSEL_SIE10_CLKDIV - PLL_CLKSEL_R32_OFFSET))

/*r33*/
#define PLL_CLKSEL_SIE11_CLKDIV_MASK     (0xFF << (PLL_CLKSEL_SIE11_CLKDIV - PLL_CLKSEL_R33_OFFSET))
#define PLL_CLKSEL_SIE12_CLKDIV_MASK     (0xFF << (PLL_CLKSEL_SIE12_CLKDIV - PLL_CLKSEL_R33_OFFSET))

/*r34*/
#define PLL_CLKSEL_SENSOR_MCLK6DIV_MASK (0xFF << (PLL_CLKSEL_SENSOR_MCLK6DIV - PLL_CLKSEL_R34_OFFSET))
#define PLL_CLKSEL_SENSOR_MCLK7DIV_MASK (0xFF << (PLL_CLKSEL_SENSOR_MCLK7DIV - PLL_CLKSEL_R34_OFFSET))

/*r35*/
#define PLL_CLKSEL_SENSOR_MCLK8DIV_MASK (0xFF << (PLL_CLKSEL_SENSOR_MCLK8DIV - PLL_CLKSEL_R35_OFFSET))

/*r36*/
#define PLL_CLKSEL_LCD_LITE_CLKDIV_MASK       (0xFF << (PLL_CLKSEL_LCD_LITE_CLKDIV - PLL_CLKSEL_R36_OFFSET))
#define PLL_CLKSEL_LCD_LITE_OUTIF_CLKDIV_MASK (0xFF << (PLL_CLKSEL_LCD_LITE_OUTIF_CLKDIV - PLL_CLKSEL_R36_OFFSET))
#define PLL_CLKSEL_LCD_LITE_MCLKDIV_MASK      (0xFF << (PLL_CLKSEL_LCD_LITE_MCLKDIV - PLL_CLKSEL_R36_OFFSET))

/*r37*/
#define PLL_CLKSEL_PWM12_CLKDIV_MASK       (0xFF << (PLL_CLKSEL_PWM12_CLKDIV - PLL_CLKSEL_R37_OFFSET))