/**
    PLL register header

    PLL register header file

    @file       pll_reg.h
    @ingroup    mIDrvSys_CG
    @note       Nothing

    Copyright   Novatek Microelectronics Corp. 2011.  All rights reserved.
*/

#ifndef _PLL_REG_H
#define _PLL_REG_H

#include <rcw_macro.h>
//#define PLL_STBC_BASE_OFFSET 0x00000000 // base address from 0xF0020000 to 0xF0580000

//
//0x00 PLL power enable Register
//
#define PLL_PLL_PWREN0_REG_OFS           0x00
REGDEF_BEGIN(PLL_PLL_PWREN0_REG)
REGDEF_BIT(DONTCARE, 32)
REGDEF_END(PLL_PLL_PWREN0_REG)

//
//0x04 PLL Status Register
//
#define PLL_PLL_STATUS0_REG_OFS          0x04
REGDEF_BEGIN(PLL_PLL_STATUS0_REG)
REGDEF_BIT(DONTCARE, 32)
REGDEF_END(PLL_PLL_STATUS0_REG)

//
//0x08 PLL power enable Register 1
//
#define PLL_PLL_PWREN1_REG_OFS           0x08
REGDEF_BEGIN(PLL_PLL_PWREN1_REG)
REGDEF_BIT(DONTCARE, 32)
REGDEF_END(PLL_PLL_PWREN1_REG)

//
//0x0C PLL Status Register 1
//
#define PLL_PLL_STATUS1_REG_OFS          0x0C
REGDEF_BEGIN(PLL_PLL_STATUS1_REG)
REGDEF_BIT(DONTCARE, 32)
REGDEF_END(PLL_PLL_STATUS1_REG)

//
//0x10 System Clock Rate Register
//
#define PLL_SYS_CR_REG_OFS              0x10
REGDEF_BEGIN(PLL_SYS_CR_REG)
REGDEF_BIT(DONTCARE, 32)
REGDEF_END(PLL_SYS_CR_REG)

//
//0x14 IPP Clock Rate Register 0
//
#define PLL_IPP_CR0_REG_OFS             0x14
REGDEF_BEGIN(PLL_IPP_CR0_REG)
REGDEF_BIT(DONTCARE, 32)
REGDEF_END(PLL_IPP_CR0_REG)

//
//0x18 IPP Clock Rate Register 1
//
#define PLL_IPP_CR1_REG_OFS             0x18
REGDEF_BEGIN(PLL_IPP_CR1_REG)
REGDEF_BIT(DONTCARE, 32)
REGDEF_END(PLL_IPP_CR1_REG)

//
//0x1C CODEC Clock Rate Register
//
#define PLL_CODEC_CR_REG_OFS            0x1C
REGDEF_BEGIN(PLL_CODEC_CR_REG)
REGDEF_BIT(DONTCARE, 32)
REGDEF_END(PLL_CODEC_CR_REG)

//
//0x20 Peripheral Clock Rate Register
//
#define PLL_PERI_CR_REG_OFS             0x20
REGDEF_BEGIN(PLL_PERI_CR_REG)
REGDEF_BIT(DONTCARE, 32)
REGDEF_END(PLL_PERI_CR_REG)

//
//0x24 Peripheral Clock Rate Register 1
//
#define PLL_PERI_CR1_REG_OFS             0x24
REGDEF_BEGIN(PLL_PERI_CR1_REG)
REGDEF_BIT(DONTCARE, 32)
REGDEF_END(PLL_PERI_CR1_REG)

//
//0x28 Peripheral Clock Rate Register 2
//
#define PLL_PERI_CR2_REG_OFS             0x28
REGDEF_BEGIN(PLL_PERI_CR2_REG)
REGDEF_BIT(DONTCARE, 32)
REGDEF_END(PLL_PERI_CR2_REG)

//
//0x2C Peripheral Clock Rate Register 3
//
#define PLL_PERI_CR3_REG_OFS             0x2C
REGDEF_BEGIN(PLL_PERI_CR3_REG)
REGDEF_BIT(DONTCARE, 32)
REGDEF_END(PLL_PERI_CR3_REG)

//
//0x30 PWM Clock Divider Register 0
//
#define PLL_PWM_CLKDIV0_REG_OFS          0x30
REGDEF_BEGIN(PLL_PWM_CLKDIV0_REG)
REGDEF_BIT(DONTCARE, 32)
REGDEF_END(PLL_PWM_CLKDIV0_REG)

//
//0x34 PWM Clock Divider Register 1
//
#define PLL_PWM_CLKDIV1_REG_OFS          0x34
REGDEF_BEGIN(PLL_PWM_CLKDIV1_REG)
REGDEF_BIT(DONTCARE, 32)
REGDEF_END(PLL_PWM_CLKDIV1_REG)

//
//0x38 PWM Clock Divider Register 2
//
#define PLL_PWM_CLKDIV2_REG_OFS          0x38
REGDEF_BEGIN(PLL_PWM_CLKDIV2_REG)
REGDEF_BIT(DONTCARE, 32)
REGDEF_END(PLL_PWM_CLKDIV2_REG)

//
//0x3C DAI MCLK Clock Divider Register
//
#define PLL_DAI_CLKDIV_REG_OFS          0x3C
REGDEF_BEGIN(PLL_DAI_CLKDIV_REG)
REGDEF_BIT(DONTCARE, 32)
REGDEF_END(PLL_DAI_CLKDIV_REG)

//
//0x40 SDIO Clock Divider Register 0
//
#define PLL_SDIO_CLKDIV0_REG_OFS         0x40
REGDEF_BEGIN(PLL_SDIO_CLKDIV0_REG)
REGDEF_BIT(DONTCARE, 32)
REGDEF_END(PLL_SDIO_CLKDIV0_REG)


//
//0x44 UART Clock Divider Register 0
//
#define PLL_UART_CLKDIV0_REG_OFS        0x44
REGDEF_BEGIN(PLL_UART_CLKDIV0_REG)
REGDEF_BIT(DONTCARE, 32)
REGDEF_END(PLL_UART_CLKDIV0_REG)

//
//0x48 peripheral Clock Divider Register 0
//
#define PLL_PERI_CLKDIV0_REG_OFS          0x48
REGDEF_BEGIN(PLL_PERI_CLKDIV0_REG)
REGDEF_BIT(DONTCARE, 32)
REGDEF_END(PLL_PERI_CLKDIV0_REG)

//
//0x4C Display Clock Divider Register
//
#define PLL_DISP_CLKDIV_REG_OFS         0x4C
REGDEF_BEGIN(PLL_DISP_CLKDIV_REG)
REGDEF_BIT(DONTCARE, 32)
REGDEF_END(PLL_DISP_CLKDIV_REG)


//
//0x50 Peripheral Clock Divider Register 1
//
#define PLL_PERI_CLKDIV1_REG_OFS          0x50
REGDEF_BEGIN(PLL_PERI_CLKDIV1_REG)
REGDEF_BIT(DONTCARE, 32)
REGDEF_END(PLL_PERI_CLKDIV1_REG)

//
//0x54 DSP Clock Divider Register
//
#define PLL_DSP_CLKDIV_REG_OFS          0x54
REGDEF_BEGIN(PLL_DSP_CLKDIV_REG)
REGDEF_BIT(DONTCARE, 32)
REGDEF_END(PLL_DSP_CLKDIV_REG)

//
//0x58 Audio Clock Divider Register
//
#define PLL_ADO_CLKDIV_REG_OFS          0x58
REGDEF_BEGIN(PLL_ADO_CLKDIV_REG)
REGDEF_BIT(DONTCARE, 32)
REGDEF_END(PLL_ADO_CLKDIV_REG)

//
//0x5C SDIO Clock Divider Register 0
//
#define PLL_SDIO_CLKDIV1_REG_OFS         0x5C
REGDEF_BEGIN(PLL_SDIO_CLKDIV1_REG)
REGDEF_BIT(DONTCARE, 32)
REGDEF_END(PLL_SDIO_CLKDIV1_REG)

//
//0x60 UART Clock Divider Register 1
//
#define PLL_UART_CLKDIV1_REG_OFS        0x60
REGDEF_BEGIN(PLL_UART_CLKDIV1_REG)
REGDEF_BIT(DONTCARE, 32)
REGDEF_END(PLL_UART_CLKDIV1_REG)

//
//0x64 SPI Clock Divider Register 0
//
#define PLL_SPI_CLKDIV0_REG_OFS        0x64
REGDEF_BEGIN(PLL_SPI_CLKDIV0_REG)
REGDEF_BIT(DONTCARE, 32)
REGDEF_END(PLL_SPI_CLKDIV0_REG)

//
//0x68 SPI Clock Divider Register 1
//
#define PLL_SPI_CLKDIV1_REG_OFS        0x68
REGDEF_BEGIN(PLL_SPI_CLKDIV1_REG)
REGDEF_BIT(DONTCARE, 32)
REGDEF_END(PLL_SPI_CLKDIV1_REG)

//
//0x6C SPI Clock Divider Register 2
//
#define PLL_SPI_CLKDIV2_REG_OFS        0x6C
REGDEF_BEGIN(PLL_SPI_CLKDIV2_REG)
REGDEF_BIT(DONTCARE, 32)
REGDEF_END(PLL_SPI_CLKDIV2_REG)

//
//0x300 Extended IPP Clock Divider Register 0
//
#define PLL_EXT_IPP_CLKDIV0_REG_OFS        0x300
REGDEF_BEGIN(PLL_EXT_IPP_CLKDIV0_REG)
REGDEF_BIT(DONTCARE, 32)
REGDEF_END(PLL_EXT_IPP_CLKDIV0_REG)

//
//0x304 Extended IPP Clock Divider Register 1
//
#define PLL_EXT_IPP_CLKDIV1_REG_OFS        0x304
REGDEF_BEGIN(PLL_EXT_IPP_CLKDIV1_REG)
REGDEF_BIT(DONTCARE, 32)
REGDEF_END(PLL_EXT_IPP_CLKDIV1_REG)

//
//0x308 Extended IPP Clock Divider Register 2
//
#define PLL_EXT_IPP_CLKDIV2_REG_OFS        0x308
REGDEF_BEGIN(PLL_EXT_IPP_CLKDIV2_REG)
REGDEF_BIT(DONTCARE, 32)
REGDEF_END(PLL_EXT_IPP_CLKDIV2_REG)

//
//0x30C Extended IPP Clock Divider Register 3
//
#define PLL_EXT_IPP_CLKDIV3_REG_OFS        0x30C
REGDEF_BEGIN(PLL_EXT_IPP_CLKDIV3_REG)
REGDEF_BIT(DONTCARE, 32)
REGDEF_END(PLL_EXT_IPP_CLKDIV3_REG)

//
//0x310 Extended IPP Clock Divider Register 4
//
#define PLL_EXT_IPP_CLKDIV4_REG_OFS        0x310
REGDEF_BEGIN(PLL_EXT_IPP_CLKDIV4_REG)
REGDEF_BIT(DONTCARE, 32)
REGDEF_END(PLL_EXT_IPP_CLKDIV4_REG)

//
//0x314 Extended IPP Clock Divider Register 5
//
#define PLL_EXT_IPP_CLKDIV5_REG_OFS        0x314
REGDEF_BEGIN(PLL_EXT_IPP_CLKDIV5_REG)
REGDEF_BIT(DONTCARE, 32)
REGDEF_END(PLL_EXT_IPP_CLKDIV5_REG)

//
//0x318 Extended IPP Clock Divider Register 6
//
#define PLL_EXT_IPP_CLKDIV6_REG_OFS        0x318
REGDEF_BEGIN(PLL_EXT_IPP_CLKDIV6_REG)
REGDEF_BIT(DONTCARE, 32)
REGDEF_END(PLL_EXT_IPP_CLKDIV6_REG)

//
//0x31C Extended IPP Clock Divider Register 7
//
#define PLL_EXT_IPP_CLKDIV7_REG_OFS        0x31C
REGDEF_BEGIN(PLL_EXT_IPP_CLKDIV7_REG)
REGDEF_BIT(DONTCARE, 32)
REGDEF_END(PLL_EXT_IPP_CLKDIV7_REG)

//
//0x320 Extended Display Clock Divider Register 8
//
#define PLL_EXT_DISP_CLKDIV8_REG_OFS        0x320
REGDEF_BEGIN(PLL_EXT_DISP_CLKDIV8_REG)
REGDEF_BIT(DONTCARE, 32)
REGDEF_END(PLL_EXT_DISP_CLKDIV8_REG)

//
//0x324 Extended PWM Clock Divider Register
//
#define PLL_EXT_PWM_CLKDIV_REG_OFS        0x324
REGDEF_BEGIN(PLL_EXT_PWM_CLKDIV_REG)
REGDEF_BIT(DONTCARE, 32)
REGDEF_END(PLL_EXT_PWM_CLKDIV_REG)

//
//0x70 Clock Enable Register 0
//
#define PLL_CLKEN0_REG_OFS              0x70
REGDEF_BEGIN(PLL_CLKEN0_REG)
REGDEF_BIT(DONTCARE, 32)
REGDEF_END(PLL_CLKEN0_REG)

//
//0x74 Clock Enable Register 1
//
#define PLL_CLKEN1_REG_OFS              0x74
REGDEF_BEGIN(PLL_CLKEN1_REG)
REGDEF_BIT(DONTCARE, 32)
REGDEF_END(PLL_CLKEN1_REG)

//
//0x78 Clock Enable Register 2
//
#define PLL_CLKEN2_REG_OFS              0x78
REGDEF_BEGIN(PLL_CLKEN2_REG)
REGDEF_BIT(DONTCARE, 32)
REGDEF_END(PLL_CLKEN2_REG)

//
//0x7C Clock Enable Register 3
//
#define PLL_CLKEN3_REG_OFS              0x7C
REGDEF_BEGIN(PLL_CLKEN3_REG)
REGDEF_BIT(DONTCARE, 32)
REGDEF_END(PLL_CLKEN3_REG)

//
//0x80 Clock Enable Register 4
//
#define PLL_CLKEN4_REG_OFS              0x80
REGDEF_BEGIN(PLL_CLKEN4_REG)
REGDEF_BIT(DONTCARE, 32)
REGDEF_END(PLL_CLKEN4_REG)

//
//0x84 Clock Enable Register 5
//
#define PLL_CLKEN5_REG_OFS              0x84
REGDEF_BEGIN(PLL_CLKEN5_REG)
REGDEF_BIT(DONTCARE, 32)
REGDEF_END(PLL_CLKEN5_REG)

//
//0x88 Clock Enable Register 6
//
#define PLL_CLKEN6_REG_OFS              0x88
REGDEF_BEGIN(PLL_CLKEN6_REG)
REGDEF_BIT(DONTCARE, 32)
REGDEF_END(PLL_CLKEN6_REG)

//
//0x8C Clock Enable Register 7
//
#define PLL_CLKEN7_REG_OFS              0x8C
REGDEF_BEGIN(PLL_CLKEN7_REG)
REGDEF_BIT(DONTCARE, 32)
REGDEF_END(PLL_CLKEN7_REG)


//
//0x110 RingOSC Clock Control Register
//
#define PLL_RINGOSC_CLK_CTRL_REG_OFS 	0x110
REGDEF_BEGIN(PLL_RINGOSC_CLK_CTRL_REG)
REGDEF_BIT(RO_PHY_CLKSEL, 		2)
REGDEF_BIT(RO_PHY_FREQ_CTL,	 	1)
REGDEF_BIT(, 					1)
REGDEF_BIT(RO_32K_CLKDIV, 	   12)
REGDEF_BIT(RO_32K_DIV_TESTEN, 	1)
REGDEF_BIT(RO_32K_CLKEN, 		1)
REGDEF_BIT(LVD_RO_CLK12M_CLKEN, 1)
REGDEF_BIT(, 					13)
REGDEF_END(PLL_RINGOSC_CLK_CTRL_REG)

//
//0x90 System Reset Register 0
//
#define PLL_SYS_RST0_REG_OFS            0x90
REGDEF_BEGIN(PLL_SYS_RST0_REG)
REGDEF_BIT(DONTCARE, 32)
REGDEF_END(PLL_SYS_RST0_REG)


//
//0x94 System Reset Register 1
//
#define PLL_SYS_RST1_REG_OFS            0x94
REGDEF_BEGIN(PLL_SYS_RST1_REG)
REGDEF_BIT(DONTCARE, 32)
REGDEF_END(PLL_SYS_RST1_REG)

//
//0x98 System Reset Register 2
//
#define PLL_SYS_RST2_REG_OFS            0x98
REGDEF_BEGIN(PLL_SYS_RST2_REG)
REGDEF_BIT(DONTCARE, 32)
REGDEF_END(PLL_SYS_RST2_REG)

//
//0x9C System Reset Register 3
//
#define PLL_SYS_RST3_REG_OFS            0x9C
REGDEF_BEGIN(PLL_SYS_RST3_REG)
REGDEF_BIT(DONTCARE, 32)
REGDEF_END(PLL_SYS_RST3_REG)

//
//0xA0 System Reset Register 4
//
#define PLL_SYS_RST4_REG_OFS            0xA0
REGDEF_BEGIN(PLL_SYS_RST4_REG)
REGDEF_BIT(DONTCARE, 32)
REGDEF_END(PLL_SYS_RST4_REG)

//
//0xA4 System Reset Register 5
//
#define PLL_SYS_RST5_REG_OFS            0xA4
REGDEF_BEGIN(PLL_SYS_RST5_REG)
REGDEF_BIT(DONTCARE, 32)
REGDEF_END(PLL_SYS_RST5_REG)

//
//0xA8 System Reset Register 6
//
#define PLL_SYS_RST6_REG_OFS            0xA8
REGDEF_BEGIN(PLL_SYS_RST6_REG)
REGDEF_BIT(DONTCARE, 32)
REGDEF_END(PLL_SYS_RST6_REG)

//
//0xAC System Reset Register 7
//
#define PLL_SYS_RST7_REG_OFS            0xAC
REGDEF_BEGIN(PLL_SYS_RST7_REG)
REGDEF_BIT(DONTCARE, 32)
REGDEF_END(PLL_SYS_RST7_REG)

//
//0x8C Reserved Register
//

/*
//
//0x90 CPU2 clock enable
//
#define PLL_CPU2_CLKEN_REG_OFS          0x90
REGDEF_BEGIN(PLL_CPU2_CLKEN_REG)
REGDEF_BIT(DONTCARE, 32)
REGDEF_END(PLL_CPU2_CLKEN_REG)

//
//0x94 CPU2 Reset Register
//
#define PLL_CPU2_RST_REG_OFS            0x94
REGDEF_BEGIN(PLL_CPU2_RST_REG_REG)
REGDEF_BIT(DONTCARE, 32)
REGDEF_END(PLL_CPU2_RST_REG_REG)
*/

//
//0x98~0x9C Reserved Register
//

//
//0xA8 Power domain Reset Register
//
//#define PLL_PD_RST_REG_OFS              0xA8
//REGDEF_BEGIN(PLL_PD_RST_REG)
//REGDEF_BIT(DONTCARE, 32)
//REGDEF_END(PLL_PD_RST_REG)


//
//0xB0 Sleep Register
//
#define PLL_SLP_REG_OFS                 0xB0
REGDEF_BEGIN(PLL_SLP_REG)
REGDEF_BIT(SLP_MODE, 2)
REGDEF_BIT(SLP_EN, 1)
REGDEF_BIT(SLP_INT, 1)
REGDEF_BIT(SLP_INTE, 1)
REGDEF_BIT(SLP_SKIP_CPU_SLEEP, 1)
REGDEF_BIT(reserved1, 26)
REGDEF_END(PLL_SLP_REG)

//
//0xA4~0xAC Reserved Registers
//

//
//0xC0 CLK Auto Gating Register 0
//
#define PLL_CLKGATE0_REG_OFS            0xC0
REGDEF_BEGIN(PLL_CLKGATE0_REG)
REGDEF_BIT(DONTCARE, 32)
REGDEF_END(PLL_CLKGATE0_REG)

//
//0xC4 CLK Auto Gating Register 1
//
#define PLL_CLKGATE1_REG_OFS            0xC4
REGDEF_BEGIN(PLL_CLKGATE1_REG)
REGDEF_BIT(DONTCARE, 32)
REGDEF_END(PLL_CLKGATE1_REG)

//
//0xC8 CLK Auto Gating Register 2
//
#define PLL_CLKGATE2_REG_OFS            0xC8
REGDEF_BEGIN(PLL_CLKGATE2_REG)
REGDEF_BIT(DONTCARE, 32)
REGDEF_END(PLL_CLKGATE2_REG)

//
//0xCC Reserved Register
//

//
//0xD0 PCLK Auto Gating Register 0
//
#define PLL_PCLKGATE0_REG_OFS           0xD0
REGDEF_BEGIN(PLL_PCLKGATE0_REG)
REGDEF_BIT(DONTCARE, 32)
REGDEF_END(PLL_PCLKGATE0_REG)

//
//0xD4 PCLK Auto Gating Register 1
//
#define PLL_PCLKGATE1_REG_OFS           0xD4
REGDEF_BEGIN(PLL_PCLKGATE1_REG)
REGDEF_BIT(DONTCARE, 32)
REGDEF_END(PLL_PCLKGATE1_REG)

//
//0xD8 PCLK Auto Gating Register 2
//
#define PLL_PCLKGATE2_REG_OFS           0xD8
REGDEF_BEGIN(PLL_PCLKGATE2_REG)
REGDEF_BIT(DONTCARE, 32)
REGDEF_END(PLL_PCLKGATE2_REG)

//
//0xDC PCLK Auto Gating Register 3
//
#define PLL_PCLKGATE3_REG_OFS           0xDC
REGDEF_BEGIN(PLL_PCLKGATE3_REG)
REGDEF_BIT(DONTCARE, 32)
REGDEF_END(PLL_PCLKGATE3_REG)

//
//0xE0 PCLK Auto Gating Register 4
//
#define PLL_PCLKGATE4_REG_OFS           0xE0
REGDEF_BEGIN(PLL_PCLKGATE4_REG)
REGDEF_BIT(DONTCARE, 32)
REGDEF_END(PLL_PCLKGATE4_REG)


//
//0xE4~0xFC Reserved Register
//

//
//0xE4 CPU2 SRAM ShutDown Register
//
//#define PLL_CPU2_SRAMSD_REG_OFS            0xE4
//REGDEF_BEGIN(PLL_CPU2_SRAMSD_REG_REG)
//REGDEF_BIT(DONTCARE, 32)
//REGDEF_END(PLL_CPU2_SRAMSD_REG_REG)

//
//0x0DC~0xFFC Reserved Register
//

/****************************************************/
#define PLL_PLL00_BASE_REG_OFS        0x4400 //AXI0
#define PLL_PLL02_BASE_REG_OFS        0x4480 //AXI1
#define PLL_PLL03_BASE_REG_OFS        0x44C0 //DRAM
#define PLL_PLL04_BASE_REG_OFS        0x4500 //AHB
#define PLL_PLL05_BASE_REG_OFS        0x4540 //GPU
#define PLL_PLL06_BASE_REG_OFS        0x4580 //SDC
#define PLL_PLL07_BASE_REG_OFS        0x45C0 //MAC
#define PLL_PLL08_BASE_REG_OFS        0x4600 //LCD
#define PLL_PLL09_BASE_REG_OFS        0x4640 //LCD2
#define PLL_PLL10_BASE_REG_OFS        0x4680 //LCD3
#define PLL_PLL11_BASE_REG_OFS        0x46C0 //DSI
#define PLL_PLL12_BASE_REG_OFS        0x4700 //AUDIO
#define PLL_PLL13_BASE_REG_OFS        0x4740 //AXI2
#define PLL_PLL14_BASE_REG_OFS        0x4780 //USB3 phy
#define PLL_PLL15_BASE_REG_OFS        0x47C0 //SIE
#define PLL_PLL16_BASE_REG_OFS        0x4800 //CPU
#define PLL_PLL17_BASE_REG_OFS        0x4840 //SATA phy
#define PLL_PLL18_BASE_REG_OFS        0x4880 //SIE2
#define PLL_PLL19_BASE_REG_OFS        0x48C0 //VIE
#define PLL_PLL20_BASE_REG_OFS        0x4900 //SENSOR MCLK
#define PLL_PLL21_BASE_REG_OFS        0x4940 //DSP
#define PLL_PLL22_BASE_REG_OFS        0x4980 //DSP2
#define PLL_PLL23_BASE_REG_OFS        0x49C0 //SENOR MCLK2
#define PLL_PLL24_BASE_REG_OFS        0x4A00 //PCIE phy
#define PLL_PLL25_BASE_REG_OFS        0x4A40 //SATA phy ssc
#define PLL_PLL26_BASE_REG_OFS        0x4A80 //IPP
#define PLL_PLL27_BASE_REG_OFS        0x4AC0 //DSI2
#define PLL_PLL28_BASE_REG_OFS        0x4B00 //CNN
#define PLL_PLL29_BASE_REG_OFS        0x4B40 //CNN2
#define PLL_PLL30_BASE_REG_OFS        0x4B80 //VENC
#define PLL_PLL31_BASE_REG_OFS        0x4BC0 //VDEC
#define PLL_PLL32_BASE_REG_OFS        0x4C00 //DRAM2


#define PLL_CR0_OFS                      0x20
#define PLL_CR1_OFS                      0x24
#define PLL_CR2_OFS                      0x28


//
//PLL0 (For AXI0) Clock Rate Register 0
//
#define PLL_PLL0_CR0_REG_OFS         (PLL_PLL00_BASE_REG_OFS+PLL_CR0_OFS)
#define PLL_PLL0_CR1_REG_OFS         (PLL_PLL00_BASE_REG_OFS+PLL_CR1_OFS)
#define PLL_PLL0_CR2_REG_OFS         (PLL_PLL00_BASE_REG_OFS+PLL_CR2_OFS)

//
//PLL2 (For AXI1) Clock Rate Register 0
//
#define PLL_PLL2_CR0_REG_OFS         (PLL_PLL02_BASE_REG_OFS+PLL_CR0_OFS)
#define PLL_PLL2_CR1_REG_OFS         (PLL_PLL02_BASE_REG_OFS+PLL_CR1_OFS)
#define PLL_PLL2_CR2_REG_OFS         (PLL_PLL02_BASE_REG_OFS+PLL_CR2_OFS)

//
//PLL3 (For DMA) Clock Rate Register 0
//
#define PLL_PLL3_CR0_REG_OFS         (PLL_PLL03_BASE_REG_OFS+PLL_CR0_OFS)
#define PLL_PLL3_CR1_REG_OFS         (PLL_PLL03_BASE_REG_OFS+PLL_CR1_OFS)
#define PLL_PLL3_CR2_REG_OFS         (PLL_PLL03_BASE_REG_OFS+PLL_CR2_OFS)

//
//PLL4 (For AHB) Clock Rate Register 0
//
#define PLL_PLL4_CR0_REG_OFS         (PLL_PLL04_BASE_REG_OFS+PLL_CR0_OFS)
#define PLL_PLL4_CR1_REG_OFS         (PLL_PLL04_BASE_REG_OFS+PLL_CR1_OFS)
#define PLL_PLL4_CR2_REG_OFS         (PLL_PLL04_BASE_REG_OFS+PLL_CR2_OFS)

//
//PLL5 (For GPU) Clock Rate Register 0
//
#define PLL_PLL5_CR0_REG_OFS         (PLL_PLL05_BASE_REG_OFS+PLL_CR0_OFS)
#define PLL_PLL5_CR1_REG_OFS         (PLL_PLL05_BASE_REG_OFS+PLL_CR1_OFS)
#define PLL_PLL5_CR2_REG_OFS         (PLL_PLL05_BASE_REG_OFS+PLL_CR2_OFS)

//
//PLL6 (For SDC) Clock Rate Register 0
//
#define PLL_PLL6_CR0_REG_OFS         (PLL_PLL06_BASE_REG_OFS+PLL_CR0_OFS)
#define PLL_PLL6_CR1_REG_OFS         (PLL_PLL06_BASE_REG_OFS+PLL_CR1_OFS)
#define PLL_PLL6_CR2_REG_OFS         (PLL_PLL06_BASE_REG_OFS+PLL_CR2_OFS)

//
//PLL7 (For MAC) Clock Rate Register 0
//
#define PLL_PLL7_CR0_REG_OFS         (PLL_PLL07_BASE_REG_OFS+PLL_CR0_OFS)
#define PLL_PLL7_CR1_REG_OFS         (PLL_PLL07_BASE_REG_OFS+PLL_CR1_OFS)
#define PLL_PLL7_CR2_REG_OFS         (PLL_PLL07_BASE_REG_OFS+PLL_CR2_OFS)

//
//PLL8 (For LCD) Clock Rate Register 0
//
#define PLL_PLL8_CR0_REG_OFS         (PLL_PLL08_BASE_REG_OFS+PLL_CR0_OFS)
#define PLL_PLL8_CR1_REG_OFS         (PLL_PLL08_BASE_REG_OFS+PLL_CR1_OFS)
#define PLL_PLL8_CR2_REG_OFS         (PLL_PLL08_BASE_REG_OFS+PLL_CR2_OFS)

//
//PLL9 (For LCD2) Clock Rate Register 0
//
#define PLL_PLL9_CR0_REG_OFS         (PLL_PLL09_BASE_REG_OFS+PLL_CR0_OFS)
#define PLL_PLL9_CR1_REG_OFS         (PLL_PLL09_BASE_REG_OFS+PLL_CR1_OFS)
#define PLL_PLL9_CR2_REG_OFS         (PLL_PLL09_BASE_REG_OFS+PLL_CR2_OFS)

//
//PLL10 (For LCD3) Clock Rate Register 0
//
#define PLL_PLL10_CR0_REG_OFS        (PLL_PLL10_BASE_REG_OFS+PLL_CR0_OFS)
#define PLL_PLL10_CR1_REG_OFS        (PLL_PLL10_BASE_REG_OFS+PLL_CR1_OFS)
#define PLL_PLL10_CR2_REG_OFS        (PLL_PLL10_BASE_REG_OFS+PLL_CR2_OFS)

//
//PLL11 (For DSI) Clock Rate Register 0
//
#define PLL_PLL11_CR0_REG_OFS        (PLL_PLL11_BASE_REG_OFS+PLL_CR0_OFS)
#define PLL_PLL11_CR1_REG_OFS        (PLL_PLL11_BASE_REG_OFS+PLL_CR1_OFS)
#define PLL_PLL11_CR2_REG_OFS        (PLL_PLL11_BASE_REG_OFS+PLL_CR2_OFS)

//
//PLL12 (For AUDIO) Clock Rate Register 0
//
#define PLL_PLL12_CR0_REG_OFS        (PLL_PLL12_BASE_REG_OFS+PLL_CR0_OFS)
#define PLL_PLL12_CR1_REG_OFS        (PLL_PLL12_BASE_REG_OFS+PLL_CR1_OFS)
#define PLL_PLL12_CR2_REG_OFS        (PLL_PLL12_BASE_REG_OFS+PLL_CR2_OFS)

//
//PLL13 (For AXI2) Clock Rate Register 0
//
#define PLL_PLL13_CR0_REG_OFS        (PLL_PLL13_BASE_REG_OFS+PLL_CR0_OFS)
#define PLL_PLL13_CR1_REG_OFS        (PLL_PLL13_BASE_REG_OFS+PLL_CR1_OFS)
#define PLL_PLL13_CR2_REG_OFS        (PLL_PLL13_BASE_REG_OFS+PLL_CR2_OFS)

//
//PLL14 (For USB3 phy) Clock Rate Register 0
//
#define PLL_PLL14_CR0_REG_OFS        (PLL_PLL14_BASE_REG_OFS+PLL_CR0_OFS)
#define PLL_PLL14_CR1_REG_OFS        (PLL_PLL14_BASE_REG_OFS+PLL_CR1_OFS)
#define PLL_PLL14_CR2_REG_OFS        (PLL_PLL14_BASE_REG_OFS+PLL_CR2_OFS)

//
//PLL15 (For SIE) Clock Rate Register 0
//
#define PLL_PLL15_CR0_REG_OFS        (PLL_PLL15_BASE_REG_OFS+PLL_CR0_OFS)
#define PLL_PLL15_CR1_REG_OFS        (PLL_PLL15_BASE_REG_OFS+PLL_CR1_OFS)
#define PLL_PLL15_CR2_REG_OFS        (PLL_PLL15_BASE_REG_OFS+PLL_CR2_OFS)

#define PLL_PLL16_CR0_REG_OFS        (PLL_PLL16_BASE_REG_OFS+PLL_CR0_OFS)
#define PLL_PLL16_CR1_REG_OFS        (PLL_PLL16_BASE_REG_OFS+PLL_CR1_OFS)
#define PLL_PLL16_CR2_REG_OFS        (PLL_PLL16_BASE_REG_OFS+PLL_CR2_OFS)

#define PLL_PLL17_CR0_REG_OFS        (PLL_PLL17_BASE_REG_OFS+PLL_CR0_OFS)
#define PLL_PLL17_CR1_REG_OFS        (PLL_PLL17_BASE_REG_OFS+PLL_CR1_OFS)
#define PLL_PLL17_CR2_REG_OFS        (PLL_PLL17_BASE_REG_OFS+PLL_CR2_OFS)

#define PLL_PLL18_CR0_REG_OFS        (PLL_PLL18_BASE_REG_OFS+PLL_CR0_OFS)
#define PLL_PLL18_CR1_REG_OFS        (PLL_PLL18_BASE_REG_OFS+PLL_CR1_OFS)
#define PLL_PLL18_CR2_REG_OFS        (PLL_PLL18_BASE_REG_OFS+PLL_CR2_OFS)

#define PLL_PLL19_CR0_REG_OFS        (PLL_PLL19_BASE_REG_OFS+PLL_CR0_OFS)
#define PLL_PLL19_CR1_REG_OFS        (PLL_PLL19_BASE_REG_OFS+PLL_CR1_OFS)
#define PLL_PLL19_CR2_REG_OFS        (PLL_PLL19_BASE_REG_OFS+PLL_CR2_OFS)

#define PLL_PLL20_CR0_REG_OFS        (PLL_PLL20_BASE_REG_OFS+PLL_CR0_OFS)
#define PLL_PLL20_CR1_REG_OFS        (PLL_PLL20_BASE_REG_OFS+PLL_CR1_OFS)
#define PLL_PLL20_CR2_REG_OFS        (PLL_PLL20_BASE_REG_OFS+PLL_CR2_OFS)

#define PLL_PLL21_CR0_REG_OFS        (PLL_PLL21_BASE_REG_OFS+PLL_CR0_OFS)
#define PLL_PLL21_CR1_REG_OFS        (PLL_PLL21_BASE_REG_OFS+PLL_CR1_OFS)
#define PLL_PLL21_CR2_REG_OFS        (PLL_PLL21_BASE_REG_OFS+PLL_CR2_OFS)

#define PLL_PLL22_CR0_REG_OFS        (PLL_PLL22_BASE_REG_OFS+PLL_CR0_OFS)
#define PLL_PLL22_CR1_REG_OFS        (PLL_PLL22_BASE_REG_OFS+PLL_CR1_OFS)
#define PLL_PLL22_CR2_REG_OFS        (PLL_PLL22_BASE_REG_OFS+PLL_CR2_OFS)

#define PLL_PLL23_CR0_REG_OFS        (PLL_PLL23_BASE_REG_OFS+PLL_CR0_OFS)
#define PLL_PLL23_CR1_REG_OFS        (PLL_PLL23_BASE_REG_OFS+PLL_CR1_OFS)
#define PLL_PLL23_CR2_REG_OFS        (PLL_PLL23_BASE_REG_OFS+PLL_CR2_OFS)

#define PLL_PLL24_CR0_REG_OFS        (PLL_PLL24_BASE_REG_OFS+PLL_CR0_OFS)
#define PLL_PLL24_CR1_REG_OFS        (PLL_PLL24_BASE_REG_OFS+PLL_CR1_OFS)
#define PLL_PLL24_CR2_REG_OFS        (PLL_PLL24_BASE_REG_OFS+PLL_CR2_OFS)

#define PLL_PLL25_CR0_REG_OFS        (PLL_PLL25_BASE_REG_OFS+PLL_CR0_OFS)
#define PLL_PLL25_CR1_REG_OFS        (PLL_PLL25_BASE_REG_OFS+PLL_CR1_OFS)
#define PLL_PLL25_CR2_REG_OFS        (PLL_PLL25_BASE_REG_OFS+PLL_CR2_OFS)

#define PLL_PLL26_CR0_REG_OFS        (PLL_PLL26_BASE_REG_OFS+PLL_CR0_OFS)
#define PLL_PLL26_CR1_REG_OFS        (PLL_PLL26_BASE_REG_OFS+PLL_CR1_OFS)
#define PLL_PLL26_CR2_REG_OFS        (PLL_PLL26_BASE_REG_OFS+PLL_CR2_OFS)

#define PLL_PLL27_CR0_REG_OFS        (PLL_PLL27_BASE_REG_OFS+PLL_CR0_OFS)
#define PLL_PLL27_CR1_REG_OFS        (PLL_PLL27_BASE_REG_OFS+PLL_CR1_OFS)
#define PLL_PLL27_CR2_REG_OFS        (PLL_PLL27_BASE_REG_OFS+PLL_CR2_OFS)

#define PLL_PLL28_CR0_REG_OFS        (PLL_PLL28_BASE_REG_OFS+PLL_CR0_OFS)
#define PLL_PLL28_CR1_REG_OFS        (PLL_PLL28_BASE_REG_OFS+PLL_CR1_OFS)
#define PLL_PLL28_CR2_REG_OFS        (PLL_PLL28_BASE_REG_OFS+PLL_CR2_OFS)

#define PLL_PLL29_CR0_REG_OFS        (PLL_PLL29_BASE_REG_OFS+PLL_CR0_OFS)
#define PLL_PLL29_CR1_REG_OFS        (PLL_PLL29_BASE_REG_OFS+PLL_CR1_OFS)
#define PLL_PLL29_CR2_REG_OFS        (PLL_PLL29_BASE_REG_OFS+PLL_CR2_OFS)

#define PLL_PLL30_CR0_REG_OFS        (PLL_PLL30_BASE_REG_OFS+PLL_CR0_OFS)
#define PLL_PLL30_CR1_REG_OFS        (PLL_PLL30_BASE_REG_OFS+PLL_CR1_OFS)
#define PLL_PLL30_CR2_REG_OFS        (PLL_PLL30_BASE_REG_OFS+PLL_CR2_OFS)

#define PLL_PLL31_CR0_REG_OFS        (PLL_PLL31_BASE_REG_OFS+PLL_CR0_OFS)
#define PLL_PLL31_CR1_REG_OFS        (PLL_PLL31_BASE_REG_OFS+PLL_CR1_OFS)
#define PLL_PLL31_CR2_REG_OFS        (PLL_PLL31_BASE_REG_OFS+PLL_CR2_OFS)

#define PLL_PLL32_CR0_REG_OFS        (PLL_PLL32_BASE_REG_OFS+PLL_CR0_OFS)
#define PLL_PLL32_CR1_REG_OFS        (PLL_PLL32_BASE_REG_OFS+PLL_CR1_OFS)
#define PLL_PLL32_CR2_REG_OFS        (PLL_PLL32_BASE_REG_OFS+PLL_CR2_OFS)


REGDEF_BEGIN(PLL_PLL2_CR0_REG)
REGDEF_BIT(PLL_RATIO0, 8)
REGDEF_BIT(reserved1, 24)
REGDEF_END(PLL_PLL2_CR0_REG)

REGDEF_BEGIN(PLL_PLL2_CR1_REG)
REGDEF_BIT(PLL_RATIO1, 8)
REGDEF_BIT(reserved1, 24)
REGDEF_END(PLL_PLL2_CR1_REG)

REGDEF_BEGIN(PLL_PLL2_CR2_REG)
REGDEF_BIT(PLL_RATIO2, 8)
REGDEF_BIT(reserved1, 24)
REGDEF_END(PLL_PLL2_CR2_REG)


#define PLL_PLLX_SSPLL0_REG_OFS         0x0C // en,rst,new_mode,step_sel,mmu_syn_ssc,dssc
REGDEF_BEGIN(PLL_PLLX_SSPLL0_REG)
REGDEF_BIT(SSC_EN, 1)                           // 0: disable, 1: enable
REGDEF_BIT(SSC_RST, 1)
REGDEF_BIT(SSC_NEW_MODE, 1)                     // 0: legacy mode, 1: NT96650 new mode
REGDEF_BIT(, 1)
REGDEF_BIT(SSC_STEP_SEL, 2)
REGDEF_BIT(MMU_SYN_SSC, 1)
REGDEF_BIT(DSSC, 1)                             // 0: center spread, 1: down spread
REGDEF_BIT(reserved1, 24)
REGDEF_END(PLL_PLLX_SSPLL0_REG)

#define PLL_PLLX_SSPLL1_REG_OFS          0x10 // mulfac
REGDEF_BEGIN(PLL_PLLX_SSPLL1_REG)
REGDEF_BIT(SSC_MULFAC, 8)
REGDEF_BIT(reserved1, 24)
REGDEF_END(PLL_PLLX_SSPLL1_REG)

#define PLL_PLLX_SSPLL2_REG_OFS          0x14 // period_value
REGDEF_BEGIN(PLL_PLLX_SSPLL2_REG)
REGDEF_BIT(SSC_PERIOD_VALUE, 8)
REGDEF_BIT(reserved1, 24)
REGDEF_END(PLL_PLLX_SSPLL2_REG)

//
//PLL4 (For SSPLL) Spread Spectrum Register 0
//
#define PLL_PLL4_SSPLL0_REG_OFS         0x11C8
REGDEF_BEGIN(PLL_PLL4_SSPLL0_REG)
REGDEF_BIT(SSC_RST, 1)
REGDEF_BIT(SSC_NEW_MODE, 1)                     // 0: legacy mode, 1: NT96650 new mode
REGDEF_BIT(SSC_STEP_SEL, 2)
REGDEF_BIT(, 2)
REGDEF_BIT(DSSC, 1)                             // 0: center spread, 1: down spread
REGDEF_BIT(reserved1, 25)
REGDEF_END(PLL_PLL4_SSPLL0_REG)

//
//PLL4 (For SSPLL) Spread Spectrum Register 1
//
#define PLL_PLL4_SSPLL1_REG_OFS         0x11CC
REGDEF_BEGIN(PLL_PLL4_SSPLL1_REG)
REGDEF_BIT(SSC_EN, 1)                           // 0: disable, 1: enable
REGDEF_BIT(SSC_RATIO, 4)
REGDEF_BIT(SSC_FREQ, 3)
REGDEF_BIT(reserved1, 24)
REGDEF_END(PLL_PLL4_SSPLL1_REG)

//
//PLL4 (For SSPLL) Spread Spectrum Register 2
//
#define PLL_PLL4_SSPLL2_REG_OFS         0x11D0
REGDEF_BEGIN(PLL_PLL4_SSPLL2_REG)
REGDEF_BIT(SSC_MULFAC, 8)
REGDEF_BIT(reserved1, 24)
REGDEF_END(PLL_PLL4_SSPLL2_REG)

//
//PLL4 (For SSPLL) Spread Spectrum Register 3
//
#define PLL_PLL4_SSPLL3_REG_OFS         0x11D4
REGDEF_BEGIN(PLL_PLL4_SSPLL3_REG)
REGDEF_BIT(SSC_PERIOD_VALUE, 8)
REGDEF_BIT(reserved1, 24)
REGDEF_END(PLL_PLL4_SSPLL3_REG)



#endif
