#ifndef __SENPHY_REG_H__
#define __SENPHY_REG_H__

#ifdef __KERNEL__
#include "rcw_macro.h"
#include "kwrap/type.h"
#else

#include "rcw_macro.h"

#endif

// 0x00 SENPHY Control Register 0
REGDEF_OFFSET(SENPHY_CTRL0_REG, 0x00)
REGDEF_BEGIN(SENPHY_CTRL0_REG)
REGDEF_BIT(, 4)
REGDEF_BIT(EN_BIAS, 1)     // Group1: C0~C1, D0~D3
REGDEF_BIT(DLY_EN, 1)
REGDEF_BIT(EN_BIAS2, 1)    // Group2: C2~C3, D4~D7
REGDEF_BIT(DLY_EN2, 1)
REGDEF_BIT(IADJ, 2)
REGDEF_BIT(IADJ2, 2)
REGDEF_BIT(CKINV, 4)       // Clock lane inverse, C0~C3
REGDEF_BIT(LPVSEL, 2)
REGDEF_BIT(LPVSEL2, 2)
REGDEF_BIT(RTERM, 4)
REGDEF_BIT(PHA_CLK_SEL, 2)
REGDEF_BIT(PHA_CLK_SEL2, 2)
REGDEF_BIT(RTERM2, 4)
REGDEF_END(SENPHY_CTRL0_REG)


// 0x04 SENPHY Control Register 1
REGDEF_OFFSET(SENPHY_CTRL1_REG, 0x04)
REGDEF_BEGIN(SENPHY_CTRL1_REG)
REGDEF_BIT(, 32)
REGDEF_END(SENPHY_CTRL1_REG)


// 0x08 SENPHY Control Register 2
REGDEF_OFFSET(SENPHY_CTRL2_REG, 0x08)
REGDEF_BEGIN(SENPHY_CTRL2_REG)
REGDEF_BIT(, 32)
REGDEF_END(SENPHY_CTRL2_REG)


// 0x0C SENPHY Control Register 3
REGDEF_OFFSET(SENPHY_CTRL3_REG, 0x0C)
REGDEF_BEGIN(SENPHY_CTRL3_REG)
REGDEF_BIT(CLKENO_DLY, 8)
REGDEF_BIT(, 8)
REGDEF_BIT(CSI_DDLY_LVDS, 8)
REGDEF_BIT(, 8)
REGDEF_END(SENPHY_CTRL3_REG)


// 0x10 SENPHY Control Register 4
REGDEF_OFFSET(SENPHY_CTRL4_REG, 0x10)
REGDEF_BEGIN(SENPHY_CTRL4_REG)
REGDEF_BIT(D01RST, 1)
REGDEF_BIT(D23RST, 1)
REGDEF_BIT(D45RST, 1)
REGDEF_BIT(D67RST, 1)
REGDEF_BIT(, 28)
REGDEF_END(SENPHY_CTRL4_REG)


// 0x14 SENPHY Control Register 5
REGDEF_OFFSET(SENPHY_CTRL5_REG, 0x14)
REGDEF_BEGIN(SENPHY_CTRL5_REG)
REGDEF_BIT(, 32)
REGDEF_END(SENPHY_CTRL5_REG)


// 0x18 SENPHY Control Register 6
REGDEF_OFFSET(SENPHY_CTRL6_REG, 0x18)
REGDEF_BEGIN(SENPHY_CTRL6_REG)
REGDEF_BIT(CLK0_DLYADJ, 3)
REGDEF_BIT(, 1)
REGDEF_BIT(CLK1_DLYADJ, 3)
REGDEF_BIT(, 1)
REGDEF_BIT(CLK2_DLYADJ, 3)
REGDEF_BIT(, 1)
REGDEF_BIT(CLK3_DLYADJ, 3)
REGDEF_BIT(, 17)
REGDEF_END(SENPHY_CTRL6_REG)


// 0x1C SENPHY Control Register 7
REGDEF_OFFSET(SENPHY_CTRL7_REG, 0x1C)
REGDEF_BEGIN(SENPHY_CTRL7_REG)
REGDEF_BIT(, 32)
REGDEF_END(SENPHY_CTRL7_REG)


// 0x20 SENPHY Control Register 8
REGDEF_OFFSET(SENPHY_CTRL8_REG, 0x20)
REGDEF_BEGIN(SENPHY_CTRL8_REG)
REGDEF_BIT(DAT0_DLYADJ, 3)
REGDEF_BIT(, 1)
REGDEF_BIT(DAT1_DLYADJ, 3)
REGDEF_BIT(, 1)
REGDEF_BIT(DAT2_DLYADJ, 3)
REGDEF_BIT(, 1)
REGDEF_BIT(DAT3_DLYADJ, 3)
REGDEF_BIT(, 1)
REGDEF_BIT(DAT4_DLYADJ, 3)
REGDEF_BIT(, 1)
REGDEF_BIT(DAT5_DLYADJ, 3)
REGDEF_BIT(, 1)
REGDEF_BIT(DAT6_DLYADJ, 3)
REGDEF_BIT(, 1)
REGDEF_BIT(DAT7_DLYADJ, 3)
REGDEF_BIT(, 1)
REGDEF_END(SENPHY_CTRL8_REG)


// 0x24 SENPHY Control Register 9
REGDEF_OFFSET(SENPHY_CTRL9_REG, 0x24)
REGDEF_BEGIN(SENPHY_CTRL9_REG)
REGDEF_BIT(, 32)
REGDEF_END(SENPHY_CTRL9_REG)


// 0x28 SENPHY Control Register 10
REGDEF_OFFSET(SENPHY_CTRL10_REG, 0x28)
REGDEF_BEGIN(SENPHY_CTRL10_REG)
REGDEF_BIT(CLKO0_HS_EDGE, 1)
REGDEF_BIT(CLKO1_HS_EDGE, 1)
REGDEF_BIT(CLKO2_HS_EDGE, 1)
REGDEF_BIT(CLKO3_HS_EDGE, 1)
REGDEF_BIT(, 12)
REGDEF_BIT(DAT0_INV, 1)
REGDEF_BIT(DAT1_INV, 1)
REGDEF_BIT(DAT2_INV, 1)
REGDEF_BIT(DAT3_INV, 1)
REGDEF_BIT(DAT4_INV, 1)
REGDEF_BIT(DAT5_INV, 1)
REGDEF_BIT(DAT6_INV, 1)
REGDEF_BIT(DAT7_INV, 1)
REGDEF_BIT(, 8)
REGDEF_END(SENPHY_CTRL10_REG)


// 0x2C SENPHY Control Mode Register
REGDEF_OFFSET(SENPHY_MODE_REG, 0x2C)
REGDEF_BEGIN(SENPHY_MODE_REG)
REGDEF_BIT(CSI_MODE, 1)
REGDEF_BIT(LVDS_MODE, 1)
REGDEF_BIT(CSI2_MODE, 1)
REGDEF_BIT(LVDS2_MODE, 1)
REGDEF_BIT(CSI3_MODE, 1)
REGDEF_BIT(LVDS3_MODE, 1)
REGDEF_BIT(CSI4_MODE, 1)
REGDEF_BIT(LVDS4_MODE, 1)
REGDEF_BIT(, 24)
REGDEF_END(SENPHY_MODE_REG)


// 0x30 SENPHY HSRX Control Register 0
REGDEF_OFFSET(SENPHY_HSRX0_REG, 0x30)
REGDEF_BEGIN(SENPHY_HSRX0_REG)
REGDEF_BIT(, 8)
REGDEF_BIT(SRRO_C0_D01, 1)
REGDEF_BIT(SRRO_C1_D23, 1)
REGDEF_BIT(SRRO_C2_D45, 1)
REGDEF_BIT(SRRO_C3_D67, 1)
REGDEF_BIT(ISEL_C0_D01, 2)
REGDEF_BIT(, 2)
REGDEF_BIT(ISEL_C1_D23, 2)
REGDEF_BIT(, 2)
REGDEF_BIT(ISEL_C2_D45, 2)
REGDEF_BIT(, 2)
REGDEF_BIT(ISEL_C3_D67, 2)
REGDEF_BIT(, 6)
REGDEF_END(SENPHY_HSRX0_REG)


// 0x34 SENPHY HSRX Control Register 1
REGDEF_OFFSET(SENPHY_HSRX1_REG, 0x34)
REGDEF_BEGIN(SENPHY_HSRX1_REG)
REGDEF_BIT(C0_RS_CTLE, 3)
REGDEF_BIT(, 1)
REGDEF_BIT(C1_RS_CTLE, 3)
REGDEF_BIT(, 1)
REGDEF_BIT(C2_RS_CTLE, 3)
REGDEF_BIT(, 1)
REGDEF_BIT(C3_RS_CTLE, 3)
REGDEF_BIT(, 17)
REGDEF_END(SENPHY_HSRX1_REG)


// 0x38 SENPHY HSRX Control Register 2
REGDEF_OFFSET(SENPHY_HSRX2_REG, 0x38)
REGDEF_BEGIN(SENPHY_HSRX2_REG)
REGDEF_BIT(D0_RS_CTLE, 3)
REGDEF_BIT(, 1)
REGDEF_BIT(D1_RS_CTLE, 3)
REGDEF_BIT(, 1)
REGDEF_BIT(D2_RS_CTLE, 3)
REGDEF_BIT(, 1)
REGDEF_BIT(D3_RS_CTLE, 3)
REGDEF_BIT(, 1)
REGDEF_BIT(D4_RS_CTLE, 3)
REGDEF_BIT(, 1)
REGDEF_BIT(D5_RS_CTLE, 3)
REGDEF_BIT(, 1)
REGDEF_BIT(D6_RS_CTLE, 3)
REGDEF_BIT(, 1)
REGDEF_BIT(D7_RS_CTLE, 3)
REGDEF_BIT(, 1)
REGDEF_END(SENPHY_HSRX2_REG)


// 0x3C SENPHY HSRX Control Register 3
REGDEF_OFFSET(SENPHY_HSRX3_REG, 0x3C)
REGDEF_BEGIN(SENPHY_HSRX3_REG)
REGDEF_BIT(C0_CS_CTLE, 3)
REGDEF_BIT(, 1)
REGDEF_BIT(C1_CS_CTLE, 3)
REGDEF_BIT(, 1)
REGDEF_BIT(C2_CS_CTLE, 3)
REGDEF_BIT(, 1)
REGDEF_BIT(C3_CS_CTLE, 3)
REGDEF_BIT(, 17)
REGDEF_END(SENPHY_HSRX3_REG)

// 0x40 SENPHY HSRX Control Register 4
REGDEF_OFFSET(SENPHY_HSRX4_REG, 0x40)
REGDEF_BEGIN(SENPHY_HSRX4_REG)
REGDEF_BIT(D0_CS_CTLE, 3)
REGDEF_BIT(, 1)
REGDEF_BIT(D1_CS_CTLE, 3)
REGDEF_BIT(, 1)
REGDEF_BIT(D2_CS_CTLE, 3)
REGDEF_BIT(, 1)
REGDEF_BIT(D3_CS_CTLE, 3)
REGDEF_BIT(, 1)
REGDEF_BIT(D4_CS_CTLE, 3)
REGDEF_BIT(, 1)
REGDEF_BIT(D5_CS_CTLE, 3)
REGDEF_BIT(, 1)
REGDEF_BIT(D6_CS_CTLE, 3)
REGDEF_BIT(, 1)
REGDEF_BIT(D7_CS_CTLE, 3)
REGDEF_BIT(, 1)
REGDEF_END(SENPHY_HSRX4_REG)

#if 0 // 538 not support EOC
// 0x80 OFSCAL Control Register 0
REGDEF_OFFSET(SENPHY_OFSCAL0_REG, 0x80)
REGDEF_BEGIN(SENPHY_OFSCAL0_REG)
REGDEF_BIT(RSTN, 1)
REGDEF_BIT(, 31)
REGDEF_END(SENPHY_OFSCAL0_REG)


// 0x84 OFSCAL Control Register 1
REGDEF_OFFSET(SENPHY_OFSCAL1_REG, 0x84)
REGDEF_BEGIN(SENPHY_OFSCAL1_REG)
REGDEF_BIT(OFSCAL_EN, 1)
REGDEF_BIT(OFSCAL_INV, 1)
REGDEF_BIT(OFSCAL_START, 1)
REGDEF_BIT(, 1)
REGDEF_BIT(OFSCAL_ICTRL_SEL, 2)
REGDEF_BIT(, 2)
REGDEF_BIT(OFSCAL_DBG_SEL, 4)
REGDEF_BIT(OFSCAL_DONE, 1)
REGDEF_BIT(, 19)
REGDEF_END(SENPHY_OFSCAL1_REG)


// 0x88 OFSCAL Control Register 2
REGDEF_OFFSET(SENPHY_OFSCAL2_REG, 0x88)
REGDEF_BEGIN(SENPHY_OFSCAL2_REG)
REGDEF_BIT(OFSCAL_DBG, 16)
REGDEF_BIT(, 16)
REGDEF_END(SENPHY_OFSCAL2_REG)


// 0x8C OFSCAL Control Register 3
REGDEF_OFFSET(SENPHY_OFSCAL3_REG, 0x8C)
REGDEF_BEGIN(SENPHY_OFSCAL3_REG)
REGDEF_BIT(EQ_ISEL_G0, 2)
REGDEF_BIT(EQ_ISEL_G1, 2)
REGDEF_BIT(EQ_ISEL_G2, 2)
REGDEF_BIT(EQ_ISEL_G3, 2)
REGDEF_BIT(AI_PRE_AMP_N, 1)
REGDEF_BIT(EQ_ISEL_N, 2)
REGDEF_BIT(, 21)
REGDEF_END(SENPHY_OFSCAL3_REG)


// 0x90 OFSCAL Control Register 4
REGDEF_OFFSET(SENPHY_OFSCAL4_REG, 0x90)
REGDEF_BEGIN(SENPHY_OFSCAL4_REG)
REGDEF_BIT(EQ_CLK_G0, 3)
REGDEF_BIT(, 1)
REGDEF_BIT(EQ_CLK_G1, 3)
REGDEF_BIT(, 1)
REGDEF_BIT(EQ_CLK_G2, 3)
REGDEF_BIT(, 1)
REGDEF_BIT(EQ_CLK_G3, 3)
REGDEF_BIT(, 1)
REGDEF_BIT(EQ_TEST_CLK_N, 3)
REGDEF_BIT(, 13)
REGDEF_END(SENPHY_OFSCAL4_REG)


// 0x94 OFSCAL Control Register 5
REGDEF_OFFSET(SENPHY_OFSCAL5_REG, 0x94)
REGDEF_BEGIN(SENPHY_OFSCAL5_REG)
REGDEF_BIT(EQ_D0_G0, 3)
REGDEF_BIT(, 1)
REGDEF_BIT(EQ_D0_G1, 3)
REGDEF_BIT(, 1)
REGDEF_BIT(EQ_D0_G2, 3)
REGDEF_BIT(, 1)
REGDEF_BIT(EQ_D0_G3, 3)
REGDEF_BIT(, 1)
REGDEF_BIT(EQ_TEST_D0_N, 3)
REGDEF_BIT(, 13)
REGDEF_END(SENPHY_OFSCAL5_REG)


// 0x98 OFSCAL Control Register 6
REGDEF_OFFSET(SENPHY_OFSCAL6_REG, 0x98)
REGDEF_BEGIN(SENPHY_OFSCAL6_REG)
REGDEF_BIT(EQ_D1_G0, 3)
REGDEF_BIT(, 1)
REGDEF_BIT(EQ_D1_G1, 3)
REGDEF_BIT(, 1)
REGDEF_BIT(EQ_D1_G2, 3)
REGDEF_BIT(, 1)
REGDEF_BIT(EQ_D1_G3, 3)
REGDEF_BIT(, 1)
REGDEF_BIT(EQ_TEST_D1_N, 3)
REGDEF_BIT(, 13)
REGDEF_END(SENPHY_OFSCAL6_REG)


// 0x9C OFSCAL Control Register 7
REGDEF_OFFSET(SENPHY_OFSCAL7_REG, 0x9C)
REGDEF_BEGIN(SENPHY_OFSCAL7_REG)
REGDEF_BIT(EQ_D2_G0, 3)
REGDEF_BIT(, 1)
REGDEF_BIT(EQ_D2_G1, 3)
REGDEF_BIT(, 1)
REGDEF_BIT(EQ_D2_G2, 3)
REGDEF_BIT(, 1)
REGDEF_BIT(EQ_D2_G3, 3)
REGDEF_BIT(, 1)
REGDEF_BIT(EQ_TEST_D2_N, 3)
REGDEF_BIT(, 13)
REGDEF_END(SENPHY_OFSCAL7_REG)


// 0xA0 OFSCAL Control Register 8
REGDEF_OFFSET(SENPHY_OFSCAL8_REG, 0xA0)
REGDEF_BEGIN(SENPHY_OFSCAL8_REG)
REGDEF_BIT(EQ_D3_G0, 3)
REGDEF_BIT(, 1)
REGDEF_BIT(EQ_D3_G1, 3)
REGDEF_BIT(, 1)
REGDEF_BIT(EQ_D3_G2, 3)
REGDEF_BIT(, 1)
REGDEF_BIT(EQ_D3_G3, 3)
REGDEF_BIT(, 1)
REGDEF_BIT(EQ_TEST_D3_N, 3)
REGDEF_BIT(, 13)
REGDEF_END(SENPHY_OFSCAL8_REG)


// 0xA4 OFSCAL Control Register 9
REGDEF_OFFSET(SENPHY_OFSCAL9_REG, 0xA4)
REGDEF_BEGIN(SENPHY_OFSCAL9_REG)
REGDEF_BIT(CSI_EQ_TEST_CLK, 3)
REGDEF_BIT(, 1)
REGDEF_BIT(CSI_EQ_TEST_D0, 3)
REGDEF_BIT(, 1)
REGDEF_BIT(CSI_EQ_TEST_D1, 3)
REGDEF_BIT(, 1)
REGDEF_BIT(CSI_EQ_TEST_D2, 3)
REGDEF_BIT(, 1)
REGDEF_BIT(CSI_EQ_TEST_D3, 3)
REGDEF_BIT(, 1)
REGDEF_BIT(CSI_EQ_SW, 1)
REGDEF_BIT(CSI_AI_PRE_AMP, 1)
REGDEF_BIT(CSI_EQ_ISEL, 2)
REGDEF_BIT(OFSCAL_CTL_SEL, 1)
REGDEF_BIT(, 7)
REGDEF_END(SENPHY_OFSCAL9_REG)


// 0xA8 OFSCAL Control Register 10
REGDEF_OFFSET(SENPHY_OFSCAL10_REG, 0xA8)
REGDEF_BEGIN(SENPHY_OFSCAL10_REG)
REGDEF_BIT(CSI_EQ_ICTRL_CLK, 5)
REGDEF_BIT(, 3)
REGDEF_BIT(CSI_EQ_ICTRL_D0, 5)
REGDEF_BIT(, 3)
REGDEF_BIT(CSI_EQ_ICTRL_D1, 5)
REGDEF_BIT(, 3)
REGDEF_BIT(CSI_EQ_ICTRL_D2, 5)
REGDEF_BIT(, 3)
REGDEF_END(SENPHY_OFSCAL10_REG)


// 0xAC OFSCAL Control Register 11
REGDEF_OFFSET(SENPHY_OFSCAL11_REG, 0xAC)
REGDEF_BEGIN(SENPHY_OFSCAL11_REG)
REGDEF_BIT(CSI_EQ_ICTRL_D3, 5)
REGDEF_BIT(, 27)
REGDEF_END(SENPHY_OFSCAL11_REG)
#endif

#endif
