#!/bin/sh
echo "sys2" > /proc/nvt_info/bootts

#KERVER=`cat /proc/version | awk -F'version ' '{print $2}' | awk -F' ' '{print $1}'`
KERVER=5.10.168
if [ ${NVT_CHIP_ID} == "CHIP_NT98539A" ]; then
KO_SUFFIX="_539a"
fi

if [[ -f /lib/modules/$KERVER/hdal/kdrv_builtin$KO_SUFFIX/kdrv_builtin$KO_SUFFIX.ko ]]; then
insmod /lib/modules/$KERVER/vos/kwrap/kwrap.ko
insmod /lib/modules/$KERVER/hdal/kdrv_builtin$KO_SUFFIX/kdrv_builtin$KO_SUFFIX.ko
fi

if [[ -f /lib/modules/$KERVER/hdal/comm/kdrv_comm.ko ]]; then
insmod /lib/modules/$KERVER/kernel/drivers/dma/nvt_hwcpy.ko
insmod /lib/modules/$KERVER/hdal/comm/kdrv_comm.ko log_ksize=2000
echo 0 > /proc/videograph/mode
echo /mnt/sd > /proc/videograph/dumplog
insmod /lib/modules/$KERVER/hdal/kdrv_gfx2d/kdrv_gfx2d.ko
insmod /lib/modules/$KERVER/hdal/kdrv_videocapture/kdrv_videocapture.ko
insmod /lib/modules/$KERVER/hdal/kdrv_videoprocess$KO_SUFFIX/kdrv_videoprocess$KO_SUFFIX.ko
insmod /lib/modules/$KERVER/hdal/kdrv_videoprocess/kdrv_vpe/kdrv_vpe.ko
insmod /lib/modules/$KERVER/hdal/kdrv_videoprocess/kdrv_dre/kdrv_dre.ko
insmod /lib/modules/$KERVER/hdal/kdrv_videocodec/kdrv_h26x.ko
insmod /lib/modules/$KERVER/hdal/kdrv_videojpeg/kdrv_jpg.ko
insmod /lib/modules/$KERVER/hdal/kdrv_audioio/audio_common/nvt_audio.ko
insmod /lib/modules/$KERVER/hdal/kdrv_audioio/kdrv_audio/nvt_kdrv_audio.ko
insmod /lib/modules/$KERVER/hdal/kflow_common/kflow_common.ko
insmod /lib/modules/$KERVER/hdal/kflow_gfx/videosprite/nvt_videosprite.ko
insmod /lib/modules/$KERVER/hdal/kflow_gfx/nvt_gfx.ko
insmod /lib/modules/$KERVER/hdal/kflow_videocapture/kflow_videocapture.ko
insmod /lib/modules/$KERVER/hdal/kflow_videoprocess$KO_SUFFIX/kflow_videoprocess$KO_SUFFIX.ko
insmod /lib/modules/$KERVER/hdal/nvt_vencrc/nvt_vencrc.ko
insmod /lib/modules/$KERVER/hdal/kflow_videoenc/unit/kflow_videoenc.ko
insmod /lib/modules/$KERVER/hdal/kflow_audiocapture/unit/kflow_audiocap.ko
insmod /lib/modules/$KERVER/hdal/kflow_audioout/unit/kflow_audioout.ko
insmod /lib/modules/$KERVER/hdal/isp$KO_SUFFIX/nvt_isp$KO_SUFFIX.ko
insmod /lib/modules/$KERVER/hdal/iq$KO_SUFFIX/nvt_iq$KO_SUFFIX.ko
fi

# 2a
if [[ -f /lib/modules/$KERVER/hdal/awb/nvt_awb.ko ]]; then
insmod /lib/modules/$KERVER/hdal/awb/nvt_awb.ko
insmod /lib/modules/$KERVER/hdal/ae/nvt_ae.ko
fi

# motor & sensor
insmod /lib/modules/$KERVER/hdal/${SENSOR1}/nvt_$SENSOR1.ko sen_cfg_path=/usr/local/etc/${SENSOR1}${SENSOR_CFG_SUFFIX}.cfg
if [ "${SENSOR2}" != "sen_off" ] && [ "${SENSOR2}" != "${SENSOR1}" ]; then
insmod /lib/modules/$KERVER/hdal/${SENSOR2}/nvt_$SENSOR2.ko sen_cfg_path=/usr/local/etc/${SENSOR2}${SENSOR_CFG_SUFFIX}.cfg
fi

if [[ ! -d /sys/firmware/devicetree/base/hd_devnum ]]; then
mknod /dev/nvt_vos c `cat /sys/class/nvt_vos/nvt_vos/dev | sed "s/:/\ /g"`
mknod /dev/log_vg c `cat /sys/class/misc/log_vg/dev | sed "s/:/\ /g"`
mknod /dev/nvtmpp c `cat /sys/class/nvtmpp/nvtmpp/dev | sed "s/:/\ /g"`
mknod /dev/isf_flow0 c `cat /sys/class/isf_flow/isf_flow0/dev | sed "s/:/\ /g"`
mknod /dev/isf_flow1 c `cat /sys/class/isf_flow/isf_flow1/dev | sed "s/:/\ /g"`
mknod /dev/nvt_isp c `cat /sys/class/nvt_isp/nvt_isp/dev | sed "s/:/\ /g"`
mknod /dev/null c 1 3
mknod /dev/mem c `cat /sys/class/mem/mem/dev | sed "s/:/\ /g"`
fi

echo "sys2" > /proc/nvt_info/bootts

[[ ! -z "$NVT_BOOT_APP" ]] && $NVT_BOOT_APP &
