/*
    Digital Audio Interface(DAI) Controller register header

    Header file for DAI module register
    This file is the header file that define register for DAI module

    @file       dai_reg.h
    @ingroup    mIDrvAud_DAI
    @note       Nothing

    Copyright   Novatek Microelectronics Corp. 2021.  All rights reserved.
*/


#ifndef _DAI_REG_H
#define _DAI_REG_H


#include <linux/soc/nvt/rcw_macro.h>

// Control Register
REGDEF_OFFSET(DAI_CTRL_REG, 0x00)
REGDEF_BEGIN(DAI_CTRL_REG)
REGDEF_BIT(DAIEN, 1)
REGDEF_BIT(, 3)
REGDEF_BIT(DMA_TX1_EN, 1)
REGDEF_BIT(DMA_TX2_EN, 1)
REGDEF_BIT(DMA_RX_EN, 1)
REGDEF_BIT(DMA_TXLB_EN, 1)
REGDEF_BIT(, 4)
REGDEF_BIT(TX1_EN, 1)
REGDEF_BIT(TX2_EN, 1)
REGDEF_BIT(RX_EN, 1)
REGDEF_BIT(TXLB_EN, 1)
REGDEF_BIT(, 16)
REGDEF_END(DAI_CTRL_REG)

// Mode Configuration Register 0
REGDEF_OFFSET(DAI_CONFIG_REG, 0x04)
REGDEF_BEGIN(DAI_CONFIG_REG)
REGDEF_BIT(EXCODEC_EN, 1)
REGDEF_BIT(, 6)
REGDEF_BIT(RX_SRC_MUX_SEL, 1)
REGDEF_BIT(TX_MUX_SEL, 1)
REGDEF_BIT(TX_MIXER, 1)
REGDEF_BIT(, 2)
REGDEF_BIT(HDMI_CH_SEL, 4)
REGDEF_BIT(, 4)
REGDEF_BIT(AVSYNC, 1)
REGDEF_BIT(TXLB_SYNC, 1)
REGDEF_BIT(, 2)
REGDEF_BIT(AVSYNC_SRC, 4)
REGDEF_BIT(DMA_MODE_SEL, 1)
REGDEF_BIT(DMA_STADR2_EN, 1)
REGDEF_BIT(, 2)
REGDEF_END(DAI_CONFIG_REG)

// I2S Mode Configuration Register
REGDEF_OFFSET(DAI_I2SCONFIG_REG, 0x08)
REGDEF_BEGIN(DAI_I2SCONFIG_REG)
REGDEF_BIT(SLAVE, 1)
REGDEF_BIT(I2S_CLK_DET_STS, 1)
REGDEF_BIT(, 2)
REGDEF_BIT(CKRATIO, 3)
REGDEF_BIT(, 1)
REGDEF_BIT(CHANNEL_LEN, 1)
REGDEF_BIT(, 3)
REGDEF_BIT(I2SCKR_MATCH, 1)
REGDEF_BIT(, 3)
REGDEF_BIT(I2SCKR_CUR, 3)
REGDEF_BIT(, 1)
REGDEF_BIT(I2S_ASFCK_OFS, 9)
REGDEF_BIT(, 2)
REGDEF_BIT(I2S_BCLK_PAD_SEL, 1)
REGDEF_END(DAI_I2SCONFIG_REG)


// Format Configuration Register 0
REGDEF_OFFSET(DAI_FMTCFG0_REG, 0x10)
REGDEF_BEGIN(DAI_FMTCFG0_REG)
REGDEF_BIT(TX1_SOUNDM, 2)
REGDEF_BIT(, 2)
REGDEF_BIT(TX1_SOUNDCH, 4)
REGDEF_BIT(TX1_PCMLEN, 2)
REGDEF_BIT(, 1)
REGDEF_BIT(TX1_DRAMCH, 1)
REGDEF_BIT(, 4)
REGDEF_BIT(TX2_SOUNDM, 2)
REGDEF_BIT(, 2)
REGDEF_BIT(TX2_SOUNDCH, 4)
REGDEF_BIT(TX2_PCMLEN, 2)
REGDEF_BIT(, 1)
REGDEF_BIT(TX2_DRAMCH, 1)
REGDEF_BIT(, 4)
REGDEF_END(DAI_FMTCFG0_REG)

// Format Configuration Register 1
REGDEF_OFFSET(DAI_FMTCFG1_REG, 0x14)
REGDEF_BEGIN(DAI_FMTCFG1_REG)
REGDEF_BIT(RX_SOUNDM, 2)
REGDEF_BIT(, 2)
REGDEF_BIT(RX_SOUNDCH, 4)
REGDEF_BIT(RX_PCMLEN, 2)
REGDEF_BIT(, 1)
REGDEF_BIT(RX_DRAMCH, 1)
REGDEF_BIT(, 20)
REGDEF_END(DAI_FMTCFG1_REG)

// Format Configuration Register 2
REGDEF_OFFSET(DAI_FMTCFG2_REG, 0x18)
REGDEF_BEGIN(DAI_FMTCFG2_REG)
REGDEF_BIT(TXLB_SOUNDM, 2)
REGDEF_BIT(, 2)
REGDEF_BIT(TXLB_SOUNDCH, 4)
REGDEF_BIT(TXLB_PCMLEN, 2)
REGDEF_BIT(, 1)
REGDEF_BIT(TXLB_DRAMCH, 1)
REGDEF_BIT(, 20)
REGDEF_END(DAI_FMTCFG2_REG)


// Interrupt enable Register
REGDEF_OFFSET(DAI_INTEN_REG, 0x20)
REGDEF_BEGIN(DAI_INTEN_REG)
REGDEF_BIT(TX1_DMABFI_INTEN, 1)
REGDEF_BIT(TX2_DMABFI_INTEN, 1)
REGDEF_BIT(RX1_DMABFI_INTEN, 1)
REGDEF_BIT(RX2_DMABFI_INTEN, 1)
REGDEF_BIT(TX1_DMALOAD_INTEN, 1)
REGDEF_BIT(TX2_DMALOAD_INTEN, 1)
REGDEF_BIT(RX_DMALOAD_INTEN, 1)
REGDEF_BIT(, 1)
REGDEF_BIT(TX1_STOP_INTEN, 1)
REGDEF_BIT(TX2_STOP_INTEN, 1)
REGDEF_BIT(RX_STOP_INTEN, 1)
REGDEF_BIT(, 1)
REGDEF_BIT(TX1_BWERR_INTEN, 1)
REGDEF_BIT(TX2_BWERR_INTEN, 1)
REGDEF_BIT(RX1_BWERR_INTEN, 1)
REGDEF_BIT(RX2_BWERR_INTEN, 1)
REGDEF_BIT(TX1_TCI_INTEN, 1)
REGDEF_BIT(, 1)
REGDEF_BIT(RX_TCI_INTEN, 1)
REGDEF_BIT(, 1)
REGDEF_BIT(RX_TCLATI_INTEN, 1)
REGDEF_BIT(, 7)
REGDEF_BIT(I2S_CLK_CHG_INTEN , 1)
REGDEF_BIT(, 3)
REGDEF_END(DAI_INTEN_REG)

// Interrupt enable Register
REGDEF_OFFSET(DAI_INTEN2_REG, 0x24)
REGDEF_BEGIN(DAI_INTEN2_REG)
REGDEF_BIT(TXLB_DMABFI_INTEN, 1)
REGDEF_BIT(, 3)
REGDEF_BIT(TXLB_DMALOAD_INTEN, 1)
REGDEF_BIT(, 3)
REGDEF_BIT(TXLB_STOP_INTEN, 1)
REGDEF_BIT(, 3)
REGDEF_BIT(TXLB_BWERR_INTEN, 1)
REGDEF_BIT(, 19)
REGDEF_END(DAI_INTEN2_REG)

// Interrupt status Register
REGDEF_OFFSET(DAI_INTSTATUS_REG, 0x28)
REGDEF_BEGIN(DAI_INTSTATUS_REG)
REGDEF_BIT(TX1_DMABFI, 1)
REGDEF_BIT(TX2_DMABFI, 1)
REGDEF_BIT(RX1_DMABFI, 1)
REGDEF_BIT(RX2_DMABFI, 1)
REGDEF_BIT(TX1_DMALOAD, 1)
REGDEF_BIT(TX2_DMALOAD, 1)
REGDEF_BIT(RX_DMALOAD, 1)
REGDEF_BIT(, 1)
REGDEF_BIT(TX1_STOP, 1)
REGDEF_BIT(TX2_STOP, 1)
REGDEF_BIT(RX_STOP, 1)
REGDEF_BIT(, 1)
REGDEF_BIT(TX1_BWERR, 1)
REGDEF_BIT(TX2_BWERR, 1)
REGDEF_BIT(RX1_BWERR, 1)
REGDEF_BIT(RX2_BWERR, 1)
REGDEF_BIT(TX1_TCI, 1)
REGDEF_BIT(, 1)
REGDEF_BIT(RX_TCI, 1)
REGDEF_BIT(, 1)
REGDEF_BIT(RX_TCLATI, 1)
REGDEF_BIT(, 7)
REGDEF_BIT(I2S_CLK_CHG_STS, 1)
REGDEF_BIT(, 3)
REGDEF_END(DAI_INTSTATUS_REG)

// Interrupt status Register 2
REGDEF_OFFSET(DAI_INTSTATUS2_REG, 0x2C)
REGDEF_BEGIN(DAI_INTSTATUS2_REG)
REGDEF_BIT(TXLB_DMABFI, 1)
REGDEF_BIT(, 3)
REGDEF_BIT(TXLB_DMALOAD, 1)
REGDEF_BIT(, 3)
REGDEF_BIT(TXLB_STOP, 1)
REGDEF_BIT(, 3)
REGDEF_BIT(TXLB_BWERR, 1)
REGDEF_BIT(, 19)
REGDEF_END(DAI_INTSTATUS2_REG)

// Interrupt enable Register 3
REGDEF_OFFSET(DAI_INTEN3_REG, 0x30)
REGDEF_BEGIN(DAI_INTEN3_REG)
REGDEF_BIT(TRX20CH_DMABFI_INTEN, 20)
REGDEF_BIT(, 12)
REGDEF_END(DAI_INTEN3_REG)

// Interrupt enable Register 4
REGDEF_OFFSET(DAI_INTEN4_REG, 0x34)
REGDEF_BEGIN(DAI_INTEN4_REG)
REGDEF_BIT(TRX20CH_DMALOAD_INTEN, 20)
REGDEF_BIT(, 12)
REGDEF_END(DAI_INTEN4_REG)

// Interrupt enable Register 5
REGDEF_OFFSET(DAI_INTEN5_REG, 0x38)
REGDEF_BEGIN(DAI_INTEN5_REG)
REGDEF_BIT(TRX20CH_BWERR_INTEN, 20)
REGDEF_BIT(, 12)
REGDEF_END(DAI_INTEN5_REG)


// I2S DMA CURADR_SAME_REGISTER
REGDEF_OFFSET(DAI_DMA_CURADR_SAM_REG, 0x44)
REGDEF_BEGIN(DAI_DMA_CURADR_SAM_REG)
REGDEF_BIT(TX1_CUADR_SAME, 1)
REGDEF_BIT(TX2_CUADR_SAME, 1)
REGDEF_BIT(RX1_CUADR_SAME, 1)
REGDEF_BIT(RX2_CUADR_SAME, 1)
REGDEF_BIT(TXLB_CUADR_SAME, 1)
REGDEF_BIT(, 27)
REGDEF_END(DAI_DMA_CURADR_SAM_REG)

// I2S DMA CURADR_SAME2_REGISTER
REGDEF_OFFSET(DAI_DMA_CURADR_SAM2_REG, 0x48)
REGDEF_BEGIN(DAI_DMA_CURADR_SAM2_REG)
REGDEF_BIT(TRX20CH_CUADR_SAME, 21)
REGDEF_BIT(, 11)
REGDEF_END(DAI_DMA_CURADR_SAM2_REG)

// TX1 Time code offset value Register
REGDEF_OFFSET(DAI_TX1TCOFFSET_REG, 0xA0)
REGDEF_BEGIN(DAI_TX1TCOFFSET_REG)
REGDEF_BIT(TX1TCOFST, 32)
REGDEF_END(DAI_TX1TCOFFSET_REG)

// TX1 Time code interrupt trigger value Register
REGDEF_OFFSET(DAI_TX1TCTRIGGER_REG, 0xA4)
REGDEF_BEGIN(DAI_TX1TCTRIGGER_REG)
REGDEF_BIT(TX1TCITV, 32)
REGDEF_END(DAI_TX1TCTRIGGER_REG)

// TX1 Time code value Register
REGDEF_OFFSET(DAI_TX1TCVALUE_REG, 0xA8)
REGDEF_BEGIN(DAI_TX1TCVALUE_REG)
REGDEF_BIT(TX1TCV, 32)
REGDEF_END(DAI_TX1TCVALUE_REG)

// RX Time code offset value Register
REGDEF_OFFSET(DAI_RXTCOFFSET_REG, 0xB0)
REGDEF_BEGIN(DAI_RXTCOFFSET_REG)
REGDEF_BIT(RXTCOFST, 32)
REGDEF_END(DAI_RXTCOFFSET_REG)

// RX Time code interrupt trigger value Register
REGDEF_OFFSET(DAI_RXTCTRIGGER_REG, 0xB4)
REGDEF_BEGIN(DAI_RXTCTRIGGER_REG)
REGDEF_BIT(RXTCITV, 32)
REGDEF_END(DAI_RXTCTRIGGER_REG)

// RX Time code value Register
REGDEF_OFFSET(DAI_RXTCVALUE_REG, 0xB8)
REGDEF_BEGIN(DAI_RXTCVALUE_REG)
REGDEF_BIT(RXTCV, 32)
REGDEF_END(DAI_RXTCVALUE_REG)

// Interrupt status Register 3
REGDEF_OFFSET(DAI_INTSTATUS3_REG, 0xC0)
REGDEF_BEGIN(DAI_INTSTATUS3_REG)
REGDEF_BIT(TRX20CH_DMABFI_STATUS, 20)
REGDEF_BIT(, 12)
REGDEF_END(DAI_INTSTATUS3_REG)

// Interrupt status Register 4
REGDEF_OFFSET(DAI_INTSTATUS4_REG, 0xC4)
REGDEF_BEGIN(DAI_INTSTATUS4_REG)
REGDEF_BIT(TRX20CH_DMALOAD_STATUS, 20)
REGDEF_BIT(, 12)
REGDEF_END(DAI_INTSTATUS4_REG)

// Interrupt status Register 5
REGDEF_OFFSET(DAI_INTSTATUS5_REG, 0xC8)
REGDEF_BEGIN(DAI_INTSTATUS5_REG)
REGDEF_BIT(TRX20CH_DMABWERR_STATUS, 20)
REGDEF_BIT(, 12)
REGDEF_END(DAI_INTSTATUS5_REG)

// only for dai3
//
// Debug Mode Config Register
//
////#define DAI_DBG_CONFIG_REG_OFS          0xF0
REGDEF_OFFSET(DAI_DBG_CONFIG_REG, 0xF0)
REGDEF_BEGIN(DAI_DBG_CONFIG_REG)
REGDEF_BIT(DBGEN, 1)
REGDEF_BIT(, 3)
REGDEF_BIT(EAC_DBG_EN, 1)
REGDEF_BIT(EAC_DBG_MODE, 1)
REGDEF_BIT(rsv, 26)
REGDEF_END(DAI_DBG_CONFIG_REG)

// Debug Mode Start Address Register
////#define DAI_DBG_ADDR_REG_OFS            0xF4
REGDEF_OFFSET(DAI_DBG_ADDR_REG, 0xF4)
REGDEF_BEGIN(DAI_DBG_ADDR_REG)
REGDEF_BIT(DMASTADR, 31)
REGDEF_BIT(, 1)
REGDEF_END(DAI_DBG_ADDR_REG)

// Debug Mode Buf Size Register
////#define DAI_DBG_SIZE_REG_OFS            0xF8
REGDEF_OFFSET(DAI_DBG_SIZE_REG, 0xF8)
REGDEF_BEGIN(DAI_DBG_SIZE_REG)
REGDEF_BIT(DMABUFSZ, 19)
REGDEF_BIT(, 13)
REGDEF_END(DAI_DBG_SIZE_REG)

// Debug Mode Status Register
////#define DAI_DBG_STS_REG_OFS            0xFC
REGDEF_OFFSET(DAI_DBG_STS_REG, 0xFC)
REGDEF_BEGIN(DAI_DBG_STS_REG)
REGDEF_BIT(DONE, 1)
REGDEF_BIT(, 31)
REGDEF_END(DAI_DBG_STS_REG)



// I2S TDM Data Order Register
REGDEF_OFFSET(DAI_I2S_TDM_ORDER_REG, 0xD0)
REGDEF_BEGIN(DAI_I2S_TDM_ORDER_REG)
REGDEF_BIT(I2S_TDM_ORDER_POS0, 8)
REGDEF_BIT(I2S_TDM_ORDER_POS1, 8)
REGDEF_BIT(I2S_TDM_ORDER_POS2, 8)
REGDEF_BIT(I2S_TDM_ORDER_POS3, 8)
REGDEF_END(DAI_I2S_TDM_ORDER_REG)

// I2S TDM Data Order Register 2
REGDEF_OFFSET(DAI_I2S_TDM_ORDER2_REG, 0xD4)
REGDEF_BEGIN(DAI_I2S_TDM_ORDER2_REG)
REGDEF_BIT(I2S_TDM_ORDER_POS4, 8)
REGDEF_BIT(I2S_TDM_ORDER_POS5, 8)
REGDEF_BIT(I2S_TDM_ORDER_POS6, 8)
REGDEF_BIT(I2S_TDM_ORDER_POS7, 8)
REGDEF_END(DAI_I2S_TDM_ORDER2_REG)

// I2S TDM Data Order Register 3
REGDEF_OFFSET(DAI_I2S_TDM_ORDER3_REG, 0xD8)
REGDEF_BEGIN(DAI_I2S_TDM_ORDER3_REG)
REGDEF_BIT(I2S_TDM_ORDER_POS8 , 8)
REGDEF_BIT(I2S_TDM_ORDER_POS9 , 8)
REGDEF_BIT(I2S_TDM_ORDER_POS10, 8)
REGDEF_BIT(I2S_TDM_ORDER_POS11, 8)
REGDEF_END(DAI_I2S_TDM_ORDER3_REG)

// I2S TDM Data Order Register 4
REGDEF_OFFSET(DAI_I2S_TDM_ORDER4_REG, 0xDC)
REGDEF_BEGIN(DAI_I2S_TDM_ORDER4_REG)
REGDEF_BIT(I2S_TDM_ORDER_POS12, 8)
REGDEF_BIT(I2S_TDM_ORDER_POS13, 8)
REGDEF_BIT(I2S_TDM_ORDER_POS14, 8)
REGDEF_BIT(I2S_TDM_ORDER_POS15, 8)
REGDEF_END(DAI_I2S_TDM_ORDER4_REG)

// I2S TDM Data Order Register 5
REGDEF_OFFSET(DAI_I2S_TDM_ORDER5_REG, 0xE0)
REGDEF_BEGIN(DAI_I2S_TDM_ORDER5_REG)
REGDEF_BIT(I2S_TDM_ORDER_POS16, 8)
REGDEF_BIT(I2S_TDM_ORDER_POS17, 8)
REGDEF_BIT(I2S_TDM_ORDER_POS18, 8)
REGDEF_BIT(I2S_TDM_ORDER_POS19, 8)
REGDEF_END(DAI_I2S_TDM_ORDER5_REG)

// TX1 DMA starting address Register
REGDEF_OFFSET(DAI_TX1DMASTART_REG, 0x100)
REGDEF_BEGIN(DAI_TX1DMASTART_REG)
REGDEF_BIT(TX1DMASTADR, 32)
REGDEF_END(DAI_TX1DMASTART_REG)

// TX1 DMA starting address Register MSB
REGDEF_OFFSET(DAI_TX1DMASTARTMSB_REG, 0x104)
REGDEF_BEGIN(DAI_TX1DMASTARTMSB_REG)
REGDEF_BIT(TX1DMASTADRMSB, 4)
REGDEF_BIT(, 28)
REGDEF_END(DAI_TX1DMASTARTMSB_REG)

// TX1 DMA RAM current address Register
REGDEF_OFFSET(DAI_TX1DMACURRENT_REG, 0x108)
REGDEF_BEGIN(DAI_TX1DMACURRENT_REG)
REGDEF_BIT(TX1DMACUADR, 32)
REGDEF_END(DAI_TX1DMACURRENT_REG)

// TX1 DMA current address Register MSB
REGDEF_OFFSET(DAI_TX1DMACURRENTMSB_REG, 0x10C)
REGDEF_BEGIN(DAI_TX1DMACURRENTMSB_REG)
REGDEF_BIT(TX1DMACURRENTMSB, 4)
REGDEF_BIT(, 28)
REGDEF_END(DAI_TX1DMACURRENTMSB_REG)

// TX1 DMA RAM buffer size Register
REGDEF_OFFSET(DAI_TX1DMABUFSIZE_REG, 0x110)
REGDEF_BEGIN(DAI_TX1DMABUFSIZE_REG)
REGDEF_BIT(TX1DMABUFSZ, 19)
REGDEF_BIT(, 13)
REGDEF_END(DAI_TX1DMABUFSIZE_REG)

// TX2 DMA starting address Register
REGDEF_OFFSET(DAI_TX2DMASTART_REG, 0x120)
REGDEF_BEGIN(DAI_TX2DMASTART_REG)
REGDEF_BIT(TX2DMASTADR, 32)
REGDEF_END(DAI_TX2DMASTART_REG)

// TX2 DMA starting address Register MSB
REGDEF_OFFSET(DAI_TX2DMASTARTMSB_REG, 0x124)
REGDEF_BEGIN(DAI_TX2DMASTARTMSB_REG)
REGDEF_BIT(TX2DMASTADRMSB, 4)
REGDEF_BIT(, 28)
REGDEF_END(DAI_TX2DMASTARTMSB_REG)


// TX2 DMA RAM current address Register
REGDEF_OFFSET(DAI_TX2DMACURRENT_REG, 0x128)
REGDEF_BEGIN(DAI_TX2DMACURRENT_REG)
REGDEF_BIT(TX2DMACUADR, 32)
REGDEF_END(DAI_TX2DMACURRENT_REG)

// TX2 DMA current address Register MSB
REGDEF_OFFSET(DAI_TX2DMACURRENTMSB_REG, 0x12C)
REGDEF_BEGIN(DAI_TX2DMACURRENTMSB_REG)
REGDEF_BIT(TX2DMACURRENTMSB, 4)
REGDEF_BIT(, 28)
REGDEF_END(DAI_TX2DMACURRENTMSB_REG)

// TX2 DMA RAM buffer size Register
REGDEF_OFFSET(DAI_TX2DMABUFSIZE_REG, 0x130)
REGDEF_BEGIN(DAI_TX2DMABUFSIZE_REG)
REGDEF_BIT(TX2DMABUFSZ, 19)
REGDEF_BIT(, 13)
REGDEF_END(DAI_TX2DMABUFSIZE_REG)


// RX1 DMA starting address Register
REGDEF_OFFSET(DAI_1CHRX1DMASTART_REG, 0x140)
REGDEF_BEGIN(DAI_1CHRX1DMASTART_REG)
REGDEF_BIT(RX1DMASTADR, 32)
REGDEF_END(DAI_1CHRX1DMASTART_REG)

// RX1 DMA starting address Register MSB
REGDEF_OFFSET(DAI_1CHRX1DMASTARTMSB_REG, 0x144)
REGDEF_BEGIN(DAI_1CHRX1DMASTARTMSB_REG)
REGDEF_BIT(RX1DMASTADRMSB, 4)
REGDEF_BIT(, 28)
REGDEF_END(DAI_1CHRX1DMASTARTMSB_REG)

// RX1 DMA RAM current address Register
REGDEF_OFFSET(DAI_RX1DMACURRENT_REG, 0x148)
REGDEF_BEGIN(DAI_RX1DMACURRENT_REG)
REGDEF_BIT(RX1DMACUADR, 32)
REGDEF_END(DAI_RX1DMACURRENT_REG)

// RX1 DMA current address Register MSB
REGDEF_OFFSET(DAI_1CHRX1DMACURRENTMSB_REG, 0x14C)
REGDEF_BEGIN(DAI_1CHRX1DMACURRENTMSB_REG)
REGDEF_BIT(RX1DMACURRENTMSB, 4)
REGDEF_BIT(, 28)
REGDEF_END(DAI_1CHRX1DMACURRENTMSB_REG)

// RX1 DMA RAM buffer size Register
REGDEF_OFFSET(DAI_1CHRX1DMABUFSIZE_REG, 0x150)////DAI_1CHRX1DMABUFSIZE_REG
REGDEF_BEGIN(DAI_1CHRX1DMABUFSIZE_REG)
REGDEF_BIT(RX1DMABUFSZ, 19)
REGDEF_BIT(, 13)
REGDEF_END(DAI_1CHRX1DMABUFSIZE_REG)


// RX2 DMA starting address Register
REGDEF_OFFSET(DAI_1CHRX2DMASTART_REG, 0x160)
REGDEF_BEGIN(DAI_1CHRX2DMASTART_REG)
REGDEF_BIT(RX2DMASTADR, 32)
REGDEF_END(DAI_1CHRX2DMASTART_REG)

// RX2 DMA starting address Register MSB
REGDEF_OFFSET(DAI_1CHRX2DMASTARTMSB_REG, 0x164)
REGDEF_BEGIN(DAI_1CHRX2DMASTARTMSB_REG)
REGDEF_BIT(RX2DMASTADRMSB, 4)
REGDEF_BIT(, 28)
REGDEF_END(DAI_1CHRX2DMASTARTMSB_REG)


// RX2 DMA RAM current address Register
REGDEF_OFFSET(DAI_RX2DMACURRENT_REG, 0x168)
REGDEF_BEGIN(DAI_RX2DMACURRENT_REG)
REGDEF_BIT(RX2DMACUADR, 32)
REGDEF_END(DAI_RX2DMACURRENT_REG)

// RX2 DMA starting address Register MSB
REGDEF_OFFSET(DAI_CHRX2DMACURRENTMSB_REG, 0x16C)
REGDEF_BEGIN(DAI_CHRX2DMACURRENTMSB_REG)
REGDEF_BIT(RX2DMASTADRMSB, 4)
REGDEF_BIT(, 28)
REGDEF_END(DAI_CHRX2DMACURRENTMSB_REG)

// RX2 DMA RAM buffer size Register
REGDEF_OFFSET(DAI_1CHRX2DMABUFSIZE_REG, 0x170)
REGDEF_BEGIN(DAI_1CHRX2DMABUFSIZE_REG)
REGDEF_BIT(RX2DMABUFSZ, 19)
REGDEF_BIT(, 13)
REGDEF_END(DAI_1CHRX2DMABUFSIZE_REG)

// TXLB DMA starting address Register
REGDEF_OFFSET(DAI_TXLBDMASTART_REG, 0x180)
REGDEF_BEGIN(DAI_TXLBDMASTART_REG)
REGDEF_BIT(TXLBDMASTADR, 32)
REGDEF_END(DAI_TXLBDMASTART_REG)

// TXLB DMA starting address Register MSB
REGDEF_OFFSET(DAI_TXLBDMASTARTMSB_REG, 0x184)//0x50
REGDEF_BEGIN(DAI_TXLBDMASTARTMSB_REG)
REGDEF_BIT(TXLBDMASTADRMSB, 4)
REGDEF_BIT(, 28)
REGDEF_END(DAI_TXLBDMASTARTMSB_REG)


// TXLB DMA RAM current address Register
REGDEF_OFFSET(DAI_TXLBDMACURRENT_REG, 0x188)
REGDEF_BEGIN(DAI_TXLBDMACURRENT_REG)
REGDEF_BIT(TXLBDMACUADR, 32)
REGDEF_END(DAI_TXLBDMACURRENT_REG)

// RX2 DMA starting address Register MSB
REGDEF_OFFSET(DAI_TXLBDMACURRENTMSB_REG, 0x18C)
REGDEF_BEGIN(DAI_TXLBDMACURRENTMSB_REG)
REGDEF_BIT(RX2DMASTADRMSB, 4)
REGDEF_BIT(, 28)
REGDEF_END(DAI_TXLBDMACURRENTMSB_REG)

// TXLB DMA RAM buffer size Register
REGDEF_OFFSET(DAI_TXLBDMABUFSIZE_REG, 0x190)
REGDEF_BEGIN(DAI_TXLBDMABUFSIZE_REG)
REGDEF_BIT(TXLBDMABUFSZ, 19)
REGDEF_BIT(, 13)
REGDEF_END(DAI_TXLBDMABUFSIZE_REG)

#if 1 // 20ch dma Rx

// RX1 DMA starting address Register
REGDEF_OFFSET(DAI_RX1DMASTART_REG, 0x200)
REGDEF_BEGIN(DAI_RX1DMASTART_REG)
REGDEF_BIT(RX1DMASTADR, 32)
REGDEF_END(DAI_RX1DMASTART_REG)

// RX2 DMA starting address Register
REGDEF_OFFSET(DAI_RX2DMASTART_REG, 0x220)
REGDEF_BEGIN(DAI_RX2DMASTART_REG)
REGDEF_BIT(RX2DMASTADR, 32)
REGDEF_END(DAI_RX2DMASTART_REG)

// RX3 DMA starting address Register
REGDEF_OFFSET(DAI_RX3DMASTART_REG, 0x240)
REGDEF_BEGIN(DAI_RX3DMASTART_REG)
REGDEF_BIT(RX3DMASTADR, 32)
REGDEF_END(DAI_RX3DMASTART_REG)

// RX4 DMA starting address Register
REGDEF_OFFSET(DAI_RX4DMASTART_REG, 0x260)
REGDEF_BEGIN(DAI_RX4DMASTART_REG)
REGDEF_BIT(RX4DMASTADR, 32)
REGDEF_END(DAI_RX4DMASTART_REG)

// RX5 DMA starting address Register
REGDEF_OFFSET(DAI_RX5DMASTART_REG, 0x280)
REGDEF_BEGIN(DAI_RX5DMASTART_REG)
REGDEF_BIT(RX5DMASTADR, 32)
REGDEF_END(DAI_RX5DMASTART_REG)

// RX6 DMA starting address Register
REGDEF_OFFSET(DAI_RX6DMASTART_REG, 0x2A0)
REGDEF_BEGIN(DAI_RX6DMASTART_REG)
REGDEF_BIT(RX6DMASTADR, 32)
REGDEF_END(DAI_RX6DMASTART_REG)

// RX7 DMA starting address Register
REGDEF_OFFSET(DAI_RX7DMASTART_REG, 0x2C0)
REGDEF_BEGIN(DAI_RX7DMASTART_REG)
REGDEF_BIT(RX7DMASTADR, 32)
REGDEF_END(DAI_RX7DMASTART_REG)

// RX8 DMA starting address Register
REGDEF_OFFSET(DAI_RX8DMASTART_REG, 0x2E0)
REGDEF_BEGIN(DAI_RX8DMASTART_REG)
REGDEF_BIT(RX8DMASTADR, 32)
REGDEF_END(DAI_RX8DMASTART_REG)

// RX9 DMA starting address Register
REGDEF_OFFSET(DAI_RX9DMASTART_REG, 0x300)
REGDEF_BEGIN(DAI_RX9DMASTART_REG)
REGDEF_BIT(RX9DMASTADR, 32)
REGDEF_END(DAI_RX9DMASTART_REG)

// RX10 DMA starting address Register
REGDEF_OFFSET(DAI_RX10DMASTART_REG, 0x320)
REGDEF_BEGIN(DAI_RX10DMASTART_REG)
REGDEF_BIT(RX10DMASTADR, 32)
REGDEF_END(DAI_RX10DMASTART_REG)

// RX11 DMA starting address Register
REGDEF_OFFSET(DAI_RX11DMASTART_REG, 0x340)
REGDEF_BEGIN(DAI_RX11DMASTART_REG)
REGDEF_BIT(RX11DMASTADR, 32)
REGDEF_END(DAI_RX11DMASTART_REG)

// RX12 DMA starting address Register
REGDEF_OFFSET(DAI_RX12DMASTART_REG, 0x360)
REGDEF_BEGIN(DAI_RX12DMASTART_REG)
REGDEF_BIT(RX12DMASTADR, 32)
REGDEF_END(DAI_RX12DMASTART_REG)

// RX13 DMA starting address Register
REGDEF_OFFSET(DAI_RX13DMASTART_REG, 0x380)
REGDEF_BEGIN(DAI_RX13DMASTART_REG)
REGDEF_BIT(RX13DMASTADR, 32)
REGDEF_END(DAI_RX13DMASTART_REG)

// RX14 DMA starting address Register
REGDEF_OFFSET(DAI_RX14DMASTART_REG, 0x3A0)
REGDEF_BEGIN(DAI_RX14DMASTART_REG)
REGDEF_BIT(RX14DMASTADR, 32)
REGDEF_END(DAI_RX14DMASTART_REG)

// RX15 DMA starting address Register
REGDEF_OFFSET(DAI_RX15DMASTART_REG, 0x3C0)
REGDEF_BEGIN(DAI_RX15DMASTART_REG)
REGDEF_BIT(RX15DMASTADR, 32)
REGDEF_END(DAI_RX15DMASTART_REG)

// RX16 DMA starting address Register
REGDEF_OFFSET(DAI_RX16DMASTART_REG, 0x3E0)
REGDEF_BEGIN(DAI_RX16DMASTART_REG)
REGDEF_BIT(RX16DMASTADR, 32)
REGDEF_END(DAI_RX16DMASTART_REG)

// RX17 DMA starting address Register
REGDEF_OFFSET(DAI_RX17DMASTART_REG, 0x400)
REGDEF_BEGIN(DAI_RX17DMASTART_REG)
REGDEF_BIT(RX17DMASTADR, 32)
REGDEF_END(DAI_RX17DMASTART_REG)

// RX18 DMA starting address Register
REGDEF_OFFSET(DAI_RX18DMASTART_REG, 0x420)
REGDEF_BEGIN(DAI_RX18DMASTART_REG)
REGDEF_BIT(RX18DMASTADR, 32)
REGDEF_END(DAI_RX18DMASTART_REG)

// RX19 DMA starting address Register
REGDEF_OFFSET(DAI_RX19DMASTART_REG, 0x440)
REGDEF_BEGIN(DAI_RX19DMASTART_REG)
REGDEF_BIT(RX19DMASTADR, 32)
REGDEF_END(DAI_RX19DMASTART_REG)

// RX20 DMA starting address Register
REGDEF_OFFSET(DAI_RX20DMASTART_REG, 0x460)
REGDEF_BEGIN(DAI_RX20DMASTART_REG)
REGDEF_BIT(RX20DMASTADR, 32)
REGDEF_END(DAI_RX20DMASTART_REG)


// RX21 DMA starting address Register
REGDEF_OFFSET(DAI_RX21DMASTART_REG, 0x480)
REGDEF_BEGIN(DAI_RX21DMASTART_REG)
REGDEF_BIT(RX21DMASTADR, 32)
REGDEF_END(DAI_RX21DMASTART_REG)



// RX1 DMA starting address Register MSB
REGDEF_OFFSET(DAI_RX1DMASTARTMSB_REG, 0x204)
REGDEF_BEGIN(DAI_RX1DMASTARTMSB_REG)
REGDEF_BIT(RX1DMASTADRMSB, 4)
REGDEF_BIT(, 28)
REGDEF_END(DAI_RX1DMASTARTMSB_REG)

// RX2 DMA starting address Register MSB
REGDEF_OFFSET(DAI_RX2DMASTARTMSB_REG, 0x224)
REGDEF_BEGIN(DAI_RX2DMASTARTMSB_REG)
REGDEF_BIT(RX2DMASTADRMSB, 4)
REGDEF_BIT(, 28)
REGDEF_END(DAI_RX2DMASTARTMSB_REG)

// RX3 DMA starting address Register MSB
REGDEF_OFFSET(DAI_RX3DMASTARTMSB_REG, 0x244)
REGDEF_BEGIN(DAI_RX3DMASTARTMSB_REG)
REGDEF_BIT(RX3DMASTADRMSB, 4)
REGDEF_BIT(, 28)
REGDEF_END(DAI_RX3DMASTARTMSB_REG)

// RX4 DMA starting address Register
REGDEF_OFFSET(DAI_RX4DMASTARTMSB_REG, 0x264)
REGDEF_BEGIN(DAI_RX4DMASTARTMSB_REG)
REGDEF_BIT(RX4DMASTADRMSB, 4)
REGDEF_BIT(, 28)
REGDEF_END(DAI_RX4DMASTARTMSB_REG)

// RX5 DMA starting address Register
REGDEF_OFFSET(DAI_RX5DMASTARTMSB_REG, 0x284)
REGDEF_BEGIN(DAI_RX5DMASTARTMSB_REG)
REGDEF_BIT(RX5DMASTADRMSB, 4)
REGDEF_BIT(, 28)
REGDEF_END(DAI_RX5DMASTARTMSB_REG)

// RX6 DMA starting address Register
REGDEF_OFFSET(DAI_RX6DMASTARTMSB_REG, 0x2A4)
REGDEF_BEGIN(DAI_RX6DMASTARTMSB_REG)
REGDEF_BIT(RX6DMASTADRMSB, 4)
REGDEF_BIT(, 28)
REGDEF_END(DAI_RX6DMASTARTMSB_REG)

// RX7 DMA starting address Register
REGDEF_OFFSET(DAI_RX7DMASTARTMSB_REG, 0x2C4)
REGDEF_BEGIN(DAI_RX7DMASTARTMSB_REG)
REGDEF_BIT(RX7DMASTADRMSB, 4)
REGDEF_BIT(, 28)
REGDEF_END(DAI_RX7DMASTARTMSB_REG)

// RX8 DMA starting address Register
REGDEF_OFFSET(DAI_RX8DMASTARTMSB_REG, 0x2E4)
REGDEF_BEGIN(DAI_RX8DMASTARTMSB_REG)
REGDEF_BIT(RX8DMASTADRMSB, 4)
REGDEF_BIT(, 28)
REGDEF_END(DAI_RX8DMASTARTMSB_REG)

// RX9 DMA starting address Register
REGDEF_OFFSET(DAI_RX9DMASTARTMSB_REG, 0x304)
REGDEF_BEGIN(DAI_RX9DMASTARTMSB_REG)
REGDEF_BIT(RX9DMASTADRMSB, 4)
REGDEF_BIT(, 28)
REGDEF_END(DAI_RX9DMASTARTMSB_REG)

// RX10 DMA starting address Register
REGDEF_OFFSET(DAI_RX10DMASTARTMSB_REG, 0x324)
REGDEF_BEGIN(DAI_RX10DMASTARTMSB_REG)
REGDEF_BIT(RX10DMASTADRMSB, 4)
REGDEF_BIT(, 28)
REGDEF_END(DAI_RX10DMASTARTMSB_REG)

// RX11 DMA starting address Register
REGDEF_OFFSET(DAI_RX11DMASTARTMSB_REG, 0x344)
REGDEF_BEGIN(DAI_RX11DMASTARTMSB_REG)
REGDEF_BIT(RX11DMASTADRMSB, 4)
REGDEF_BIT(, 28)
REGDEF_END(DAI_RX11DMASTARTMSB_REG)

// RX12 DMA starting address Register
REGDEF_OFFSET(DAI_RX12DMASTARTMSB_REG, 0x364)
REGDEF_BEGIN(DAI_RX12DMASTARTMSB_REG)
REGDEF_BIT(RX12DMASTADRMSB, 4)
REGDEF_BIT(, 28)
REGDEF_END(DAI_RX12DMASTARTMSB_REG)

// RX13 DMA starting address Register
REGDEF_OFFSET(DAI_RX13DMASTARTMSB_REG, 0x384)
REGDEF_BEGIN(DAI_RX13DMASTARTMSB_REG)
REGDEF_BIT(RX13DMASTADRMSB, 4)
REGDEF_BIT(, 28)
REGDEF_END(DAI_RX13DMASTARTMSB_REG)

// RX14 DMA starting address Register
REGDEF_OFFSET(DAI_RX14DMASTARTMSB_REG, 0x3A4)
REGDEF_BEGIN(DAI_RX14DMASTARTMSB_REG)
REGDEF_BIT(RX14DMASTADRMSB, 4)
REGDEF_BIT(, 28)
REGDEF_END(DAI_RX14DMASTARTMSB_REG)

// RX15 DMA starting address Register
REGDEF_OFFSET(DAI_RX15DMASTARTMSB_REG, 0x3C4)
REGDEF_BEGIN(DAI_RX15DMASTARTMSB_REG)
REGDEF_BIT(RX15DMASTADRMSB, 4)
REGDEF_BIT(, 28)
REGDEF_END(DAI_RX15DMASTARTMSB_REG)

// RX16 DMA starting address Register
REGDEF_OFFSET(DAI_RX16DMASTARTMSB_REG, 0x3E4)
REGDEF_BEGIN(DAI_RX16DMASTARTMSB_REG)
REGDEF_BIT(RX16DMASTADRMSB, 4)
REGDEF_BIT(, 28)
REGDEF_END(DAI_RX16DMASTARTMSB_REG)

// RX17 DMA starting address Register
REGDEF_OFFSET(DAI_RX17DMASTARTMSB_REG, 0x404)
REGDEF_BEGIN(DAI_RX17DMASTARTMSB_REG)
REGDEF_BIT(RX17DMASTADRMSB, 4)
REGDEF_BIT(, 28)
REGDEF_END(DAI_RX17DMASTARTMSB_REG)

// RX18 DMA starting address Register
REGDEF_OFFSET(DAI_RX18DMASTARTMSB_REG, 0x424)
REGDEF_BEGIN(DAI_RX18DMASTARTMSB_REG)
REGDEF_BIT(RX18DMASTADRMSB, 4)
REGDEF_BIT(, 28)
REGDEF_END(DAI_RX18DMASTARTMSB_REG)

// RX19 DMA starting address Register
REGDEF_OFFSET(DAI_RX19DMASTARTMSB_REG, 0x444)
REGDEF_BEGIN(DAI_RX19DMASTARTMSB_REG)
REGDEF_BIT(RX19DMASTADRMSB, 4)
REGDEF_BIT(, 28)
REGDEF_END(DAI_RX19DMASTARTMSB_REG)

// RX20 DMA starting address Register
REGDEF_OFFSET(DAI_RX20DMASTARTMSB_REG, 0x464)
REGDEF_BEGIN(DAI_RX20DMASTARTMSB_REG)
REGDEF_BIT(RX20DMASTADRMSB, 4)
REGDEF_BIT(, 28)
REGDEF_END(DAI_RX20DMASTARTMSB_REG)


// RX21 DMA starting address Register
REGDEF_OFFSET(DAI_RX21DMASTARTMSB_REG, 0x484)
REGDEF_BEGIN(DAI_RX21DMASTARTMSB_REG)
REGDEF_BIT(RX21DMASTADRMSB, 4)
REGDEF_BIT(, 28)
REGDEF_END(DAI_RX21DMASTARTMSB_REG)

// CURRENT ADDRESS 0X208 - (multi-ch TX:0x208,  RX ch0:0x228)
REGDEF_OFFSET(DAI_RXN1DMACURRENT_REG, 0x208)
REGDEF_BEGIN(DAI_RXN1DMACURRENT_REG)
REGDEF_BIT(RXN1DMACUADR, 32)
REGDEF_END(DAI_RXN1DMACURRENT_REG)

REGDEF_OFFSET(DAI_RXN2DMACURRENT_REG, 0x228)
REGDEF_BEGIN(DAI_RXN2DMACURRENT_REG)
REGDEF_BIT(RXN2DMACUADR, 32)
REGDEF_END(DAI_RXN2DMACURRENT_REG)


// CURRENT ADDRESS MSB 0X20C - (multi-ch TX:0x20C,  RX ch0:0x22C)
REGDEF_OFFSET(DAI_RXN1DMACURRENTNSB_REG, 0x20C)
REGDEF_BEGIN(DAI_RXN1DMACURRENTNSB_REG)
REGDEF_BIT(RXN1DMACUADR_MSB, 4)
REGDEF_BIT(, 28)
REGDEF_END(DAI_RXN1DMACURRENTNSB_REG)

REGDEF_OFFSET(DAI_RXN2DMACURRENTNSB_REG, 0x22C)
REGDEF_BEGIN(DAI_RXN2DMACURRENTNSB_REG)
REGDEF_BIT(RXN2DMACUADR_MSB, 4)
REGDEF_BIT(, 28)
REGDEF_END(DAI_RXN2DMACURRENTNSB_REG)


// RX1 DMA RAM buffer size Register
REGDEF_OFFSET(DAI_RX1DMABUFSIZE_REG, 0x210)
REGDEF_BEGIN(DAI_RX1DMABUFSIZE_REG)
REGDEF_BIT(RX1DMABUFSZ, 19)
REGDEF_BIT(, 13)
REGDEF_END(DAI_RX1DMABUFSIZE_REG)

// RX2 DMA RAM buffer size Register
REGDEF_OFFSET(DAI_RX2DMABUFSIZE_REG, 0x230)
REGDEF_BEGIN(DAI_RX2DMABUFSIZE_REG)
REGDEF_BIT(RX2DMABUFSZ, 19)
REGDEF_BIT(, 13)
REGDEF_END(DAI_RX2DMABUFSIZE_REG)

// RX3 DMA RAM buffer size Register
REGDEF_OFFSET(DAI_RX3DMABUFSIZE_REG, 0x250)
REGDEF_BEGIN(DAI_RX3DMABUFSIZE_REG)
REGDEF_BIT(RX3DMABUFSZ, 19)
REGDEF_BIT(, 13)
REGDEF_END(DAI_RX3DMABUFSIZE_REG)

// RX4 DMA RAM buffer size Register
REGDEF_OFFSET(DAI_RX4DMABUFSIZE_REG, 0x270)
REGDEF_BEGIN(DAI_RX4DMABUFSIZE_REG)
REGDEF_BIT(RX4DMABUFSZ, 19)
REGDEF_BIT(, 13)
REGDEF_END(DAI_RX4DMABUFSIZE_REG)

// RX5 DMA RAM buffer size Register
REGDEF_OFFSET(DAI_RX5DMABUFSIZE_REG, 0x290)
REGDEF_BEGIN(DAI_RX5DMABUFSIZE_REG)
REGDEF_BIT(RX5DMABUFSZ, 19)
REGDEF_BIT(, 13)
REGDEF_END(DAI_RX5DMABUFSIZE_REG)

// RX6 DMA RAM buffer size Register
REGDEF_OFFSET(DAI_RX6DMABUFSIZE_REG, 0x2B0)
REGDEF_BEGIN(DAI_RX6DMABUFSIZE_REG)
REGDEF_BIT(RX6DMABUFSZ, 19)
REGDEF_BIT(, 13)
REGDEF_END(DAI_RX6DMABUFSIZE_REG)

// RX7 DMA RAM buffer size Register
REGDEF_OFFSET(DAI_RX7DMABUFSIZE_REG, 0x2D0)
REGDEF_BEGIN(DAI_RX7DMABUFSIZE_REG)
REGDEF_BIT(RX7DMABUFSZ, 19)
REGDEF_BIT(, 13)
REGDEF_END(DAI_RX7DMABUFSIZE_REG)

// RX8 DMA RAM buffer size Register
REGDEF_OFFSET(DAI_RX8DMABUFSIZE_REG, 0x2F0)
REGDEF_BEGIN(DAI_RX8DMABUFSIZE_REG)
REGDEF_BIT(RX8DMABUFSZ, 19)
REGDEF_BIT(, 13)
REGDEF_END(DAI_RX8DMABUFSIZE_REG)

// RX9 DMA RAM buffer size Register
REGDEF_OFFSET(DAI_RX9DMABUFSIZE_REG, 0x310)
REGDEF_BEGIN(DAI_RX9DMABUFSIZE_REG)
REGDEF_BIT(RX9DMABUFSZ, 19)
REGDEF_BIT(, 13)
REGDEF_END(DAI_RX9DMABUFSIZE_REG)

// RX10 DMA RAM buffer size Register
REGDEF_OFFSET(DAI_RX10DMABUFSIZE_REG, 0x330)
REGDEF_BEGIN(DAI_RX10DMABUFSIZE_REG)
REGDEF_BIT(RX10DMABUFSZ, 19)
REGDEF_BIT(, 13)
REGDEF_END(DAI_RX10DMABUFSIZE_REG)

// RX11 DMA RAM buffer size Register
REGDEF_OFFSET(DAI_RX11DMABUFSIZE_REG, 0x350)
REGDEF_BEGIN(DAI_RX11DMABUFSIZE_REG)
REGDEF_BIT(RX11DMABUFSZ, 19)
REGDEF_BIT(, 13)
REGDEF_END(DAI_RX11DMABUFSIZE_REG)

// RX12 DMA RAM buffer size Register
REGDEF_OFFSET(DAI_RX12DMABUFSIZE_REG, 0x370)
REGDEF_BEGIN(DAI_RX12DMABUFSIZE_REG)
REGDEF_BIT(RX12DMABUFSZ, 19)
REGDEF_BIT(, 13)
REGDEF_END(DAI_RX12DMABUFSIZE_REG)

// RX13 DMA RAM buffer size Register
REGDEF_OFFSET(DAI_RX13DMABUFSIZE_REG, 0x390)
REGDEF_BEGIN(DAI_RX13DMABUFSIZE_REG)
REGDEF_BIT(RX13DMABUFSZ, 19)
REGDEF_BIT(, 13)
REGDEF_END(DAI_RX13DMABUFSIZE_REG)

// RX14 DMA RAM buffer size Register
REGDEF_OFFSET(DAI_RX14DMABUFSIZE_REG, 0x3B0)
REGDEF_BEGIN(DAI_RX14DMABUFSIZE_REG)
REGDEF_BIT(RX14DMABUFSZ, 19)
REGDEF_BIT(, 13)
REGDEF_END(DAI_RX14DMABUFSIZE_REG)

// RX15 DMA RAM buffer size Register
REGDEF_OFFSET(DAI_RX15DMABUFSIZE_REG, 0x3D0)
REGDEF_BEGIN(DAI_RX15DMABUFSIZE_REG)
REGDEF_BIT(RX15DMABUFSZ, 19)
REGDEF_BIT(, 13)
REGDEF_END(DAI_RX15DMABUFSIZE_REG)

// RX16 DMA RAM buffer size Register
REGDEF_OFFSET(DAI_RX16DMABUFSIZE_REG, 0x3F0)
REGDEF_BEGIN(DAI_RX16DMABUFSIZE_REG)
REGDEF_BIT(RX16DMABUFSZ, 19)
REGDEF_BIT(, 13)
REGDEF_END(DAI_RX16DMABUFSIZE_REG)

// RX17 DMA RAM buffer size Register
REGDEF_OFFSET(DAI_RX17DMABUFSIZE_REG, 0x410)
REGDEF_BEGIN(DAI_RX17DMABUFSIZE_REG)
REGDEF_BIT(RX17DMABUFSZ, 19)
REGDEF_BIT(, 13)
REGDEF_END(DAI_RX17DMABUFSIZE_REG)

// RX18 DMA RAM buffer size Register
REGDEF_OFFSET(DAI_RX18DMABUFSIZE_REG, 0x430)
REGDEF_BEGIN(DAI_RX18DMABUFSIZE_REG)
REGDEF_BIT(RX18DMABUFSZ, 19)
REGDEF_BIT(, 13)
REGDEF_END(DAI_RX18DMABUFSIZE_REG)

// RX19 DMA RAM buffer size Register
REGDEF_OFFSET(DAI_RX19DMABUFSIZE_REG, 0x450)
REGDEF_BEGIN(DAI_RX19DMABUFSIZE_REG)
REGDEF_BIT(RX19DMABUFSZ, 19)
REGDEF_BIT(, 13)
REGDEF_END(DAI_RX19DMABUFSIZE_REG)

// RX20 DMA RAM buffer size Register
REGDEF_OFFSET(DAI_RX20DMABUFSIZE_REG, 0x470)
REGDEF_BEGIN(DAI_RX20DMABUFSIZE_REG)
REGDEF_BIT(RX20DMABUFSZ, 19)
REGDEF_BIT(, 13)
REGDEF_END(DAI_RX20DMABUFSIZE_REG)

// RX21 DMA RAM buffer size Register
REGDEF_OFFSET(DAI_RX21DMABUFSIZE_REG, 0x490)
REGDEF_BEGIN(DAI_RX21DMABUFSIZE_REG)
REGDEF_BIT(RX21DMABUFSZ, 19)
REGDEF_BIT(, 13)
REGDEF_END(DAI_RX21DMABUFSIZE_REG)

#endif


#if 1  //  1ch start address 2

// TX1 DMA starting address Register
REGDEF_OFFSET(DAI_TX1DMASTART2_REG, 0x500)
REGDEF_BEGIN(DAI_TX1DMASTART2_REG)
REGDEF_BIT(TX1DMASTADR, 32)
REGDEF_END(DAI_TX1DMASTART2_REG)

// TX1 DMA starting address Register MSB
REGDEF_OFFSET(DAI_TX1DMASTART2MSB_REG, 0x504)
REGDEF_BEGIN(DAI_TX1DMASTART2MSB_REG)
REGDEF_BIT(TX1DMASTADRMSB, 4)
REGDEF_BIT(, 28)
REGDEF_END(DAI_TX1DMASTART2MSB_REG)

// TX1 DMA RAM buffer size Register
REGDEF_OFFSET(DAI_TX1DMABUFSIZE2_REG, 0x510)
REGDEF_BEGIN(DAI_TX1DMABUFSIZE2_REG)
REGDEF_BIT(TX1DMABUFSZ, 19)
REGDEF_BIT(, 13)
REGDEF_END(DAI_TX1DMABUFSIZE2_REG)

// TX2 DMA starting address Register
REGDEF_OFFSET(DAI_TX2DMASTART2_REG, 0x520)
REGDEF_BEGIN(DAI_TX2DMASTART2_REG)
REGDEF_BIT(TX2DMASTADR, 32)
REGDEF_END(DAI_TX2DMASTART2_REG)

// TX2 DMA starting address Register MSB
REGDEF_OFFSET(DAI_TX2DMASTART2MSB_REG, 0x524)
REGDEF_BEGIN(DAI_TX2DMASTART2MSB_REG)
REGDEF_BIT(TX2DMASTADRMSB, 4)
REGDEF_BIT(, 28)
REGDEF_END(DAI_TX2DMASTART2MSB_REG)

// TX2 DMA RAM buffer size Register
REGDEF_OFFSET(DAI_TX2DMABUFSIZE2_REG, 0x530)
REGDEF_BEGIN(DAI_TX2DMABUFSIZE2_REG)
REGDEF_BIT(TX2DMABUFSZ, 19)
REGDEF_BIT(, 13)
REGDEF_END(DAI_TX2DMABUFSIZE2_REG)

// RX1 DMA starting address Register
REGDEF_OFFSET(DAI_1CHRX1DMASTART2_REG, 0x540)
REGDEF_BEGIN(DAI_1CHRX1DMASTART2_REG)
REGDEF_BIT(RX1DMASTADR, 32)
REGDEF_END(DAI_1CHRX1DMASTART2_REG)

// RX1 DMA starting address Register MSB
REGDEF_OFFSET(DAI_1CHRX1DMASTART2MSB_REG, 0x544)
REGDEF_BEGIN(DAI_1CHRX1DMASTART2MSB_REG)
REGDEF_BIT(RX1DMASTADRMSB, 4)
REGDEF_BIT(, 28)
REGDEF_END(DAI_1CHRX1DMASTART2MSB_REG)

// RX1 DMA RAM buffer size Register
REGDEF_OFFSET(DAI_1CHRX1DMABUFSIZE2_REG, 0x550)////DAI_1CHRX1DMABUFSIZE_REG
REGDEF_BEGIN(DAI_1CHRX1DMABUFSIZE2_REG)
REGDEF_BIT(RX1DMABUFSZ, 19)
REGDEF_BIT(, 13)
REGDEF_END(DAI_1CHRX1DMABUFSIZE2_REG)


// RX2 DMA starting address Register
REGDEF_OFFSET(DAI_1CHRX2DMASTART2_REG, 0x560)
REGDEF_BEGIN(DAI_1CHRX2DMASTART2_REG)
REGDEF_BIT(RX2DMASTADR, 32)
REGDEF_END(DAI_1CHRX2DMASTART2_REG)

// RX2 DMA starting address Register MSB
REGDEF_OFFSET(DAI_1CHRX2DMASTART2MSB_REG, 0x564)
REGDEF_BEGIN(DAI_1CHRX2DMASTART2MSB_REG)
REGDEF_BIT(RX2DMASTADRMSB, 4)
REGDEF_BIT(, 28)
REGDEF_END(DAI_1CHRX2DMASTART2MSB_REG)

// RX2 DMA RAM buffer size Register
REGDEF_OFFSET(DAI_1CHRX2DMABUFSIZE2_REG, 0x570)
REGDEF_BEGIN(DAI_1CHRX2DMABUFSIZE2_REG)
REGDEF_BIT(RX2DMABUFSZ, 19)
REGDEF_BIT(, 13)
REGDEF_END(DAI_1CHRX2DMABUFSIZE2_REG)

// TXLB DMA starting address Register
REGDEF_OFFSET(DAI_TXLBDMASTART2_REG, 0x580)
REGDEF_BEGIN(DAI_TXLBDMASTART2_REG)
REGDEF_BIT(TXLBDMASTADR, 32)
REGDEF_END(DAI_TXLBDMASTART2_REG)

// TXLB DMA starting address Register MSB
REGDEF_OFFSET(DAI_TXLBDMASTART2MSB_REG, 0x584)
REGDEF_BEGIN(DAI_TXLBDMASTART2MSB_REG)
REGDEF_BIT(TXLBDMASTADRMSB, 4)
REGDEF_BIT(, 28)
REGDEF_END(DAI_TXLBDMASTART2MSB_REG)

// TXLB DMA RAM buffer size Register
REGDEF_OFFSET(DAI_TXLBDMABUFSIZE2_REG, 0x590)
REGDEF_BEGIN(DAI_TXLBDMABUFSIZE2_REG)
REGDEF_BIT(TXLBDMABUFSZ, 19)
REGDEF_BIT(, 13)
REGDEF_END(DAI_TXLBDMABUFSIZE2_REG)
#endif

#if 1  //  20 ch start address 2

// RX1 DMA starting address Register
REGDEF_OFFSET(DAI_RX1DMASTART2_REG, 0x600)
REGDEF_BEGIN(DAI_RX1DMASTART2_REG)
REGDEF_BIT(RX1DMASTADR, 32)
REGDEF_END(DAI_RX1DMASTART2_REG)

// RX2 DMA starting address Register
REGDEF_OFFSET(DAI_RX2DMASTART2_REG, 0x620)
REGDEF_BEGIN(DAI_RX2DMASTART2_REG)
REGDEF_BIT(RX2DMASTADR, 32)
REGDEF_END(DAI_RX2DMASTART2_REG)

// RX3 DMA starting address Register
REGDEF_OFFSET(DAI_RX3DMASTART2_REG, 0x640)
REGDEF_BEGIN(DAI_RX3DMASTART2_REG)
REGDEF_BIT(RX3DMASTADR, 32)
REGDEF_END(DAI_RX3DMASTART2_REG)

// RX4 DMA starting address Register
REGDEF_OFFSET(DAI_RX4DMASTART2_REG, 0x660)
REGDEF_BEGIN(DAI_RX4DMASTART2_REG)
REGDEF_BIT(RX4DMASTADR, 32)
REGDEF_END(DAI_RX4DMASTART2_REG)

// RX5 DMA starting address Register
REGDEF_OFFSET(DAI_RX5DMASTART2_REG, 0x680)
REGDEF_BEGIN(DAI_RX5DMASTART2_REG)
REGDEF_BIT(RX5DMASTADR, 32)
REGDEF_END(DAI_RX5DMASTART2_REG)

// RX6 DMA starting address Register
REGDEF_OFFSET(DAI_RX6DMASTART2_REG, 0x6A0)
REGDEF_BEGIN(DAI_RX6DMASTART2_REG)
REGDEF_BIT(RX6DMASTADR, 32)
REGDEF_END(DAI_RX6DMASTART2_REG)

// RX7 DMA starting address Register
REGDEF_OFFSET(DAI_RX7DMASTART2_REG, 0x6C0)
REGDEF_BEGIN(DAI_RX7DMASTART2_REG)
REGDEF_BIT(RX7DMASTADR, 32)
REGDEF_END(DAI_RX7DMASTART2_REG)

// RX8 DMA starting address Register
REGDEF_OFFSET(DAI_RX8DMASTART2_REG, 0x6E0)
REGDEF_BEGIN(DAI_RX8DMASTART2_REG)
REGDEF_BIT(RX8DMASTADR, 32)
REGDEF_END(DAI_RX8DMASTART2_REG)

// RX9 DMA starting address Register
REGDEF_OFFSET(DAI_RX9DMASTART2_REG, 0x700)
REGDEF_BEGIN(DAI_RX9DMASTART2_REG)
REGDEF_BIT(RX9DMASTADR, 32)
REGDEF_END(DAI_RX9DMASTART2_REG)

// RX10 DMA starting address Register
REGDEF_OFFSET(DAI_RX10DMASTART2_REG, 0x720)
REGDEF_BEGIN(DAI_RX10DMASTART2_REG)
REGDEF_BIT(RX10DMASTADR, 32)
REGDEF_END(DAI_RX10DMASTART2_REG)

// RX11 DMA starting address Register
REGDEF_OFFSET(DAI_RX11DMASTART2_REG, 0x740)
REGDEF_BEGIN(DAI_RX11DMASTART2_REG)
REGDEF_BIT(RX11DMASTADR, 32)
REGDEF_END(DAI_RX11DMASTART2_REG)

// RX12 DMA starting address Register
REGDEF_OFFSET(DAI_RX12DMASTART2_REG, 0x760)
REGDEF_BEGIN(DAI_RX12DMASTART2_REG)
REGDEF_BIT(RX12DMASTADR, 32)
REGDEF_END(DAI_RX12DMASTART2_REG)

// RX13 DMA starting address Register
REGDEF_OFFSET(DAI_RX13DMASTART2_REG, 0x780)
REGDEF_BEGIN(DAI_RX13DMASTART2_REG)
REGDEF_BIT(RX13DMASTADR, 32)
REGDEF_END(DAI_RX13DMASTART2_REG)

// RX14 DMA starting address Register
REGDEF_OFFSET(DAI_RX14DMASTART2_REG, 0x7A0)
REGDEF_BEGIN(DAI_RX14DMASTART2_REG)
REGDEF_BIT(RX14DMASTADR, 32)
REGDEF_END(DAI_RX14DMASTART2_REG)

// RX15 DMA starting address Register
REGDEF_OFFSET(DAI_RX15DMASTART2_REG, 0x7C0)
REGDEF_BEGIN(DAI_RX15DMASTART2_REG)
REGDEF_BIT(RX15DMASTADR, 32)
REGDEF_END(DAI_RX15DMASTART2_REG)

// RX16 DMA starting address Register
REGDEF_OFFSET(DAI_RX16DMASTART2_REG, 0x7E0)
REGDEF_BEGIN(DAI_RX16DMASTART2_REG)
REGDEF_BIT(RX16DMASTADR, 32)
REGDEF_END(DAI_RX16DMASTART2_REG)

// RX17 DMA starting address Register
REGDEF_OFFSET(DAI_RX17DMASTART2_REG, 0x800)
REGDEF_BEGIN(DAI_RX17DMASTART2_REG)
REGDEF_BIT(RX17DMASTADR, 32)
REGDEF_END(DAI_RX17DMASTART2_REG)

// RX18 DMA starting address Register
REGDEF_OFFSET(DAI_RX18DMASTART2_REG, 0x820)
REGDEF_BEGIN(DAI_RX18DMASTART2_REG)
REGDEF_BIT(RX18DMASTADR, 32)
REGDEF_END(DAI_RX18DMASTART2_REG)

// RX19 DMA starting address Register
REGDEF_OFFSET(DAI_RX19DMASTART2_REG, 0x840)
REGDEF_BEGIN(DAI_RX19DMASTART2_REG)
REGDEF_BIT(RX19DMASTADR, 32)
REGDEF_END(DAI_RX19DMASTART2_REG)

// RX20 DMA starting address Register
REGDEF_OFFSET(DAI_RX20DMASTART2_REG, 0x860)
REGDEF_BEGIN(DAI_RX20DMASTART2_REG)
REGDEF_BIT(RX20DMASTADR, 32)
REGDEF_END(DAI_RX20DMASTART2_REG)


// RX21 DMA starting address Register
REGDEF_OFFSET(DAI_RX21DMASTART2_REG, 0x880)
REGDEF_BEGIN(DAI_RX21DMASTART2_REG)
REGDEF_BIT(RX21DMASTADR, 32)
REGDEF_END(DAI_RX21DMASTART2_REG)



// RX1 DMA starting address Register MSB
REGDEF_OFFSET(DAI_RX1DMASTART2MSB_REG, 0x604)
REGDEF_BEGIN(DAI_RX1DMASTART2MSB_REG)
REGDEF_BIT(RX1DMASTADRMSB, 4)
REGDEF_BIT(, 28)
REGDEF_END(DAI_RX1DMASTART2MSB_REG)

// RX2 DMA starting address Register MSB
REGDEF_OFFSET(DAI_RX2DMASTART2MSB_REG, 0x624)
REGDEF_BEGIN(DAI_RX2DMASTART2MSB_REG)
REGDEF_BIT(RX2DMASTADRMSB, 4)
REGDEF_BIT(, 28)
REGDEF_END(DAI_RX2DMASTART2MSB_REG)

// RX3 DMA starting address Register MSB
REGDEF_OFFSET(DAI_RX3DMASTART2MSB_REG, 0x644)
REGDEF_BEGIN(DAI_RX3DMASTART2MSB_REG)
REGDEF_BIT(RX3DMASTADRMSB, 4)
REGDEF_BIT(, 28)
REGDEF_END(DAI_RX3DMASTART2MSB_REG)

// RX4 DMA starting address Register
REGDEF_OFFSET(DAI_RX4DMASTART2MSB_REG, 0x664)
REGDEF_BEGIN(DAI_RX4DMASTART2MSB_REG)
REGDEF_BIT(RX4DMASTADRMSB, 4)
REGDEF_BIT(, 28)
REGDEF_END(DAI_RX4DMASTART2MSB_REG)

// RX5 DMA starting address Register
REGDEF_OFFSET(DAI_RX5DMASTART2MSB_REG, 0x684)
REGDEF_BEGIN(DAI_RX5DMASTART2MSB_REG)
REGDEF_BIT(RX5DMASTADRMSB, 4)
REGDEF_BIT(, 28)
REGDEF_END(DAI_RX5DMASTART2MSB_REG)

// RX6 DMA starting address Register
REGDEF_OFFSET(DAI_RX6DMASTART2MSB_REG, 0x6A4)
REGDEF_BEGIN(DAI_RX6DMASTART2MSB_REG)
REGDEF_BIT(RX6DMASTADRMSB, 4)
REGDEF_BIT(, 28)
REGDEF_END(DAI_RX6DMASTART2MSB_REG)

// RX7 DMA starting address Register
REGDEF_OFFSET(DAI_RX7DMASTART2MSB_REG, 0x6C4)
REGDEF_BEGIN(DAI_RX7DMASTART2MSB_REG)
REGDEF_BIT(RX7DMASTADRMSB, 4)
REGDEF_BIT(, 28)
REGDEF_END(DAI_RX7DMASTART2MSB_REG)

// RX8 DMA starting address Register
REGDEF_OFFSET(DAI_RX8DMASTART2MSB_REG, 0x6E4)
REGDEF_BEGIN(DAI_RX8DMASTART2MSB_REG)
REGDEF_BIT(RX8DMASTADRMSB, 4)
REGDEF_BIT(, 28)
REGDEF_END(DAI_RX8DMASTART2MSB_REG)

// RX9 DMA starting address Register
REGDEF_OFFSET(DAI_RX9DMASTART2MSB_REG, 0x704)
REGDEF_BEGIN(DAI_RX9DMASTART2MSB_REG)
REGDEF_BIT(RX9DMASTADRMSB, 4)
REGDEF_BIT(, 28)
REGDEF_END(DAI_RX9DMASTART2MSB_REG)

// RX10 DMA starting address Register
REGDEF_OFFSET(DAI_RX10DMASTART2MSB_REG, 0x724)
REGDEF_BEGIN(DAI_RX10DMASTART2MSB_REG)
REGDEF_BIT(RX10DMASTADRMSB, 4)
REGDEF_BIT(, 28)
REGDEF_END(DAI_RX10DMASTART2MSB_REG)

// RX11 DMA starting address Register
REGDEF_OFFSET(DAI_RX11DMASTART2MSB_REG, 0x744)
REGDEF_BEGIN(DAI_RX11DMASTART2MSB_REG)
REGDEF_BIT(RX11DMASTADRMSB, 4)
REGDEF_BIT(, 28)
REGDEF_END(DAI_RX11DMASTART2MSB_REG)

// RX12 DMA starting address Register
REGDEF_OFFSET(DAI_RX12DMASTART2MSB_REG, 0x764)
REGDEF_BEGIN(DAI_RX12DMASTART2MSB_REG)
REGDEF_BIT(RX12DMASTADRMSB, 4)
REGDEF_BIT(, 28)
REGDEF_END(DAI_RX12DMASTART2MSB_REG)

// RX13 DMA starting address Register
REGDEF_OFFSET(DAI_RX13DMASTART2MSB_REG, 0x784)
REGDEF_BEGIN(DAI_RX13DMASTART2MSB_REG)
REGDEF_BIT(RX13DMASTADRMSB, 4)
REGDEF_BIT(, 28)
REGDEF_END(DAI_RX13DMASTART2MSB_REG)

// RX14 DMA starting address Register
REGDEF_OFFSET(DAI_RX14DMASTART2MSB_REG, 0x7A4)
REGDEF_BEGIN(DAI_RX14DMASTART2MSB_REG)
REGDEF_BIT(RX14DMASTADRMSB, 4)
REGDEF_BIT(, 28)
REGDEF_END(DAI_RX14DMASTART2MSB_REG)

// RX15 DMA starting address Register
REGDEF_OFFSET(DAI_RX15DMASTART2MSB_REG, 0x7C4)
REGDEF_BEGIN(DAI_RX15DMASTART2MSB_REG)
REGDEF_BIT(RX15DMASTADRMSB, 4)
REGDEF_BIT(, 28)
REGDEF_END(DAI_RX15DMASTART2MSB_REG)

// RX16 DMA starting address Register
REGDEF_OFFSET(DAI_RX16DMASTART2MSB_REG, 0x7E4)
REGDEF_BEGIN(DAI_RX16DMASTART2MSB_REG)
REGDEF_BIT(RX16DMASTADRMSB, 4)
REGDEF_BIT(, 28)
REGDEF_END(DAI_RX16DMASTART2MSB_REG)

// RX17 DMA starting address Register
REGDEF_OFFSET(DAI_RX17DMASTART2MSB_REG, 0x804)
REGDEF_BEGIN(DAI_RX17DMASTART2MSB_REG)
REGDEF_BIT(RX17DMASTADRMSB, 4)
REGDEF_BIT(, 28)
REGDEF_END(DAI_RX17DMASTART2MSB_REG)

// RX18 DMA starting address Register
REGDEF_OFFSET(DAI_RX18DMASTART2MSB_REG, 0x824)
REGDEF_BEGIN(DAI_RX18DMASTART2MSB_REG)
REGDEF_BIT(RX18DMASTADRMSB, 4)
REGDEF_BIT(, 28)
REGDEF_END(DAI_RX18DMASTART2MSB_REG)

// RX19 DMA starting address Register
REGDEF_OFFSET(DAI_RX19DMASTART2MSB_REG, 0x844)
REGDEF_BEGIN(DAI_RX19DMASTART2MSB_REG)
REGDEF_BIT(RX19DMASTADRMSB, 4)
REGDEF_BIT(, 28)
REGDEF_END(DAI_RX19DMASTART2MSB_REG)

// RX20 DMA starting address Register
REGDEF_OFFSET(DAI_RX20DMASTART2MSB_REG, 0x864)
REGDEF_BEGIN(DAI_RX20DMASTART2MSB_REG)
REGDEF_BIT(RX20DMASTADRMSB, 4)
REGDEF_BIT(, 28)
REGDEF_END(DAI_RX20DMASTART2MSB_REG)


// RX21 DMA starting address Register
REGDEF_OFFSET(DAI_RX21DMASTART2MSB_REG, 0x884)
REGDEF_BEGIN(DAI_RX21DMASTART2MSB_REG)
REGDEF_BIT(RX21DMASTADRMSB, 4)
REGDEF_BIT(, 28)
REGDEF_END(DAI_RX21DMASTART2MSB_REG)


// RX1 DMA RAM buffer size Register
REGDEF_OFFSET(DAI_RX1DMABUFSIZE2_REG, 0x610)
REGDEF_BEGIN(DAI_RX1DMABUFSIZE2_REG)
REGDEF_BIT(RX1DMABUFSZ, 19)
REGDEF_BIT(, 13)
REGDEF_END(DAI_RX1DMABUFSIZE2_REG)

// RX2 DMA RAM buffer size Register
REGDEF_OFFSET(DAI_RX2DMABUFSIZE2_REG, 0x630)
REGDEF_BEGIN(DAI_RX2DMABUFSIZE2_REG)
REGDEF_BIT(RX2DMABUFSZ, 19)
REGDEF_BIT(, 13)
REGDEF_END(DAI_RX2DMABUFSIZE2_REG)

// RX3 DMA RAM buffer size Register
REGDEF_OFFSET(DAI_RX3DMABUFSIZE2_REG, 0x650)
REGDEF_BEGIN(DAI_RX3DMABUFSIZE2_REG)
REGDEF_BIT(RX3DMABUFSZ, 19)
REGDEF_BIT(, 13)
REGDEF_END(DAI_RX3DMABUFSIZE2_REG)

// RX4 DMA RAM buffer size Register
REGDEF_OFFSET(DAI_RX4DMABUFSIZE2_REG, 0x670)
REGDEF_BEGIN(DAI_RX4DMABUFSIZE2_REG)
REGDEF_BIT(RX4DMABUFSZ, 19)
REGDEF_BIT(, 13)
REGDEF_END(DAI_RX4DMABUFSIZE2_REG)

// RX5 DMA RAM buffer size Register
REGDEF_OFFSET(DAI_RX5DMABUFSIZE2_REG, 0x690)
REGDEF_BEGIN(DAI_RX5DMABUFSIZE2_REG)
REGDEF_BIT(RX5DMABUFSZ, 19)
REGDEF_BIT(, 13)
REGDEF_END(DAI_RX5DMABUFSIZE2_REG)

// RX6 DMA RAM buffer size Register
REGDEF_OFFSET(DAI_RX6DMABUFSIZE2_REG, 0x6B0)
REGDEF_BEGIN(DAI_RX6DMABUFSIZE2_REG)
REGDEF_BIT(RX6DMABUFSZ, 19)
REGDEF_BIT(, 13)
REGDEF_END(DAI_RX6DMABUFSIZE2_REG)

// RX7 DMA RAM buffer size Register
REGDEF_OFFSET(DAI_RX7DMABUFSIZE2_REG, 0x6D0)
REGDEF_BEGIN(DAI_RX7DMABUFSIZE2_REG)
REGDEF_BIT(RX7DMABUFSZ, 19)
REGDEF_BIT(, 13)
REGDEF_END(DAI_RX7DMABUFSIZE2_REG)

// RX8 DMA RAM buffer size Register
REGDEF_OFFSET(DAI_RX8DMABUFSIZE2_REG, 0x6F0)
REGDEF_BEGIN(DAI_RX8DMABUFSIZE2_REG)
REGDEF_BIT(RX8DMABUFSZ, 19)
REGDEF_BIT(, 13)
REGDEF_END(DAI_RX8DMABUFSIZE2_REG)

// RX9 DMA RAM buffer size Register
REGDEF_OFFSET(DAI_RX9DMABUFSIZE2_REG, 0x710)
REGDEF_BEGIN(DAI_RX9DMABUFSIZE2_REG)
REGDEF_BIT(RX9DMABUFSZ, 19)
REGDEF_BIT(, 13)
REGDEF_END(DAI_RX9DMABUFSIZE2_REG)

// RX10 DMA RAM buffer size Register
REGDEF_OFFSET(DAI_RX10DMABUFSIZE2_REG, 0x730)
REGDEF_BEGIN(DAI_RX10DMABUFSIZE2_REG)
REGDEF_BIT(RX10DMABUFSZ, 19)
REGDEF_BIT(, 13)
REGDEF_END(DAI_RX10DMABUFSIZE2_REG)

// RX11 DMA RAM buffer size Register
REGDEF_OFFSET(DAI_RX11DMABUFSIZE2_REG, 0x750)
REGDEF_BEGIN(DAI_RX11DMABUFSIZE2_REG)
REGDEF_BIT(RX11DMABUFSZ, 19)
REGDEF_BIT(, 13)
REGDEF_END(DAI_RX11DMABUFSIZE2_REG)

// RX12 DMA RAM buffer size Register
REGDEF_OFFSET(DAI_RX12DMABUFSIZE2_REG, 0x770)
REGDEF_BEGIN(DAI_RX12DMABUFSIZE2_REG)
REGDEF_BIT(RX12DMABUFSZ, 19)
REGDEF_BIT(, 13)
REGDEF_END(DAI_RX12DMABUFSIZE2_REG)

// RX13 DMA RAM buffer size Register
REGDEF_OFFSET(DAI_RX13DMABUFSIZE2_REG, 0x790)
REGDEF_BEGIN(DAI_RX13DMABUFSIZE2_REG)
REGDEF_BIT(RX13DMABUFSZ, 19)
REGDEF_BIT(, 13)
REGDEF_END(DAI_RX13DMABUFSIZE2_REG)

// RX14 DMA RAM buffer size Register
REGDEF_OFFSET(DAI_RX14DMABUFSIZE2_REG, 0x7B0)
REGDEF_BEGIN(DAI_RX14DMABUFSIZE2_REG)
REGDEF_BIT(RX14DMABUFSZ, 19)
REGDEF_BIT(, 13)
REGDEF_END(DAI_RX14DMABUFSIZE2_REG)

// RX15 DMA RAM buffer size Register
REGDEF_OFFSET(DAI_RX15DMABUFSIZE2_REG, 0x7D0)
REGDEF_BEGIN(DAI_RX15DMABUFSIZE2_REG)
REGDEF_BIT(RX15DMABUFSZ, 19)
REGDEF_BIT(, 13)
REGDEF_END(DAI_RX15DMABUFSIZE2_REG)

// RX16 DMA RAM buffer size Register
REGDEF_OFFSET(DAI_RX16DMABUFSIZE2_REG, 0x7F0)
REGDEF_BEGIN(DAI_RX16DMABUFSIZE2_REG)
REGDEF_BIT(RX16DMABUFSZ, 19)
REGDEF_BIT(, 13)
REGDEF_END(DAI_RX16DMABUFSIZE2_REG)

// RX17 DMA RAM buffer size Register
REGDEF_OFFSET(DAI_RX17DMABUFSIZE2_REG, 0x810)
REGDEF_BEGIN(DAI_RX17DMABUFSIZE2_REG)
REGDEF_BIT(RX17DMABUFSZ, 19)
REGDEF_BIT(, 13)
REGDEF_END(DAI_RX17DMABUFSIZE2_REG)

// RX18 DMA RAM buffer size Register
REGDEF_OFFSET(DAI_RX18DMABUFSIZE2_REG, 0x830)
REGDEF_BEGIN(DAI_RX18DMABUFSIZE2_REG)
REGDEF_BIT(RX18DMABUFSZ, 19)
REGDEF_BIT(, 13)
REGDEF_END(DAI_RX18DMABUFSIZE2_REG)

// RX19 DMA RAM buffer size Register
REGDEF_OFFSET(DAI_RX19DMABUFSIZE2_REG, 0x850)
REGDEF_BEGIN(DAI_RX19DMABUFSIZE2_REG)
REGDEF_BIT(RX19DMABUFSZ, 19)
REGDEF_BIT(, 13)
REGDEF_END(DAI_RX19DMABUFSIZE2_REG)

// RX20 DMA RAM buffer size Register
REGDEF_OFFSET(DAI_RX20DMABUFSIZE2_REG, 0x870)
REGDEF_BEGIN(DAI_RX20DMABUFSIZE2_REG)
REGDEF_BIT(RX20DMABUFSZ, 19)
REGDEF_BIT(, 13)
REGDEF_END(DAI_RX20DMABUFSIZE2_REG)

// RX21 DMA RAM buffer size Register
REGDEF_OFFSET(DAI_RX21DMABUFSIZE2_REG, 0x890)
REGDEF_BEGIN(DAI_RX21DMABUFSIZE2_REG)
REGDEF_BIT(RX21DMABUFSZ, 19)
REGDEF_BIT(, 13)
REGDEF_END(DAI_RX21DMABUFSIZE2_REG)

// RX1 DMA current address Register
REGDEF_OFFSET(DAI_RX1DMACURR_REG, 0x208)
REGDEF_BEGIN(DAI_RX1DMACURR_REG)
REGDEF_BIT(RX1DMACUADR, 32)
REGDEF_END(DAI_RX1DMACURR_REG)

// RX2 DMA current address Register
REGDEF_OFFSET(DAI_RX2DMACURR_REG, 0x228)
REGDEF_BEGIN(DAI_RX2DMACURR_REG)
REGDEF_BIT(RX2DMACUADR, 32)
REGDEF_END(DAI_RX2DMACURR_REG)

// RX3 DMA current address Register
REGDEF_OFFSET(DAI_RX3DMACURR_REG, 0x248)
REGDEF_BEGIN(DAI_RX3DMACURR_REG)
REGDEF_BIT(RX3DMACUADR, 32)
REGDEF_END(DAI_RX3DMACURR_REG)

// RX4 DMA current address Register
REGDEF_OFFSET(DAI_RX4DMACURR_REG, 0x268)
REGDEF_BEGIN(DAI_RX4DMACURR_REG)
REGDEF_BIT(RX4DMACUADR, 32)
REGDEF_END(DAI_RX4DMACURR_REG)

// RX5 DMA current address Register
REGDEF_OFFSET(DAI_RX5DMACURR_REG, 0x288)
REGDEF_BEGIN(DAI_RX5DMACURR_REG)
REGDEF_BIT(RX5DMACUADR, 32)
REGDEF_END(DAI_RX5DMACURR_REG)

// RX6 DMA current address Register
REGDEF_OFFSET(DAI_RX6DMACURR_REG, 0x2A8)
REGDEF_BEGIN(DAI_RX6DMACURR_REG)
REGDEF_BIT(RX6DMACUADR, 32)
REGDEF_END(DAI_RX6DMACURR_REG)

// RX7 DMA current address Register
REGDEF_OFFSET(DAI_RX7DMACURR_REG, 0x2C8)
REGDEF_BEGIN(DAI_RX7DMACURR_REG)
REGDEF_BIT(RX7DMACUADR, 32)
REGDEF_END(DAI_RX7DMACURR_REG)

// RX8 DMA current address Register
REGDEF_OFFSET(DAI_RX8DMACURR_REG, 0x2E8)
REGDEF_BEGIN(DAI_RX8DMACURR_REG)
REGDEF_BIT(RX8DMACUADR, 32)
REGDEF_END(DAI_RX8DMACURR_REG)

// RX9 DMA current address Register
REGDEF_OFFSET(DAI_RX9DMACURR_REG, 0x308)
REGDEF_BEGIN(DAI_RX9DMACURR_REG)
REGDEF_BIT(RX9DMACUADR, 32)
REGDEF_END(DAI_RX9DMACURR_REG)

// RX10 DMA current address Register
REGDEF_OFFSET(DAI_RX10DMACURR_REG, 0x328)
REGDEF_BEGIN(DAI_RX10DMACURR_REG)
REGDEF_BIT(RX10DMACUADR, 32)
REGDEF_END(DAI_RX10DMACURR_REG)

// RX11 DMA current address Register
REGDEF_OFFSET(DAI_RX11DMACURR_REG, 0x348)
REGDEF_BEGIN(DAI_RX11DMACURR_REG)
REGDEF_BIT(RX11DMACUADR, 32)
REGDEF_END(DAI_RX11DMACURR_REG)

// RX12 DMA current address Register
REGDEF_OFFSET(DAI_RX12DMACURR_REG, 0x368)
REGDEF_BEGIN(DAI_RX12DMACURR_REG)
REGDEF_BIT(RX12DMACUADR, 32)
REGDEF_END(DAI_RX12DMACURR_REG)

// RX13 DMA current address Register
REGDEF_OFFSET(DAI_RX13DMACURR_REG, 0x388)
REGDEF_BEGIN(DAI_RX13DMACURR_REG)
REGDEF_BIT(RX13DMACUADR, 32)
REGDEF_END(DAI_RX13DMACURR_REG)

// RX14 DMA current address Register
REGDEF_OFFSET(DAI_RX14DMACURR_REG, 0x3A8)
REGDEF_BEGIN(DAI_RX14DMACURR_REG)
REGDEF_BIT(RX14DMACUADR, 32)
REGDEF_END(DAI_RX14DMACURR_REG)

// RX15 DMA current address Register
REGDEF_OFFSET(DAI_RX15DMACURR_REG, 0x3C8)
REGDEF_BEGIN(DAI_RX15DMACURR_REG)
REGDEF_BIT(RX15DMACUADR, 32)
REGDEF_END(DAI_RX15DMACURR_REG)

// RX16 DMA current address Register
REGDEF_OFFSET(DAI_RX16DMACURR_REG, 0x3E8)
REGDEF_BEGIN(DAI_RX16DMACURR_REG)
REGDEF_BIT(RX16DMACUADR, 32)
REGDEF_END(DAI_RX16DMACURR_REG)

// RX17 DMA current address Register
REGDEF_OFFSET(DAI_RX17DMACURR_REG, 0x408)
REGDEF_BEGIN(DAI_RX17DMACURR_REG)
REGDEF_BIT(RX17DMACUADR, 32)
REGDEF_END(DAI_RX17DMACURR_REG)

// RX18 DMA current address Register
REGDEF_OFFSET(DAI_RX18DMACURR_REG, 0x428)
REGDEF_BEGIN(DAI_RX18DMACURR_REG)
REGDEF_BIT(RX18DMACUADR, 32)
REGDEF_END(DAI_RX18DMACURR_REG)

// RX19 DMA current address Register
REGDEF_OFFSET(DAI_RX19DMACURR_REG, 0x448)
REGDEF_BEGIN(DAI_RX19DMACURR_REG)
REGDEF_BIT(RX19DMACUADR, 32)
REGDEF_END(DAI_RX19DMACURR_REG)

// RX20 DMA current address Register
REGDEF_OFFSET(DAI_RX20DMACURR_REG, 0x468)
REGDEF_BEGIN(DAI_RX20DMACURR_REG)
REGDEF_BIT(RX20DMACUADR, 32)
REGDEF_END(DAI_RX20DMACURR_REG)


// RX21 DMA current address Register
REGDEF_OFFSET(DAI_RX21DMACURR_REG, 0x488)
REGDEF_BEGIN(DAI_RX21DMACURR_REG)
REGDEF_BIT(RX21DMACUADR, 32)
REGDEF_END(DAI_RX21DMACURR_REG)



// RX1 DMA current address Register MSB
REGDEF_OFFSET(DAI_RX1DMACURRMSB_REG, 0x20C)
REGDEF_BEGIN(DAI_RX1DMACURRMSB_REG)
REGDEF_BIT(RX1DMACUADRMSB, 4)
REGDEF_BIT(, 28)
REGDEF_END(DAI_RX1DMACURRMSB_REG)

// RX2 DMA current address Register MSB
REGDEF_OFFSET(DAI_RX2DMACURRMSB_REG, 0x22C)
REGDEF_BEGIN(DAI_RX2DMACURRMSB_REG)
REGDEF_BIT(RX2DMACUADRMSB, 4)
REGDEF_BIT(, 28)
REGDEF_END(DAI_RX2DMACURRMSB_REG)

// RX3 DMA current address Register MSB
REGDEF_OFFSET(DAI_RX3DMACURRMSB_REG, 0x24C)
REGDEF_BEGIN(DAI_RX3DMACURRMSB_REG)
REGDEF_BIT(RX3DMACUADRMSB, 4)
REGDEF_BIT(, 28)
REGDEF_END(DAI_RX3DMACURRMSB_REG)

// RX4 DMA current address Register
REGDEF_OFFSET(DAI_RX4DMACURRMSB_REG, 0x26C)
REGDEF_BEGIN(DAI_RX4DMACURRMSB_REG)
REGDEF_BIT(RX4DMACUADRMSB, 4)
REGDEF_BIT(, 28)
REGDEF_END(DAI_RX4DMACURRMSB_REG)

// RX5 DMA current address Register
REGDEF_OFFSET(DAI_RX5DMACURRMSB_REG, 0x28C)
REGDEF_BEGIN(DAI_RX5DMACURRMSB_REG)
REGDEF_BIT(RX5DMACUADRMSB, 4)
REGDEF_BIT(, 28)
REGDEF_END(DAI_RX5DMACURRMSB_REG)

// RX6 DMA current address Register
REGDEF_OFFSET(DAI_RX6DMACURRMSB_REG, 0x2AC)
REGDEF_BEGIN(DAI_RX6DMACURRMSB_REG)
REGDEF_BIT(RX6DMACUADRMSB, 4)
REGDEF_BIT(, 28)
REGDEF_END(DAI_RX6DMACURRMSB_REG)

// RX7 DMA current address Register
REGDEF_OFFSET(DAI_RX7DMACURRMSB_REG, 0x2CC)
REGDEF_BEGIN(DAI_RX7DMACURRMSB_REG)
REGDEF_BIT(RX7DMACUADRMSB, 4)
REGDEF_BIT(, 28)
REGDEF_END(DAI_RX7DMACURRMSB_REG)

// RX8 DMA current address Register
REGDEF_OFFSET(DAI_RX8DMACURRMSB_REG, 0x2EC)
REGDEF_BEGIN(DAI_RX8DMACURRMSB_REG)
REGDEF_BIT(RX8DMACUADRMSB, 4)
REGDEF_BIT(, 28)
REGDEF_END(DAI_RX8DMACURRMSB_REG)

// RX9 DMA current address Register
REGDEF_OFFSET(DAI_RX9DMACURRMSB_REG, 0x30C)
REGDEF_BEGIN(DAI_RX9DMACURRMSB_REG)
REGDEF_BIT(RX9DMACUADRMSB, 4)
REGDEF_BIT(, 28)
REGDEF_END(DAI_RX9DMACURRMSB_REG)

// RX10 DMA current address Register
REGDEF_OFFSET(DAI_RX10DMACURRMSB_REG, 0x32C)
REGDEF_BEGIN(DAI_RX10DMACURRMSB_REG)
REGDEF_BIT(RX10DMACUADRMSB, 4)
REGDEF_BIT(, 28)
REGDEF_END(DAI_RX10DMACURRMSB_REG)

// RX11 DMA current address Register
REGDEF_OFFSET(DAI_RX11DMACURRMSB_REG, 0x34C)
REGDEF_BEGIN(DAI_RX11DMACURRMSB_REG)
REGDEF_BIT(RX11DMACUADRMSB, 4)
REGDEF_BIT(, 28)
REGDEF_END(DAI_RX11DMACURRMSB_REG)

// RX12 DMA current address Register
REGDEF_OFFSET(DAI_RX12DMACURRMSB_REG, 0x36C)
REGDEF_BEGIN(DAI_RX12DMACURRMSB_REG)
REGDEF_BIT(RX12DMACUADRMSB, 4)
REGDEF_BIT(, 28)
REGDEF_END(DAI_RX12DMACURRMSB_REG)

// RX13 DMA current address Register
REGDEF_OFFSET(DAI_RX13DMACURRMSB_REG, 0x38C)
REGDEF_BEGIN(DAI_RX13DMACURRMSB_REG)
REGDEF_BIT(RX13DMACUADRMSB, 4)
REGDEF_BIT(, 28)
REGDEF_END(DAI_RX13DMACURRMSB_REG)

// RX14 DMA current address Register
REGDEF_OFFSET(DAI_RX14DMACURRMSB_REG, 0x3AC)
REGDEF_BEGIN(DAI_RX14DMACURRMSB_REG)
REGDEF_BIT(RX14DMACUADRMSB, 4)
REGDEF_BIT(, 28)
REGDEF_END(DAI_RX14DMACURRMSB_REG)

// RX15 DMA current address Register
REGDEF_OFFSET(DAI_RX15DMACURRMSB_REG, 0x3CC)
REGDEF_BEGIN(DAI_RX15DMACURRMSB_REG)
REGDEF_BIT(RX15DMACUADRMSB, 4)
REGDEF_BIT(, 28)
REGDEF_END(DAI_RX15DMACURRMSB_REG)

// RX16 DMA current address Register
REGDEF_OFFSET(DAI_RX16DMACURRMSB_REG, 0x3EC)
REGDEF_BEGIN(DAI_RX16DMACURRMSB_REG)
REGDEF_BIT(RX16DMACUADRMSB, 4)
REGDEF_BIT(, 28)
REGDEF_END(DAI_RX16DMACURRMSB_REG)

// RX17 DMA current address Register
REGDEF_OFFSET(DAI_RX17DMACURRMSB_REG, 0x40C)
REGDEF_BEGIN(DAI_RX17DMACURRMSB_REG)
REGDEF_BIT(RX17DMACUADRMSB, 4)
REGDEF_BIT(, 28)
REGDEF_END(DAI_RX17DMACURRMSB_REG)

// RX18 DMA current address Register
REGDEF_OFFSET(DAI_RX18DMACURRMSB_REG, 0x42C)
REGDEF_BEGIN(DAI_RX18DMACURRMSB_REG)
REGDEF_BIT(RX18DMACUADRMSB, 4)
REGDEF_BIT(, 28)
REGDEF_END(DAI_RX18DMACURRMSB_REG)

// RX19 DMA current address Register
REGDEF_OFFSET(DAI_RX19DMACURRMSB_REG, 0x44C)
REGDEF_BEGIN(DAI_RX19DMACURRMSB_REG)
REGDEF_BIT(RX19DMACUADRMSB, 4)
REGDEF_BIT(, 28)
REGDEF_END(DAI_RX19DMACURRMSB_REG)

// RX20 DMA current address Register
REGDEF_OFFSET(DAI_RX20DMACURRMSB_REG, 0x46C)
REGDEF_BEGIN(DAI_RX20DMACURRMSB_REG)
REGDEF_BIT(RX20DMACUADRMSB, 4)
REGDEF_BIT(, 28)
REGDEF_END(DAI_RX20DMACURRMSB_REG)


// RX21 DMA current address Register
REGDEF_OFFSET(DAI_RX21DMACURRMSB_REG, 0x48C)
REGDEF_BEGIN(DAI_RX21DMACURRMSB_REG)
REGDEF_BIT(RX21DMACUADRMSB, 4)
REGDEF_BIT(, 28)
REGDEF_END(DAI_RX21DMACURRMSB_REG)
#endif

#endif

