#
# Copyright (C) 2021 NovaTek Corp.
#
#

obj-$(CONFIG_NVT_CRYPTO) += ns02301_crypto.o
obj-$(CONFIG_NVT_HASH) += ns02301_hash.o
obj-$(CONFIG_NVT_RSA) += ns02301_rsa.o
obj-$(CONFIG_NVT_ECDSA) += ns02301_ecdsa.o
