#
# Copyright (C) 2021 NovaTek Corp.
#
#

obj-$(CONFIG_NVT_CRYPTO) += ns02302_crypto.o
obj-$(CONFIG_NVT_HASH) += ns02302_hash.o
obj-$(CONFIG_NVT_RSA) += ns02302_rsa.o
obj-$(CONFIG_NVT_ECDSA) += ns02302_ecdsa.o
