#ifndef __DSIPHY_REG_H__
#define __DSIPHY_REG_H__

#ifdef __KERNEL__
#include "rcw_macro.h"
#include "kwrap/type.h"
#else

#include "rcw_macro.h"

#endif



/* DSIPHY register */

// 0x000 D-PHY Enable Register
#define DSIPHY_ENABLE_REG_OFS               0x000
REGDEF_BEGIN(DSIPHY_ENABLE_REG)
REGDEF_BIT(DSIPHY_EN, 1)
REGDEF_BIT(DSIPHY_DELAY_EN, 1)
REGDEF_BIT(DSIPHY_HS_SLEW_RATE, 1)
REGDEF_BIT(, 29)
REGDEF_END(DSIPHY_ENABLE_REG)

// 0x004 D-PHY Delay Register
#define DSIPHY_DELAY_REG_OFS                0x004
REGDEF_BEGIN(DSIPHY_DELAY_REG)
REGDEF_BIT(DSIPHY_DAT0_PHASE_OFS, 4)
REGDEF_BIT(DSIPHY_DAT1_PHASE_OFS, 4)
REGDEF_BIT(DSIPHY_DAT2_PHASE_OFS, 4)
REGDEF_BIT(DSIPHY_DAT3_PHASE_OFS, 4)
REGDEF_BIT(, 16)
REGDEF_END(DSIPHY_DELAY_REG)

// 0x008 D-PHY Control Register
#define DSIPHY_CONTROL_REG_OFS              0x008
REGDEF_BEGIN(DSIPHY_CONTROL_REG)
REGDEF_BIT(DSIPHY_OPSEL, 1)
REGDEF_BIT(, 1)
REGDEF_BIT(DSIPHY_SEL, 1)
REGDEF_BIT(DSIPHY_PDO, 1)
REGDEF_BIT(DSIPHY_EN_SLEW, 1)
REGDEF_BIT(DSIPHY_EN_PEM, 1)
REGDEF_BIT(DSIPHY_SR, 2)
REGDEF_BIT(DSIPHY_SF, 2)
REGDEF_BIT(DSIPHY_ISEL_C, 1)
REGDEF_BIT(DSIPHY_ISEL_D, 1)
REGDEF_BIT(DSIPHY_IADJ_C, 3)
REGDEF_BIT(, 1)
REGDEF_BIT(DSIPHY_IADJ_D, 3)
REGDEF_BIT(, 1)
REGDEF_BIT(DSIPHY_CLK_SEL_C, 2)
REGDEF_BIT(, 2)
REGDEF_BIT(DSIPHY_CLK_SEL_D, 4)
REGDEF_BIT(DSIPHY_PLL_SEL, 1)
REGDEF_BIT(, 3)
REGDEF_END(DSIPHY_CONTROL_REG)

// 0x00C D-PHY Current Register
#define DSIPHY_CURRENT_REG_OFS              0x00C
REGDEF_BEGIN(DSIPHY_CURRENT_REG)
REGDEF_BIT(DSIPHY_MODE_18V_EN, 1)
REGDEF_BIT(DSIPHY_LDO_OUTPUT_BYPASS, 1)
REGDEF_BIT(DSIPHY_EN_TEST, 1)
REGDEF_BIT(DSIPHY_EN_INTR, 3)
REGDEF_BIT(, 2)
REGDEF_BIT(DSIPHY_REG_EMCTRL_0, 4)
REGDEF_BIT(DSIPHY_REG_EMCTRL_1, 4)
REGDEF_BIT(DSIPHY_REG_EMCTRL_2, 4)
REGDEF_BIT(DSIPHY_REG_EMCTRL_3, 4)
REGDEF_BIT(DSIPHY_LP_VSEL, 2)
REGDEF_BIT(DSIPHY_TESTREFSEL, 3)
REGDEF_BIT(DSIPHY_LP_DRIVING_CURRENT, 2)
REGDEF_BIT(, 1)
REGDEF_END(DSIPHY_CURRENT_REG)

// 0x100, 0x200 D-PHY Clock Register
#define DSIPHY_CTRL1_CLOCK_REG_OFS          0x100
#define DSIPHY_CTRL2_CLOCK_REG_OFS          0x200
REGDEF_BEGIN(DSIPHY_CTRL_CLOCK_REG)
REGDEF_BIT(PHY_EN_DIV, 1)
REGDEF_BIT(PHY_SEL_CKIN, 1)
REGDEF_BIT(PHY_HS_CLK_INV, 1)
REGDEF_BIT(, 1)
REGDEF_BIT(PHY_DLY_CK, 8)
REGDEF_BIT(, 20)
REGDEF_END(DSIPHY_CTRL_CLOCK_REG)

// 0x104, 0x204 D-PHY Clock Register
#define DSIPHY_CTRL1_CONTROLLER_REG_OFS     0x104
#define DSIPHY_CTRL2_CONTROLLER_REG_OFS     0x204
REGDEF_BEGIN(DSIPHY_CTRL_CONTROLLER_REG)
REGDEF_BIT(DSIPHY_LP_RX_DAT0_EN, 1)
REGDEF_BIT(DSIPHY_LP_RX_DAT1_EN, 1)
REGDEF_BIT(DSIPHY_LP_RX_DAT2_EN, 1)
REGDEF_BIT(DSIPHY_LP_RX_DAT3_EN, 1)
REGDEF_BIT(, 12)
REGDEF_BIT(DSIPHY_REG_EMCTRL_C, 4)
REGDEF_BIT(, 12)
REGDEF_END(DSIPHY_CTRL_CONTROLLER_REG)

// 0x108, 0x208 D-PHY PLL Register 1
#define DSIPHY_CTRL1_PLL1_REG_OFS           0x108
#define DSIPHY_CTRL2_PLL1_REG_OFS           0x208
REGDEF_BEGIN(DSIPHY_CTRL_PLL1_REG)
REGDEF_BIT(REG_DSITXPLL_EN, 1)
REGDEF_BIT(REG_DSITXPLL_EN_C, 1)
REGDEF_BIT(REG_DSITXPLL_EN_TEST_RG, 1)
REGDEF_BIT(REG_DSITXPLL_RESETB, 1)
REGDEF_BIT(REG_DSITXPLL_RG_BG_SEL, 1)
REGDEF_BIT(, 3)
REGDEF_BIT(REG_DSITXPLL_RG_LEVEL, 4)
REGDEF_BIT(REG_DSITXPLL_BAND_SEL, 2)
REGDEF_BIT(REG_DSITXPLL_TEST_RG_SEL, 2)
REGDEF_BIT(REG_DSITXPLL_CP, 2)
REGDEF_BIT(, 14)
REGDEF_END(DSIPHY_CTRL_PLL1_REG)

// 0x10C, 0x20C D-PHY PLL Register 2
// Not used in 538
#define DSIPHY_CTRL1_PLL2_REG_OFS           0x10C
#define DSIPHY_CTRL2_PLL2_REG_OFS           0x20C
REGDEF_BEGIN(DSIPHY_CTRL_PLL2_REG)
REGDEF_BIT(DSIPHY_PLL_TEST_CLK_EN, 1)
REGDEF_BIT(DSIPHY_PLL_TEST_DC_EN, 1)
REGDEF_BIT(DSIPHY_PLL_TEST_DC_SEL, 1)
REGDEF_BIT(DSIPHY_PLL_TEST_DIV_POST_EN, 1)
REGDEF_BIT(DSIPHY_PLL_TEST_VCTRL_EN, 1)
REGDEF_BIT(, 3)
REGDEF_BIT(DSIPHY_PLL_CLK_SEL, 2)
REGDEF_BIT(, 2)
REGDEF_BIT(DSIPHY_PLL_TEST_DIV_POST, 2)
REGDEF_BIT(, 18)
REGDEF_END(DSIPHY_CTRL_PLL2_REG)


#endif
