#ifndef __CSI_TX_REG_H__
#define __CSI_TX_REG_H__



#ifdef __KERNEL__
#include <rcw_macro.h>
#include "kwrap/type.h"

#define REGISTER_ADDR_START 0xf0850000
#define REGISTER_ADDR_END   0xf0850900
#define IRQ_ID              1
#else
#if defined(__FREERTOS)
#include "rcw_macro.h"
#include "kwrap/type.h"
#else
#include "DrvCommon.h"
#endif
#endif


// 0x00 MIPI CSI_TX Global Control 0 Register
#define CSI_TX_GCTRL0_REG_OFS                      0x00
REGDEF_BEGIN(CSI_TX_GCTRL0_REG)
REGDEF_BIT(CSITX_EN, 1)
REGDEF_BIT(, 1)
REGDEF_BIT(LOAD, 1)
REGDEF_BIT(, 1)
REGDEF_BIT(DAT0_ESC_TRIG, 1)
REGDEF_BIT(DAT1_ESC_TRIG, 1)
REGDEF_BIT(DAT2_ESC_TRIG, 1)
REGDEF_BIT(DAT3_ESC_TRIG, 1)
REGDEF_BIT(CLK_ULP_TRIG, 1)
REGDEF_BIT(, 23)
REGDEF_END(CSI_TX_GCTRL0_REG)

// 0x04 MIPI CSI_TX Global Control 1 Register
#define CSI_TX_GCTRL1_REG_OFS                   0x04
REGDEF_BEGIN(CSI_TX_GCTRL1_REG)
REGDEF_BIT(PIXEL_PACK_FMT, 4)
REGDEF_BIT(CSITX_LANE_NO, 2)
REGDEF_BIT(, 6)
REGDEF_BIT(DESKEW_PKT_EN, 2)
REGDEF_BIT(BLANKING_PKT_EN, 1)
REGDEF_BIT(CLK_LP_EN, 1)
REGDEF_BIT(LINE_SP_VACT_EN, 1)
REGDEF_BIT(LINE_SP_VBLK_EN, 1)
REGDEF_BIT(LINE_SP_WC_CTRL, 1)
REGDEF_BIT(FRAME_SP_WC_CTRL, 1)
REGDEF_BIT(, 4)
REGDEF_BIT(U_V_SWAP, 1)
REGDEF_BIT(Y_UV_SWAP, 1)
REGDEF_BIT(, 6)
REGDEF_END(CSI_TX_GCTRL1_REG)

// 0x08 MIPI CSI_TX Global Control 2 Register
#define CSI_TX_GCTRL2_REG_OFS                 0x08
REGDEF_BEGIN(CSI_TX_GCTRL2_REG)
REGDEF_BIT(BUFFER_MODE, 2)
REGDEF_BIT(, 2)
REGDEF_BIT(MANUAL_BUFFER_ID, 2)
REGDEF_BIT(, 2)
REGDEF_BIT(CURR_BUFFER_ID, 2)
REGDEF_BIT(, 22)
REGDEF_END(CSI_TX_GCTRL2_REG)

// 0x10 MIPI CSI_TX Packet Control 0 Register
#define CSI_TX_PACKET_CTRL0_REG_OFS            0x10
REGDEF_BEGIN(CSI_TX_PACKET_CTRL0_REG)
REGDEF_BIT(CSITX_DT, 6)
REGDEF_BIT(CSITX_VC, 2)
REGDEF_BIT(, 16)
REGDEF_BIT(BLANK_DATA, 8)
REGDEF_END(CSI_TX_PACKET_CTRL0_REG)

// 0x14 MIPI CSI_TX Packet Control 1 Register
#define CSI_TX_PACKET_CTRL1_REG_OFS              0x14
REGDEF_BEGIN(CSI_TX_PACKET_CTRL1_REG)
REGDEF_BIT(LINE_SP_WC_FIXED, 16)
REGDEF_BIT(FRAME_SP_WC_FIXED, 16)
REGDEF_END(CSI_TX_PACKET_CTRL1_REG)

// 0x18 MIPI CSI_TX Packet Control 2 Register
//#define CSI_TX_PACKET_CTRL2_REG_OFS              0x18
//REGDEF_BEGIN(CSI_TX_PACKET_CTRL2_REG)
//REGDEF_BIT(INITIAL_DESKEW_PKT_LEN, 16)
//REGDEF_BIT(PERIODIC_DESKEW_PKT_LEN, 16)
//REGDEF_END(CSI_TX_PACKET_CTRL2_REG)

// 0x20 MIPI CSI_TX Escape Control 0 Register
#define CSI_TX_ESCAPE_CTRL0_REG_OFS              0x20
REGDEF_BEGIN(CSI_TX_ESCAPE_CTRL0_REG)
REGDEF_BIT(DAT0_ESC_START, 1)
REGDEF_BIT(DAT1_ESC_START, 1)
REGDEF_BIT(DAT2_ESC_START, 1)
REGDEF_BIT(DAT3_ESC_START, 1)
REGDEF_BIT(DAT0_ESC_STOP, 2)
REGDEF_BIT(DAT1_ESC_STOP, 2)
REGDEF_BIT(DAT2_ESC_STOP, 2)
REGDEF_BIT(DAT3_ESC_STOP, 2)
REGDEF_BIT(CLK_ULP_SEL, 1)
REGDEF_BIT(, 19)
REGDEF_END(CSI_TX_ESCAPE_CTRL0_REG)

// 0x24 MIPI CSI_TX Escape Control 1 Register
#define CSI_TX_ESCAPE_CTRL1_REG_OFS                0x24
REGDEF_BEGIN(CSI_TX_ESCAPE_CTRL1_REG)
REGDEF_BIT(DAT0_ESC_CMD, 8)
REGDEF_BIT(DAT1_ESC_CMD, 8)
REGDEF_BIT(DAT2_ESC_CMD, 8)
REGDEF_BIT(DAT3_ESC_CMD, 8)
REGDEF_END(CSI_TX_ESCAPE_CTRL1_REG)

// 0x40 MIPI CSI_TX Timing Control Register 0
#define CSI_TX_TIME0_REG_OFS               0x40
REGDEF_BEGIN(CSI_TX_TIME0_REG)
REGDEF_BIT(INITIAL_DESKEW_PKT_LEN, 16)
REGDEF_BIT(PERIODIC_DESKEW_PKT_LEN, 16)
REGDEF_END(CSI_TX_TIME0_REG)

// 0x44 MIPI CSI_TX Timing Control Register 1
#define CSI_TX_TIME1_REG_OFS               0x44
REGDEF_BEGIN(CSI_TX_TIME1_REG)
REGDEF_BIT(CSITX_VTOTAL, 13)
REGDEF_BIT(, 3)
REGDEF_BIT(CSITX_VVALID_START, 12)
REGDEF_BIT(, 4)
REGDEF_END(CSI_TX_TIME1_REG)

// 0x48 MIPI CSI_TX Timing Control Register 2
#define CSI_TX_TIME2_REG_OFS               0x48
REGDEF_BEGIN(CSI_TX_TIME2_REG)
REGDEF_BIT(CSITX_VVALID_END, 13)
REGDEF_BIT(, 3)
REGDEF_BIT(CSITX_BLLP, 16)
REGDEF_END(CSI_TX_TIME2_REG)

// 0x4C MIPI CSI_TX Timing Control Register 3
#define CSI_TX_TIME3_REG_OFS                0x4C
REGDEF_BEGIN(CSI_TX_TIME3_REG)
REGDEF_BIT(CSITX_HBP, 12)
REGDEF_BIT(, 4)
REGDEF_BIT(CSITX_HFP, 12)
REGDEF_BIT(, 4)
REGDEF_END(CSI_TX_TIME3_REG)

// 0x50 MIPI CSI_TX Timing Control Register 4
#define CSI_TX_TIME4_REG_OFS               0x50
REGDEF_BEGIN(CSI_TX_TIME4_REG)
REGDEF_BIT(CSITX_HACT, 16)
REGDEF_BIT(CSITX_DESKEW_DLY, 12)
REGDEF_BIT(, 4)
REGDEF_END(CSI_TX_TIME4_REG)

// 0x54 MIPI CSI_TX Timing Control Register 5
#define CSI_TX_TIME5_REG_OFS               0x54
REGDEF_BEGIN(CSI_TX_TIME5_REG)
REGDEF_BIT(CSITX_HINV, 16)
REGDEF_BIT(, 16)
REGDEF_END(CSI_TX_TIME5_REG)


// 0x60 MIPI CSI_TX Bus Timing Control Register 0
#define CSI_TX_BUS_TIME0_REG_OFS            0x60
REGDEF_BEGIN(CSI_TX_BUS_TIME0_REG)
REGDEF_BIT(CSITX_LPX, 4)
REGDEF_BIT(CSITX_THS_PREPARE, 4)
REGDEF_BIT(CSITX_THS_ZERO, 5)
REGDEF_BIT(, 3)
REGDEF_BIT(CSITX_THS_TRAIL, 4)
REGDEF_BIT(CSITX_THS_EXIT, 8)
REGDEF_BIT(, 4)
REGDEF_END(CSI_TX_BUS_TIME0_REG)

// 0x64 MIPI CSI_TX Bus Timing Control Register 1
#define CSI_TX_BUS_TIME1_REG_OFS                  0x64
REGDEF_BEGIN(CSI_TX_BUS_TIME1_REG)
REGDEF_BIT(CSI_TWAKEUP, 11)
REGDEF_BIT(, 1)
REGDEF_BIT(CSITX_TCLK_PREPARE, 4)
REGDEF_BIT(CSITX_TCLK_ZERO, 6)
REGDEF_BIT(, 2)
REGDEF_BIT(CSITX_TCLK_POST, 7)
REGDEF_BIT(, 1)
REGDEF_END(CSI_TX_BUS_TIME1_REG)

// 0x68 MIPI CSI_TX Bus Timing Control Register 2
#define CSI_TX_BUS_TIME2_REG_OFS                  0x68
REGDEF_BEGIN(CSI_TX_BUS_TIME2_REG)
REGDEF_BIT(CSITX_TCLK_PRE, 4)
REGDEF_BIT(CSITX_TCLK_TRAIL, 5)
REGDEF_BIT(, 23)
REGDEF_END(CSI_TX_BUS_TIME2_REG)

// 0x70 MIPI CSI_TX Interrupt Enable Register
#define CSI_TX_INTEN_REG_OFS                  0x70
REGDEF_BEGIN(CSI_TX_INTEN_REG)
REGDEF_BIT(CSITX_DIS_INTEN, 1)
REGDEF_BIT(CSITX_FRM_START_INTEN, 1)
REGDEF_BIT(CSITX_FRM_END_INTEN, 1)
REGDEF_BIT(CSITX_FIFO_UNDERRUN_INTEN, 1)
REGDEF_BIT(CSITX_FRM_WIDTH_ERR_INTEN, 1)
REGDEF_BIT(CSITX_FRM_HEIGHT_ERR_INTEN, 1)
REGDEF_BIT(CSITX_FRM_TOTAL_END_INTEN, 1)
REGDEF_BIT(CSITX_LINEBUF_EMPTY_INTEN, 1)
REGDEF_BIT(, 16)
REGDEF_BIT(DAT0_ESC_DONE_INTEN, 1)
REGDEF_BIT(DAT1_ESC_DONE_INTEN, 1)
REGDEF_BIT(DAT2_ESC_DONE_INTEN, 1)
REGDEF_BIT(DAT3_ESC_DONE_INTEN, 1)
REGDEF_BIT(CLK_ULPS_DONE_INTEN, 1)
REGDEF_BIT(, 3)
REGDEF_END(CSI_TX_INTEN_REG)

// 0x78 MIPI CSI_TX Interrupt Status Register
#define CSI_TX_INTSTS_REG_OFS                  0x78
REGDEF_BEGIN(CSI_TX_INTSTS_REG)
REGDEF_BIT(CSITX_DIS_STS, 1)
REGDEF_BIT(CSITX_FRM_START_STS, 1)
REGDEF_BIT(CSITX_FRM_END_STS, 1)
REGDEF_BIT(CSITX_FIFO_UNDERRUN_STS, 1)
REGDEF_BIT(CSITX_FRM_WIDTH_ERR_STS, 1)
REGDEF_BIT(CSITX_FRM_HEIGHT_ERR_STS, 1)
REGDEF_BIT(CSITX_FRM_TOTAL_END_STS, 1)
REGDEF_BIT(CSITX_LINEBUF_EMPTY_STS, 1)
REGDEF_BIT(, 16)
REGDEF_BIT(DAT0_ESC_DONE_STS, 1)
REGDEF_BIT(DAT1_ESC_DONE_STS, 1)
REGDEF_BIT(DAT2_ESC_DONE_STS, 1)
REGDEF_BIT(DAT3_ESC_DONE_STS, 1)
REGDEF_BIT(CLK_ULPS_DONE_STS, 1)
REGDEF_BIT(, 3)
REGDEF_END(CSI_TX_INTSTS_REG)

// 0x98 MIPI CSI_TX Buffer dimension Register 1
#define CSI_TX_BUFF_DIM_REG_OFS                  0x98
REGDEF_BEGIN(CSI_TX_BUF_DIM_ADDR_REG)
REGDEF_BIT(FRAME_WIDTH, 13)
REGDEF_BIT(, 3)
REGDEF_BIT(FRAME_HEIGHT, 12)
REGDEF_BIT(, 4)
REGDEF_END(CSI_TX_BUF_DIM_ADDR_REG)

// 0x9C MIPI CSI_TX Buffer Attribute Register 1
#define CSI_TX_BUFF_ATTR_REG_OFS                  0x9C
REGDEF_BEGIN(CSI_TX_BUF_ATTR_ADDR_REG)
REGDEF_BIT(Y_LINE_OFFSET, 13)
REGDEF_BIT(, 3)
REGDEF_BIT(UV_LINE_OFFSET, 13)
REGDEF_BIT(, 3)
REGDEF_END(CSI_TX_BUF_ATTR_ADDR_REG)

// 0xA4 MIPI CSI_TX Axi Wrapper Control Register
#define CSI_TX_AXIWRAP_CTRL_REG_OFS                  0xA4
REGDEF_BEGIN(CSI_TX_AXIWRAP_CTRL_REG)
REGDEF_BIT(CSITX_WRAP1_EN, 1)
REGDEF_BIT(CSITX_WRAP2_EN, 1)
REGDEF_BIT(, 2)
REGDEF_BIT(CSITX_WRAP1_LOCK_EN, 1)
REGDEF_BIT(CSITX_WRAP2_LOCK_EN, 1)
REGDEF_BIT(, 2)
REGDEF_BIT(CSITX_AXI_W_OSTD_NUM, 8)
REGDEF_BIT(CSITX_AXI_R_OSTD_NUM, 8)
REGDEF_BIT(CSITX_AXI_CH_DIS, 1)
REGDEF_BIT(, 7)
REGDEF_END(CSI_TX_AXIWRAP_CTRL_REG)

// 0xA8 MIPI CSI_TX Axi Wrapper Status Register
#define CSI_TX_AXIWRAP_STS_REG_OFS                  0xA8
REGDEF_BEGIN(CSI_TX_AXIWRAP_STS_REG)
REGDEF_BIT(CSITX_WRAP_STS, 32)
REGDEF_END(CSI_TX_AXIWRAP_STS_REG)

// 0xAC MIPI CSI_TX Command Control Register
#define CSI_TX_CMD_CTRL_REG_OFS                  0xAC
REGDEF_BEGIN(CSI_TX_CMD_CTRL_REG)
REGDEF_BIT(CSITX_ACMD_ENABLE, 1)
REGDEF_BIT(, 3)
REGDEF_BIT(CSITX_ACMD_NUMBER, 3)
REGDEF_BIT(, 25)
REGDEF_END(CSI_TX_CMD_CTRL_REG)

// 0xB0 MIPI CSI_TX Command 0 Register
#define CSI_TX_CMD0_REG_OFS                  0xB0
REGDEF_BEGIN(CSI_TX_CMD0_REG)
REGDEF_BIT(CSITX_CMD0_DT, 6)
REGDEF_BIT(CSITX_CMD0_VC, 2)
REGDEF_BIT(CSITX_CMD0_WC, 16)
REGDEF_BIT(, 4)
REGDEF_BIT(CSITX_CMD0_PT, 1)
REGDEF_BIT(, 3)
REGDEF_END(CSI_TX_CMD0_REG)

// 0xB4 MIPI CSI_TX Command 1 Register
#define CSI_TX_CMD1_REG_OFS                  0xB4
REGDEF_BEGIN(CSI_TX_CMD1_REG)
REGDEF_BIT(CSITX_CMD_DT, 6)
REGDEF_BIT(CSITX_CMD_VC, 2)
REGDEF_BIT(CSITX_CMD_WC, 16)
REGDEF_BIT(, 4)
REGDEF_BIT(CSITX_CMD_PT, 1)
REGDEF_BIT(, 3)
REGDEF_END(CSI_TX_CMD1_REG)

// 0xB8 MIPI CSI_TX Command 2 Register
#define CSI_TX_CMD2_REG_OFS                  0xB8
REGDEF_BEGIN(CSI_TX_CMD2_REG)
REGDEF_BIT(CSITX_CMD_DT, 6)
REGDEF_BIT(CSITX_CMD_VC, 2)
REGDEF_BIT(CSITX_CMD_WC, 16)
REGDEF_BIT(, 4)
REGDEF_BIT(CSITX_CMD_PT, 1)
REGDEF_BIT(, 3)
REGDEF_END(CSI_TX_CMD2_REG)

// 0xBC MIPI CSI_TX Command 3 Register
#define CSI_TX_CMD3_REG_OFS                  0xBC
REGDEF_BEGIN(CSI_TX_CMD3_REG)
REGDEF_BIT(CSITX_CMD_DT, 6)
REGDEF_BIT(CSITX_CMD_VC, 2)
REGDEF_BIT(CSITX_CMD_WC, 16)
REGDEF_BIT(, 4)
REGDEF_BIT(CSITX_CMD_PT, 1)
REGDEF_BIT(, 3)
REGDEF_END(CSI_TX_CMD3_REG)

// 0xC0 MIPI CSI_TX Command 4 Register
#define CSI_TX_CMD4_REG_OFS                  0xC0
REGDEF_BEGIN(CSI_TX_CMD4_REG)
REGDEF_BIT(CSITX_CMD_DT, 6)
REGDEF_BIT(CSITX_CMD_VC, 2)
REGDEF_BIT(CSITX_CMD_WC, 16)
REGDEF_BIT(, 4)
REGDEF_BIT(CSITX_CMD_PT, 1)
REGDEF_BIT(, 3)
REGDEF_END(CSI_TX_CMD4_REG)

// 0xC4 MIPI CSI_TX Command 5 Register
#define CSI_TX_CMD5_REG_OFS                  0xC4
REGDEF_BEGIN(CSI_TX_CMD5_REG)
REGDEF_BIT(CSITX_CMD_DT, 6)
REGDEF_BIT(CSITX_CMD_VC, 2)
REGDEF_BIT(CSITX_CMD_WC, 16)
REGDEF_BIT(, 4)
REGDEF_BIT(CSITX_CMD_PT, 1)
REGDEF_BIT(, 3)
REGDEF_END(CSI_TX_CMD5_REG)

// 0xC8 MIPI CSI_TX Command 6 Register
#define CSI_TX_CMD6_REG_OFS                  0xC8
REGDEF_BEGIN(CSI_TX_CMD6_REG)
REGDEF_BIT(CSITX_CMD_DT, 6)
REGDEF_BIT(CSITX_CMD_VC, 2)
REGDEF_BIT(CSITX_CMD_WC, 16)
REGDEF_BIT(, 4)
REGDEF_BIT(CSITX_CMD_PT, 1)
REGDEF_BIT(, 3)
REGDEF_END(CSI_TX_CMD6_REG)

// 0xCC MIPI CSI_TX Command 7 Register
#define CSI_TX_CMD7_REG_OFS                  0xCC
REGDEF_BEGIN(CSI_TX_CMD7_REG)
REGDEF_BIT(CSITX_CMD_DT, 6)
REGDEF_BIT(CSITX_CMD_VC, 2)
REGDEF_BIT(CSITX_CMD_WC, 16)
REGDEF_BIT(, 4)
REGDEF_BIT(CSITX_CMD_PT, 1)
REGDEF_BIT(, 3)
REGDEF_END(CSI_TX_CMD7_REG)

// 0xD0 MIPI CSI_TX PHY Register
#define CSI_TX_PHY_REG_OFS                  0xD0
REGDEF_BEGIN(CSI_TX_PHY_REG)
REGDEF_BIT(,29)
REGDEF_BIT(CD_STOP_PHY, 1)
REGDEF_BIT(,2)
REGDEF_END(CSI_TX_PHY_REG)

// 0xD4 MIPI CSI_TX Phy  Register 2
#define CSITXPHY_DATA_LAN_REG_OFS               0xD4
REGDEF_BEGIN(CSITXPHY_DATA_LAN_REG)
REGDEF_BIT(, 20)
REGDEF_BIT(DAT0_LAND_SEL, 2)
REGDEF_BIT(DAT1_LAND_SEL, 2)
REGDEF_BIT(DAT2_LAND_SEL, 2)
REGDEF_BIT(DAT3_LAND_SEL, 2)
REGDEF_BIT(, 4)
REGDEF_END(CSITXPHY_DATA_LAN_REG)

// 0xD8 MIPI CSI_TX Phy Register 3
#define CSI_TX_PHY3_REG_OFS                  0xD8
REGDEF_BEGIN(CSI_TX_PHY3_REG)
REGDEF_BIT(, 32)
REGDEF_END(CSI_TX_PHY3_REG)

// 0xDC CSI_TX PHY IO Test Mode Control Register
#define CSI_TX_IO_TEST_CTRL_REG_OFS            0xDC
REGDEF_BEGIN(CSI_TX_IO_TEST_CTRL_REG)
REGDEF_BIT(PHY_IO_TEST_EN, 1)
REGDEF_BIT(, 3)
REGDEF_BIT(PHY_IO_TEST_SEL, 2)
REGDEF_BIT(, 2)
REGDEF_BIT(PHY_IO_TEST_OUT_DATA_SEL, 2)
REGDEF_BIT(, 2)
REGDEF_BIT(PHY_IO_TEST_OUT_CLK_SEL, 2)
REGDEF_BIT(, 18)
REGDEF_END(CSI_TX_IO_TEST_CTRL_REG)



// 0xE4 CSI_TX PHY IO Test Mode Input Data Register
#define CSI_TX_IO_TEST_INPUT_DATA_REG_OFS      0xE4
REGDEF_BEGIN(CSI_TX_IO_TEST_INPUT_DATA_REG)
REGDEF_BIT(DAT0_POS_LP_INPUT, 1)
REGDEF_BIT(DAT0_NEG_LP_INPUT, 1)
REGDEF_BIT(DAT0_POS_CONTENT_DET, 1)
REGDEF_BIT(DAT0_NEG_CONTENT_DET, 1)
REGDEF_BIT(DAT1_POS_LP_INPUT, 1)
REGDEF_BIT(DAT1_NEG_LP_INPUT, 1)
REGDEF_BIT(DAT1_POS_CONTENT_DET, 1)
REGDEF_BIT(DAT1_NEG_CONTENT_DET, 1)
REGDEF_BIT(DAT2_POS_LP_INPUT, 1)
REGDEF_BIT(DAT2_NEG_LP_INPUT, 1)
REGDEF_BIT(DAT2_POS_CONTENT_DET, 1)
REGDEF_BIT(DAT2_NEG_CONTENT_DET, 1)
REGDEF_BIT(DAT3_POS_LP_INPUT, 1)
REGDEF_BIT(DAT3_NEG_LP_INPUT, 1)
REGDEF_BIT(DAT3_POS_CONTENT_DET, 1)
REGDEF_BIT(DAT3_NEG_CONTENT_DET, 1)
REGDEF_BIT(, 16)
REGDEF_END(CSI_TX_IO_TEST_INPUT_DATA_REG)

// 0xE8 CSI_TX check pixel register
#define CSI_TX_CHK_PIXEL_REG_OFS               0xE8
REGDEF_BEGIN(CSI_TX_CHK_PIXEL_REG)
REGDEF_BIT(DRAM_CHECK_DATA, 8)
REGDEF_BIT(, 8)
REGDEF_BIT(CSI_TX_CHECK_DATA, 8)
REGDEF_BIT(, 8)
REGDEF_END(CSI_TX_CHK_PIXEL_REG)

// 0xEC CSI_TX version register
#define CSI_TX_VERSION_REG_OFS                 0xEC
REGDEF_BEGIN(CSI_TX_VERSION_REG)
REGDEF_BIT(CSI_TX_VERSION, 32)
REGDEF_END(CSI_TX_VERSION_REG)

// 0xF0 CSI_TX PHY IO Test Mode Output Data0 Register
#define CSI_TX_IO_TEST_DAT0_OUT_REG_OFS        0xF0
REGDEF_BEGIN(CSI_TX_IO_TEST_DAT0_OUT_REG)
REGDEF_BIT(IO_TEST_DAT0_OUT, 24)
REGDEF_BIT(, 8)
REGDEF_END(CSI_TX_IO_TEST_DAT0_OUT_REG)

// 0xF4 CSI_TX PHY IO Test Mode Output Data1 Register
#define CSI_TX_IO_TEST_DAT1_OUT_REG_OFS        0xF4
REGDEF_BEGIN(CSI_TX_IO_TEST_DAT1_OUT_REG)
REGDEF_BIT(IO_TEST_DAT1_OUT, 24)
REGDEF_BIT(, 8)
REGDEF_END(CSI_TX_IO_TEST_DAT1_OUT_REG)

// 0xF8 CSI_TX PHY IO Test Mode Output Data1 Register
#define CSI_TX_IO_TEST_DAT2_OUT_REG_OFS        0xF8
REGDEF_BEGIN(CSI_TX_IO_TEST_DAT2_OUT_REG)
REGDEF_BIT(IO_TEST_DAT2_OUT, 24)
REGDEF_BIT(, 8)
REGDEF_END(CSI_TX_IO_TEST_DAT2_OUT_REG)

// 0xFC CSI_TX PHY IO Test Mode Output Data1 Register
#define CSI_TX_IO_TEST_DAT3_OUT_REG_OFS        0xFC
REGDEF_BEGIN(CSI_TX_IO_TEST_DAT3_OUT_REG)
REGDEF_BIT(IO_TEST_DAT3_OUT, 24)
REGDEF_BIT(, 8)
REGDEF_END(CSI_TX_IO_TEST_DAT3_OUT_REG)


#if 0
// 0xD0 MIPI CSI_TX Phy Register
#define CSI_TX_DEBUG2_REG_OFS                  0xD0
REGDEF_BEGIN(CSI_TX_DEBUG2_REG)
REGDEF_BIT(CONTENT_HS_SEL, 1)
REGDEF_BIT(, 1)
REGDEF_BIT(PHY_LP_VSEL, 2)
REGDEF_BIT(CONTENT_LP_HF_D0P, 2)
REGDEF_BIT(, 2)
REGDEF_BIT(CONTENT_LP_HF_D0N, 2)
REGDEF_BIT(, 2)
REGDEF_BIT(CONTENT_LP_LF_D0P, 2)
REGDEF_BIT(, 2)
REGDEF_BIT(CONTENT_LP_LF_D0N, 2)
REGDEF_BIT(, 1)
REGDEF_BIT(PHY_HS_SLEW_RATE, 1)
REGDEF_BIT(PHY_HS_DRIVING, 3)
REGDEF_BIT(PHY_TRANSITION_OVLP, 1)
REGDEF_BIT(PHY_LP_DRIVING, 2)
REGDEF_BIT(, 2)
REGDEF_BIT(VDO_MODE_SLICE_INTERVAL_PACKET_TYPE, 1)
REGDEF_BIT(CD_STOP_PHY, 1)
REGDEF_BIT(PHY_DIV8_EN, 1)
REGDEF_BIT(PHY_CKIN_SEL, 1)
REGDEF_END(CSI_TX_DEBUG2_REG)

// 0xD4 MIPI CSI_TX Phy 1 Register
#define CSI_TX_DEBUG3_REG_OFS                  0xD4
REGDEF_BEGIN(CSI_TX_DEBUG3_REG)
REGDEF_BIT(CLK_PHASE_OFS, 3)
REGDEF_BIT(, 1)
REGDEF_BIT(DAT0_PHASE_OFS, 3)
REGDEF_BIT(, 1)
REGDEF_BIT(DAT1_PHASE_OFS, 3)
REGDEF_BIT(, 1)
REGDEF_BIT(DAT2_PHASE_OFS, 3)
REGDEF_BIT(, 1)
REGDEF_BIT(DAT3_PHASE_OFS, 3)
REGDEF_BIT(, 1)
REGDEF_BIT(DAT0_LAND_SEL, 2)
REGDEF_BIT(DAT1_LAND_SEL, 2)
REGDEF_BIT(DAT2_LAND_SEL, 2)
REGDEF_BIT(DAT3_LAND_SEL, 2)
REGDEF_BIT(PHY_HS_CLK_INV, 1)
REGDEF_BIT(, 2)
REGDEF_BIT(PHY_DELAY_EN, 1)
REGDEF_END(CSI_TX_DEBUG3_REG)

// 0xD8 MIPI CSI_TX Phy 2 Register
#define CSI_TX_DEBUG4_REG_OFS                  0xD8
REGDEF_BEGIN(CSI_TX_DEBUG4_REG)
REGDEF_BIT(PHY_OPSEL, 1)
REGDEF_BIT(PHY_ISEL, 1)
REGDEF_BIT(PHY_VSEL, 1)
REGDEF_BIT(PHY_PDO, 1)
REGDEF_BIT(PHY_EN_SLEW, 1)
REGDEF_BIT(PHY_EN_PEM, 1)
REGDEF_BIT(PHY_SR, 2)
REGDEF_BIT(PHY_SF, 2)
REGDEF_BIT(, 18)
REGDEF_BIT(PHY_LP_RX_DAT0_EN, 1)
REGDEF_BIT(PHY_LP_RX_DAT1_EN, 1)
REGDEF_BIT(PHY_LP_RX_DAT2_EN, 1)
REGDEF_BIT(PHY_LP_RX_DAT3_EN, 1)
REGDEF_END(CSI_TX_DEBUG4_REG)

// 0xDC CSI_TX PHY IO Test Mode Control Register
#define CSI_TX_IO_TEST_CTRL_REG_OFS            0xDC
REGDEF_BEGIN(CSI_TX_IO_TEST_CTRL_REG)
REGDEF_BIT(PHY_IO_TEST_EN, 1)
REGDEF_BIT(, 3)
REGDEF_BIT(PHY_IO_TEST_SEL, 2)
REGDEF_BIT(, 2)
REGDEF_BIT(PHY_IO_TEST_OUT_DATA_SEL, 2)
REGDEF_BIT(, 2)
REGDEF_BIT(PHY_IO_TEST_OUT_CLK_SEL, 2)
REGDEF_BIT(, 18)
REGDEF_END(CSI_TX_IO_TEST_CTRL_REG)

// 0x300 CSI_TX Phy Register 3
#define CSI_TX_PHY3_REG_OFS                    0x300
REGDEF_BEGIN(CSI_TX_PHY3_REG)
REGDEF_BIT(PHY_EN_DSI_MODE_18V, 1)
REGDEF_BIT(PHY_BYPASS, 1)
REGDEF_BIT(PHY_EN_TEST, 1)
REGDEF_BIT(PHY_EN_INTR, 3)
REGDEF_BIT(PHY_TESTREFSEL, 2)
REGDEF_BIT(PHY_REG_EMCTRL_0, 4)
REGDEF_BIT(PHY_REG_EMCTRL_1, 4)
REGDEF_BIT(PHY_REG_EMCTRL_2, 4)
REGDEF_BIT(PHY_REG_EMCTRL_3, 4)
REGDEF_BIT(PHY_REG_EMCTRL_C, 4)
REGDEF_BIT(, 4)
REGDEF_END(CSI_TX_PHY3_REG)

// 0x304 CSI_TX Phy PLL Register 0
#define CSI_TX_PHY_PLL0_REG_OFS                0x304
REGDEF_BEGIN(CSI_TX_PHY_PLL0_REG)
REGDEF_BIT(PHY_PLL_SEL, 1)
REGDEF_BIT(, 3)
REGDEF_BIT(PHY_REG_DSITXPLL_BAND_SEL, 4)
REGDEF_BIT(PHY_REG_DSITXPLL_CP, 2)
REGDEF_BIT(, 2)
REGDEF_BIT(PHY_REG_DSITXPLL_DIV_CNT, 6)
REGDEF_BIT(, 2)
REGDEF_BIT(REG_DSITXPLL_EN, 1)
REGDEF_BIT(PHY_REG_DSITXPLL_EN_C, 1)
REGDEF_BIT(PHY_REG_DSITXPLL_EN_TEST_RG, 1)
REGDEF_BIT(PHY_REG_DSITXPLL_EN_TEST_VCTRL, 1)
REGDEF_BIT(REG_DSITXPLL_NCBAND_SEL, 5)
REGDEF_BIT(, 3)
REGDEF_END(CSI_TX_PHY_PLL0_REG)

// 0x308 CSI_TX Phy PLL Register 1
#define CSI_TX_PHY_PLL1_REG_OFS                0x308
REGDEF_BEGIN(CSI_TX_PHY_PLL1_REG)
REGDEF_BIT(REG_DSITXPLL_POSTDIV_CNT, 6)
REGDEF_BIT(, 2)
REGDEF_BIT(REG_DSITXPLL_RG_BG_SEL, 1)
REGDEF_BIT(, 3)
REGDEF_BIT(REG_DSITXPLL_RG_LEVEL, 2)
REGDEF_BIT(, 2)
REGDEF_BIT(REG_DSITXPLL_TEST_RG_SEL, 2)
REGDEF_BIT(, 2)
REGDEF_BIT(REG_DSITXPLL_RESETB, 1)
REGDEF_BIT(, 11)
REGDEF_END(CSI_TX_PHY_PLL1_REG)
#endif

// 0x100-0x1FC MIPI CSI_TX SRAM Register Bank
#define CSI_TX_SRAM_REG_OFS                    0x100


// 0x200 MIPI CSI_TX LINE START CNT Register
#define CSI_TX_LINE_STCNT_REG_OFS              0x200
REGDEF_BEGIN(CSI_TX_LINE_STCNT_REG)
REGDEF_BIT(CSITX_CNT, 16)
REGDEF_BIT(CSITX_CNT_CL, 1)
REGDEF_BIT(, 15)
REGDEF_END(CSI_TX_LINE_STCNT_REG)

// 0x204 MIPI CSI_TX LINE END CNT Register
#define CSI_TX_LINE_ENDCNT_REG_OFS             0x204
REGDEF_BEGIN(CSI_TX_LINE_ENDCNT_REG)
REGDEF_BIT(CSITX_CNT, 16)
REGDEF_BIT(CSITX_CNT_CL, 1)
REGDEF_BIT(, 15)
REGDEF_END(CSI_TX_LINE_ENDCNT_REG)

// 0x208 MIPI CSI_TX FRAME START CNT Register
#define CSI_TX_FRAME_STCNT_REG_OFS             0x208
REGDEF_BEGIN(CSI_TX_FRAME_STCNT_REG)
REGDEF_BIT(CSITX_CNT, 16)
REGDEF_BIT(CSITX_CNT_CL, 1)
REGDEF_BIT(, 15)
REGDEF_END(CSI_TX_FRAME_STCNT_REG)

// 0x20C MIPI CSI_TX FRAME END CNT Register
#define CSI_TX_FRAME_ENDCNT_REG_OFS            0x20C
REGDEF_BEGIN(CSI_TX_FRAME_ENDCNT_REG)
REGDEF_BIT(CSITX_CNT, 16)
REGDEF_BIT(CSITX_CNT_CL, 1)
REGDEF_BIT(, 15)
REGDEF_END(CSI_TX_FRAME_ENDCNT_REG)


// 0x300 MIPI CSI_TX Buffer0 address Register 0
#define CSI_TX_BUFF0_0_REG_OFS                  0x300
REGDEF_BEGIN(CSI_TX_BUF0_0_ADDR_REG)
REGDEF_BIT(BUF0_0_ADDR, 32)
REGDEF_END(CSI_TX_BUF0_0_ADDR_REG)

// 0x304 MIPI CSI_TX Buffer0 MSB address Register 0
#define CSI_TX_BUFF0_0_MSB_REG_OFS                  0x304
REGDEF_BEGIN(CSI_TX_BUF0_0_ADDR_MSB_REG)
REGDEF_BIT(BUF0_0_ADDR_MSB, 32)
REGDEF_END(CSI_TX_BUF0_0_ADDR_MSB_REG)

// 0x308 MIPI CSI_TX Buffer0 address Register 1
#define CSI_TX_BUFF0_1_REG_OFS                  0x308
REGDEF_BEGIN(CSI_TX_BUF0_1_ADDR_REG)
REGDEF_BIT(BUF0_1_ADDR, 32)
REGDEF_END(CSI_TX_BUF0_1_ADDR_REG)

// 0x30C MIPI CSI_TX Buffer0 address MSB Register 1
#define CSI_TX_BUFF0_1_MSB_REG_OFS                  0x30C
REGDEF_BEGIN(CSI_TX_BUF0_1_ADDR_MSB_REG)
REGDEF_BIT(BUF0_1_ADDR_MSB, 32)
REGDEF_END(CSI_TX_BUF0_1_ADDR_MSB_REG)

// 0x310 MIPI CSI_TX Buffer1 address Register 0
#define CSI_TX_BUFF1_0_REG_OFS                  0x310
REGDEF_BEGIN(CSI_TX_BUF1_0_ADDR_REG)
REGDEF_BIT(BUF1_0_ADDR, 32)
REGDEF_END(CSI_TX_BUF1_0_ADDR_REG)

// 0x314 MIPI CSI_TX Buffer1 address MSB Register 0
#define CSI_TX_BUFF1_0_MSB_REG_OFS                  0x314
REGDEF_BEGIN(CSI_TX_BUF1_0_ADDR_MSB_REG)
REGDEF_BIT(BUF1_0_ADDR_MSB, 32)
REGDEF_END(CSI_TX_BUF1_0_ADDR_MSB_REG)

// 0x318 MIPI CSI_TX Buffer1 address Register 1
#define CSI_TX_BUFF1_1_REG_OFS                  0x318
REGDEF_BEGIN(CSI_TX_BUF1_1_ADDR_REG)
REGDEF_BIT(BUF1_1_ADDR, 32)
REGDEF_END(CSI_TX_BUF1_1_ADDR_REG)

// 0x31C MIPI CSI_TX Buffer1 address MSB Register 1
#define CSI_TX_BUFF1_1_MSB_REG_OFS                  0x31C
REGDEF_BEGIN(CSI_TX_BUF1_1_ADDR_MSB_REG)
REGDEF_BIT(BUF1_1_ADDR_MSB, 32)
REGDEF_END(CSI_TX_BUF1_1_ADDR_MSB_REG)

// 0x320 MIPI CSI_TX Buffer2 address Register 0
#define CSI_TX_BUFF2_0_REG_OFS                  0x320
REGDEF_BEGIN(CSI_TX_BUF2_0_ADDR_REG)
REGDEF_BIT(BUF2_0_ADDR, 32)
REGDEF_END(CSI_TX_BUF2_0_ADDR_REG)

// 0x324 MIPI CSI_TX Buffer2 address MSB Register 0
#define CSI_TX_BUFF2_0_MSB_REG_OFS                  0x324
REGDEF_BEGIN(CSI_TX_BUF2_0_ADDR_MSB_REG)
REGDEF_BIT(BUF2_0_ADDR_MSB, 32)
REGDEF_END(CSI_TX_BUF2_0_ADDR_MSB_REG)

// 0x328 MIPI CSI_TX Buffer2 address Register 1
#define CSI_TX_BUFF2_1_REG_OFS                  0x328
REGDEF_BEGIN(CSI_TX_BUF2_1_ADDR_REG)
REGDEF_BIT(BUF2_1_ADDR, 32)
REGDEF_END(CSI_TX_BUF2_1_ADDR_REG)

// 0x32C MIPI CSI_TX Buffer2 address MSB Register 1
#define CSI_TX_BUFF2_1_MSB_REG_OFS                  0x32C
REGDEF_BEGIN(CSI_TX_BUF2_1_ADDR_MSB_REG)
REGDEF_BIT(BUF2_1_ADDR_MSB, 32)
REGDEF_END(CSI_TX_BUF2_1_ADDR_MSB_REG)



/* CSITXPHY register */

// 0x000 D-PHY Enable Register
#define CSITXPHY_ENABLE_REG_OFS               0x000
REGDEF_BEGIN(CSITXPHY_ENABLE_REG)
REGDEF_BIT(CSITXPHY_EN, 1)
REGDEF_BIT(CSITXPHY_DELAY_EN, 1)
REGDEF_BIT(CSITXPHY_HS_SLEW_RATE, 1)
REGDEF_BIT(, 29)
REGDEF_END(CSITXPHY_ENABLE_REG)

// 0x004 D-PHY Delay Register
#define CSITXPHY_DELAY_REG_OFS                0x004
REGDEF_BEGIN(CSITXPHY_DELAY_REG)
REGDEF_BIT(CSITXPHY_DAT0_PHASE_OFS, 4)
REGDEF_BIT(CSITXPHY_DAT1_PHASE_OFS, 4)
REGDEF_BIT(CSITXPHY_DAT2_PHASE_OFS, 4)
REGDEF_BIT(CSITXPHY_DAT3_PHASE_OFS, 4)
REGDEF_BIT(, 16)
REGDEF_END(CSITXPHY_DELAY_REG)

// 0x008 D-PHY Control Register
#define CSITXPHY_CONTROL_REG_OFS              0x008
REGDEF_BEGIN(CSITXPHY_CONTROL_REG)
REGDEF_BIT(CSITXPHY_OPSEL, 1)
REGDEF_BIT(, 1)
REGDEF_BIT(CSITXPHY_SEL, 1)
REGDEF_BIT(CSITXPHY_PDO, 1)
REGDEF_BIT(CSITXPHY_EN_SLEW, 1)
REGDEF_BIT(CSITXPHY_EN_PEM, 1)
REGDEF_BIT(CSITXPHY_SR, 2)
REGDEF_BIT(CSITXPHY_SF, 2)
REGDEF_BIT(CSITXPHY_ISEL_C, 1)
REGDEF_BIT(CSITXPHY_ISEL_D, 1)
REGDEF_BIT(CSITXPHY_IADJ_C, 3)
REGDEF_BIT(, 1)
REGDEF_BIT(CSITXPHY_IADJ_D, 3)
REGDEF_BIT(, 1)
REGDEF_BIT(CSITXPHY_CLK_SEL_C, 2)
REGDEF_BIT(, 2)
REGDEF_BIT(CSITXPHY_CLK_SEL_D, 4)
REGDEF_BIT(CSITXPHY_PLL_SEL, 1)
REGDEF_BIT(, 3)
REGDEF_END(CSITXPHY_CONTROL_REG)

// 0x00C D-PHY Current Register
#define CSITXPHY_CURRENT_REG_OFS              0x00C
REGDEF_BEGIN(CSITXPHY_CURRENT_REG)
REGDEF_BIT(CSITXPHY_MODE_18V_EN, 1)
REGDEF_BIT(CSITXPHY_LDO_OUTPUT_BYPASS, 1)
REGDEF_BIT(CSITXPHY_EN_TEST, 1)
REGDEF_BIT(CSITXPHY_EN_INTR, 3)
REGDEF_BIT(, 2)
REGDEF_BIT(CSITXPHY_REG_EMCTRL_0, 4)
REGDEF_BIT(CSITXPHY_REG_EMCTRL_1, 4)
REGDEF_BIT(CSITXPHY_REG_EMCTRL_2, 4)
REGDEF_BIT(CSITXPHY_REG_EMCTRL_3, 4)
REGDEF_BIT(CSITXPHY_LP_VSEL, 2)
REGDEF_BIT(CSITXPHY_TESTREFSEL, 3)
REGDEF_BIT(CSITXPHY_LP_DRIVING_CURRENT, 2)
REGDEF_BIT(, 1)
REGDEF_END(CSITXPHY_CURRENT_REG)

// 0x100, 0x200 D-PHY Clock Register
#define CSITXPHY_CTRL1_CLOCK_REG_OFS          0x100
#define CSITXPHY_CTRL2_CLOCK_REG_OFS          0x200
REGDEF_BEGIN(CSITXPHY_CTRL_CLOCK_REG)
REGDEF_BIT(CSITXPHY_DIV8_EN, 1)
REGDEF_BIT(CSITXPHY_CKIN_SEL, 1)
REGDEF_BIT(CSITXPHY_HS_CLK_INV, 1)
REGDEF_BIT(, 1)
REGDEF_BIT(CSITXPHY_CLK_PHASE_OFS, 4)
REGDEF_BIT(, 24)
REGDEF_END(CSITXPHY_CTRL_CLOCK_REG)

// 0x104, 0x204 D-PHY Clock Register
#define CSITXPHY_CTRL1_CONTROLLER_REG_OFS     0x104
#define CSITXPHY_CTRL2_CONTROLLER_REG_OFS     0x204
REGDEF_BEGIN(CSITXPHY_CTRL_CONTROLLER_REG)
REGDEF_BIT(CSITXPHY_LP_RX_DAT0_EN, 1)
REGDEF_BIT(CSITXPHY_LP_RX_DAT1_EN, 1)
REGDEF_BIT(CSITXPHY_LP_RX_DAT2_EN, 1)
REGDEF_BIT(CSITXPHY_LP_RX_DAT3_EN, 1)
REGDEF_BIT(, 12)
REGDEF_BIT(CSITXPHY_REG_EMCTRL_C, 4)
REGDEF_BIT(, 12)
REGDEF_END(CSITXPHY_CTRL_CONTROLLER_REG)

// 0x108, 0x208 D-PHY PLL Register 1
#define CSITXPHY_CTRL1_PLL1_REG_OFS           0x108
#define CSITXPHY_CTRL2_PLL1_REG_OFS           0x208
REGDEF_BEGIN(CSITXPHY_CTRL_PLL1_REG)
REGDEF_BIT(, 1)
REGDEF_BIT(CSITXPHY_EN_LDO, 1)
REGDEF_BIT(CSITXPHY_PLL_PDB, 1)
REGDEF_BIT(, 1)
REGDEF_BIT(CSITXPHY_PLL_DIV_CNT, 5)
REGDEF_BIT(, 3)
REGDEF_BIT(CSITXPHY_PLL_CP, 2)
REGDEF_BIT(, 2)
REGDEF_BIT(CSITXPHY_PLL_RSV, 4)
REGDEF_BIT(CSITXPHY_PLL_CLKMULT_CTL, 3)
REGDEF_BIT(, 1)
REGDEF_BIT(CSITXPHY_PLL_DIV_PRE, 3)
REGDEF_BIT(CSITXPHY_PLL_FLOCK_EN, 1)
REGDEF_BIT(CSITXPHY_PLL_VCO_BAND_SEL, 1)
REGDEF_BIT(CSITXPHY_PLL_VCO_CAP_EN, 1)
REGDEF_BIT(CSITXPHY_PLL_VLDOSEL, 2)
REGDEF_END(CSITXPHY_CTRL_PLL1_REG)

// 0x10C, 0x20C D-PHY PLL Register 2
#define CSITXPHY_CTRL1_PLL2_REG_OFS           0x10C
#define CSITXPHY_CTRL2_PLL2_REG_OFS           0x20C
REGDEF_BEGIN(CSITXPHY_CTRL_PLL2_REG)
REGDEF_BIT(CSITXPHY_PLL_TEST_CLK_EN, 1)
REGDEF_BIT(CSITXPHY_PLL_TEST_DC_EN, 1)
REGDEF_BIT(CSITXPHY_PLL_TEST_DC_SEL, 1)
REGDEF_BIT(CSITXPHY_PLL_TEST_DIV_POST_EN, 1)
REGDEF_BIT(CSITXPHY_PLL_TEST_VCTRL_EN, 1)
REGDEF_BIT(, 3)
REGDEF_BIT(CSITXPHY_PLL_CLK_SEL, 2)
REGDEF_BIT(, 2)
REGDEF_BIT(CSITXPHY_PLL_TEST_DIV_POST, 2)
REGDEF_BIT(, 18)
REGDEF_END(CSITXPHY_CTRL_PLL2_REG)




#endif // __CSI_TX_REG_H__
