
#define _CTL_VPE_VER_TOKEN_STR(a)  #a
#define CTL_VPE_VER_TOKEN_STR(a)  _CTL_VPE_VER_TOKEN_STR(a)
#define CTL_VPE_DRV_NAME "kflow_ctl_vpe"
#define CTL_VPE_VER_MAJOR 1
#define CTL_VPE_VER_MINOR 00
#define CTL_VPE_VER_PATCH 005
#define CTL_VPE_VER_EXT 00
#define CTL_VPE_MODULE_VERSION CTL_VPE_VER_TOKEN_STR(CTL_VPE_VER_MAJOR) "." CTL_VPE_VER_TOKEN_STR(CTL_VPE_VER_MINOR) "." CTL_VPE_VER_TOKEN_STR(CTL_VPE_VER_PATCH) "." CTL_VPE_VER_TOKEN_STR(CTL_VPE_VER_EXT)
